// La Reta Vortaro, GPLv2
'use strict';
var revo_sr = [
["Fejsbuko, Vizaĝlibro","Фејсбук"],
["Hipokrato","Хипократ"],
["Morfeo","Морфеј"],
["Ohio","Охајо"],
["alburno","кедер"],
["alpako","алпака"],
["burokratio","бирократија"],
["disidento","дисидент"],
["filateliisto","филателист"],
["filatelio","филателија"],
["fregato","фрегата"],
["haŝio","штапићи за јело"],
["koano","коан"],
["kopernicio","коперницијум"],
["latrino","латрине"],
["livermorumo","ливерморијум"],
["metodologio","методика","методологија"],
["metropolito","митрополит"],
["pino","бор"],
["rentgenio","рендгенијум"],
["stupao","ступа"],
["tigo","стабло"],
["Ĥarono","Харон"],
["ĥameleono","камелеон"],
["ĥitino","хитин"],
];
var revo_sr_lower = revo_sr.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
