// La Reta Vortaro, GPLv2
'use strict';
var revo_tr = [
["Afrikano","Afrika'lı"],
["Afriko","Afrika"],
["Amudarjo","Amuderya"],
["Anatolio","Anadolu"],
["Azerbajĝano","Azerbaycan"],
["Azerio","Azerbaycan"],
["Aŭstralio","Avusturalya"],
["Babelo","Babil","Babilon"],
["Babelturo","Babil kulesi"],
["Balta maro","Baltık Denizi"],
["Belgio","Belçika"],
["Biblio","Kutsal Kitap","Tevrat, Zebur ve İncil"],
["Bruselo","Brüksel"],
["Duŝanbeo","Düşenbe"],
["Eŭfrato","Fırat"],
["Francio","Fransa"],
["Gabrielo","Cebrail"],
["Germanio","Alemanya"],
["Gilgameŝo, Gilgameŝ","Gılgamış"],
["Granda fasto","hıristiyanlarda büyük pehriz","ramazan ayı"],
["Granda ursino","Büyük Ayı","Büyükayı"],
["Grekio","Yunanistan"],
["Guĝarato","Gücerat"],
["Holando","Hollanda"],
["Istanbulo","İstanbul"],
["Kaspio","Hazar denizi","Hazer denizi"],
["Kievo","Kiev"],
["Kipro","Kıbrıs"],
["Kirgizio","Kırgızistan"],
["Luksemburgio","Lüksenburg"],
["Luksemburgo","Lüksenburg"],
["Malgrand-Azio","Anadolu","Küçük Asya"],
["Mezopotamio","Mezopotamya"],
["Monda Organizaĵo pri sano","DSÖ(Dünya Sağlık Örgütü)"],
["Nigra maro","Karadeniz"],
["Nova testamento","İncil"],
["Oriono","Avcı"],
["Plejadoj","Ülker","Süreyya","Yedi Kızkardeşler"],
["Svedio","İsveç"],
["Svisio","İsviçre"],
["Tigriso","Dicle"],
["Turkio","Türkiye"],
["Unio de sovetaj Socialismaj Respublikoj","Sovyetler Birliği","Sovyet Sosyalist Cumhuriyetler Birliği","SSCB"],
["Unuiĝintaj nacioj","Birleşmiş Milletler ","BM"],
["Urugvajo","Uruguay"],
["abako","abaküs"],
["abdomeno","karın"],
["abelo","bal arısı","arı"],
["abelujo","kovan"],
["abio","göknar"],
["abismo","uçurum"],
["ablativo","-den hali"],
["abnegacio","vazgeçme"],
["abrikoto","kayısı"],
["abrikotujo, abrikotarbo","kayısı"],
["absorbi","meşgul etmek (düşuncelerini)","emmek (emici madde tarafından. örek: sünger)"],
["absorbiĝi","derin düşünceye dalmak"],
["absurda","saçma","mantıksız"],
["adjudiki","ihaleye çıkarmak"],
["adjudiko","ihale"],
["adresanto","gönderen"],
["adreso","adres"],
["adulti","zîna yapmak"],
["adulto","zîna"],
["aero","hava"],
["aeroplano","uçak"],
["aferisto","iş adamı"],
["afero","problem","sorun","iş","dert","şey","eşya"],
["afganio","Afganistan"],
["afiŝi","yollamak"],
["afiŝo","afiş"],
["afranki","pulunu yapıştırmak"," önceden ödemek(masrafını)","özgür kılmak","vergiyi kaldırmak"],
["agariko","çayırmantarı"],
["agema","etkin","faal","çalışkan","zinde","hamarat"],
["agendo","masa takvimi","ajanda"],
["agi","iş görmek","etken olmak","etkilemek","davranmak","hareket etmek"],
["agiti","çalkalamak","sallayıp karıştırmak","şaşırtmak","ayaklandırmak","kışkırtmak"],
["aglo","kartal","Kartal"],
["aglomeri","toplanmak","toplayıp yığmak"],
["aglutini","yapıştırmak","bitiştirmek"],
["agnoski","kabullenmek"],
["agnostikismo","bilinemezcilik"],
["ago","hareket","davranış"],
["agonii","can çekişmek"],
["agonio","can çekişme"],
["agrabla","hoş"],
["agrafi","kopçalamak"],
["agresema","sataşkan","saldırgan"],
["agresemo","saldırganlık"],
["agresi","sataşmak","saldırmak"],
["agreso","saldırı","sataşma"],
["agrikulturisto","çiftçi"],
["agrikulturo","tarım","çiftçilik","ziraat"],
["agronomio","tarım bilim","agronomi"],
["agropiro","ayrıkotu"],
["ajlo","sarımsak"],
["akapari","tekeline almak","istifçilik etmek"],
["akceptejo","resepsiyon"],
["akcepti","kabul etmek","kabullenmek","karşılamak"],
["akceptisto","resepsiyonist"],
["akcepto","karşılama","kabullenme"],
["akcia kompanio","hisse senetli şirket(A.Ş.)"],
["akcia societo","hisse senetli şirket(A.Ş.)"],
["akcio","hisse senedi"],
["akcizi","vergiye taabi tutmak "],
["akcizisto","vergi toplayan kişi"],
["akcizo","vergi"],
["akso","mihver"],
["akvo","su"],
["akvofalo","şelale"],
["akĉento","şive"],
["alesti, apudesti","mevcut olmak"],
["algluiĝi","yapışmak"],
["alivesti","kılık değiştirmek"],
["alkoholaĵo","içki"],
["alkoholo","alkol"],
["alta","yüksek"],
["altvalora","çok değerli"],
["aluminio","alüminyum"],
["amafero","macera(aşk)"],
["ambasadoro","büyükelçi"],
["ami","sevmek"],
["amiko","arkadaş","dost"],
["amo","sevgi","aşk","sevda"],
["amovendistino","orospu"],
["anaso","ördek"],
["anastigmata","anastigmat"],
["anastigmato","anastigmat"],
["animalo","hayvan"],
["ankaŭ","da","de","dahi","kadar"],
["antaŭgarda","sakingan","çekingen","titiz"],
["antaŭhieraŭ","evvelki gün"],
["antimono","antimon"],
["anuso","anüs"],
["anĝelo","melek"],
["aparataro","donanım"],
["apendico","apandis"],
["apogseĝo, brakseĝo","koltuk"],
["apoteko","eczane"],
["aprilo","nisan"],
["arakido","yer fıstığı"],
["araneo","örümcek"],
["arbaro","orman"],
["arbo","ağaç"],
["argono","argon"],
["arseno","arsenik"],
["arĝento","gümüş"],
["arŝino","arşın","endaze"],
["avelo","fındık"],
["avelujo","fındık"],
["avino","nine","büyük anne"],
["avo","dede","büyük baba"],
["azeno","eşşek"],
["azerujo","Azerbaycan"],
["aĉetanto","alıcı"],
["aĉetebla","satılık"],
["aĉeti","satın almak","rüşvet vermek","baştan çıkarmak","bozmak"],
["aĝa","yaşlı"],
["aĝo","yaş"],
["aŭ","veya","ya da","yoksa","yahut"],
["aŭgusto","ağustos"],
["aŭskulti","dinlemek"],
["aŭtismo","otizm"],
["aŭto","oto"],
["aŭtuno","sonbahar"],
["bagaĝo","valiz","bağaj"],
["balai","süpürmek"],
["balailo","süpürge"],
["balkono","balkon"],
["balotrajtiga karto","seçmen kartı"],
["balta","Baltık"],
["balto","Baltık"],
["banano","muz"],
["bandomo","hamam"],
["banĉambro","banyo"],
["barejno","Bahreyn"],
["barikadi","barikat kurmak"],
["barikado","barikat"],
["barometro","basınçölçer","barometre"],
["basbalo","base-ball"],
["baseno","havuz"],
["basketbalo","basketball"],
["bastardo","piç"],
["bastono","baston"],
["bazilio","reyhan"],
["belgrajno","ben(tende)"],
["belgujo","Belçika"],
["bero","üzüm"],
["besto","hayvan"],
["beto","pancar"],
["biciklo","bisiklet"],
["biero","bira"],
["bildkarto","posta kartı"],
["birdo","kuş"],
["birdoj","kuşlar"],
["biskvito","bisküvi"],
["blanka","beyaz","ak"],
["blanketa","beyazımsı"],
["blankulo","beyaz"],
["blua","mavi"],
["bofilino","gelin"],
["bofilo","damat"],
["boji","havlamak","ürümek"],
["bolkuiri","kaynatmak"],
["bona","iyi"],
["bosono","bozon","Bose-részecske"],
["botelo","şişe"],
["bovaĵo","sığır eti"],
["bovido","buzağı"],
["bovino","inek"],
["bovo","boğa"],
["bracelethorloĝo","kol saati"],
["brako","kol"],
["brakringo","bilezik"],
["bremsi","fren yapmak"],
["bremso","fren"],
["brilpura","pırıl pırıl"],
["brulgaso, lumgaso","doğalgaz"],
["brusto","göğüs"],
["budaismo","budizm","budistlik"],
["budaisto, budaano","budist"],
["butero","tereyağ"],
["butiko","dükkân"],
["buŝo","ağız"],
["celerio","kereviz"],
["cent","yüz"],
["cepo","soğan"],
["cidro","elma şarabı"],
["cikonio","leylek"],
["cilindro","silindir"],
["cinamo","tarçın"],
["citrono","limon"],
["citronujo","limon"],
["dalajlamao","Dalay Lama"],
["dancejo","diskotek"],
["danci","dansetmek"],
["danco","dans"],
["dancŝuo","dans ayakkabısı"],
["danki","teşekkür etmek"],
["danko, dankado","teşekkür"],
["danĝera","tehlikeli"],
["danĝero","tehlike"],
["dati","tarih atmak"],
["dato","tarih"],
["datreveno","doğum günü"],
["decembro","aralık"],
["dek","on"],
["dekstra","sağ"],
["dekstrulo","sağcı"],
["demandi","sormak"],
["demando","soru"],
["deserto","tatlı(yemek sonunda yenen)"],
["dika intesto","kalın bağırsak"],
["dio","Allah","Tanrı"],
["disporti","yayınlamak","dağıtmak"],
["diverskolora","çok renkli","rengârenk"],
["dizajno","tasarım"],
["domego","bina"],
["domkolorigisto, murkolorigisto","boyacı"],
["domo","ev"],
["doni","vermek"],
["dormoĉambro","yatak odası"],
["dosiero","dosya"],
["dosierujo","dizin"],
["drinkaĵo","alkollü içecek"],
["drinkejo","meyhane","bar"],
["drinki","içmek","içki içmek"],
["du","iki"],
["duonfilino","gelin"],
["duonfilo","damat"],
["duoninsulo","yarımada"],
["duono","yarı"],
["edzigi","evlendirmek"],
["edzino","karı","eş","evli"],
["edziĝi","evlenmek"],
["edzo","koca","eş","evli"],
["egiptujo","Mısır"],
["ekesti","olmaya başlamak"],
["ekliptiko","ekliptik","tutulum"],
["eksedziĝi","boşanmak"],
["ekvinokso","ekinoks","gün gece eşitliği"],
["ekzemple","meselâ","örneğin"],
["ekzemplo","örnek"],
["elaĉeti","geri satın almak"],
["elcento, elcentaĵo","yüzde"],
["elefanto","fil"],
["emiro","emir"],
["engorĝiĝi","boğazında kalmak"],
["enporti","ithal etmek"],
["estanteco","şimdi"],
["estas","işte"],
["estaĵo","varlık"],
["esti","olmak"],
["estigi","oldurmak"],
["estinteco","geçmiş"],
["estiĝi","oluşmak"],
["estona","Estonca"],
["estono","Eston","Estonyalı"],
["estonteco","gelecek"],
["estonujo","Estonya"],
["eĉ","bile"],
["fabrikado","üretim"],
["fabrikanto","üretici","üreten"],
["fabriki","üretmek"],
["fabriko","fabrika"],
["facila","kolay"],
["facile","kolayca"],
["faciligi","kolaylaştırmak","basitleştirmek"],
["faco","cephe"],
["fadeno","iplik"],
["fadi","gözden kaybolmak(uzaklaşarak)"],
["fago","gürgen"],
["fagopiro","kara buğday"],
["fajenco","fayans"],
["fajfado","ıslık"],
["fajfi","ıslık çalmak"],
["fajfilo","ıslık","düdük"],
["fajra","ateşli"],
["fajraĵo","havai fişek"],
["fajre","ateşle","tutkuyla"],
["fajrejo","şömine"],
["fajrero","kıvılcım"],
["fajri","alev"],
["fajrigi","ateş yakmak"],
["fajro","ateş"],
["fajroprenilo","maşa"],
["fakiro","fakir"],
["faksaĵo","faks(belge)"],
["faksi","fakslamak"],
["faksilo","faks(araç)"],
["faksnumero","faks numarası"],
["fakturo","hesap","not"],
["faldebla","katlanabilen(eşya)"],
["faldi","katlamak"],
["faldo, faldaĵo","kıvrım","kırışık"],
["fali","düşmek"],
["faligi","düşürmek"],
["falo","düşme"],
["familio","aile"],
["farbo","boya"],
["faruno","un"],
["farĉi","doldurmak(dolma)"],
["farĉo","(dolma içi)"],
["fasti","oruç tutmak"],
["fasto","pehriz","oruç"],
["fazeolo","fasulye"],
["febro","ateş","coşkunluk","hararet"],
["februaro","şubat"],
["feministo","feminist"],
["femuro","uyluk"],
["fenomena","olağanüstü"],
["fenomeno","fenomen"],
["fermi","kapatmak"],
["festeno","şölen"],
["festivalo","festival"],
["figo","incir"],
["filigi","evlatlık edinmek"],
["filino","kız çocuğu"],
["filo","oğul"],
["fingro","parmak"],
["fiŝisto","balıkçı"],
["fiŝo","balık"],
["flamo","alev"],
["flano","krep","gözleme"],
["flava","sarı"],
["flavmalsano","sarılık"],
["foko","fok"],
["folio","yaprak"],
["foresti","olmamak"],
["foresto","yokluk"],
["forkapti","kaçırmak"],
["forko","çatal"],
["formiko","karınca"],
["forno","ocak"],
["forporti","götürmek"],
["forvendi","ucuz fiyatla elden çıkarmak"],
["fotosfero","renk küresi","fotosfer"],
["frago","çilek"],
["francujo","Fransa"],
["frateco","kardeşlik"],
["fratino","kız kardeş"],
["frato","erkek kardeş"],
["fratoj","üvey kardeşler","kardeşler"],
["freŝdata","yeni(zaman)","yakın(zaman)"],
["friti","kızartmak"],
["frito","kızarmış patates"],
["fromaĝo","peynir"],
["frukto","meyve"],
["gaja","neşeli"],
["gajiga","neşelendiren","eğlendiren"],
["gajigi","neşelendirmek","eğlendirmek"],
["gajni","kazanmak (para; bir mücadeleyi,savaşi; oyunu kazanmak, örnek: loto, sport)"],
["gajno","kazanç"],
["galanto","kardelen"],
["galerio","galeri","siçanyolu"],
["galero","çok zor iş, uğraş","kürek cezası"],
["galope","dörtnala"],
["galopi","dörtnala gitmek"],
["galvanizi","galvanizlemek"],
["gambo","bacak"],
["gamo","gam (müzik)"],
["gangreno","kangren"],
["gantisto","eldivenci (eldiven yapan yada satan)"],
["ganto","eldiven"],
["garantianto","kefil"],
["garantiaĵo","kefalet"],
["garantii","garantilemek","sigortalamak","söz vermek"],
["garantio","garanti","sigorta"],
["garaĝo","garaj"],
["gardestari, gardostari","nöbet tutmak"],
["gardi","gözetlemek","korumak"],
["gardo","nöbetçi"],
["garni","doldurmak","döşemek","süslemek"],
["garnituro","süs","süs gereçleri","donatım","garnitür"],
["garnizono","garnizon"],
["garolo","alakarga"],
["gasa","gaz halinde"],
["gasmasko","gaz maskesi"],
["gaso","gaz"],
["gastama, gastigema","misafirperver"],
["gastejo","han"],
["gasti","misafir olmak","ağırlanmak"],
["gastiganto","ev sahibi(misafiri ağırlayan)"],
["gastigi","ağırlamak","misafir etmek"],
["gasto","misafir","konuk"],
["gastronomio","iyi yemek merakı","gastronomi"],
["gazelo","ceylan"],
["gazetara konferenco","basın konferansı"],
["gazetaro","basın"],
["gazetisto","gazeteci"],
["gazeto","gazete"],
["gazono","çimen"],
["gelateno","jelatin"],
["genciano","kızılkantaron","centiyan"],
["genealogia arbo, genealogiarbo","soyağacı"],
["genealogio","soybilim","jeneoloji"],
["generacio","kuşak","nesil"],
["generalo","general"],
["genezo","oluş","oluşma"],
["genio","dahi","üstün yetenek","dahilik","cin"],
["geno","gen"],
["genocido","soykırım"],
["genro","cins","tür"],
["genuigi","diz çöktürmek"],
["genuiĝi, ekgenui","diz çökmek"],
["genuo","diz"],
["geofiziko","jeofizik"],
["geografio","jeografi"],
["geologo","yerbilimci","jeolog"],
["geometro","jeometre"],
["geranio","sardunya"],
["germana","alman"],
["germano","alman vatandaşı","alman"],
["germanujo","Almanya"],
["gilotini","giyotinle kafa uçurma"],
["gilotino","giyotin"],
["gimnastiko","beden eğitimi","jimnastik"],
["gimnaziano","lice öğrencisi"],
["gimnazio","lise"],
["ginekologiisto","jinekolog"],
["ginekologio","nisaiye","jinekoloji"],
["ginekologo","jinekolog"],
["gingivo","dişeti"],
["gipsi","sıvalamak"],
["gipso","sıva","alçı"],
["girlando","çiçekten/yapraktan çelenk","bezek kordonu"],
["gisfero","dökme demir"],
["gisto","maya mantarı"],
["gitaro","gitar"],
["glaciaĵo","dondurma"],
["glaciigi","dondurmak"],
["glaciiĝi","donmak"],
["glacio","buz"],
["glaciujo, glaciŝranko","buz dolabı"],
["gladi","ütülemek"],
["gladiatoro","gladyatör"],
["gladilo","ütü"],
["glando","salgıbezi"],
["glaso","bardak"],
["glicerino","gliserin"],
["glicirizo","meyankökü"],
["glikozo","glikoz"],
["gliro","tarla sıçanı"],
["glisi","süzülmek(kuş, uçak)"],
["glisilo","planör"],
["glori","ululamak","yüceltmek"],
["glosaro","terim sözlüğü"],
["gloso","açıklama","yorum","açımlama"],
["glubendo","bant"],
["glui","yapıştırmak"],
["gluilo","tutkal"],
["glutema","obur"],
["gluti","yutmak"],
["gluto","lokma"],
["gnomo","cüce"],
["gobeleno","halıcılık","kilimcilik","duvar kağıdı","duvar halısı"],
["golejisto","kaleci"],
["golejo","kale (gol)"],
["golfo","körfez"],
["golo","gol"],
["gorilo","goril"],
["gorĝo","boğaz(anatomi)"],
["gota","gotik"],
["gracia","incelikli","zarafetli","lütuflu"],
["gracie","zerafetle"],
["gracieco","incelik","zarafet","lütuf"],
["grada","dereceli","kerteli"],
["gradigi","derecelemek","kerte kerte yükseltmek"],
["grado","derece"],
["graflando","kontluk"],
["grafo","kont"],
["grajno","tane(buğday ve benzeri)"],
["gramatiko","dilbilgisi"],
["gramo","gram"],
["granatarbo, granatujo","nar ağacı"],
["granato","nar"],
["granda litero, ĉeflitero","büyük harf"],
["grandaĝulo","yaşlı kişi"],
["granito","granit"],
["grapfruktarbo","greyfurt ağacı"],
["grapfrukto","greyfurt"],
["grapolo","salkım"],
["grasa","yağlı"],
["grasiĝi","şişmanlamak"],
["graso","yağ"],
["gratenaĵo","güveçte pişmiş yiyecek"],
["grateni","güveçte pişirmek "],
["grati","kazımak","kaşımak","yavaşça(kapı) çalmak"],
["gratvundi"," pençelemek","tırmalamak"],
["grio","irmik"],
["griza","boz","gri"],
["gujavo","hintarmudu"],
["hadiso","hadis"],
["hamburgero","hamburger"],
["haveno","liman"],
["helianto","ayçiçeği"],
["heliumo","helyum"],
["hepato","ciğer"],
["hidrogeno","hidrojen"],
["hieraŭ","dün"],
["hodiaŭ","bugün"],
["homa","insan","insan oğlu"],
["homama","insansever"],
["homaro","insanlık"],
["homevitulo","insandan kaçar","mizantrop"],
["homido","insan oğlu"],
["homino","kadın"],
["hommanĝulo","yamyam"],
["horloĝisto","saatçi"],
["hundejo","köpek kulübesi"],
["hundo","köpek","tazı"],
["infano","çocuk"],
["informi","bildirmek"],
["infuzi","demlemek"],
["insekto","böcek"],
["insula","adaya ait"],
["insulano","adalı"],
["insularo","takımada"],
["insuleto","adacık"],
["insulo","ada"],
["insulo de Princo Eduardo","Prens Edward Adası"],
["interago","karşılıklı etki","etkileşim"],
["internacia","uluslararası"],
["internaciismo","uluslararası birlik düşüncesi ","uluslararası durum"],
["intestaro","bağırsaklar"],
["intesto","bağırsak"],
["iri","gitmek"],
["islama","İslamî"],
["islamano","Müslüman"],
["islamismo","İslamcılık"],
["islamisto","İslamcı"],
["islamo","İslam"],
["jahurto","yoğurt"],
["janiĉaro","yeniçeri"],
["januaro","ocak"],
["jarcento","yüzyıl"],
["jarmilo","binyıl"],
["jasmeno","yasemin"],
["jes","evet"],
["juglando","ceviz"],
["juglandujo, juglandarbo","ceviz"],
["julio","temmuz"],
["junio","haziran"],
["kabano","kulübe"],
["kabaredo","kabare","gece kulübü","meyhane"],
["kabineto","büro","kabine","bakanlar kurulu"],
["kabinetulo","kurul üyesi"],
["kabla televido","kablo TV"],
["kablo","kablo"],
["kabo","burun(deniz)"],
["kaco","sik(penis)"],
["kadavro","ceset","kadavra"],
["kadenco","ölçü","ahenk"],
["kadeto","ortanca oğul"],
["kadmio","kadmiyum"],
["kadri","çerçevelemek"],
["kadro","çerçeve"],
["kadukiĝi","harabeye dönmek"],
["kafarbo","kahve bitkisi"],
["kafeino","kafein"],
["kafejo","kahvehane"],
["kafkruĉo","cezve"],
["kafo","kahve(içecek)","kahve(ürün)"],
["kafpulvoro","kahve(ögütülmüş hali)"],
["kaftano","kaftan"],
["kahelaro","taş döşeme"],
["kaheli","taş döşemek"],
["kahelo","döşeme taşı"],
["kaj","ve"],
["kajaki","kayak yapmak"],
["kajako","kayak"],
["kajero","defter"],
["kajto","uçurtma"],
["kajuto","kamara"],
["kakaarbo, kakaoarbo","kakao"],
["kakao","kakao"],
["kakapulvoro, kakaopulvoro","pudra kakao"],
["kakaujo","kakao"],
["kakofonio","kakafoni","kakışma"],
["kakto","kaktüs"],
["kalifo","halife"],
["kalifujo","halifelik"],
["kalorio","kalori"],
["kamelo","deve"],
["kanuo","kano"],
["kapsiketo","biber"],
["kapsiko","dolmalık biber"],
["kapti","yakalamak"],
["kaptilo","tuzak"],
["kapuĉino","kapuçino"],
["karamelo","karamela"],
["kardamomo","kakule"],
["kardinala moŝto","kardinal ünvanı"],
["kardono","yabanienginar"],
["kareo","hint baharatı","köri"],
["kariofilo","karanfil tanesi"],
["karobo","keçi boynuzu"],
["karoto","havuç"],
["kartaro","oyun kartı"],
["karto","kart"],
["kartvelio","Gürcistan"],
["kartvelo","Gürcü"],
["kartvelujo","Gürcistan"],
["karvio","kimyon"],
["kaserolo","saplı tencere"],
["kavernhomo","mağara adamı"],
["kaviaro","kavyar"],
["kazeo","kesik süt","kazein"],
["kazo","hali"],
["kaĉaloto","ispermeçet balinası","kaşalot"],
["kaĝo","kafes"],
["kaĵola","pohpohçu","seven"],
["kaĵoli","okşamak","sevmek","tavlamak","piyazlamak"],
["kaŝtanarbo, kaŝtanujo","kestane ağacı"],
["kaŝtano","kestane"],
["kie","nerede"],
["kiel","neden","niçin","nasıl"],
["kiel se","sanki"],
["kielo","biçim","hal","tarz","tavır","görünüş"],
["kies","kimden","hangisinden","kimin"],
["kikero","nohut"],
["kilo","gemi omurgası"],
["kinejo","sinema salonu"],
["kinisto","yönetmen"],
["kino","sinema"],
["kiom","ne kadar"],
["kiomo","nicelik"],
["kiosko","köşk"],
["kirurgia","cerrahi"],
["kirurgiisto","cerrah"],
["kirurgio","cerrahlık"],
["kisi","öpmek"],
["kiu","kim"],
["kivo","kivi"],
["klavaro","klavye"],
["klavi","tuşlamak"],
["klavo","tuş"],
["klaĉi","dedikodu yapmak"],
["klaĉo","dedikodu"],
["klaŭno","palyaço"],
["kleo","anahtar(muzik)"],
["klientaro","müşteriler"],
["kliento","müşteri"],
["klimato","iklim"],
["knabino","kız çocuk","genç kız"],
["knabo","erkek çocuk","oğlan","delikanlı","genç erkek"],
["koaguli","pıhtılaştırmak","dondurmak"],
["koaguliĝi","pıhtılaşmak"],
["koko","tavuk","horoz"],
["kolibro","sinekkuşu"],
["kolo","boyun"],
["kolora","renkli","boyalı"],
["kolori","boyamak","renk vermek"],
["kolorigi","renklendirmek","boyamak"],
["kolorigilo","boya"],
["kolorigisto","renk sanatçısı","renkçi"],
["kolorilo","boya"],
["koloro","renk"],
["kometo","kuyruklu yıldız"],
["kompoto","hoşaf","komposto"],
["komputilo","bilgisayar"],
["kondukpermesilo, stirpermesilo","araba ehliyeti"],
["konferenco","konferans"],
["krajono","kurşun kalem"],
["kreditkarto","kredi kartı"],
["kremo","kaymak"],
["krokodilo","timsah"],
["kruĉo","testi","sürahi"],
["kuirejo","mutfak"],
["kuiri","pişirmek"],
["kuiristo","aşçı"],
["kukurbo","kabak"],
["kulero","kaşık"],
["kumino","kimyon"],
["kunesti","ile birlikte olmak"],
["kunlabori","işbirliği yapmak"],
["kunlaboro","işbirliği"],
["kunporti","beraberinde taşımak"],
["kuzino","amca\dayı\hala veya teyze çocuğu(kız, bayan)"],
["kuzo","amca\dayı\hala veya teyze çocuğu(erkek)"],
["kvar","dört"],
["kvin","beş"],
["laborantaro","personel"],
["laborema","çalışkan"],
["laborestro","şef"],
["labori","çalışmak"],
["laboristo, laborulo","işçi"],
["laboro","iş"],
["lacerto","kertenkele"],
["lago","göl"],
["lakta Vojo","Samanyolu"],
["lakteca, lakta","süt gibi"],
["lakto","süt"],
["laktumo","süt"],
["lando","ülke"],
["lango","dil"],
["lano","yün"],
["larmo","gözyaşı"],
["larĝa","geniş"],
["latitudo","enlem"],
["lavi","yıkamak"],
["lavpulvoro","çamaşır deterjanı(toz hali)"],
["lento","mercimek"],
["leono","aslan","Aslan"],
["leterportisto","postacı"],
["librejo","kitabevi"],
["libro","kitap"],
["librotenejo","kitaplık"],
["librovendejo","kitabevi"],
["lignoŝuo, ligna ŝuo","takunya"],
["lingvisto, lingvosciencisto","dilci","lengüist"],
["lingvo","dil"],
["lingvoscienco","dilcilik","dilbilim","lengüistik"],
["litero","harf"],
["literumi","hecelemek"],
["litio","lityum"],
["lokkazo","de hali"],
["lukumo","lokum"],
["luma","aydınlık"],
["lumi","ışık saçmak"],
["lumigi","ışıklandırmak","aydınlandırmak"],
["lumigilo","ışıklandırma"],
["lumilo","ışık kaynağı"],
["lumo","ışık","aydınlık"],
["lumrapido","ışık hızı"],
["lundo","pazartesi"],
["lupo","kurt"],
["maizo","mısır"],
["majo","mayis"],
["majonezo","majonez"],
["makuli","lekelemek"],
["makulo","leke"],
["malagnoski","kabullenmemek"],
["malagrabla","tatsız","hoş olmayan"],
["malagrafi","kopçalarını çözmek"],
["malakcepti","reddetmek"],
["malamiko","düşman"],
["malamo","nefret"],
["maldekstrulo","solcu"],
["maldika intesto","ince bağırsak"],
["malesti","var olmamak"],
["malfacila","zor"],
["malfacilaĵo","zorluk","problem"],
["malfaciligi","zorlaştırmak"],
["malfermi","açmak"],
["malfrui","geç kalmak"],
["malfruigi","geciktirmek"],
["malfruiĝi","gecikmek"],
["malfruo","gecikme"],
["malgaja","üzgün","kederli","gamlı","hüzünlü"],
["malgaji","üzülmek","kederlenmek","hüzünlenmek","gamlanmak"],
["malgajni","kaybetmek (parayi, oyunu : örneğin loto; savaşi, mücadeleyi)"],
["malgajo","mutsuzluk"],
["malgranda litero, etlitero","küçük harf"],
["mallaborema","tembel"],
["malluma","karanlık"],
["mallumo","karanlık"],
["malnova mondo","eski dünya"],
["malpermesi","yasaklamak"],
["malriĉigi","yoksullaştırmak"],
["malriĉiĝi","yoksullaşmak"],
["malriĉo","yoksulluk"],
["malsaniĝi","hastalanmak"],
["malscio","cahillik"],
["malseka","ıslak","nemli"],
["malserena","huzursuz","kaygılı"],
["malutili","zarar vermek"],
["malutilo","zararlılık"],
["malvarma","soğuk"],
["malvarmeta","serin"],
["malvarmo","soğukluk"],
["malvarmsanga","soğuk kanlı"],
["malvesti","soymak"],
["mambestoj","memeliler"],
["mameto","meme başı"],
["mamnutri","emzirmek"],
["mamo","meme"],
["mampinto","meme başı"],
["mamsuĉigi","emzirmek"],
["mamuloj","memeliler"],
["manĝaĵo","yiyecek"],
["manĝeti","atıştırmak"],
["manĝi","yemek","yemek yemek"],
["manĝigi","yedirmek"],
["manĝilaro","sofra takımı"],
["manĝokarto","yemek listesi","menü"],
["mardo","salı"],
["marestaĵo","deniz yaratığı"],
["markaŝtano","deniz kestanesi"],
["marmelado","reçel"],
["maro","deniz"],
["marto","mart"],
["masakri","katletmek"],
["masakro","katliyam"],
["masko","maske"],
["matematiko","matematik"],
["matenmanĝo","kahvaltı"],
["meleagro","hindi"],
["melongeno","patlıcan"],
["mento","nane"],
["mevo","martı"],
["mezaĝa","orta yaş"],
["mielmonato","bal ayı"],
["miksrasulo","kırma","melez","karışık"],
["mil","bin"],
["miliono","milyon"],
["milionulo","milyoner"],
["mokfajfi","ıslıklamak(birilerini yuhlamak)"],
["monata","aylık"],
["monataĵo","adet(kadınlar ayda bir adet olur)","aybaşı"],
["monato","ay(ocak, şubat, mart, nisan ...)"],
["monda","dünyasal","global"],
["mondo","dünya"],
["monduma","sosyetik"],
["mondumo","yüksek sosyete"],
["mono","para"],
["monopolo","tekel"],
["monujo","cüzdan"],
["morgaŭ","yarın"],
["moruso","dut"],
["morusujo, morusarbo","dut"],
["moŝto","yükseklik","üstünlük"],
["multenombro, plurnombro","cem","çoğul"],
["murhorloĝo","duvar saati"],
["muso","fare"],
["muzeo","müze"],
["muŝbirdo","sinekkuşu"],
["muŝo","sinek"],
["nabo","poyra","tekerlek göbeği"],
["nacia","ulusal"],
["nacieco","uyrukluk","vatandaşlık"],
["naciismo","milliyetçilik","ulusçuluk"],
["naciisto","milliyetçi","ulusçu"],
["nacio","ulus"],
["nadlo","iğne"],
["naftalino","naftalin"],
["nafto","petrol"],
["naiva","Saf","deneyimsiz","sade","doğal"],
["najbara","komşu"],
["najbaraĵo","komşuluk","çevre"],
["najbaro","komşu"],
["najtingalo","bülbül"],
["nanplanedo","cüce gezegen"],
["nazo","burun"],
["naĝbaseno","yüzme havuzu"],
["naĝi","yüzmek"],
["naĝilo","yüzgeç"],
["naĝobirdo, naĝbirdo","su kuşu"],
["naŭ","dokuz"],
["ne","hayır"],
["neesto","yokluk"],
["neforgesumino","unutma beni"],
["negro","zenci"],
["neniam","asla"],
["nepino","kız torun"],
["nepo","erkek torun"],
["neutila, senutila","gereksiz","lüzumsuz"],
["nevino","kız yeğen"],
["nevo","erkek yeğen"],
["neĝbulo","kar topu"],
["neĝero","kar tanesi"],
["neĝi","kar yağmak"],
["neĝo","kar"],
["neĝulino","Pamuk Prenses"],
["neĝŝuo","kar ayakkabısı"],
["nigra","kara","siyah"],
["nigra truo","kara delik"],
["nigrigi","karalamak"],
["nikotiano","tütün"],
["nitrido","nitrür"],
["nokte","geceleyin"],
["nokto","gece"],
["nomadejo","göçebe konağı"],
["nomadi","göçmek"],
["nomadismo","göçebe hayatı"],
["nomado","göçebe"],
["nombro","tek"],
["nomkarto","kartvizit"],
["nova mondo","yeni dünya"],
["novembro","kasım"],
["ok","sekiz"],
["oktobro","ekim"],
["okulario","oküler","göz merceği"],
["okulo","göz"],
["okulvitroj","gözlük"],
["olivo","zeytin"],
["oranĝo","portakal"],
["orbito","yörünge"],
["orfejo","yetimhane","öksüzler yurdu"],
["orfigi","yetim bırakmak","öksüz bırakmak"],
["orfo","yetim","öksüz"],
["ovario","yumurtalık","mebiz"],
["ovo","yumurta"],
["ovoflavo, ovoflavaĵo","yumurta sarısı"],
["ovolo","yumurtacık","yumurtacıkğı"],
["ovoĉelo","yumurtacık","yumurtacıkğı"],
["ovri","açmak"],
["ovulo","yumurtacık","yumurtacıkğı"],
["paco","barış"],
["pakaĵujo","bagaj yeri"],
["papago","papağan"],
["pasporto","pasaport"],
["patrino","anne"],
["patrio","vatan","yurt"],
["patro","baba"],
["patrujo","vatan","yurt"],
["paĝo","sayfa"],
["pelto","kürk"],
["perihelio","enberi"],
["permesi","izin vermek"],
["permesilo","izin"],
["persiko","şeftali"],
["persikujo, persikarbo","şeftali"],
["persona","şahsi","kişisel","özel"],
["persone","şahsen","şahsi olarak"],
["personeco","kişilik","şahsiyet"],
["persono","kişi"],
["petroselo","maydanoz"],
["petveturi","otostop yapmak"],
["piedo","ayak"],
["pilko","top"],
["pino","çam"],
["piro","armut"],
["pistako","fıstık"],
["planedo","gezegen"],
["plenaĝa","ergin"],
["poemo","manzume","destan"],
["poligono","çokgen"],
["pomo","elma"],
["ponto","köprü"],
["porko","domuz"],
["porti","taşımak","getirmek"],
["portisto","taşıyıcı"],
["posta tago","ertesi gün"],
["postmorgaŭ","öbür gün"],
["postveturilo","römork"],
["praeksplodo","Büyük Patlama"],
["prahomo","tarihöncesi insanı"],
["praknalo","Büyük Patlama"],
["prilabori","şekillendirmek","biçimlendirmek"],
["prilumi","aydınlatmak"],
["printempo","ilkbahar","bahar"],
["programaro","yazılım"],
["prostituitino","orospu"],
["pruno","erik"],
["pugnoganto","boks eldiveni"],
["pulvorigi","toz etmek","paramparça etmek","yok etmek","püskürtmek"],
["pulvoro","pudra"],
["pura","temiz"],
["purema","temiz(temizliği seven)"],
["purigi","temizlemek"],
["rajtigilo","izin"],
["raketo","füze"],
["rampuloj","sürüngenler"],
["rasismo","ırkçılık"],
["rasisto","ırkçı"],
["raso","ırk"],
["razi","tıraş etmek"],
["razilo","ustura","tıraş bıçağı"],
["reago","tepki"],
["recepto","reçete"],
["rekapti","yeniden yakalamak","yeniden ele geçirmek"],
["rekta intesto","göden","rektom"],
["remorko","römork"],
["resanigilo","ilaç"],
["revendi","geri satmak"],
["rezigni","vazgeçmek"],
["rizejo","pirinç tarlası"],
["rizo","pirinç"],
["riĉa","zengin","yoksul","fakir"],
["riĉaĵo","zenginlik"],
["riĉigi","zenginleştirmek"],
["riĉiĝi","zenginleşmek"],
["riĉulo","zengin(kişi)"],
["rosmareno","biberiye"],
["rostro","hortum"],
["rostruloj","hortumlular"],
["roza","pembe"],
["rozo","gül"],
["ruldomo","karavan"],
["ruĝa","kırmızı","kızıl"],
["sabli","kumlamak"],
["sablo","kum"],
["sablohorloĝo, sabla horloĝo","kum saati"],
["sabloŝtono","kumtaşı"],
["samkiel","aynı","tıpkı"],
["samvalora","eşdeğer"],
["sana","sağlıklı","hasta"],
["sanema","sağlığı hasas"],
["sangadi","kanamak"],
["sango","kan"],
["saniga","sağlığa yararlı"],
["sanigi","iğleştirmek","iyleştirmek"],
["sanilo","çare","ilaç"],
["sanktulo","aziz","veli"],
["sano","sağlık","hastalık"],
["sanulejo","hastahane"],
["scienco","bilim"],
["scii","bilmek"],
["scio","bilge","bilme"],
["scipovi","bilmek"],
["scivola","meraklı"],
["seanco","seans"],
["seka","kuru"],
["sekigi","kurutmak"],
["sekiĝi","kurumak"],
["semgrajno","tohum"],
["senagado","etkisizlik","hareketsizlik","işsizlik","çalşmazlık"],
["senlabora","işsiz"],
["senlaboreco","işsizlik"],
["senmakula","arı","lekesiz"],
["senvalora","değersiz"],
["sep","yedi"],
["sepio","mürekkep balığı","supya","sepya"],
["septembro","eylül"],
["serajlo","saray","harem"],
["serena","huzurlu"],
["sereno","huzurluluk"],
["serpento","yılan"],
["ses","altı"],
["sezamo","susam"],
["sezono","mevsim"],
["signo","işaret"],
["sinjorino","bayan","hanım"],
["sinjoro","bay","bey"],
["skribilo","kalem"],
["societo","şirket"],
["sojkazeo","tofu"],
["sola","yalnız"],
["sole","yalnızca"],
["soleco","yalnızlık"],
["somerdomo","kır evi"],
["somere","yazın"],
["somero","yaz"],
["sovetunio","Sovyetler Birliği"],
["spiko","başak"],
["spinaco","ıspanak"],
["stacidomo","istasyon","gar"],
["statuo","heykel","yontu"],
["strato","sokak"],
["subbrako","koltuk altı"],
["subporti","desteklemek(fiziksel olarak)"],
["subvesto","iç çamaşırı"],
["sukerbeto","şeker pancarı"],
["sukero","şeker"],
["sunfloro","ayçiçeği"],
["suno","güneş"],
["superhoma","insanüstü"],
["supo","çorba"],
["surfadenigi","ipe geçirmek"],
["surĉevaliĝi","ata binmek"],
["svedujo","İsveç"],
["svislando","İsviçre"],
["svisujo","İsviçre"],
["tabako","tütün"],
["taga","gündüz"],
["tage","gündüzleyin"],
["tage kaj nokte","gündüz ve gece"],
["tagiĝi","gün ağarıyor"],
["tagmanĝo","öğlen yemeği"],
["tagnoktegaleco","ekinoks","gün gece eşitliği"],
["tagnokto","gün(24 saat)"],
["tago","gün"],
["taso","fincan"],
["tataro","Tatar"],
["taŝo","çanta","zembil"],
["tearbo","çay"],
["tekruĉo","çaydanlık"],
["telefonkarto","telefon kartı"],
["telero","tabak"],
["televidilo","televizyon"],
["tempo","zaman","vakit"],
["tendo","çadır"],
["teo","çay"],
["teretaĝo","zemin kat"],
["terkapo","burun"],
["termometro","derece","termometre"],
["tero","dünya","Yer","yeryüzü","toprak"],
["terpomo","patates"],
["terpomujo","patates"],
["tervermo","yer solucanı"],
["tigro","kaplan"],
["tilio","ıhlamur"],
["timiano","kekik"],
["tjurko","Türk"],
["tomato","domates"],
["toporo","balta"],
["tranokti","geceyi geçirmek"],
["transporti","bir yerden bir yere taşımak"],
["transportilo","ulaşım araçları"],
["transportisto","taşıyıcı"],
["transruĝa","kırmızıöte"],
["transviola","moröte"],
["tri","üç"],
["tria mondo","üçüncü dünya ülkeleri"],
["tritiko","buğday"],
["troja ĉevalo","Truva atı"],
["tuj","hemen ","çar çabuk"],
["turko","Türk"],
["turkujo","Türkiye"],
["tutmondigo","globalleşme"],
["ukrainio","Ukrayna"],
["ulcero","ülser"],
["unio","birlik"],
["universitato","üniversite"],
["unu","bir"],
["urbo","şehir"],
["urbodomo","belediye","belediye binası"],
["urso","ayı"],
["utila","gerekli","yaralı","zararlı"],
["utiligi","kullanmak"],
["utilo","yaralılık","gerklilik"],
["uzi","kullanmak"],
["vadbirdoj, vadobirdoj","uzun bacaklı kuşlar"],
["vakcinado","aşılama"],
["vakcini","aşılamak"],
["vakcino","aşı"],
["valizo","bavul","valiz"],
["valora","değerli(eşya)"],
["valori","değmek(değer)"],
["valoro","değer"],
["vanilo","vanilya"],
["vapora","buhar ile ilgili"],
["vapori","buhar çıkarmak"],
["vaporigi","buharlaştırmak"],
["vaporigilo","püskürgeç"],
["vaporiĝi","buharlaşmak"],
["vaporo","buhar"],
["varma","sıcak"],
["varmega","yakıcı"],
["varmeta","ılık"],
["varmeto","serinlik"],
["varmigi","ısıtmak","sıcak tutmak"],
["varmo","sıcaklık"],
["varmumi","üşütmek"],
["vasta","geniş"],
["vastigi","genişletmek","büyütmek"],
["vejno","kan damarı"],
["veki","uyandırmak"],
["vekiĝi","uyanmak"],
["veluro","kadife"],
["vendejo","mağaza(satım yapılan her yer)"],
["vendi","satmak"],
["vendisto","satıcı"],
["vendo","satış"],
["vendredo","cuma"],
["veneno","zehir"],
["vento","rüzgâr"],
["ventro","karın"],
["vera","gerçek"],
["veraĵo, vero","gerçek(bir gerçek)"],
["verbo","fiil"],
["verda","yeşil"],
["vere","gerçekten"],
["vereco","gerçeklik"],
["vermo","solucan","kurt"],
["versaĵo","şiir"],
["vertebraro","omurga"],
["vertebro","omur"],
["vertebruloj","omurgalı hayvanlar"],
["vespermanĝo","akşam yemeği"],
["vespero","akşam"],
["vestejo","vestiyer"],
["vesti","giymek","giyinmek"],
["vesto","elbise","giysi"],
["veterinaro","veteriner"],
["vetero","hava (hava derecesi, güneşli hava vesaire) "],
["vetoo","veto"],
["veturi","arabayla bir yerden bir yere gitmek"],
["veturigi","araç sürmek"],
["veturigisto","sürücü","şoför"],
["veturilo","taşıma aracı"],
["veziro","vezir"],
["viadukto","viyadük"],
["vinagro","sirke"],
["vinberarbo, vinberujo","asma"],
["vino","şarap"],
["viola","mor"],
["violkolora","mor"],
["violo","menekşe"],
["virino","kadın"],
["viro","erkek","adam"],
["vivoĉambro","oturma odası"],
["vizitĉambro","salon"],
["viŝi","silmek"],
["vojo","yol"],
["vortaro","sözlük","lugât","lügat"],
["vorto","söz"],
["zebro","zebra"],
["zodiako","burçlar kuşağı","Zodyak"],
["zoo","hayvanat bahçesi"],
["ĉambro","oda"],
["ĉampano","şampanya"],
["ĉapelo","şapka"],
["ĉashundo","av köpeği"],
["ĉasi","avlamak"],
["ĉasisto","avcı"],
["ĉeesti","hazır bulunmak"],
["ĉeesto","hazır bulunma"],
["ĉefanĝelo","büyük melek"],
["ĉefurbo","başkent"],
["ĉeko","çek"],
["ĉemizo","gömlek"],
["ĉerizo","kiraz (dolĉa)","vişne (acida)"],
["ĉevalo","at"],
["ĉi-tage","bu gün"],
["ĉieesto","aynı anda her yerde bulunma"],
["ĉirkaŭbraki","kucaklamak","sarılmak"],
["ĉiuhoma","evrensel"],
["ĉiutaga","günlük"],
["ĉokolado","çikolata"],
["ĉu","mı","mi","mu","mü"],
["ĝihado","cihad"],
["ĝino","cin(içecek)"],
["ĝirafo","zürafa"],
["ĝonko","conk"],
["ĥalifo","halife"],
["ĥalifujo","halifelik"],
["ĥanujo","hanlık"],
["ŝakludo","satranç"],
["ŝarko","köpekbalığı"],
["ŝati","takdir etmek","sevmek"],
["ŝipo","gemi"],
["ŝranko","dolap"],
["ŝtalo","çelik"],
["ŝtato","devlet"],
["ŝultro","omuz"],
["ŝuo","ayakkabı"],
["ŝviti","terlemek"],
];
var revo_tr_lower = revo_tr.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
