// La Reta Vortaro, GPLv2
'use strict';
var revo_zh = [
["Jupitero","木星 [Mùxīng]"],
["Konfuceo","孔夫子 [Kǒngfūzǐ]","孔子 [Kǒngzǐ]"],
["Marsano","火星人 [huǒ xīng rén]"],
["Marso","马尔斯 [mǎ ěr sī] (罗马神话中的战神)","火星 [huǒ xīng]","荧惑 [yíng huò]"],
["Menceo","孟子 [Mèngzǐ]"],
["Merkuro","水星 [Shuǐxīng]"],
["Moskvo","莫斯科 [Mòsike]"],
["Neptuno","海王星 [Hǎiwángxīng]"],
["Plutono","冥王星 [míng wáng xīng]"],
["Rusio","俄国","tr. 俄國 [Éguó]","俄罗斯 [Éluósī]"],
["Saturno","土星 [Tǔxīng]"],
["Tokio","东京 [dōng jīng]"],
["Unio de sovetaj Socialismaj Respublikoj","苏维埃","tr. 蘇維埃 [Sūwéi'āi]","苏","tr. 蘇 [sū]"],
["Urano","天王星 [Tiānwángxīng]"],
["Usonano","美国人"],
["Usono","美国"],
["Venuso","金星 [jīnxīng]"],
["adjektivo","形容词 [xíng róng cí]"],
["advokato","律师","tr. 律師 [lǜshī]"],
["aero","空气","空氣 [kōngqì]"],
["akvo","水 [shuǐ]"],
["ami","爱","tr. 愛 [ài]"],
["amkanto","情歌 [qíng gē]"],
["amo","爱","tr. 愛 [ài]"],
["ateismo","无神论","tr. 無神論 [wúshénlùn]"],
["beloruso","白俄罗斯人 [bái é luó sī rén]"],
["belorusujo","白俄罗斯 [bái é luó sī]"],
["birdo","鸟 [niǎo]"],
["blanka","白 [bái]"],
["blua","蓝 [lán]"],
["bona","好 [hǎo]"],
["cent","百","佰 [bǎi]"],
["centro","中心 [zhōngxīn]"],
["dago","匕首 [bǐ shǒu]"],
["danki","感谢","tr. 感謝 [gǎnxiè] ","谢","tr. 謝 [xiè]"],
["daŭismo","道教 [dàojiāo]"],
["daŭo","道 [dào]"],
["dek","十 [shí]"],
["deka","第十 [dìshí]"],
["dekstra","右 [yòu]"],
["dekuma","小数","tr. 小數 [xiǎoshù]"],
["dimanĉo","星期日 [xīng qí rì]","周日 [zhōu rì]","礼拜天 [lǐ bài tiān]"],
["dormema","贪睡 [tān shuì]"],
["dormeti","小睡 [xiǎo shuì]"],
["dormi","睡 [shuì]","眠 [mián]","睡觉 [shuì jiào]"],
["du","二 [èr]"],
["dua","第二 [dì èr]"],
["due","第二 [dì èr] (副词)","其次 [qí cì]"],
["duono","半 [bàn]","一半 [yī bàn]","二分之一 [èr fēn zhī yī]"],
["elcento, elcentaĵo","百分比 [bǎifēnbǐ]","百分率 [bǎifēnlǜ]","百分数","tr. 百分數 [bǎifēnshù]"],
["esti","是 [shì]"],
["fajrero","火星 [huǒxīng]","火星儿","tr. 火星兒 [huǒxīngr]","星火 [xīnghuǒ]","火花 [huǒhuā]"],
["fajro","火 [huǒ]"],
["festi","庆祝 [qìng zhù]","过(节) [guò]"],
["filino","女儿","tr. 女兒 [nǚ'ér] "],
["filo","儿子","tr. 兒子 [érzi]"],
["flari","闻 [wén]","嗅 [xiù]"],
["flava","黄 [huáng]"],
["franca lingvo","法文 [Fǎwén]"],
["francujo","法国","tr. 法國 [Fǎguó]","法兰西","tr. 法蘭西 [Fǎlánxī]"],
["frazo","语句 [yǔ jù]","表达式 [biǎo dá shì]"],
["funkcio","函数 [hán shù]"],
["gepatroj","父母 [fùmǔ]"],
["goo","圍棋 (trad.)","围棋 [wéiqí] (simp.)"],
["gramo","克 [kè]"],
["granda","大 [dà]"],
["havi","有 [yǒu]"],
["hieraŭ","昨日 [zuó rì]","昨天 [zuó tiān]"],
["homaro","人类","tr. 人類 [rénlèi]"],
["homo","人 [rén]"],
["horloĝo","时钟","tr. 時鐘 [shízhōng]"],
["ili","他们","tr. 他們","她们","tr. 她們","它们","tr. 它們 [tāmen]"],
["ilia","他们的","tr. 他們的 [tāmende]"],
["infano","孩子 [háizi]","子 [zǐ]","儿","tr. 兒 [ér]"],
["jarcento","世纪 [shìjì]"],
["jaro","年 [nián]"],
["judo","犹太人","tr. 猶太人 [yóutàirén]"],
["kamarado","同志 [tóngzhì]"],
["kero","红心 [hóng xīn]"],
["knabino","女孩 [nǚ hái]"],
["knabo","男孩 [nán hái]"],
["koano","公案"],
["koko","鸡","tr. 雞 (jī)"],
["komento","注释 [zhù shì]"],
["komputi","计算 [jì suàn]"],
["komputilo","计算机 [jì suàn jī]"],
["komunismo","共产主义","tr. 共產主義 [gòngchǎnzhǔyì]"],
["koro","心 [xīn]","心脏 [xīn zàng]","中心 [zhōng xīn]","核心 [hé xīn]"],
["kvar","四 [sì]"],
["kvin","五","伍 [wǔ]"],
["labori","劳动 [láo dòng]"],
["lernejo","学校","tr. 學校 [xuéxiào]"],
["lerni","学","tr. 學 [xué]"],
["li","他 [tā]"],
["lia","他的 [tāde]"],
["lingvisto, lingvosciencisto","语言学家 [yǔ yán xué jiā]"],
["lingvo","语言 [yǔ yán]"],
["lio","里 [lǐ]"],
["luno","月 [yuè]","月亮 [yuèliang]","月球 [yuèqiú]"],
["maldekstra","左 [zuǒ]"],
["malgranda","小 [xiǎo]"],
["malsama","异 [yì]","不同 [bù tóng]"],
["mateno","晨 [chén]","早上 [zǎo shang]"],
["maŝinlingvo","机器语言 [jī qì yǔ yán]"],
["mezo","中"],
["mi","我 [wǒ]","吾 [wú]"],
["mia","我 [wǒ] (adj.)","我的 [wǒ de]"],
["mil","千 [qiān]"],
["minuto","分 [fēn]","分钟 [fēn zhōng]"],
["monato","月 [yuè]","月份 [yuèfèn]","月度 [yuèdù]"],
["mondo","世界 [shìjiè]","世间","tr. 世間 [shìjiān]"],
["mono","钱 [qián]","金钱 [jīn qián]"],
["morgaŭ","明日 [míng rì]","明天 [míng tiān]","明朝 [míng zhāo]"],
["muziko","音乐","tr. 音樂 [yīnyuè]"],
["naŭ","九 [jiǔ]"],
["naŭa","第九 [dìjiǔ]"],
["ne","不 [bù]"],
["nehavi","没有","tr. 沒有 [méiyǒu] "],
["ni","我们","tr. 我們 [wǒmen]"],
["nia","我们的","tr. 我們的 [wǒmende]"],
["nigra","黑 [hēi]"],
["nokto","夜 [yè]","宵 [xiāo]"],
["nomo","名 [míng]","名字 [míngzi]"],
["nordo","北 [běi]","北方 [běifāng]"],
["nuda","裸 [luǒ]"],
["nulo","零 [líng]","〇"],
["numerebla","可数的 [kě shǔ de]"],
["numeri","编号 [bīan hào]"],
["ok","八 [bā]"],
["oka","第八 [dì bā] (adj.)"],
["okcidento","西 [xī]","西方 [xīfāng]"],
["oke","第八 [dì bā] (adv.)"],
["okuma","逢八进一 [féng bā jìn yī]"],
["oriento","东","tr. 東 [dōng]","东方","tr. 東方 [dōngfāng]"],
["pacismo","和平主义","tr. 和平主義 [hépíngzhǔyì]"],
["paco","和平 [hépíng]"],
["patrino","母 [mǔ]","母亲","tr.. 母親 [mǔqin]"],
["patro","父 [fù]","父亲","tr. 父親 [fùqin]"],
["pelmenoj","饺子","tr. 餃子 [jiǎozi]"],
["planedo","行星 [xíng xīng]"],
["pomo","苹果 [pǐng guǒ]"],
["programlingvo","编��‹语言 [biān chéng yǔ yán]"],
["revolucio","革命 [gémìng]"],
["rizo","米 [mǐ]"],
["rusa","俄 [é]"],
["rusujano, ruslandano","俄国人","tr. 俄國人 [éguórén]"],
["rusujo, ruslando","俄国","tr. 俄國 [Éguó]","俄罗斯 [Éluósī]"],
["ruĝa","红 [hóng]"],
["sama","同 [tóng]","一样 [yī yàng]"],
["satelito","卫星","tr. 衛星 [wèixīng] "],
["sekundo","秒 [miǎo]"],
["sendieco, sendiismo","无神论","tr. 無神論 [wúshénlùn]"],
["sendormeco","失眠 [shī mián]"],
["sep","七 [qī]"],
["sepa","第七 [dì qī]"],
["sepe","第七 [dì qī] (副词)"],
["ses","六 [liù]"],
["sesa","第六 [dìliù]"],
["sinjoro","先生 [xiānsheng]"],
["skribi","写","tr. 寫 [xiě]"],
["stelpomarbo, stelpomujo","金星果 [jīn xīng guǒ]"],
["substantivo","名词 [míng cí]"],
["sudo","南 [nán]","南方 [nánfāng]"],
["suno","日 [rì]","太阳","tr. 太陽 [tàiyáng]"],
["tago","天 [tiān]","日 [rì]"],
["tao","道 [dào]"],
["taoismo","道教 [dàojiāo]"],
["telefono","电话","tr. 電話 [diànhuà]"],
["tempo","时 [shí]","时态 [shí tài]"],
["teo","茶 [chá]","茶叶 [cháyè]"],
["terglobo","地球 [dìqiú]"],
["tero","土 [tǔ]","地球 [dìqiú] "],
["tipo","类型 [lèi xíng]"],
["toleri","忍 [rěn]"],
["tri","三 [sān]"],
["tria","第三 [dìsān] "],
["unu","一 [yī]"],
["unua","第一 [dìyī]"],
["urbano","市民 [shì mín]"],
["urbo","市 [shì]","城市 [chéng shì]","都市 [dū shì]"],
["uŝuo","武术 [wǔshù]","tr. 武術"],
["vagonaro","火车","tr. 火車 [huǒchē]"],
["vagono","车","tr. 車 [chē]"],
["valoriza","赋值 [fù zhí]"],
["variablo","变量 [biàn liàng]"],
["vejĉio","圍棋 (trad.)","围棋 [wéi qí] (simp.)"],
["vendejo","店 [diàn]","商店 [shāng diàn]"],
["vendi","卖 [mài]","售 [shòu]"],
["vento","风 [fēng]"],
["verda","绿 [lǜ]"],
["vespero","晚上 [wǎnshang]","夕 [xī]"],
["veturilo","车","tr. 車 [chē]"],
["vino","酒 [jiǔ]"],
["virina","女 [nǚ]"],
["virino","女人 [nǚ rén]","女子 [nǚ zǐ]","成年女子 [chéng nián nǚ zǐ]","妇女 [fù nǚ]"],
["vivi","活 [huó]","生 [shēng]"],
["vivo","生活 [shēnghuó]","生命 [shēngmìng]"],
["vjetnamo","越南人 [yuè nán rén]"],
["vjetnamujo","越南 [yuè nán]"],
["vortaro","词典","tr. 詞典 [cídiǎn]"],
["vorto","词","tr. 詞 [cí]"],
["zeno","禅","tr. 禪 [chán]"],
["Ĉikago","芝加哥"],
["ĉevalo","马","tr. 馬 [mǎ]"],
["ĉino","中国人 [zhōng guó rén]","中华民族 [zhōng huá mín zú]","华人 [huá rén]"],
["ĉinujo","中国 [Zhōngguó]","tr. 中國 [Zhōngguó] ","中华 [Zhōng huá]","tr. 中華 [Zhōng huá]"],
["ĉu","吗","tr. 嗎 [ma]"],
["ĝi","它 [tā]"],
["ĝia","它的 [tāde]"],
["ĥino","中国人"],
["ĥinujo","中国"],
["ŝi","她 [tā]"],
["ŝia","她的 [tāde]"],
];
var revo_zh_lower = revo_zh.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
