// La Reta Vortaro, GPLv2
'use strict';
var revo_no = [
["Afrikano","afrikaner"],
["Afriko","Afrika"],
["Akada","akkadisch"],
["Akado","Akkad","Agade"],
["Akadujo","akkadisk rike"],
["Aleksandro","Aleksander"],
["Aleksandro la Granda","Aleksander den store"],
["Arkansaso","Arkansas"],
["Arĥimedo","Arkimedes"],
["Balkano","Balkan"],
["Bankoko, Bangkoko","Bangkok"],
["Belgio","Belgia"],
["Bolivio","Bolivia"],
["Bruselo","Brussel"],
["Centr-Afriko","Sentral-Afrika"],
["Cindra merkredo, Cindromerkredo","askeonsdag"],
["Danio","Danmark"],
["Estonio","Estland"],
["Eŭropa","europeisk"],
["Eŭropo","Europa"],
["Fejsbuko, Vizaĝlibro","Facebook"],
["Flandrio","Flandern"],
["Francio","Frankrike"],
["Gabono","Gabon"],
["Germanio","Tyskland"],
["Goao","Goa"],
["Grekio","Hellas"],
["Gronlando","Grønland"],
["Henriko","Henrik"],
["Hindukuŝo","Hindu Kush"],
["Hispanio","Spania"],
["Islando","Island"],
["Israela","israelsk"],
["Israelano","israelier"],
["Israelo","Israel"],
["Italio","Italia"],
["Kenjo","Kenya"],
["Kopenhago","København"],
["Marteno","Morten"],
["Masaĉuseco","Massachusetts"],
["Minesoto","Minnesota"],
["Misisipio","Mississipi"],
["Misisipo","Mississipi"],
["Misurio","Missouri"],
["Misuro","Missouri"],
["Miĉigano","Michigan"],
["Miŝnao","Misjná"],
["Miŝno","Misjná"],
["Mocarto","Mozart"],
["Nederlanda","nederlandsk"],
["Nederlandano","nederlender"],
["Nederlando","Nederland"],
["Nevado","Nevada"],
["Norvegio","Norge"],
["Novlando","Newfoundland"],
["Novlando kaj Labradoro","Newfoundland og Labrador"],
["Noŭruzo","nauroz"],
["Organizaĵo por ekonomiaj Kunlaboro kaj Evoluigo","Organisasjon for Økonomisk Samarbeid og Utvikling","OECD"],
["Pluto","Pluto"],
["Portugalio","Portugal"],
["Prago","Praha"],
["Rejno","Rhinen"],
["Sebastiano","Sebastian"],
["Sud-Afriko","Sør-Afrika"],
["Sudano","Sudan"],
["Svedio","Sverige"],
["Svisio","Sveits"],
["Tebo","Theben"],
["Teto, Tetfesto","tet"],
["Tvitero, Tŭitero","Twitter"],
["Venero","Venus"],
["Venezuelo","Venezuela"],
["Venuso","Venus"],
["Zimbabvo","Zimbabwe"],
["al","til"],
["al antaŭ, antaŭ ...-n","foran"],
["al apud, apud ...-n","ved (retning)"],
["al malantaŭ, malantaŭ ...-n","bak"],
["alia","annen"],
["alie","ellers"],
["aligi","legge til","melde på"],
["aliigi","endre"],
["aliiĝi","endre seg"],
["alio","noe annet"],
["aliĝi","melde seg på","bli med på"],
["aliĝilo","påmeldingsskjema"],
["alko","elg"],
["almenaŭ","i det minste"],
["amanto, amantino","kjæreste","elsker","elskerinne","amatør"],
["amataĵo","hobby"],
["amaĉi, amaĵi","knulle"],
["amaĵisto, amaĵistino","elsker","elskerinne"],
["ameti","like"],
["ami","elske"],
["amika","vennlig"],
["amikaĵo","vennetjeneste"],
["amikeco","vennskap"],
["amikino","venninne"],
["amiko","venn"],
["amindumi","flørte"],
["amo","kjærlighet"],
["amovendistino","prostituert"],
["amovendisto","prostituert"],
["anarĥia","anarkistisk"],
["anarĥiismo","anarkisme"],
["anarĥiisto","anarkist"],
["anarĥio","anarki"],
["anarĥiulo","anarkist"],
["anaso","and"],
["ankaŭ","også"],
["ankoraŭ","ennå","enda"],
["ansero","gås"],
["antaŭ","foran","før","for ... siden","fremfor"],
["antaŭ ke","før"],
["antaŭ ol, antaŭ kiam","før"],
["antaŭa","fremre","forrige"],
["antaŭanto","forløper"],
["antaŭaĵo","forside","det forrige"],
["antaŭe","foran","før"],
["antaŭen","frem","fremover"],
["antaŭenema","foroverlent"],
["antaŭenigi","fremme"],
["antaŭlonge","for lenge siden"],
["antaŭnelonge, antaŭ nelonge","for ikke lenge siden"],
["antaŭo","forside","det forrige"],
["antaŭpagi","forhåndsbetale"],
["antaŭulo","forganger"],
["apartenaĵo","eiendom"],
["aparteni","tilhøre"],
["aporio","aporie"],
["aprilo","april"],
["apud","ved","i nærheten av"],
["apuda","like ved"],
["arbaro","skog"],
["arbetaro","buskas"],
["arbeto","busk"],
["arbo","tre"],
["argumenti","argumentere"],
["argumento","argument"],
["artrozo","artrose"],
["aspekti","se ut som","virke (se ut som)","synes (se ut som)"],
["aspekto","syn"],
["asteroido","asteroide"],
["ato-","atto-"],
["atrio","atrium"],
["avino","bestemor"],
["avo","bestefar"],
["aŭ","eller"],
["aŭ...","enten... eller..."],
["aŭdado","hørsel"],
["aŭdi","høre"],
["aŭdpovo, aŭdkapablo","hørsel"],
["aŭskultanto","lytter"],
["aŭskulti","lytte"],
["aŭtismo","autisme"],
["aŭtografo","autograf","signatur"],
["babilaĉi","bable"],
["babilejo","chattested"],
["babili","bable","småprate"],
["banala","banal"],
["barbiro","frisør"],
["bedaŭre","med sorg"],
["bedaŭri","sorge over","beklage seg over"],
["bedaŭrinda","sorgelig","beklagelig"],
["bedaŭrinde","beklageligvis"],
["bedaŭro","sorg","anger"],
["bela","vakker","pen"],
["beleco","skjønnhet"],
["belega","smellvakker"],
["beleta","søt"],
["belgujo","Belgia"],
["beligaĵo","pynt"],
["birdo","fugl"],
["birdoj","fugler"],
["bludento","Blåtann"],
["bobsledo","bobsleigh","bobsled"],
["bona","god","bra","dårlig","slem"],
["bone","godt","bra","greit"],
["bopatrino","svigermor"],
["bopatro","svigerfar"],
["boraparato","boremaskin"],
["bori","bore"],
["borilo","bor"],
["bovaĵo","oksekjøtt"],
["bovido","kalv"],
["bovino","ku"],
["bovo","tyr"],
["burgo","borg"],
["caro","tsar"],
["cementi","sementere"],
["cemento","sement"],
["cent","hundre"],
["centi-","senti-"],
["centimetro","sentimeter"],
["centra","sentral"],
["centro","middelpunkt","sentrum","senter"],
["certa","sikker","viss","en viss"],
["certe","sikkert"],
["citrono","sitron"],
["citronujo","sitrontre"],
["cxehxoslovakio","Tsjekkoslovakia"],
["dana","dansk"],
["danka","takknemlig"],
["danke","takket være"],
["danke al, dank' al","takket være"],
["dankema","takknemmelig"],
["danki","takke"],
["danko, dankado","takk"],
["dankofesto, dankotago","høsttakkefest","takkefest"],
["dano","danske"],
["danujo","Danmark"],
["deci-","desi-"],
["deka-","deka-"],
["delegacio","delegasjon"],
["delegitaro","delegasjon"],
["delegito","representant"],
["delonge","i lang tid"],
["demono","demon"],
["depago","skatt"],
["dermito","dermatitis"],
["disfandi, forfandi","smelte vekk"],
["diveni","gjette"],
["dodekafonismo","dodekafoni","tolvtonemusikk"],
["dokumenti","dokumentere"],
["dokumento","dokument"],
["du","to"],
["dua","annen"],
["due","for det andre"],
["duobla","dobbel"],
["duoninsulo","halvøy"],
["duonpatrino","stemor"],
["duonpatro","stefar"],
["dura","hard"],
["duuma","binær"],
["egipta","egyptisk"],
["egipto","egypter","Egypt"],
["egiptujano","egypter"],
["egiptujo","Egypt"],
["ekonomia","økonomisk"],
["ekonomiisto","økonom"],
["ekonomio","økonomi"],
["eksa-","exa-"],
["elcento, elcentaĵo","prosent"],
["elektrokemio","elektrokjemi"],
["elektroĥemia","elektrokjemisk"],
["elektroĥemio","elektrokjemi"],
["ellabori","utarbeide"],
["ellogi","fralure"],
["elsendi","kringkaste"],
["empirismo","empirisme"],
["enamiĝi","forelske seg"],
["engaĝi","engasjere"],
["epistemologio","erkjennelsesteori","epistemologi"],
["epistemologo","epistemolog"],
["estona","estisk"],
["estonujo","Estland"],
["familia","familie-"],
["familio","familie"],
["fandi","smelte (gjøre til en væske)"],
["fandiĝi","smelte (bli væske)","smelte (emosjonelt)"],
["fantasmo","fantasme"],
["femto-","femto-"],
["finna","finsk"],
["finnlando, finnujo","Finland"],
["finno","finne","finlender","finlending"],
["firmo","firma","bedrift"],
["flandra","flamsk"],
["flandro","flamlender"],
["flandrujo","Flandern"],
["flavaj paĝoj","gule sider"],
["fojero","foajé"],
["forno","Smelteovnen (stjernebilde)"],
["frambo","bringebær"],
["frambujo","bringebær","bringebærbusk"],
["franca","fransk"],
["franca lingvo","fransk"],
["franclingvano","fransktalende"],
["franco","franskmann"],
["francujo","Frankrike"],
["fulmi","lyne"],
["fulmo","lyn"],
["fulmobati, fulmofrapi","lyne ned"],
["fulmotondro","uvær"],
["g","g (konsonant)","g (bokstav)"],
["gambo","ben"],
["gazetara konferenco","pressekonferanse"],
["geamantoj","kjærester"],
["generacio","generasjon"],
["generalo","general"],
["genuartrozo","artrose i kne","gonartrose"],
["geotermiko","jordvarme","geotermisk energi"],
["gepatroj","foreldre"],
["germana","tysk"],
["germano","tysk statsborger","tysker"],
["germanujo","Tyskland"],
["giga-","giga-"],
["graco","nåde"],
["grekujo","Hellas"],
["hejma","hus-"],
["hejme","hjemme"],
["hejmo","hjem"],
["hejmpaĝo","hjemmeside"],
["hekto-","hekto-"],
["hepatiko","blåveis"],
["hispana","spansk"],
["hispano","spanjol"],
["hispanujo","Spania"],
["homamo","filantropi"],
["honduro","Honduras"],
["humanitara","humanitær"],
["humoro","humør","humor"],
["imunoĥemio","immunokjemi"],
["inkubacio","inkubasjonstid"],
["insula","øy-"],
["insulano","øyboer"],
["insularo","arkipel"],
["insulo","øy"],
["interalie","blant annet"],
["itala","italiensk"],
["italo","italiener"],
["italujo","Italia"],
["jarcento","århundre"],
["jarduono","halvår"],
["jaro","år","millenium","årtusen"],
["jen","der","se der"],
["jen vi havas","der har du det"],
["jena","følgende","neste"],
["jene","som følger"],
["jeno","følgende"],
["jokto-","yokto-"],
["jota-","yotta-"],
["kajaŭ","og/eller"],
["kamplaboristo","landarbeider"],
["kanado","Canada"],
["kanajlo","slyngel"],
["kanapo","sjeselong"],
["kancero","kreft"],
["kandelo","lys (talg-)"],
["kandidati","kandidere"],
["kandidato","kandidat"],
["kankro","kreps","Kreps (stjernetegn)"],
["kantado","sang"],
["kantaĵo","sang"],
["kanteti","nynne"],
["kanti","synge"],
["kantisto","sanger"],
["kanto","sang"],
["kemio","kjemi"],
["kie","hvor"],
["kien","hvorhen"],
["kies","hvis","hvem sin"],
["kilo-","kilo-"],
["koksartrozo","hofteleddsartrose","artrose i hofte","coxartrose"],
["konferenco","konferanse"],
["koramikino","kjæreste"],
["koramiko","kjæreste"],
["kristnaskarbo","juletre"],
["krucreferenco","kryssreferanse"],
["kulposento","skyldfølelse"],
["kunfandi","sammensmelte"],
["kunlabori","samarbeide"],
["kunlaboro","samarbeid"],
["kunsendaĵo","vedlegg"],
["kunsentemo","empati"],
["kuskuso","couscous"],
["la","den","det"],
["labordonanto","arbeidsgiver"],
["laborema","ivrig"],
["laborestro","arbeidsleder","formann"],
["labori","jobbe","arbeide"],
["laboristo, laborulo","arbeider"],
["laborloko","arbeidsplass"],
["laboro","jobb","arbeid"],
["lamao","lama"],
["libera profesio","fritt yrke"],
["lingvosento","språkfølelse"],
["logi","lokke","tiltrekke"],
["logo, logaĵo","lokkemiddel"],
["longa","lang","kort"],
["longe","lenge","langt"],
["longo","lengde"],
["lumbartrozo","artrose i korsryggen"],
["lumjaro","lysår"],
["malamiko","uvenn","fiende"],
["malamo","hat"],
["malantaŭ","bak"],
["malantaŭa","bakre"],
["malantaŭe","bak (sted)"],
["malantaŭen","bak (retning)"],
["malantaŭo, malantaŭaĵo","bakside"],
["malapud","langt fra"],
["malbela","stygg"],
["malcerta, necerta","usikker","uviss"],
["mallaborema","lat"],
["mallogi","frastøte"],
["mallongigi","korte ned"],
["mallongigo","forkortelse"],
["malpacienca","utålmodig"],
["malpacienco","utålmodighet"],
["malunueco","uenighet"],
["malĝentila","uhøflig"],
["maŝinpafilo","maskingevær"],
["mega-","mega-"],
["memamo, sinamo","egoisme","egenkjærlighet"],
["memsufiĉo","selvforsynt"],
["merkatekonomio","markedsøkonomi"],
["merkredo","onsdag"],
["meteoro","meteor"],
["meteorologo","meteorolog"],
["meteorŝtono","meteoritt","meteorstein"],
["mezurunuo","enhet"],
["migdalarbo, migdalujo","mandeltre"],
["migdalo","mandel (nøtt)"],
["mikro-","mikro-"],
["mili-","milli-"],
["miliono","million"],
["milionulo","millionær"],
["mitokondrio","mitokondrium"],
["mitoĥondrio","mitokondrium"],
["monunuo","myntenhet"],
["mortpafi","skyte ned"],
["nano-","nano-"],
["neaŭdita","uhørt"],
["nelonge","kort"],
["nigra truo","sort hull"],
["nikabo","niqab"],
["nitrogeno","nitrogen"],
["norvega","norsk"],
["norvego","nordmann"],
["norvegujo","Norge"],
["nukartrozo","artrose i nakken"],
["nula","verdiløs"],
["nuligi","annulere","tilintetgjøre"],
["nuliĝi","forsvinne"],
["nulo","null"],
["nur se","kun hvis","bare hvis"],
["oksimoro","oxymoron"],
["omeroo","omer"],
["operaci","operere"],
["operaco","operasjon"],
["orelringo","øredobbe"],
["orielo","karnapp"],
["pacienca","tålmodig"],
["pacienci","være tådmodig"],
["pacienco","tålmodighet"],
["pafado, pafaro","salve"],
["pafi","skyte"],
["pafilego","kanon"],
["pafilo","gevær"],
["pafo","skudd"],
["pagejo","kasse"],
["pagi","betale"],
["pago","betaling"],
["pajlero","halmstrå"],
["pajlo","strå"],
["pala","blek"],
["palata","palatal"],
["palato","gane"],
["paleontologiisto","paleontolog"],
["paleontologio","paleontologi"],
["paletro","palett"],
["paligi","bleke"],
["paliseto","stokk"],
["paliso","pål","staur"],
["paliĝi","blekne"],
["palpebro","øyelokk","øye"],
["palpebrumi","blinke (med øynene)"],
["palpi","ta på","føle på"],
["patreco","farskap"],
["patrineco","morskap"],
["patrino","mor"],
["patrio","fedreland"],
["patro","far"],
["patroj","svigerforeldre","svigers"],
["patrujo","fedreland"],
["paĝo","side"],
["peta-","peta-"],
["petrolĥemio","petrokjemi"],
["piko-","piko-"],
["planekonomio","planøkonomi"],
["pliami","foretrekke"],
["plibeligi","pynte"],
["plibonigi","forbedre","utbedre"],
["plori","gråte"],
["plusendi","videresende"],
["pluvarbaro","regnskog"],
["poliartrozo","polyartrose"],
["poluri","polere","finpusse"],
["ponto","bro"],
["portugalujo","Portugal"],
["porĉiama","for alltid","evig"],
["porĉiame","for alltid","evig"],
["postnelonge, post nelonge","rett etterpå"],
["praavino","oldemor"],
["praavismo","atavisme"],
["praavo","oldefar"],
["prapatro","forfar"],
["preskaŭ ĉiuj","nesten alle"],
["prilabori","bearbeide"],
["printempo","vår"],
["profesio","yrke"],
["psikologo","psykolog"],
["punpagi","bøte"],
["punpago","bot"],
["puĉo","kuppforsøk"],
["puŝi","dytte"],
["puŝo","dytt"],
["rebonigi","reparere"],
["rekantaĵo","refregn"],
["repagi","betale tilbake"],
["retbabilejo","chattested"],
["rezino","harpiks","kvae"],
["ringo","ring"],
["sagao","saga"],
["satureo","sar"],
["se","hvis"],
["sendanka","utakknemmelig"],
["sendi","sende"],
["sendito","utsendt"],
["senhejmulo","husløse"],
["senlabora","arbeidsledig"],
["senlaboreco","arbeidsledighet"],
["senpaga","gratis"],
["senta","følelses-"],
["sentebla","merkbar"],
["senteble","merkbar"],
["sentema","følsom"],
["senti","føle"],
["sentilo","sensor"],
["sento","følelse"],
["sentumo","sans"],
["sinonimo","synonym"],
["skvaŝo","squash"],
["studjaro","skoleår"],
["subaŭskulti","avlytte"],
["sudoko","sudoku"],
["sufiĉa","nok"],
["sufiĉe","nok"],
["sufiĉega","rikelig"],
["suoma","finsk"],
["suomo","finne","finlender","finlending"],
["suomujo, Suomio","Finland"],
["superjaro","skuddår"],
["suspensio","suspensjon"],
["sveda","svensk"],
["svedo","svenske"],
["svedujo","Sverige"],
["svisa","sveitsisk"],
["svislando","Sveits"],
["sviso","sveitser"],
["svisujo","Sveits"],
["tera-","tera-"],
["testudo","skilpadde"],
["tie","der"],
["tien","dit"],
["tokipono","Toki pona"],
["tolteka","toltekisk"],
["tolteko","tolteker"],
["tribunalo","tribunal"],
["trista","trist"],
["tvisto","twist"],
["ulcero","sår"],
["unikorno","enhjørning"],
["unu","en","ett"],
["unua","første"],
["unue","først (och fremst)","for det første"],
["unueco","enighet"],
["unuigi","forene"],
["unuiĝi","forene seg"],
["unuo","enhet"],
["uzino","jernverk","fabrikkanlegg"],
["vakcinio","tyttebær"],
["virbovo","okse"],
["zepto-","zepto-"],
["zeta-","zetta-"],
["ĉ","ĉ (konsonant)","ĉ (bokstav)"],
["ĉar","fordi"],
["ĉe","ved"],
["ĉef-","hoved-"],
["ĉefa","hoved-"],
["ĉefo","sjef"],
["ĉeĥa","tsjekkisk"],
["ĉeĥo","tsjekker"],
["ĉeĥoslovakujo","Tsjekkoslovakia"],
["ĉeĥujo","Tsjekkia","Tsjekkisk Republikk"],
["ĉi tie, tie ĉi","her"],
["ĉi tien, tien ĉi","hit"],
["ĉiam","alltid"],
["ĉiama","evig"],
["ĉiom","alt sammen"],
["ĉioma","hele (mengde)"],
["ĉiu","hver","enhver"],
["ĉiujara","årlig"],
["ĉo","tsj"],
["ĉu","om"],
["ĉu...","om ... eller om ..."],
["ĝentila","høflig"],
["ĥamemoro, kamemoro","molte"],
["ĥaosa","kaotisk"],
["ĥaose","kaotisk"],
["ĥaoso","kaos","rot"],
["ĥemia","kjemisk"],
["ĥemiaĵo","kjemikalie"],
["ĥemio","kjemi"],
["ĥolero","kolera"],
["ĵus","nettopp"],
["ĵusa","nyeste","siste"],
["ŝtatrenverso","kuppforsøk"],
];
var revo_no_lower = revo_no.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
