// La Reta Vortaro, GPLv2
'use strict';
var revo_hr = [
["Francio","Francuska"],
["Germanio","Njemačka"],
["Herkulo","Herkul"],
["Jerusalemo","Jeruzalem"],
["abako","abak, abak"],
["abdiki","abdicirati"],
["abdiko","abdikacija"],
["aboco","abeceda, abecedar, osnove"],
["acero","javor"],
["alpako","alpaka"],
["anabaptismo","anabaptizam"],
["aĉetanto","kupac"],
["aĉetebla","kupljiv"],
["aĉeti","kupiti, potkupiti, podmititi"],
["aŭtismo","autizam"],
["burokratio","birokracija"],
["citosolo","citosol"],
["disidento","disident"],
["dizajni","dizajnirati"],
["dizajnisto","dizajner"],
["dizajno","dizajn"],
["elaĉeti","otkupiti"],
["estero","ester"],
["filateliisto","filatelist"],
["filatelio","filatelija"],
["francujo","Francuska"],
["germanujo","Njemačka"],
["griledoj","zrikavci"],
["insekticido","insekticid"],
["interŝanĝi","razmijeniti"],
["kanuo","kanu"],
["karateisto","karatist"],
["karateo","karate"],
["kareto","glavata želva"],
["katetero","kateter, sonda"],
["klimatologio","klimatologija"],
["kopernicio","kopernicij"],
["kopro","kopra"],
["livermorumo","livermorij"],
["lizosomo","lizosom"],
["metropolito","metropolit"],
["mi","ja"],
["mitozo","mitoza"],
["nikabo","nikab"],
["ok","osam"],
["okcidento","zapad"],
["oktobro","listopad"],
["okulo","oko"],
["orelo","uho"],
["poliestero","poliester"],
["poplino","puplin"],
["rakito","rahitis"],
["ravino","jaruga"],
["rentgenio","roentgenij"],
["ribosomo","ribosom"],
["salamo","salama"],
["salato","salata"],
["sapo","sapun"],
["semaforo","semafor"],
["senŝanĝa","neizmjenjen"],
["stadio","stadij, stadion, stadij, faza"],
["stomako","trbuh"],
["stupao","stupa"],
["sudo","jug"],
["supo","juha"],
["svedujo","Švedska"],
["tigo","stabljika"],
["timino","timin"],
["vango","obraz"],
["vino","vino"],
["vizaĝo","lice"],
["ĥameleono","kameleon"],
["ĥi","hi"],
["ĥitino","hitin"],
["ŝanĝa","promjenjiv"],
["ŝanĝi","promjeniti, promjeniti"],
["ŝanĝiĝi","mijenjati se"],
["ŝultro","rame"],
];
var revo_hr_lower = revo_hr.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
