// La Reta Vortaro, GPLv2
'use strict';
var revo_oc = [
["Davido, David","Dàvid"],
["Francio","França"],
["Germanio","Alemanha"],
["Ireneo","Irenèu"],
["Libio","Libia"],
["abatejo","abadiá"],
["abatinejo"," abadiá (de monjas)"],
["abatino","abadessa"],
["abato","abat"],
["abeledoj","Apids"],
["abelisto","apicultor","abelhaire"],
["abelo","abelha"],
["abelreĝino","abelha reina"],
["abelujo","bornat","bornhon","buc","brusc"],
["abio","avet"],
["abismo","abisme"],
["ablativo","ablatiu"],
["abnegacio","abnegacion","renonciament","sacrifici"],
["aboco","abecé","abecedari","beçaròlas"],
["abolicii","abolir"],
["adiaŭ","adieu","adieu-siatz"],
["aero","aire"],
["afabla","aimable"],
["afero","afar","causa"],
["ago","accion"],
["agrabla","agradable"],
["agro","camp"],
["aj","ai !"],
["akcidento","accident"],
["akvo","aiga"],
["al","a"],
["aldiri","ajustar"],
["alia","autre"],
["alie","autrament"],
["almenaŭ","al mens"],
["alveni","arribar"],
["ami","aimar"],
["amikino","amiga"],
["amiko","amic"],
["amo","amor"],
["amuzi","amusar"],
["angulo","angle","caire","cantonada","canton"],
["anstataŭ","al lòc de","allòc de"],
["antaŭe","abans"],
["antaŭeniri","avançar"],
["aparato","aparelh"],
["aperitivo","aperitiu"],
["apostrofi","elidir"],
["apostrofo","apostròf"],
["aprilo","abril"],
["aranĝi","adobar"],
["arbaro","bòsc"],
["arbo","arbre"],
["armeo","armada"],
["astro","astre"],
["atento","atencion"],
["atribui","atribuir"],
["aviadilo","avion"],
["aĵo","causa"],
["aŭdi","ausir"],
["aŭgusto","agost","August (prenom)"],
["aŭto","auto"],
["aŭtobuso","autobus"],
["aŭtuno","auton"],
["banano","banana"],
["bananujo","bananièr"],
["bano","banh"],
["bela","bèl"],
["besto","bèstia"],
["bezoni","aver besonh"],
["bezono","besonh"],
["biciklo","bicicleta"],
["biero","bièrra"],
["bileto","bilhet"],
["birdo","aucèl"],
["blanka","blanc"],
["blua","blau"],
["bona","bon"],
["botelo","botelha"],
["brako","braç"],
["bruo","bruch"],
["buŝo","boca"],
["cent","cent"],
["centimo","centim"],
["centro","centre"],
["cifero","chifra"],
["dekstra","drech"],
["dekstre","a drecha"],
["diri","dire"],
["dolo","dòl"],
["domo","ostal"],
["doni","donar","balhar","ajustar"],
["dormoĉambro","cambra"],
["eble","benlèu"],
["ekbruligi","alucar"],
["ekde","a partir de"],
["ekvidi","apercebre"],
["elekti","causir"],
["elturniĝi","s'adobar"],
["emancipi","desmancipar"],
["emancipo","desmancipacion"],
["embrigenezo, embriogenezo","embriogenèsi"],
["en","a"],
["enhavi","claure"],
["enteni","claure"],
["estingi","atudar"],
["estingiĝi","s'atudar"],
["facila","aisit"],
["farti","anar"],
["fazanedoj","Fasianids"],
["feliĉa","aürós"],
["feliĉe","aürosament"],
["fine","a la fin"],
["fine de","a la fin de"],
["fini","acabar"],
["finiĝi","s'acabar"],
["flugpilkado","voleibòl"],
["francujo","França"],
["fuksio","fúcsia"],
["garnituro","assortiment","ensortiment","garnidura","garniment"],
["genezo","genèsi","Genèsi"],
["germanujo","Alemanha"],
["ha","a"],
["halti","s'arrestar"],
["haltigi","arrestar"],
["havi","aver"],
["hela","clar"],
["helpi","ajudar"],
["hundo","can"],
["ia","una mena de"],
["irejo","camin"],
["iri","anar"],
["iu","qualqu'un","qualques unes","d'unes","un certan","qualque"],
["jaro","an"],
["je","a"],
["jen","aicí","vaquí"],
["kafejo","cafè"],
["kafo","cafè"],
["kamarado","camarada"],
["kamioneto","camioneta"],
["kamiono","camion"],
["kampo","camp"],
["kanti","cantar"],
["kapabla","capable"],
["kapo","cap"],
["kara","car"],
["kartono","carton"],
["kaŝi","amagar"],
["kaŭze de","a causa de"],
["kaŭzo","causa"],
["kiam","quand","al moment que"],
["kinaĵo","filme"],
["kinisto","cineasta"],
["kino","cinèma"],
["kiso","poton"],
["kitelo","sarguina","sarguin"],
["klara","clar"],
["klientaro","clientèla"],
["kliento","client"],
["komence de","al començament de"],
["konstrui","bastir"],
["konstruo","bastiment"],
["kontraŭe","al contrari"],
["korbopilkado","basquetbòl"],
["kosta","car","carestiós"],
["kropo","papach","fafièr","goitre","gome"],
["kruro","camba"],
["kun","amb","ambe"],
["kvin","cinc"],
["kvina","cinquen"],
["lacigi","alassar"],
["laciĝi","s'alassar"],
["laŭlonge de","al long de"],
["lerni","aprene"],
["leterkesto","bóstia de las letras"],
["leŭgo","lèga"],
["lumigi","alucar"],
["malagrabla","desagradable"],
["malalta","bas"],
["malantaŭe","darrièr","a l'endarrièr"],
["malnova","ancian"],
["malsupre","aval"],
["manpilkado","andbòl"],
["mensogi","mentir"],
["mensogo","bala"],
["meze de, meze en","al mièg de"],
["mezo","mièg"],
["mieno","aire"],
["mono","argent"],
["movi","bolegar"],
["moviĝi","se bolegar"],
["nebulastro","nebulosa"],
["negliĝa robo, ĉambra robo","rauba de cambra","vestit de dedins"],
["neniom","pas brica"],
["nomi","apelar"],
["nomiĝi","s'apelar"],
["nun","ara"],
["okazi","arribar"],
["okazo","cas"],
["oportuna","aisit"],
["orelo","aurelha"],
["orikso","orix"],
["paŝi","caminar"],
["piede","a pè","en caminant"],
["piedpilko","fotbòl"],
["piedvesto","cauçadura"],
["pilko","palma","bala","balon"],
["pinto","poncha","cap"],
["plaĉi","agradar"],
["plezurigi","agradar"],
["polemiko","polemica"],
["post","après"],
["postkropo","gresièr","peirièr"],
["posttagmezo","aprèp-miègjorn"],
["preskaŭ","quasi, gaireben"],
["pro","a causa de"],
["proksimume","a pauc près"],
["puŝi","butar"],
["rando","bòrd"],
["rigardi","agachar"],
["rilata","a respècte de"],
["saluti","saludar"],
["serĉi","cercar"],
["seĝo","cadièra"],
["sidigi","assetar"],
["sidiĝi","s'assetar"],
["skatolo","bóstia","caisseta"],
["skolopendro","escolopendra"],
["stacidomo","gara"],
["strato","carrièra"],
["sugesti","prepausar","suggerir"],
["sugesto","suggestion"],
["sukcesi","arribar","capitar"],
["supre","amont"],
["svedujo","Suècia"],
["tamen","çaquelà"],
["tiam","alara"],
["tie","aquí"],
["tiel","atal"],
["tiu","aquel"],
["trinki","beure"],
["tritiko","blat"],
["trudkitelo","camisa de fòrça"],
["universitato","universitat"],
["urbodomo","comuna, ostal comunal"],
["varma","caud"],
["varmigi","calfar"],
["viando","carn"],
["virabelo","abelha mascla","abelhard","fals bordon"],
["vizaĝo","cara"],
["vojo","camin"],
["voki","apelar"],
["ĉevalo","caval"],
["ĉi tie, tie ĉi","aicí"],
["ĉi tiu, tiu ĉi","aquel"],
["ĉielo","cèl"],
["ĉirkaŭ","a l'entorn de"],
["ĉirkaŭe","a l'entorn"],
["ĉiu","cada"],
["ĝentila","aimable"],
["ĝis","fins a","d'aicí"],
["ĝustatempe","a l'ora"],
["ŝanĝi","cambiar"],
["ŝanĝiĝi","cambiar"],
["ŝarĝi","cargar"],
["ŝati","aimar","agradar"],
["ŝlosilo","clau"],
["ŝranko","armari"],
["ŝuo","sabata"],
];
var revo_oc_lower = revo_oc.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
