// @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&dn=gpl-2.0.txt GPL-v2
// De La Reta Vortaro
'use strict';
var revo_ro = [
["Balkano","Peninsula Balcanică "],
["Kristnasko","Crăciunul"],
["Mediteraneo","Marea Mediterană"],
["Miŝno","Mişna"],
["Pasko","Paşti"],
["Pontio","Ponţiu"],
["Turkio","Тurcia"],
["abituriento","bacalaureat"],
["ablacio","ablaţiune"],
["abomena","detestabil"],
["abomenaĵo","detestare"],
["abomeni","detesta","urî"],
["abomeninda","detestabil"],
["abomeno","detestare"],
["abrupta","fulgerător"],
["absceso","peptic"],
["absido","absida"],
["absoluta","absolut","adevărat"],
["absolutismo","absolutism"],
["abstrakta","abstract"],
["abstraktaĵo, abstrakto","abstract"],
["abunda","abundent"],
["abundeco","exuberanţă"],
["abundi","abunda"],
["abundo","bogăţie"],
["abutmento","înapoi"],
["aceracoj","Aceraceae"],
["acerba","acid"],
["acetileno","acetilenă "],
["acetilo","acetil"],
["aceto","oţet"],
["acipensero","morun"],
["adaĝo","adagio"],
["adekvata","adecvat"],
["adenino","adenină"],
["adjudiki","inscriere"],
["adjunkto","asistent"],
["administracio","administraţie"],
["administrantaro","administraţie"],
["administrejo","administraţie"],
["administri","administra"],
["admiralo","amiral"],
["admiri","admira"],
["admoni","admonesta"],
["admono","admonestare"],
["adolesko","adolescenţă"],
["adoleskulo, adoleskanto","adolescent"],
["adolto","adult"],
["adori","adora","diviniza","venera"],
["adrenalino","adrenalină"],
["adzo","teslă"],
["aerodromo","aerodrom"],
["aerometro","hidrometru"],
["aeronaŭto","aviator"],
["aerostato","balon cu aer cald"],
["agonii","a agoniza"],
["ajatolo","Ajatollah"],
["akceli","a accelera"],
["aktuala","actual"],
["akurata","punctual"],
["akvohorloĝo","ceas de apă"],
["al post, post ...-n","din spate"],
["alterni","a alterna"],
["ametisto","ametist"],
["animi","anima","revigora","inspira"],
["animismo","animism"],
["animo","duhul"],
["ankoraŭ","încă"],
["antaŭhieraŭ","alaltăieri"],
["antaŭlasta","penultimul"],
["antaŭmanĝaĵo","gustare"],
["antaŭtagmezo","înainte de amiază","înainte de prânz"],
["antaŭtempa","înainte de timp"],
["antaŭvespero","seara dinainte"],
["anticipi","a anticipa"],
["antikva","antic"],
["antikvaĵo","antichităti"],
["aperitivo","aperitif"],
["apetito","apetit"],
["apetitveka","apetisant"],
["apostolo","apostol"],
["apozicio","apoziţie"],
["aprilo","aprilie"],
["arkaika","arhaic"],
["arta","artistic"],
["artaĵo","operă de artă"],
["artefarita","artificial"],
["artefaritaĵo","artefact"],
["artismo","artă"],
["artisto","artist"],
["arto","artă"],
["atendi","a aştepta"],
["aĝo","vârstă"],
["aŭdi","a auzi"],
["aŭdilo","căşti "],
["aŭgusto","august"],
["aŭtobusa haltejo","staţie de autobuz"],
["aŭtobushaltejo","staţie de autobuz"],
["aŭtuno","toamnă"],
["baldaŭ","în curând"],
["bankaŭtomato, monaŭtomato","bancomat"],
["banko","bancă"],
["belarta","artistic"],
["belartaĵo","operă de artă"],
["belarto","artă de frumuseţea"],
["bestoĝardeno, zoologia ĝardeno","zoo"],
["biero","bere"],
["bildkarto","ilustrată"],
["bracelethorloĝo","ceas cu brăţară"],
["brakhorloĝo","ceas de mână"],
["brasiko","varză"],
["bremsi","a frâna"],
["bremso","frână"],
["brulestingisto","pompier"],
["bufedo","bufet"],
["busa haltejo","staţie de autobuz"],
["bushaltejo","staţie de autobuz"],
["butero","unt"],
["cent","o sută"],
["centjaro","secol","veac"],
["cicumo","suzetă"],
["dancarto","dans artistice"],
["dati","a data"],
["dato","dată"],
["datreveno","aniversare"],
["de tempo al, tempal","uneori"],
["debuti","a debuta"],
["decembro","decembrie"],
["definitiva","definitiv"],
["denaska, kunnaskita","înnăscut"],
["desegnarto","grafica"],
["dimanĉo","duminică"],
["diurno","douăzeci şi patru de ore","zi (24 ore)"],
["doni","a da"],
["dramarto","artă dramatică","drama","teatrul dramatic"],
["dum","în timp ce"],
["efemera","efemer"],
["egala","egal"],
["egalanima","echilibrat"],
["egalanimeco","pace"],
["eks-","fost"],
["ekvinokso","ziua egală cu noaptea"],
["ekzemplo","exemplu"],
["elcento, elcentaĵo","dobândă","procente"],
["epoko","epocă"],
["erao","eră"],
["eskatologio","escatologie"],
["estanteco","prezent"],
["estaĵo","făptură"],
["esti","a fi"],
["estingi","a stinge"],
["estingiĝi","a se stinge"],
["estinteco","trecut"],
["estonteco","viitor"],
["esĥatologio","escatologie"],
["etanima","mărunte","minore"],
["etanimeco","mângâi","mangaiere"],
["etapo","etapă"],
["eterna","etern"],
["evolui","a evolua"],
["evoluo","dezvoltare"],
["facilanima","distras","frivol","frivole"],
["facilanimaĵo","nepăsare"],
["facilanimeco","nepăsare","frivolitate"],
["fajrestingilo","extinctor"],
["fajrestingisto","pompier"],
["fazo","fază"],
["februaro","februarie"],
["festo","sărbătoare"],
["fikstempo","termen"],
["fine","în sfârşit"],
["fini","a încheia"],
["finiĝi","a se încheia"],
["fino","sfârşit"],
["florbrasiko","conopidă"],
["floro","floare"],
["foj","uneori"],
["fojo","dată","oară"],
["foresto","absenţă","lipsă"],
["forgesi","a uita"],
["fotarto","fotografie","fotografie artistica"],
["freŝa","proaspăt"],
["frue, frutempe","devreme"],
["fruktoĝardeno","livadă"],
["ftizo","tuberculoză"],
["futuro","viitor"],
["glando","glandă"],
["golejisto","portar"],
["gordia nodo","nodul gordian"],
["granatarbo, granatujo","rodie"],
["granato","rodie"],
["grandanima","mărinimos"],
["grandanimeco","generozitate"],
["grenato","granat"],
["haltejo","staţie"],
["halti","a se opri"],
["haltigi","a opri"],
["haltigilo","frână"],
["halto","oprire","reţinere temporară","staţionare"],
["hasti","a se grăbi"],
["hieraŭ","ieri"],
["hodiaŭ","astăzi","azi"],
["horaro, horlibro","mersul trenurilor"],
["horloĝisto","ceasornicar"],
["horloĝo","ceas"],
["horo","oră"],
["iafoje, disfoje","uneori"],
["iam","cândva"],
["ideo","idee"],
["imagino","imago"],
["imperfekto","imperfect"],
["infana","de copil"],
["infanaĝo","copilărie"],
["infaneco","copilărie"],
["infano","copil"],
["intermita","intermitent"],
["interokazaĵo, flankokazaĵo","incident"],
["intertempe","între timp"],
["iu","cineva","un anumit"],
["jam","deja"],
["januaro","ianuarie"],
["jarcento","secol ","veac"],
["jarlibro","anuar"],
["jarmilo","mileniu"],
["jaro","an","mileniu"],
["julio","iulie"],
["juna","tânăr","bătrân","în vârstă","vechi"],
["junaĝo","tinereţe"],
["juneco","tinereţe"],
["junio","iunie"],
["junularo","tineret"],
["junulo","bătrîn"],
["jura persono","persoană juridică"],
["kadenco","cadenţă"],
["kaduka","caduc"],
["kadukaĵo","decadenţă"],
["kafo","cafea"],
["kalendaro","calendar"],
["kantarto","voce"],
["kapaŭdilo","căşti "],
["karbo","cărbune"],
["kiam","când"],
["kinarto","film","film artă","cinematografie"],
["kiu","cine"],
["klepsidro","clepsidră"],
["kolaziono","gustare"],
["komenci","a începe"],
["komenciĝi","a se începe"],
["komenco","început"],
["konstanta","constant"],
["konstruarto","arhitektură"],
["kontinuigi","a continua"],
["korbo","coşuleţ"],
["koridoro","coridor","culoar"],
["kotleto","cotlet"],
["krepusko","crepuscul"],
["krescento","semilună"],
["kreskaĵo","plantă"],
["kreski","a creşte"],
["kreskigi","a mări"],
["kresko","creştere"],
["kronologia","cronologie"],
["kronometro","cronometru"],
["kruco","cruce"],
["kuirarto","arte culinare"],
["kukolhorloĝo","ceas cu cuc"],
["kukolo","cuc"],
["kuracarto","terapie"],
["kuratoro","părinte custodian"],
["kvar","patru"],
["kvara","a patra","al patrulea"],
["kvare","pentru a patra oară"],
["kvaronjara","trimestrul"],
["kvarono","pătrime","un sfert"],
["larĝanima","deschide"],
["larĝanimeco","deschidere"],
["lasta","ultim"],
["leporo","iepure"],
["libertempo","concediu","vacanţă"],
["librejo","librărie"],
["libro","carte"],
["lignokarbo","mangal"],
["longtempe, longatempe","lung"],
["lundo","luni"],
["magazeno","depozit"],
["majo","mai"],
["malabunda","cumpănit","insuficient"],
["malfruiĝi","a întârzia"],
["malfruo","întârziere"],
["maljuneco","batrâneţe"],
["maljuniĝi","a îmbătrâni"],
["malĝoja","trist"],
["manto","mantodea"],
["manĝi","a mânca","a servi micul dejun","a servi prânzul","a servi cina"],
["manĝilaro","tacâmuri"],
["manĝo","hrană","mâncare"],
["manĝokarto","meniu"],
["mardo","marţi"],
["marto","martie"],
["matenmanĝo","mic dejun"],
["mateno","de dimineaţă","devreme"],
["matura","copt","matur"],
["memorarto","mnemonics"],
["merkredo","miercuri"],
["metroa haltejo","staţie de metrou"],
["metrohaltejo","staţie de metrou"],
["metroo","metrou"],
["meza","central","de mijloc"],
["meze de, meze en","în mijloc"],
["mezepoko","Evul Mediu"],
["mezo","mijloc"],
["mielo","miere"],
["mil","o mie"],
["minuto","minut"],
["momenta","momentan"],
["momento","clipă","moment"],
["monataĵo","ciclu","menstre"],
["monato","lună (calendaristică)"],
["mondaĝo","eră"],
["mono","ban"],
["morgaŭ","mâine"],
["morti","a muri"],
["mortigi","omorî","ucide"],
["mortintaĵo","cadavru"],
["morto","moarte"],
["motociklo","motocicletă"],
["muzeo","muzeu"],
["naski","a naşte"],
["naskiĝi","a se naşte"],
["natura persono","persoană fizică"],
["neforgesebla","de neuitat"],
["negliĝa robo, ĉambra robo","capod"],
["neniam","niciodată"],
["neplenaĝa","minor"],
["nodo","nod"],
["nokte","noaptea"],
["nokto","noapte"],
["noktomezo","miezul nopţii"],
["nomfesto","zi onomastică"],
["notlibro","agendă","carnet"],
["novembro","noiembrie"],
["nun","acum"],
["nuntempo","acum","în prezent"],
["nur","de-abia","doar"],
["ofte","adesea","deseori"],
["okazaĵo","eveniment"],
["okazi","a se întâmpla"],
["okazigi","a sorta"],
["oktobro","octombrie"],
["ono","moleculă","părticică"],
["ornamarto","artă decorativă"],
["pacienca","răbdător"],
["parolarto","retorica","artă oratoriei"],
["pasanto","pieton"],
["pasejo","trecere"],
["pasema","trecător"],
["pasi","a trece"],
["paŭzo","pauză"],
["pentrarto","pictură"],
["perfekta","perfect"],
["perfekto","perfect"],
["periodo","perioadă"],
["persona","personale"],
["personaro","dotare"],
["personaĵo","caracteristicile personale"],
["persone","persoana"],
["personeco","personalitate"],
["personigo","personalizare","întruchiparea"],
["persono","persoana"],
["piloto","aviator"],
["plenaĝa","major"],
["plenkreska","matur"],
["plenkreskulo","adult"],
["plu","încă","mai departe"],
["plui","a dura"],
["pluskvamperfekto","mai mult ca perfectul"],
["polpo","caracatiţă"],
["ponto","pod"],
["poplo","plop"],
["post","în spatele","peste"],
["posta","din spate"],
["poste","mai departe","mai târziu"],
["posten","mai departe"],
["postmanĝaĵo","desert"],
["postmorgaŭ","poimâine"],
["postmorta","postum"],
["posttagmezo","după amiaza"],
["posttempa","ulterior"],
["poŝhorloĝo","ceas de buzunar"],
["precedenco","precedent"],
["preciza","exact","perfect"],
["preni","a lua"],
["preparado","proscomidia","proteza"],
["preskaŭ","de aproape"],
["preta","gata"],
["preterito","trecut"],
["pretigi","a aranja","a pregăti"],
["prezenco","prezenţă"],
["printempo","primăvară"],
["proceso","proces"],
["procezo","proces"],
["prokrasti","a întârzia"],
["promenado","plimbare"],
["promeni","a se plimba"],
["prompta","prompt"],
["provizora","temporar"],
["provtempo, provotempo","perioadă de încercare"],
["publika ĝardeno","parc"],
["pugno","pumn"],
["pulso","puls"],
["rabato","rabat","reducere"],
["rampi","a se târî"],
["rapideco","rapiditate","viteză"],
["rapidi","a grăbi"],
["rapido","viteză"],
["rapidumo","viteză"],
["reno","rinichi"],
["ritmo","ritm"],
["robo","rochie"],
["sabato","sâmbătă"],
["salo","sare"],
["samaĝulo","de aceeasi vârstă"],
["samtempa","concomitent"],
["sapori","a plăcea"],
["saporo","gust"],
["saŭco","sos"],
["seksto","sextă"],
["sekundo","secundă"],
["semajno","săptămână"],
["senhalta","fără oprire"],
["senĉesa","neîncetat"],
["septembro","septembrie"],
["sesto","sextă"],
["sezono","sezon"],
["siatempe","la timpul său"],
["sinmortigo","sinucidere"],
["skulptarto","sculptură"],
["skutilo","trotinetă"],
["somera tempo","ora de vară","vară"],
["somero","vară"],
["sorĉarto","magie","artă de magie"],
["spaco","spaţiu"],
["stadio","stadiu"],
["suicido","suicid"],
["sunhorloĝo","ceas solar"],
["sunleviĝo","răsărit de soare"],
["suno","soare"],
["surrena","glandă suprarenală"],
["surrena glando","glandă suprarenală"],
["suveniro","suvenir"],
["suĉilo","biberon"],
["suĉinfano","sugar"],
["tage","zilnic"],
["tagiĝi","în zori"],
["taglibro, tagolibro","jurnal"],
["tagmanĝo","prânz"],
["tagmezo","amiază"],
["tagnoktegaleco","ziua egală cu noaptea"],
["tagnokto","douazeci si patru de ore","zi (24 ore)"],
["tago","zi(uă)"],
["teatro","teatru"],
["telefonlibro","carte telefonică"],
["tempaĝo","epocă"],
["tempo","timp"],
["terkarbo, minkarbo","huilă"],
["tiam","atunci"],
["tuj","imediat","îndată","numaidecât"],
["unuanime","în unanimitate"],
["ununura","unic"],
["urĝi","a urgenta"],
["vaporo","abur"],
["varii","a varia"],
["varmaera aerostato","balon cu aer cald"],
["vekhorloĝo","ceas deşteptător"],
["velki","a se ofili"],
["vendredo","vineri"],
["vespermanĝo","cină"],
["vespero","seară"],
["vinagro","oţet"],
["vintra tempo","ora de iarnă","iarnă"],
["vintro","iarnă"],
["Ĉikago","Chicago"],
["ĉeko","cec"],
["ĉesi","a înceta"],
["ĉi-tage","azi"],
["ĉiam","mereu","totodeauna"],
["ĉielo","cer"],
["ĉiutaga","zilnic"],
["ĝardeno","grădină"],
["ĝis","până la"],
["ĝisnuna","până acum"],
["ĝustatempe","la timp"],
["ĵaŭdo","joi"],
["ĵus","tocmai"],
["ĵusa","proaspăt (nou)"],
["ŝanĝi","a schimba"],
];
var revo_ro_lower = revo_ro.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
// @license-end
