// @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&dn=gpl-2.0.txt GPL-v2
// De La Reta Vortaro
'use strict';
var revo_uk = [
["Argentino","Аргентіна"],
["Babelturo","Вавилонська вежа"],
["Bagdado","Багдад"],
["Bahamoj","Багамські острови"],
["Baĥo","Бах"],
["Besarabio","Бесарабія"],
["Brazilo","Бразілія"],
["Farado","Майкла Фарадея","фарад"],
["Fejsbuko, Vizaĝlibro","Фейсбуку"],
["Gelderlando","Гелдерланд"],
["Herkulo","Геркулес"],
["Hipokrato","Гіппократ"],
["Kieva Regno","Київська Русь"],
["Kievo","Київ"],
["Morfeo","Морфей"],
["Ohio","Огайо"],
["Polio","Польща"],
["Urugvajo","Уругвай"],
["abelo","бджола"],
["ailanto","айлянт"],
["ajmara","аймара"],
["ajmaro","аймара"],
["aksiomo","аксіома"],
["aksono","аксон"],
["alburno","верховодка"],
["alpako","альпака"],
["anabolo","анаболізм"],
["araŭkariacoj","араукарієві"],
["argilo","глина"],
["avelo","горіх (звичайний)"],
["avelujo","ліщина","горішина"],
["babilaĉi","теревенити","варнякати","базікати","точити ляси"],
["bagatela","дріб’язковий","незначний","неістотний"],
["bakalaŭro","бакалавр"],
["bibliografio","бібліографія"],
["borso","біржа"],
["brulego","пожежа"],
["brulestingisto","пожежник"],
["burokratio","бюрократія"],
["cinikismo","цинізм"],
["danka","вдячний"],
["danki","дякувати"],
["disertacio","дисертація"],
["disidento","дисидент"],
["esti","бути"],
["estingi","гасити"],
["fajrestingilo","вогнегасник"],
["fajrestingisto","пожежник"],
["filateliisto","філателіст"],
["filatelio","філателія"],
["fitingo","Фітинг"],
["fokstroto","фокстрот"],
["fregato","фрегат"],
["gladiolo","гладіолус"],
["grafito","графіт"],
["grejso","ґрейзен"],
["harmoniumo","фісгармонія"],
["hemiono","кулан"],
["ignamo","ямс"],
["ileo","клубова кишка"],
["incendio","пожежа"],
["individualismo","індивідуалізм"],
["infana","дитячий"],
["infano","дитина"],
["iriso","райдужна оболонка","ірис"],
["koano","коан"],
["koloraturo","колоратура"],
["kolzo","рапс","кольза"],
["konfeto","конфетті"],
["kontrakturo","контрактура"],
["kortisolo","кортизол"],
["kortizolo","кортизол"],
["krotalo","справжній гримучник"],
["kvadrigo","квадрига"],
["kvazaro","квазар"],
["lavurso, lavurseto","єнот"],
["leontodo","кульбаба"],
["livermorumo","ліверморій"],
["metopo","метопа","метоп"],
["metropolito","митрополит"],
["miozoto","незабудка"],
["mirinfano","вундеркінд"],
["misiisto","місіонер"],
["misio","місія"],
["muskedisto","мушкетер"],
["muskedo","мушкет"],
["musketisto","мушкетер"],
["musketo","мушкет"],
["naturo","природа"],
["nikabo","Нікаб"],
["nitrata acido","азотна кислота"],
["nitrato","нітрат"],
["nitrido","нітрид"],
["nitrita acido","азотиста кислота"],
["nitrito","нітрит"],
["obelisko","обеліск"],
["ondo","хвиля"],
["pino","сосна"],
["polemiko","полеміка"],
["pollando","Польща"],
["polujo","Польща"],
["prociono","єнот"],
["programo","програма"],
["satureo","чабёр"],
["sendanka","невдячний"],
["senfina","безкінечний"],
["soleco","самота"],
["solidara","солідарний"],
["stifto","штифт"],
["sturmi","штурмувати"],
["sturmo","штурм"],
["sturno","шпак"],
["suferi","страждати"],
["suĉinfano","немовля"],
["tigo","стебло"],
["triglifo","тригліф"],
["trio","тріо"],
["tujo","туя"],
["viktimo","жертва"],
["vilaĝo","село"],
["vivero","вівера"],
["vizo","віза"],
["zloto","злотий"],
["Ĉilio","Чилі"],
["Ĝenovo","Генуя"],
["Ĥarkovo","Харків"],
["Ĥarono","Харон"],
["ĥameleono","хамелеон"],
["ĥilo","хілус"],
];
var revo_uk_lower = revo_uk.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
// @license-end
