// La Reta Vortaro, GPLv2
'use strict';
var revo_vo = [
["-a","-ik"],
["-an","-an"],
["-aĉ","lu-"],
["-eg","le-"],
["-ej","-en"],
["-et","-il"],
["-in","ji-"],
["-ist","-an"],
["-o","-"],
["-ul","-an"],
["Afrikano","fikopel"],
["Afriko","Fikop"],
["Ameriko","Melop"],
["Aziano","silopel"],
["Azio","Silop"],
["Aŭstralio","Talop"],
["Belgio","Beljän"],
["Biblio","bib"],
["Eŭropa","yulopik"],
["Eŭropo","Yulop"],
["Francio","Fransän"],
["Germanio","Deutän"],
["Romo","Rom"],
["Volapukisto","volapükel"],
["Volapuko","Volapük"],
["aero","lut"],
["ajn","sem-"],
["akademio","kadem"],
["akompani","kopanön"],
["al","äl, -e, -e"],
["alia","votik"],
["alveni","kömön"],
["ambaŭ","bofik"],
["angla","nelijik"],
["anglo","nelijel"],
["anglujo","Nelij"],
["ankaŭ","i"],
["antaŭ","bif, bif, büf"],
["aprilo","apul"],
["apud","neb"],
["aĉeti","lemön"],
["aĥ","ag"],
["aŭ","u, ud"],
["aŭdi","lilön"],
["aŭgusto","gustul"],
["aŭtuna","flukatimik"],
["aŭtuno","flukatim"],
["baki","bakön"],
["baldaŭ","sun"],
["bani","banön"],
["banko","leböb"],
["bano","ban"],
["barbo","balib"],
["bela","jönik"],
["belga","beljänik"],
["belgo","beljänel"],
["belgujo","Beljän"],
["biero","bil"],
["bildo","mag"],
["biliono","telion"],
["blanka","vietik"],
["blankaĵo, blanko","din vietik"],
["blanketa","vietilik"],
["blanko","viet"],
["blankulo","vietel"],
["blua","yulibik"],
["bona","gudik"],
["brako","lam"],
["buŝa","mudik"],
["buŝego","lemud"],
["buŝo","mud"],
["cent","tum"],
["ci","ol"],
["danka","danik"],
["danke","dano"],
["danke al, dank' al","dano"],
["danki","danön"],
["danko, dankado","dan"],
["de","-a"],
["decembro","dekul"],
["dek","bals"],
["dekstra","detik"],
["dekstre","detiko"],
["demandi","säkön"],
["demando","säk"],
["des","plu"],
["dika","bigik"],
["dimanĉo","soldél [1a], soldel [1b], balüdel [3]"],
["do","also"],
["domo","dom"],
["doni","givön"],
["du","tel"],
["eble","ba"],
["egala","leigik"],
["ek","suso"],
["el","se"],
["elen","se"],
["elirejo","segol"],
["esti","binön"],
["estimi","stimön"],
["estimo","stim"],
["fabriki","fablüdön"],
["fabriko","fablüd"],
["fajro","fil"],
["fali","falön"],
["falo","fal"],
["fari","mekön"],
["februaro","febul"],
["fera","lelik"],
["fero","lel"],
["fi-","lu-"],
["filino","jison"],
["filo","son"],
["fino","fin"],
["fiŝo","fit"],
["flanko","flan"],
["flava","yelibik"],
["franca","flentik"],
["franca lingvo","flentapük"],
["franclingvano","flentapükan"],
["franco","flentel"],
["francujo","Fransän"],
["fratino","jiblod"],
["frato","blod"],
["fulmo","lelit"],
["gambo","lög"],
["germana","deutik [pp. etno, kulturo], deutänik [pp. lando]"],
["germano","deutänel, deutel"],
["germanujo","Deutän"],
["gramatiko","glamat, glamatabuk"],
["granda","gletik"],
["grandegulo","gletel"],
["grando","glet"],
["griza","gelik"],
["grundo","glun"],
["halti","stopön"],
["havi","labön"],
["hela","klilik"],
["hieraŭ","yesdel"],
["homa","menik"],
["homaro","menad"],
["homo","men"],
["horo","hol"],
["hundo","dog"],
["ie","egefo"],
["iel","semlik"],
["ili","oms [nur viroj], ofs [nur inoj], ons [en aliaj okazoj]"],
["iluzia","citik"],
["iluzii","citön"],
["iluzio","cit"],
["imperatoro","limep"],
["imperiestro","limep"],
["ina","jilik"],
["infana","cilik"],
["infano","cil"],
["instrua","tidik"],
["instruado","tidüp"],
["instrui","tidön"],
["instruisto","tidel"],
["instruo","tidam"],
["insulano","nisulel"],
["insulo","nisul"],
["io","bos"],
["ioma","anik"],
["iri","golön"],
["itala","tälik"],
["italo","tälel"],
["italujo","Täl"],
["iu","ek"],
["jam","ya"],
["januaro","yanul"],
["jaro","yel"],
["jen","vö"],
["jes","si"],
["julio","yulul"],
["juna","yunik, bäledik"],
["junio","yunul"],
["kafo","kaf"],
["kaj","e"],
["kanti","kanidön"],
["kanto","kanid"],
["kapabli","kanön"],
["kapo","kap"],
["ke","das"],
["kemio","kiem"],
["kial","kikod, kikod"],
["kiam","ven, sesun"],
["kie","kiplad, kö"],
["kiel","äs, kibid, äslik"],
["kio","kios, kios, kelos"],
["kiu","kiomik [vira], kiofik [ina], kiosik [aĵa], kel"],
["koleri","vutön"],
["kolero","vut"],
["komenci","beginön"],
["komenciĝo","begin"],
["koncerto","konzed"],
["konsideri","konsidön"],
["konsidero, konsiderado","konsid"],
["kontraŭ","kota"],
["kora","ladlik"],
["koro","lad"],
["korpa","kopik"],
["korpo","kop"],
["kuracisto","sanel"],
["kuraĝa","kinik"],
["kuraĝo","kin"],
["kuzino","jikösel"],
["kuzo","kösel"],
["kvankam","do"],
["kvar","fol"],
["kvin","lul"],
["labori","völigön"],
["laboro","völig"],
["lakto","milig"],
["lando","laned"],
["legi","liladön"],
["lernejo","jul"],
["lerni","lernön"],
["li","om, on"],
["lia","omik"],
["libera","libik"],
["libere","libiko"],
["libereco","lib"],
["libero","lib"],
["libro","buk"],
["lingvo","pük"],
["lito","bed"],
["longa","lonedik, blefik"],
["lumo","lit"],
["lundo","mundel"],
["majo","mayul"],
["malantaŭ","po"],
["maldekstra","nedetik"],
["malgranda","smalik"],
["malhela","dagik"],
["malkuraĝa","lukinik"],
["malkuraĝo","lukin"],
["mallaŭdi","blamön"],
["manĝaĵo","fid"],
["mardo","tusdel"],
["marko","mak"],
["marto","mäzul"],
["mateno","gödel"],
["merkredo","vesdel"],
["mi","ob"],
["mil","mil"],
["miliardo","baliad"],
["miliono","balion"],
["milita","kliga"],
["militi","kligön"],
["militisto","kligel"],
["milito","klig"],
["mondo","vol"],
["mono","mon"],
["monto","bel"],
["morgaŭ","model"],
["muzeo","musoföp"],
["muzika","musigik"],
["muziki","musigön"],
["muziko","musig"],
["naŭ","zül"],
["ne","ne, nenik"],
["neniam","nevelo"],
["nenio","nos"],
["neniu","nek, nonik"],
["ni","obs"],
["nia","obsik"],
["nigra","blägik"],
["nigra truo","hog blägik"],
["nordo","nolüd"],
["novembra","novulik"],
["novembro","novul"],
["nur","te, te"],
["oficiala","calik"],
["ofico","cal"],
["ok","jöl"],
["okazi","jenön"],
["okcidento","vesüd"],
["oksido","xüd"],
["oktobra","otulik"],
["oktobro","otul"],
["okulo","log"],
["onklino","jinök"],
["onklo","nök"],
["orienta","lefüdik"],
["oriente","lefüdiko"],
["orienti","lefüdön"],
["oriento","lefüd"],
["ortografio","lotogaf"],
["paco","püd"],
["papero","pöp"],
["paroli","pükön"],
["patrino","jifat"],
["patro","fat"],
["pensi","tikön"],
["piedo","fut"],
["plej","-ün"],
["pli","-um"],
["por","plo"],
["porko","svin"],
["posedaĵo","lab"],
["posedi","labön"],
["post","pos, po"],
["povi","kanön"],
["povoscii","kanön"],
["poŝtkarto","potakad"],
["poŝto","pot"],
["pra-","ül-"],
["preskaŭ","ti"],
["pri","dö"],
["primavero","flolatim"],
["printempo","flolatim"],
["pro","dem"],
["profesii","calön"],
["profesiisto, profesiulo","calel"],
["profesio","cal"],
["programo","plogam"],
["prononci","sepükön"],
["re-","ge-"],
["redoni","gegivön"],
["remilo","gub"],
["respondi","leblüdön"],
["respondo","leblüd"],
["reĝino","jireg"],
["reĝo","reg"],
["ricevi","getön"],
["riproĉi","leblamön"],
["riproĉo","leblam"],
["riverego","elflum"],
["rivereto","bluk"],
["rivero","flum"],
["roza","lolik"],
["rozeto","lolil"],
["rozo","lol"],
["rusa","lusik, lusänik"],
["ruso","lusel"],
["rusuja, ruslanda","lusänik"],
["rusujano, ruslandano","lusänel"],
["rusujo, ruslando","Lusän"],
["ruĝa","ledik"],
["sabato","sädel"],
["sana","saunik"],
["sano","saun"],
["savi","savön"],
["savo","sav, san"],
["scipovi","kanön"],
["se","if"],
["sed","ab"],
["sep","vel"],
["septembro","setul"],
["ses","mäl"],
["si","-ok"],
["sinjoro","söl"],
["somere","solatimo"],
["somero","solatim"],
["stacidomo","stejen"],
["stelo","stel"],
["strato","süt"],
["sub","dis"],
["subtenanto","yufel"],
["subteno","yuf"],
["sudo","sulüd"],
["sunfloro","solaflol"],
["suno","sol"],
["sur","su"],
["svedujo","Svedän"],
["svisa","jveizik"],
["svislando","Jveiz"],
["sviso","jveizel"],
["svisujo","Jveiz"],
["tablo","tab"],
["tagmezo","zendel"],
["tago","del"],
["taksi","stimön"],
["tamen","ye, yed, deno"],
["tasko","sugiv"],
["tempo","tim"],
["teni","yufön"],
["tero","glun, glun"],
["tial","sikod"],
["tiam","tän"],
["tie","us"],
["tiel","so"],
["tio","osat, atos"],
["tiu","at [vira], jiat [ina]"],
["tono","ton"],
["tra","da"],
["tri","kil"],
["trua, truhava","hogik"],
["trui","hogön"],
["truo","hog"],
["unu","bal"],
["urbego","lezif"],
["urbeto","zifil"],
["urbo","zif"],
["vendredo","flidel"],
["vento","vien"],
["verda","glünik"],
["vespero","vendel"],
["vidi","logön"],
["vintro","nifatim"],
["virina","vomik"],
["virino","vom, vom"],
["viva","lifik"],
["vivi","lifön"],
["vivo","lif"],
["viziti","visitön"],
["vizito","visit"],
["vojo","veg"],
["vokalo","vokal"],
["voki","vokön"],
["voko","vok"],
["voli","vilön"],
["ĉapitro","kapit"],
["ĉar","ibo"],
["ĉe","len"],
["ĉefo","cif"],
["ĉevaleto","jevalil"],
["ĉevalo","jeval"],
["ĉi tie, tie ĉi","is"],
["ĉiam","egelo"],
["ĉie","übal"],
["ĉio","valikos"],
["ĉirkaŭe","zü"],
["ĉiu","alik"],
["ĉokolado","jokolad"],
["ĝardeno","gad"],
["ĝentila","plütik"],
["ĝi","on"],
["ĝia","onik"],
["ĝis","jü"],
["ĝoja","gälik"],
["ĝoji","gälön"],
["ĝojo","gäl"],
["ĥemia","kiemik"],
["ĥemio","kiem"],
["ĵaŭdo","tödel"],
["ŝi","of"],
["ŝia","ofik"],
["ŝuo","juk"],
];
var revo_vo_lower = revo_vo.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
