// @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&dn=gpl-2.0.txt GPL-v2
// De La Reta Vortaro
'use strict';
var revo_sv = [
["-ebl","-bar"],
["-on","-del"],
["Adamo, Adam","Adam"],
["Adolfo","Adolf"],
["Afrikano","afrikan"],
["Afriko","Afrika"],
["Afrodito, Afrodita","Afrodite"],
["Amsterdamo","Amsterdam"],
["Angaro","Angara"],
["Argentino","Argentina"],
["Aziano","asiat"],
["Azio","Asien"],
["Babelo","Babel","Babylon"],
["Babelturo","Babels torn"],
["Babilonio","Babylonien"],
["Babilono","Babylon"],
["Baden-Virtembergano","Baden-Württembergare"],
["Baden-Virtembergo","Baden-Württemberg"],
["Bagdado","Bagdad"],
["Belgio","Belgien"],
["Bruselo","Bryssel"],
["Buĥoro","Buchara","Bukhara","Buxoro"],
["Celsio","Anders Celsius"],
["Cirilo","Kyrillos"],
["Damasko","Damaskus"],
["Davido, David","David"],
["Edeno","paradis"],
["Edeno, Eden","Eden"],
["Esperantisto","esperantist"],
["Esperanto","Esperanto"],
["Estonio","Estland"],
["Eŭklida","euklidisk"],
["Eŭklido","Euklides"],
["Eŭropa","europeisk"],
["Eŭropo","Europa"],
["Flandrio","Flandern"],
["Francio","Frankrike"],
["Germanio","Tyskland"],
["Gronlando","Grönland"],
["Holando","Hollánda"],
["Interreto","internet"],
["Jakobo, Jakob","Jakob"],
["Japanio","Japan"],
["Jenisejo","Jenissej"],
["Jerusalemo","Jerusalem"],
["Jesuo","Jesus"],
["Jido","jiddisch"],
["Johanino","Johanna"],
["Johano","Johan","Johannes"],
["Jupitero","Jupiter"],
["Kulombo","Charles de Coulomb","coulomb"],
["Linukso","Linux"],
["Luksemburgio","Luxemburg"],
["Luksemburgo","Luxemburg"],
["Moskvo","Moskva"],
["Namuro","Namur"],
["Nov-Zelando","Nya Zeeland"],
["Omo","ohm"],
["Paralimpiko","paralympiska spelen"],
["Rejno","Rhen"],
["Riado","Riyadh"],
["Svedio","Sverige"],
["Svisio","Svejts"],
["Turkio","Turkiet"],
["Unikodo","Unicode"],
["Unikso","Unix"],
["Uniksulo","Unix-användare","Unix-anhängare"],
["Urugvajo","Uruguay"],
["Usona","amerikansk (gällandes USA)"],
["Usonano","amerikan (USA-medborgare)","amerikansk medborgare (USA-medborgare)"],
["Usono","Amerikas förenta stater","USA"],
["Vathoro","wattimme"],
["Vato","Watt","watt"],
["Vitruvio","Vitruvius"],
["Vizbadeno","Wiesbaden"],
["Zamenhofo","Zamenhof"],
["Zelando","Zeeland"],
["Zeŭso","Zeus"],
["Zimbabvo","Zimbabwe","Republiken Zimbabwe"],
["a-vorto","adjektiv"],
["abandoni","abandonera"],
["abandono","abandonering"],
["abato","abbot"],
["abdiki","abdikera","avsäga sig"],
["abdomeno","mage","buk","abdomen"],
["abelmanĝulo","biätare"],
["abelo","bi"],
["abelsvarmo","bisvärm"],
["abelujo","bikupa"],
["abio","gran"],
["abismo","avgrund"],
["ablativo","ablativ"],
["aboco","alfabet","abc-bok","abc"],
["abomena","avskyvärd"],
["abomeni","avsky"],
["abomeninda","avskyvärd"],
["abomeno","avsky"],
["aboni","prenumerera","abonnera (på)","teckna ett abonnemang (på)"],
["abono","abonnemang","prenumeration"],
["aborti","få missfall"],
["abortigi","göra abort"],
["abrikoto","aprikos"],
["abrikotujo, abrikotarbo","aprikosträd"],
["abrotano","åbrodd"],
["abrupta","abrupt"],
["absceso","böld","bulnad"],
["absciso","abskissa","x-koordinat"],
["absinto","malört"],
["absorbi","fängsla","upptaga (sinnet)"],
["abstinado","avhållsamhet"],
["abstini","vara avhållsam"],
["abstrakta","abstrakt"],
["abstrakti","abstrahera"],
["absurda","absurd","orimlig"],
["abunda","riklig","ymnig"],
["abundeco","överflöd","rikedom"],
["aceracoj","lönnväxter"],
["acero","lönn"],
["acetato","acetat"],
["acetileno","acetylen","etyn"],
["acetilo","acetyl"],
["aceto","vinäger"],
["acetono","aceton","propanon","dimetylketon"],
["acida","sur","syrlig"],
["acido","syra"],
["acipenseredoj","störfiskar"],
["acipenserformaj","störartade fiskar"],
["acipensero","stör"],
["adapti","anpassa"],
["adekvata","adekvat","tillfredställande","passande","lämplig"],
["adenino","adenin"],
["adianto","adiantumsläktet"],
["adiaŭ","adjö"],
["adiaŭdiri","säga farväl","säga hejdå","säga adjö"],
["adiaŭi","säga farväl","säga hejdå","säga adjö","logga ut"],
["adicii","addera"],
["adicio","addition"],
["adjektivo","adjektiv"],
["administrantaro","administration (grupp, institution)"],
["administri","administrera"],
["admiralo","amiral"],
["admiri","beundra"],
["admoni","uppmana","förmana"],
["adori","dyrka","tillbedja","avguda"],
["adresanto","avsändare"],
["adresaro","adressbok"],
["adresato","adressat"],
["adresi","adressera","rikta"],
["adreso","adress"],
["adsorbi","adsorbera"],
["adsorbo","adsorption"],
["adulta","otrogen"],
["adulti","vara otrogen","begå äktenskapsbrott"],
["adulto","äktenskapsbrott"],
["advento","advent"],
["adverbo","adverb"],
["advokato","försvarare","advokat"],
["aero","luft"],
["aerobia","aerob"],
["aeroplano","flygplan"],
["aerosolo","aerosol"],
["aerumi","vädra"],
["afabla","vänlig"],
["afelio","aphelium"],
["afikso","affix","tilläggsstavelse"],
["afranki","frankera"],
["afto","afte"],
["aftozo","mul- och klövsjuka"],
["agariko","champinjon"],
["agavo","agave"],
["agi","agera"],
["aglo","örn","Örnen"],
["aglutina","agglutinerande"],
["aglutini","klistra ihop","foga samman"],
["agnoski","erkänna"],
["agrabla","trevlig","angenäm"],
["agresema","aggressiv"],
["agronomiisto","agronom"],
["agronomo","agronom"],
["agropiro","kamvete"],
["aideso","aids"],
["aidoso","aids"],
["aidosulo","aids-sjuk person"],
["ajlo","vitlök"],
["ajn","som helst"],
["akacio","akacia"],
["akademiano","akademiker"],
["akademio","akademi"],
["akanto","akantus"],
["akapari","uppköpa (i spekulationssyfte)","lägga beslag på"],
["akaĵunukso","cashewnöt"],
["akaĵuo","njurfrukt","acajoufrukt"],
["akceli","påskynda","främja","befordra"],
["akcelilo","gaspedal","accelerator"],
["akcenti","betona"],
["akcento","accent","tonvikt","betoning"],
["akcepti","mottaga","acceptera","antaga"],
["akcesora","bi-","tilläggs-"],
["akcia kompanio","aktiebolag","AB"],
["akcia societo","aktiebolag","AB"],
["akcidento","olyckshändelse"],
["akcio","aktie"],
["akcipitredoj","hökartade rovfåglar"],
["akcipitro","hök"],
["akcizo","accis","konsumtionsskatt"],
["akileo","rölleka"],
["akiri","förvärva","skaffa sig"],
["aklami","bifallsrop","acklamation"],
["aknero","finne"],
["akno","akne","finne"],
["akomodi","anpassa"],
["akompani","följa med","ledsaga","ackompanjera"],
["akonito","stormhatt"],
["akordi","överensstämma"],
["akordiono","dragspel"],
["akordo","ackord","samklang"],
["akra","vass","skarp","spetsig"],
["akridedoj","markgräshoppor"],
["akrido","gräshoppa"],
["akrigi","vässa"],
["akrobato","akrobat"],
["akromata","akromatisk"],
["akselo","armhåla"],
["aksiomo","axiom"],
["akso","axel"],
["aktinio","aktinium"],
["aktiniumo","aktinium"],
["aktuala","aktuell"],
["akuzativo","ackusativ"],
["akva","vatten-"],
["akvarelo","akvarell"],
["akvero","vattendroppe"],
["akvi","vattna"],
["akvifoliacoj","järneksväxter"],
["akvifolio","järnek"],
["akvilegio","akleja"],
["akvo","vatten"],
["akvoralo","vattenrall"],
["akvoturno","strömvirvel"],
["akvumi","vattna","bevattna"],
["al sub, sub ...-n","in under"],
["alburno","löja"],
["aldehido","aldehyd"],
["aleno","syl"],
["alezilo","Brotsch"],
["alfabeto","alfabet"],
["alfronti","konfrontera"],
["algebro","algebra"],
["algoj","alger"],
["alianco","allians"],
["aliteracio","allitteration"],
["alizarbo, alizujo","vitoxel"],
["aljuĝi","tilldöma"],
["alkaloido","alkaloid"],
["alko","älg"],
["alkroĉi","kroka fast"],
["alkroĉiĝi","haka sig fast"],
["almanako","almanacka"],
["almanaĥo","almanacka"],
["almozi, almozpeti","tigga"],
["almozisto","tiggare"],
["almozo","allmosa"],
["almozulo","tiggare"],
["alno","al"],
["aloo","aloe"],
["alta","hög"],
["alta frekvenco","högfrekvens"],
["altaĵo","höjd","kulle"],
["alterna kurento","växelström"],
["altigi","höja"],
["alumeto","tändsticka"],
["aluminio","aluminium"],
["alveolo","alveol"],
["alĉemilo","daggkåpa"],
["amarilidacoj","amaryllisväxter"],
["amatoro","amatör"],
["amboso","städ"],
["amelo","stärkelse"],
["amen","amen"],
["amento","hänge"],
["americio","americium"],
["ametisto","ametist"],
["amiko","vän"],
["aminacido, amina acido","aminosyra"],
["amoniako","ammoniak"],
["ampelopso","vildvin"],
["amplitudo","amplitud"],
["anagalo","mire"],
["analfabeteco","analfabetism"],
["analfabeto","analfabet"],
["analizi","analysera"],
["ananaso","ananas"],
["anarkia","anarkistisk"],
["anarkiismo","anarkism"],
["anarkiisto","anarkist"],
["anarkio","anarki","laglöshet"],
["anarkiulo","anarkist"],
["anarĥia","anarkistisk"],
["anarĥiismo","anarkism"],
["anarĥiisto","anarkist"],
["anarĥio","anarki","laglöshet"],
["anaso","and","anka"],
["anatomio","anatomi"],
["anekdoto","anekdot"],
["aneksi","införliva","annektera"],
["anemono","anemon","sippa"],
["angeliko","kvanne"],
["angilo","ål"],
["angino","halsfluss"],
["angla","engelsk"],
["anglo","engelsman"],
["anglujo","England"],
["anizo","anis"],
["anizujo","anis"],
["ankaŭ","också","även"],
["ankrejo","ankringsplats"],
["ankri","ankra"],
["ankro","ankare"],
["anodo","anod"],
["anonima","anonym"],
["anstataŭ","istället för"],
["anstataŭi","ersätta","substituera"],
["antaŭbrako","underarm"],
["antaŭhieraŭ","i förrgår"],
["antaŭlonge","för länge sedan"],
["antaŭmalhelpi","förhindra"],
["antaŭmeti","lägga fram"],
["antaŭnomo","förnamn"],
["antemo","kulla"],
["anteno","antenn"],
["antibiotiko","antibiotikum"],
["anticipi","föregripa"],
["antidoto","motgift","antidot"],
["antikrezo","pantsättning av fast egendoms avkastning"],
["antilopo","antilop"],
["antimono","antimon"],
["anĝelo","ängel"],
["aparteni","tillhöra"],
["apendicito","blindtarmsinflammation"],
["apendico","blindtarm"],
["apertaĵo","öppning"],
["apertigi","öppna"],
["aperturo","öppning"],
["apiacoj","flockblommiga växter"],
["apio","floka"],
["apogi","stödja"],
["apogilo","stöd"],
["apogseĝo, brakseĝo","fåtölj","länstol"],
["apologo","fabel"],
["aprilo","april"],
["araneaĵo","spindelväv"],
["araneo","spindel"],
["arbaro","skog"],
["arbitra","godtycklig"],
["arbo","träd"],
["arda","glödande"],
["ardaĵo","glöd"],
["ardeo","häger"],
["ardezo","skiffer"],
["ardi","glöda"],
["argilo","lera"],
["argono","argon"],
["aristolokiacoj","piprankeväxter"],
["aristolokio","pipranka"],
["arkaĵaro","arkad"],
["arkaĵo","båge"],
["arkeologiisto","arkeolog"],
["arkeologio","arkeologi","fornforskning"],
["arkeologo","arkeolog"],
["arki","bilda en båge"],
["arkigi","böja"],
["arkipelago","skärgård","övärld"],
["arkitekto","arkitekt"],
["arkitekturisto","arkitekt"],
["arkitekturo","arkitektur"],
["arko","båge","ljusbåge"],
["arniko","arnika"],
["aromo","arom","doft"],
["arseniko","arsenik"],
["arseno","arsenik"],
["artaĵo","konstverk"],
["artefarita","konstgjord"],
["artemizio","(släktet) malört"],
["artiklo","artikel (handel)"],
["artiko","led"],
["artikolo","artikel"],
["artileriano, artileriisto","artillerist"],
["artilerio","artilleri"],
["artisto","artist","konstnär"],
["arto","konst"],
["artrito","inflammation i en led","gikt"],
["arĉo","stråke"],
["arĝenta","av silver","silvrig"],
["arĝenti","försilvra"],
["arĝentisto","silversmed"],
["arĝentmevo","gråtrut"],
["arĝento","silver"],
["arĥeologiisto","arkeolog"],
["arĥeologio","arkeologi","fornforskning"],
["arĥitekto","arkitekt"],
["arĥitekturisto","arkitekt"],
["arĥitekturo","arkitektur"],
["asekuri","försäkra"],
["asekuro","försäkring"],
["aserti","påstå","försäkra"],
["aserto","påstående","försäkran"],
["asfalti","asfaltera"],
["asfalto","asfalt"],
["aso","ess"],
["asparago","sparris"],
["astateno","astat"],
["astato","astat"],
["asteracoj","korgblommiga växter"],
["astero","aster"],
["astrofiziko","astrofysik"],
["astronomiisto","astronom"],
["astronomio","astronomi"],
["astronomo","astronom"],
["ateismano","ateist"],
["ateismo","ateism"],
["ateisto","ateist"],
["atendejo","vänthall","väntrum"],
["atendi","vänta"],
["atlaso","satäng","satin","atlas"],
["atletiko","friidrott"],
["atletismo","friidrott"],
["atleto","atlet"],
["atmosfero","atmosfär"],
["ato-","atto-"],
["atolo","atoll","korallö"],
["atomo","atom"],
["atonio","atoni","slapphet","bristande muskelspänning"],
["atriplo","strandmålla"],
["atuto","trumf"],
["avataro","avatar"],
["avelo","hasselnöt"],
["avelujo","hassel"],
["aveno","havre"],
["averti","varsko","varna"],
["azaleo","azalea"],
["azaro","hasselört"],
["azeno","åsna"],
["azotacido","salpetersyra"],
["azoto","kväve","kvävgas"],
["aĉetanto","köpare"],
["aĉetebla","till salu"],
["aĉeti","köpa","muta"],
["aĉetisto","inköpare"],
["aĝo","ålder"],
["aĵo","sak"],
["aŭ","eller"],
["aŭdaca","djärv","våghalsig"],
["aŭdaci","vara djärv","vara våghalsig"],
["aŭdaco","djärvhet","våghalsighet"],
["aŭdienco","audiens"],
["aŭditorio","föreläsningssal"],
["aŭgusto","augusti"],
["aŭkcii","auktionera"],
["aŭkcio","auktion"],
["aŭtejo","garage"],
["aŭti","åka (bil)"],
["aŭtismo","autism"],
["aŭtisto","bilförare"],
["aŭto","bil"],
["aŭtobuso","bus"],
["aŭtomacio","automation"],
["aŭtomata","automatisk"],
["aŭtomate","automatiskt"],
["aŭtomato","automat"],
["aŭtomobilisto","bilförare"],
["aŭtomobilo","bil"],
["aŭtuno","höst"],
["babao","baba"],
["babilaĉi","babbla","svamla","tjattra"],
["babilejo","chatt"],
["babilema","pratglad"],
["babili","babbla","prata"],
["babilulo","pratkvarn"],
["babiruso","hjortsvin","babyrousa","babirusa"],
["babordo","babord"],
["bacilo","bacill"],
["badmintono","badminton"],
["bagatela","bagatellartad","ringa","obetydlig","betydelselös"],
["bagatelema","petig","pedantisk"],
["bagateli","vara bagatellartad"],
["bagateligi","bagatellisera"],
["bagatelo","bagatell"],
["bagaĝo","bagage"],
["bagno","straffkoloni","arbetsläger"],
["bajoneto","bajonett"],
["baksodo","bikarbonat"],
["bakterio","bakterie"],
["balai","sopa"],
["balanci","gunga (någon eller något)"],
["balancilo","gunga (subst.)","gungbräda"],
["balanciĝi","gunga (sig själv)","gungas"],
["balbuti","stamma"],
["baldaŭ","snart"],
["baleno","val"],
["baleto","balett"],
["balisto","katapult"],
["balo","bal"],
["balzaminacoj","balsaminväxter"],
["balzamino","balsamin"],
["bambuo","bambu"],
["banano","banan"],
["bandomo","badhus"],
["baobabo","baobabsläktet"],
["bapti","döpa"],
["bapto","dop"],
["baptonomo","förnamn"],
["barako","barack"],
["barba","skäggig"],
["barbara","barbarisk"],
["barbaro","barbar"],
["barbhava","skäggig"],
["barbiro","barberare"],
["barbisto","barberare"],
["barblano","fjun"],
["barbo","skägg"],
["barbulo","skäggig person"],
["bardo","bard"],
["bareliefo","planrelief","målerisk relief","lågrelief"],
["bario","barium"],
["basto","bast"],
["bati","slå"],
["bato","slag"],
["baŭ","vov"],
["bebo","bebis","bäbis","spädbarn"],
["begonio","begonia"],
["beko","näbb"],
["beladono","belladonna"],
["belgujo","Belgien"],
["benzeno","bensen"],
["benzinejo","bensinmack","bensinstation"],
["benzinkruĉo","bensindunk"],
["benzino","bensin"],
["benzinstacio","bensinmack","bensinstation"],
["benzinujo","bensintank"],
["berberiso","berberis"],
["bergamoto","bergamott"],
["berilio","beryllium"],
["berkelio","berkelium"],
["bero","bär","vindruva"],
["beto","beta"],
["betoniko","syska"],
["betulacoj","björkväxter"],
["betulo","björk"],
["bezoni","behöva"],
["bezono","behov"],
["biblioteko","bibliotek"],
["bicikli","cykla"],
["biciklo","cykel"],
["biero","öl"],
["bigamio","bigami","tvegifte"],
["bigamiulo","bigamist"],
["bilardo","biljard","biljardbord"],
["biogaso","biogas"],
["biologiisto","biolog"],
["biologio","biologi"],
["biologo","biolog"],
["bismuto","vismut"],
["bito","bit"],
["blanka","vit"],
["blankdorsa buntpego","vitryggig hackspett"],
["blankflugila mevo","vitvingad trut"],
["blankspegula maranaso","svärta"],
["blankvosta maraglo","havsörn"],
["blinda","blind"],
["blinde","blint"],
["blindigi","blända"],
["blito","bärmålla","smultronmålla"],
["bloko","block","kloss"],
["blua","blå"],
["blua cirkuo","blå kärrhök"],
["bludento","bluetooth","blåtand"],
["bluflugila anaso","blåvingad årta"],
["bluvanga abelmanĝulo","grön biätare"],
["boaco","ren"],
["boao","boaorm"],
["boji","skälla"],
["boksi","boxas"],
["bokso","boxning"],
["boleto","boletus"],
["boli","koka"],
["boligi","koka (något)"],
["bolkuiri","koka"],
["bolto","bult"],
["bolŝevika","bolsjevikisk"],
["bolŝeviko","bolsjevik"],
["bolŝevismano","bolsjevik"],
["bolŝevismo","bolsjevism"],
["bombo","bomb"],
["bonkora","godhjärtad"],
["boragacoj","strävbladiga växter"],
["bordelo","bordell"],
["bori","borra"],
["borilo","borr"],
["borio","bohrium"],
["boro","bor"],
["borpinto","borr"],
["botaglo","dvärgörn"],
["boteto","känga"],
["boto","stövel"],
["brako","arm","överarm"],
["brakumi","krama","omfamna"],
["bramo","braxen"],
["brankardo","bår"],
["brasikacoj","korsblommiga växter"],
["brasiko","kål"],
["brazila nukso","paranöt"],
["brazilnuksarbo, brazila nuksarbo","paranötsträd"],
["bretaro","hylla"],
["breto","hyllplan"],
["brodaĵo","broderi"],
["brodi","brodera"],
["brokolo","broccoli"],
["bromo","brom"],
["bronzo","brons"],
["brosi","borsta"],
["broso","borste"],
["brovo","ögonbryn"],
["brulofero","eldoffer"],
["bruna","brun"],
["brunkapa anaso","brunand"],
["bufedo","buffé"],
["bufo","padda"],
["bunta","färgglad"],
["buntpego","hackspett"],
["burdo","humla"],
["burĝonbrasiko, bruselbrasiko","brysselkål"],
["buso","buss"],
["butero","smör"],
["buterumi","smöra","breda (på smör)"],
["butikumi","butik"],
["butontruo","knapphål"],
["butonumi, butoni","knäppa"],
["buĉofero","slaktoffer"],
["caro","tsar"],
["cedrato","suckatcitron","cedrat","sötcitron"],
["cedratujo","cedratträd"],
["celerio","selleri"],
["cemento","cement"],
["cent","hundra"],
["centi-","centi-"],
["centilitro","centiliter"],
["centimetro","centimeter"],
["cenzuri","censurera"],
["cerbo","hjärna"],
["cerbolavo, cerbolavado","hjärntvätt"],
["cerbumi","grubbla","fundera"],
["cerefolio","småkörvlar"],
["ceremonio","ceremoni"],
["cerio","cerium"],
["cervo","hjort","ren"],
["cetera","övrig","resterande"],
["cetere","för övrigt"],
["cetero","rest"],
["cezio","cesium"],
["ci","du"],
["ciano","dicyan"],
["cifero","siffra"],
["ciklameno","cyklamen"],
["cikorio","cikoria"],
["cikuto","sprängört"],
["cindro","aska"],
["cindrujo","askfat"],
["ciperacoj","halvgräs"],
["cirkaeto","ormörn"],
["cirkelo","passare","Cirkelpassaren"],
["cirkuo","(kärr)hök"],
["cirkvito","(elektrisk) krets"],
["citosolo","cytosol"],
["citozino","cytosin"],
["citrono","citron"],
["citruso","citrus"],
["civila","civil"],
["colo","tum"],
["da","(mängd) av"],
["dadaismo","dadaism"],
["damaski","damastväva"],
["damasko","damastväv"],
["dana","dansk"],
["danci","dansa"],
["danco","dans"],
["danke al, dank' al","tack vare"],
["dankemo, dankemeco","tacksamhet"],
["danki","tacka"],
["danko, dankado","tack"],
["dano","dansk"],
["danujo","Danmark"],
["danĝera","farlig"],
["danĝero","fara"],
["darmŝtatio","darmstadtium"],
["dateno","data"],
["dati","datera"],
["dativo","dativ"],
["dato","datum"],
["datreveno","årsdag"],
["datumbanko","databank"],
["datumbazo","databas"],
["datumo","data"],
["de sub","från under"],
["debati","debattera"],
["debato","debatt"],
["debuti","debutera"],
["deca","anständig"],
["decembro","december"],
["deci-","deci-"],
["decigramo","decigram"],
["decilitro","deciliter"],
["decimala","decimal (med talbas tio)"],
["decimalo","decimal"],
["decimetro","decimeter"],
["defendi","försvara"],
["dek","tio"],
["deka-","deka-"],
["deksesuma","hexadecimal"],
["demandi","fråga"],
["demando","fråga"],
["demeti","ta av","ta bort"],
["demokratio","demokrati"],
["demokrato","demokrat"],
["dentbroso","tandborste"],
["dentkarno, dentokarno","tandkött"],
["dentrado","kugghjul"],
["dentskrapi, skrapmanĝi","gnaga"],
["des","desto"],
["desalti","hoppa ner"],
["deskrapi","skrapa bort"],
["desoksiribonuklea acido","deoxiribonukleinsyra","DNA"],
["destrojero","jagare (fartyg)"],
["detrua","förstörande"],
["detrui","förstöra"],
["detruo, detruado","förstörelse"],
["deturni, forturni","vända bort"],
["dia","gudomlig"],
["diabeto","diabetes"],
["diagnozi","diagnosticera"],
["diagnozo","diagnos"],
["dialogo","dialog"],
["diamanto","diamant"],
["diametro","diameter"],
["digneco","dignitet","värdighet"],
["digno","dignitet","värdighet"],
["dika","tjock"],
["diktatoro","diktator"],
["diligenta","flitig"],
["diligenti","vara flitig"],
["dimanĉo","söndag"],
["dinamiko","dynamik"],
["dinamito","dynamit"],
["dio","gud"],
["diodo","diod"],
["dioptriko","dioptrik"],
["direktoro","direktör"],
["diservo","gudstjänst"],
["disfaldi, malfaldi","vika upp"],
["disipi","slösa"],
["diskriminacii","diskriminera"],
["diskriminacio","diskriminering"],
["diskuti","diskutera"],
["disprozio","dysprosium"],
["dissalti","flyga isär"],
["distanco","avstånd"],
["disŝiri","riva sönder"],
["diurno","dygn"],
["doganisto","tulltjänsteman"],
["dogano","tull"],
["domaĉo","ruckel"],
["domeno","domino (cape med kapuschong)","domino (spel)\""],
["domo","hus"],
["dormegi","sova djupt"],
["dormema","sömnig","trött"],
["dormeti","dåsa","slumra"],
["dormi","sova"],
["dormigi","söva"],
["dormigilo","sömnmedel"],
["dormo","sömn"],
["doti","begåva","ge hemgift"],
["doto","hemgift"],
["dragono","dragon"],
["drakunkolo","dragon"],
["drama","teatrisk","dramatisk"],
["dramigi","dramatisera"],
["dramo","drama"],
["driado","dryad"],
["dromedaro","dromedar"],
["droni","drunkna","gå under","försjunka"],
["dronigi","dränka"],
["druido","druid"],
["du","två"],
["dubnio","dubnium"],
["dukotiledonaj","tvåhjärtbladiga"],
["dum","under (om tid)"],
["duobla","dubbel"],
["duonfrato","halvbror"],
["duonjaro","halvår"],
["duonluno","halvmåne"],
["duono","halv"],
["duonŝtrumpo","socka","strumpa"],
["duuma","binär"],
["duŝi","duscha (någon eller något)"],
["duŝo","dusch"],
["e-vorto","adverb"],
["ebla","möjlig"],
["eble","möjligen","kanske"],
["ebligi","möjliggöra"],
["eblo","möjlighet"],
["ebono","ebenholts"],
["ebria","berusad","full"],
["eburmevo","ismås"],
["eburo","elfenben"],
["edikto","påbud"],
["edilo","edil"],
["efektiva","verklig"],
["efektive","verkligen"],
["efektivigi","förverkliga"],
["efektiviĝi","förverkligas"],
["efelido","fräkne"],
["efemera","kortvarig"],
["efika","effektiv"],
["efikeco","effektivitet"],
["efiki","verka","ha verkan"],
["egoismo","egoism","själviskhet"],
["egoisto","egoist"],
["egopodio","kirskål"],
["ejnŝtejnio","einsteinium"],
["ekipi","utrusta"],
["eklipso","förmörkelse"],
["ekliptiko","ekliptikan"],
["ekonomiko","ekonomi"],
["ekonomio","ekonomi"],
["ekrano","bildskärm","skärm"],
["eksa-","exa-"],
["eksalti","hoppa till"],
["ekscelenco","excellens"],
["ekskurso","utflykt"],
["eksperimenti","experimentera"],
["eksperimento","experiment"],
["ekspliki","förklara"],
["eksplodi","explodera"],
["eksplodo","explosion"],
["ekster","utanför","utan"],
["ekstera","yttre"],
["ekstere","ute","på utsidan"],
["eksteren","utåt"],
["ekstermi","utrota"],
["ekstra","extra"],
["ekstrema","extrem"],
["ekstreme","extremt"],
["ekvatoro","ekvator"],
["ekzameni","undersöka","examinera"],
["ekzameno","undersökning","prov","tentamen"],
["ekzekuti","avrätta"],
["ekzemo","eksem"],
["ekzemple","till exempel"],
["ekzemplero","exemplar"],
["ekzemplo","exempel"],
["ekzili","landsförvisa","utvisa"],
["el sub","från under"],
["elaĉeti","friköpa","köpa loss"],
["elcento, elcentaĵo","procent"],
["elefanto","elefant"],
["elektra","elektrisk"],
["elektristo","elektriker"],
["elektro","elektricitet"],
["elektrodinamika","elektrodynamisk"],
["elektrodinamiko","elektrodynamik"],
["elektromagnetismo","elektromagnetism"],
["elektrostatika","elektrostatisk"],
["elektrostatiko","elektrostatik"],
["elektroteĥniko","elektroteknik"],
["elmeti","ställa ut","utsätta","lägga fram"],
["elokventa","vältalig"],
["elparoli","uttala"],
["elsalti","hoppa ut"],
["elsaltulo","parveny","uppkomling","nyrik"],
["elsaluti","logga ut"],
["elturnaĵo","flyktmedel"],
["elturniĝi","vrida sig ur","ta sig ur"],
["eluzi","slita ut"],
["elŝeligi","skala"],
["emajlo","emalj"],
["emblemo","emblem","tecken"],
["embrio","embryo"],
["eminenta","framstående"],
["enbrakigi","krama","omfamna"],
["endormigi","söva"],
["endormiĝi","somna","somna in"],
["endormiĝo","insomnande"],
["energio","energi"],
["engliti","halka in i"],
["enkadrigi","rama in"],
["enmemiĝi","gå in i sig själv"],
["ensaluti","logga in"],
["entjera","heltals-"],
["entjero","heltal"],
["enviema","avundsjuk"],
["envii","avundas"],
["enviinda","avundsvärd"],
["envio","avundsjuka"],
["enzimo","enzym"],
["eozino","eosin"],
["epidemio","epidemi"],
["episkopo","biskop"],
["epoleto","axelklaff"],
["erbio","erbium"],
["erco","malm"],
["erikacoj","ljungväxter"],
["eriko","ljung"],
["erodi","erodera (något)"],
["erodo","erosion"],
["erotika","erotisk"],
["erozii","erodera (något)"],
["erozio","erosion"],
["eskadro","flotteskader"],
["eskalo","stege"],
["esprimi","uttrycka"],
["esprimo","uttryck"],
["estero","ester"],
["estonujo","Estland"],
["eta kriaglo","mindre skrikörn"],
["etaĝo","våning"],
["eterna","evig"],
["etero","eter"],
["etfingro","lillfinger"],
["etimologio","etymologi","ords härledning"],
["etno","etnisk grupp"],
["etnografio","etnografi"],
["etnologiisto","etnolog"],
["etnologio","etnologi"],
["etnologo","etnolog"],
["etoso","stämning","atmosfär"],
["evakui","evakuera"],
["eventuala","eventuell","möjlig"],
["eventuale","eventuellt"],
["evidenta","tydlig","uppenbar","självklar"],
["evidente","tydligen"],
["eviti","undvika"],
["evolui","utvecklas"],
["evoluo","utveckling"],
["ezofago","matstrupe"],
["ezoko","gädda"],
["eĥo","eko"],
["eŭgeniko","eugenik","rashygien"],
["eŭkaristio","nattvard"],
["eŭropio","europium"],
["eŭĥaristio","nattvard"],
["fabacoj","ärtväxter"],
["fabela","sago-","sagolik"],
["fabelo","saga"],
["fablo","fabel"],
["fabriko","fabrik"],
["facila","enkel","lätt"],
["facile","enkelt","lätt"],
["faciligi","underlätta","förenkla","lätta"],
["fadenbulo","nystan"],
["fadeno","tråd"],
["fago","bok"],
["fajencaĵo","fajans"],
["fajfanaso","bläsand"],
["fajlaĵo","filspån"],
["fajli","fila"],
["fajlilo","fil"],
["fajrejo","eldstad"],
["fajro","eld"],
["fakiro","fakir"],
["faksaĵo","fax(meddelande)","telefax(meddelande)"],
["faksi","faxa"],
["faksilo","fax(apparat)","telefax(apparat)"],
["faksnumero","faxnummer"],
["fakso","fax(meddelande)","telefax(meddelande)"],
["falakvo","vattenfall"],
["faldebla","vikbar"],
["faldi","vika"],
["faldo, faldaĵo","veck"],
["falĉilanaso","praktand"],
["faruno","mjöl"],
["fazeolo","böna"],
["febra","febrigt"],
["febro","feber"],
["februaro","februari"],
["fek","skit !"],
["fekado","bajsande (handling)","skitande (handling)"],
["fekaĵo","bajs","skit (subst.)","avföring"],
["feki","bajsa","skita"],
["feko","bajsande (handling)","bajs","avföring"],
["femto-","femto-"],
["fenestrobreto","fönsterbräde"],
["fenikoptero","flamingo"],
["fermio","fermium"],
["fero","järn"],
["ferrubo","järnskrot"],
["festi","fira","festa"],
["festo","fest"],
["festono","festong"],
["filozofii","filosofera"],
["filozofio","filosofi"],
["fingringo","fingerborg"],
["fingro","finger"],
["fizika","fysisk"],
["fizikisto","fysiker"],
["fiziko","fysik"],
["fiŝaglo","fiskgjuse"],
["flamengo, roza flamengo","flamingo"],
["flandrujo","Flandern"],
["flava","gul"],
["flavkrura mevo","silltrut"],
["flavmalsano","gulsot"],
["flerovio","flerovium"],
["florbrasiko","blomkål"],
["flori","att blomma"],
["floro","blomma"],
["florsuko","nektar"],
["fluoro","fluor"],
["foino","stenmård"],
["fojo","gång (ett tillfälle)"],
["fono","bakgrund"],
["fonto","källa"],
["fordormi","sova bort"],
["forkego","högaffel","grep"],
["forketo","gaffel"],
["forko","gaffel"],
["forkvosta mevo","tärnmås"],
["formaldehido","formaldehyd"],
["formanĝi","äta upp"],
["formeti","ta bort","lägga undan"],
["foroferi","uppoffra"],
["fortepiano","flygel"],
["fosfata acido","fosforsyra"],
["fosfato","fosfat"],
["fosforo","fosfor"],
["fotelo","fåtölj"],
["fotono","foton"],
["frajto","frakt"],
["francio","francium"],
["franciumo","francium"],
["francujo","Frankrike"],
["franĝi","förse med fransar"],
["franĝo","frans"],
["fratino","syster"],
["frato","bror"],
["fraŭlino","fröken"],
["fraŭlo","ungkarl"],
["frekvenco","frekvens"],
["freneza","galen"],
["frenezi","vara galen"],
["frenezigi","göra galen"],
["freneziĝi","bli galen"],
["freono","freon"],
["fresko","fresk"],
["friti","fritera"],
["fritilario","klocklilja"],
["frito","pommes frites"],
["fronte","på fronten","på framsidan"],
["fronto","front","framsida"],
["frotpurigi","skrubba"],
["frua","tidig"],
["frue, frutempe","tidigt"],
["fruntaĵo","fronton"],
["frunto","panna (anat.)"],
["fruntosto","pannben"],
["fuelo","bränsle"],
["fulmi","blixtra"],
["fulmo","blixt"],
["fulmotondro","åska"],
["fulmŝirmilo, fulmoŝirmilo","åskledare"],
["furaĝo","foder","djurfoder"],
["furzi","fisa","prutta","släppa väder"],
["futbalisto","fotbollsspelare"],
["futbalo","fotboll"],
["gado","torsk"],
["gadolinio","gadolinium"],
["gaja","glad"],
["gajlo","galläpple"],
["galaksio","galax"],
["galanto","snödroppe"],
["galeno","blyglans","blysulfid","galenit"],
["galiumo","gallium"],
["galo","galla"],
["galope","i galopp"],
["galopi","galoppera"],
["galopo","galopp"],
["galvanizi","galvanisera"],
["galveziko, gala veziko","gallblåsa"],
["gamaŝo","damask"],
["gambo","ben"],
["gamelano","gamelan"],
["ganto","handske","vante"],
["garbo","knippe"],
["gastama, gastigema","gästvänlig"],
["gastejo","värdshus"],
["gasti","gästa"],
["gastiganto","värd"],
["gastlibro","gästbok"],
["gasto","gäst"],
["gazelo","gasell"],
["gazono","gräsmatta"],
["gelateno","gelatin"],
["generacio","generation"],
["generalo","general"],
["generatoro","generator"],
["genetiko","genetik"],
["genitivo","genitiv"],
["geno","gen"],
["genuo","knä"],
["geofizikisto","geofysiker"],
["geofiziko","geofysik"],
["geometrio","geometri"],
["gepardo","gepard"],
["germana","tysk"],
["germaniumo","germanium"],
["germano","tysk medborgare","tysk"],
["germanujo","Tyskland"],
["giga-","giga-"],
["gimnastiki","gymnastisera"],
["gimnastikisto","gymnast"],
["gimnastiko","gymnastik"],
["gisto","jäst"],
["gitaro","gitarr"],
["glaciaĵo","glass"],
["glacimevo","vittrut"],
["glacio","is"],
["glacirivero","dalglaciär"],
["glacirompilo","isbrytare"],
["glando","körtel"],
["glaso","glas"],
["glavingo","(svärds)skida"],
["glavo","svärd"],
["glazuro","glasyr"],
["glekomo","Jordreva"],
["glita, glitiga","hal"],
["gliti","glida"],
["glitpunkta, glitkoma","flyttals-"],
["glitŝuo","skridsko"],
["glutejo","strupe","avgrund"],
["gluti","svälja"],
["gombo","okra"],
["gondolo","gondol"],
["gradiento","gradient"],
["grafo","greve"],
["gramatiko","grammatik"],
["gramofono","grammofon","skivspelare","gramafon"],
["granda","stor"],
["granda buntpego","större hackspett"],
["granda kriaglo","större skrikörn"],
["granda nigrakapa mevo","svarthuvad trut"],
["granda otido","stortrapp"],
["granda rabmevo","storlabb"],
["grandiĝi","växa"],
["granito","granit"],
["grapfruktarbo","grapefruktträd"],
["grapfrukto","grapefrukt"],
["grati","riva (med något vasst)","klösa"],
["gratuli","gratulera"],
["gratulo","gratulation"],
["gratvundi","klösa"],
["grava","viktig"],
["grave","viktigt"],
["graveco","viktighet","betydelse"],
["graveda","gravid"],
["gravi","vara viktig","spela roll"],
["gravuri","gravera"],
["grego","hjord"],
["grenado","granat"],
["griledoj","syrsor"],
["grimpi","klättra"],
["griza","grå"],
["griza cirkuo","ängshök"],
["griza mevo","fiskmås"],
["griza pego","gråspett"],
["groteska","grotesk"],
["gruformaj","tran- och rallfåglar"],
["gruo","trana","lyftkran"],
["gurdi","spela positiv","spela vevorgel"],
["gurdo","positiv (musikinstrument)","vevorgel"],
["guti","droppa"],
["guto","droppe"],
["gvidi","leda"],
["hafnio","hafnium"],
["hajli","hagla"],
["hajlo","hagel"],
["hamstro","hamster"],
["hangaro","hangar"],
["hararo","hår"],
["harbroso","hårborste"],
["hardi","härda"],
["haro","hårstrå"],
["harpo","harpa"],
["harpuni","harpunera"],
["harpuno","harpun"],
["harsapo","schampo"],
["harvosto","hästsvans (frisyr)"],
["hasio","hassium"],
["haveno","hamn"],
["hazardo","slump"],
["haŭto","hud","skinn"],
["hejme","hemma"],
["hejmo","hem"],
["hejmveo","hemlängtan"],
["hekto-","hekto-"],
["helikoptero","helikopter"],
["helio","helium"],
["heliumo","helium"],
["helpa","hjälpande","hjälp-"],
["helpanto, helpisto","hjälpare"],
["helpema","hjälpsam"],
["helpi","hjälpa"],
["helpilo","hjälpmedel"],
["helpo","hjälp"],
["heni","gnägga"],
["herbo","gräs"],
["heroeco","hjältemod"],
["heroo","hjälte"],
["heziti","tveka"],
["hidrargo","kvicksilver"],
["hidrogeno","väte"],
["hieno","hyena"],
["hieraŭ","i går"],
["higiena","hygienisk"],
["higieno","hygien"],
["hiki","hicka"],
["himno","hymn"],
["hiperteksto","hypertext"],
["hipopotamo","flodhäst"],
["hipotezo","hypotes"],
["historia","historisk"],
["historio","historia"],
["hodiaŭ","i dag"],
["hoktriki","virka"],
["holmio","holmium"],
["homhelpa","humanitär","filantropisk","välgörenhets-"],
["homogena","homogen"],
["honesta","ärlig"],
["honti","skämmas"],
["honto","skam"],
["horaro, horlibro","tidtabell"],
["hordeo","korn (sädesslag)"],
["horloĝisto","urmakare"],
["horloĝo","klocka","ur"],
["hormontrilo","timvisare"],
["horo","timma"],
["horoskopo","horoskop"],
["hufo","hov (på djur)"],
["huligano","huligan"],
["humoro","humör","humor"],
["humuro","humor"],
["hundo","hund"],
["husaro","husar"],
["idaro","avkomma"],
["ideala","ideal"],
["idealigi","idealisera"],
["idealismo","idealism"],
["idealisto","idealist"],
["idealo","ideal"],
["idioto","idiot"],
["ido","bebis","barn","avkomma"],
["idolo","idol"],
["ie","någonstans"],
["iel","på något sätt"],
["iele","på något sätt"],
["ies","någons"],
["ignamo","jamsrot"],
["ikso","x"],
["iktero","gulsot"],
["ilekso","järnekar"],
["ili","de"],
["ilia","deras"],
["imperia aglo","kejsarörn"],
["impona","imponerande"],
["imponi","imponera"],
["importado","import"],
["importi","importera"],
["impotenta","impotent"],
["impresi","göra intryck"],
["impreso","intryck"],
["imuna","immun"],
["incesto","incest"],
["indiano","indian"],
["indiferenta","likgiltig"],
["indiga , indigokolora","indigoblå","indigofärgad"],
["indigo","indigo"],
["indigujo","indigoväxt"],
["indio","indium"],
["infana","barnslig"],
["infanaĝo","barndom"],
["infano","barn"],
["infanteriano","infanterist"],
["infanterio","infanteri"],
["infera","helvetisk"],
["infero","helvete"],
["inflacio","inflation"],
["inhali","inhalera"],
["inkluziva","inkluderande","innefattande"],
["inkluzive","inklusive","medräknat","medtaget"],
["inkluzivi","inkludera","innefatta","inbegripa","medräkna"],
["insekto","insekt"],
["insektomanĝuloj","insektsätare"],
["insisti","insistera"],
["insulti","förolämpa"],
["insulto","förolämpning"],
["integra cirkvito","integrerad krets"],
["inteligenta","intelligent"],
["inteligenteco","intelligens"],
["inteligento","intelligens"],
["interago","interaktion"],
["interfaco","gränssnitt"],
["intermanĝeto","mellanmål"],
["inĝeniero","ingenjör"],
["iridio","iridium"],
["iterbio","ytterbium"],
["itrio","yttrium"],
["iu","någon"],
["izoli","isolera"],
["izolilo","isolator"],
["ja","ju"],
["jado","jade"],
["jaguaro","jaguar"],
["jahurto","yoghurt"],
["jako","jacka"],
["jakobeno","jakobin"],
["jam","redan","numera"],
["jambo","jamb"],
["janiĉaro","janitsjar"],
["januaro","januari"],
["japana","japansk"],
["japano","japan (person)"],
["japanujo","Japan"],
["jarcento","århundrade"],
["jardo","yard","mast","bom"],
["jarlibro","årsbok"],
["jarmilo","årtusende"],
["jaro","år"],
["jasmeno","jasmin"],
["jaspo","jaspis"],
["jaĥto","(lust)jakt"],
["je","av","på","till"],
["jen","(se) här","se!"],
["jen...","än... än"],
["jena","följande"],
["jene","så här"],
["jes","ja"],
["jesa","jakande"],
["jesi","jaka"],
["jeso","jakande svar"],
["jetavio, jetaviadilo","jetflygplan","reaplan"],
["jetmotoro","jetmotor","reamotor"],
["jezuito","jesuit","hypokrit","hycklare"],
["jodo","jod"],
["jodoformo","jodoform"],
["jogurto","yoghurt"],
["jokto-","yokto-"],
["jonigi","jonisera"],
["jonizi","jonisera"],
["jonkvilo","jonkvill"],
["jono","jon"],
["jota-","yotta-"],
["ju","ju"],
["jubileo","jubileum","heligt år","jubelår"],
["juda","judisk"],
["judaismo","judendom"],
["judismo","judendom"],
["judo","jude"],
["juglando","valnöt"],
["juglandujacoj","valnötsväxter"],
["juglandujo, juglandarbo","valnötsträd"],
["jugo","ok"],
["julio","juli","Julius"],
["juna","ung","gammal"],
["juneco","ungdom"],
["junio","juni"],
["junulo","yngling"],
["jupo","kjol"],
["jurto","jurt"],
["justa","rättvis"],
["justeco","rättvisa"],
["juto","jute"],
["juvelisto","juvelerare"],
["juvelo","juvel"],
["juvelŝtono","ädelsten"],
["juĝejo","domstol"],
["juĝi","döma","bedöma"],
["juĝisto","domare"],
["juĝo","dom"],
["kabano","hydda"],
["kabaredo","kabaré"],
["kabareto","kabaré"],
["kabla televido","kabel-TV"],
["kablo","kabel"],
["kaco","kuk"],
["kadavro","lik","kadaver"],
["kadeto","kadett"],
["kadio","qadi"],
["kadmio","kadmium"],
["kadri","rama in"],
["kadro","ram"],
["kaduka","fallfärdig","skröplig"],
["kafeino","koffein"],
["kafejo","kafé"],
["kafo","kaffe","kaffeböna"],
["kafskatolo","kaffeburk"],
["kafujo","kaffeburk"],
["kahelo","kakel"],
["kaj","och"],
["kajero","häfte"],
["kajto","drake"],
["kajuto","hytt","kajuta"],
["kakto","kaktus"],
["kala","valkig"],
["kalandri","mangla"],
["kalandrilo","mangel"],
["kalcio","kalcium"],
["kaldrono","kittel"],
["kalifornio","californium","Kalifornien"],
["kaliforniumo","californium"],
["kalio","kalium"],
["kalkano","häl"],
["kalkanumo","klack"],
["kalki","kalka"],
["kalko","kalk"],
["kalo","liktorn","valk"],
["kameleono","kameleont"],
["kamelo","kamel"],
["kameo","kamé"],
["kanabo","hampa"],
["kanalo","kanal"],
["kanapo","kanapé"],
["kantado","sång"],
["kantaĵo","sång"],
["kanteti","nynna"],
["kanti","sjunga","besjunga"],
["kantisto","sångare"],
["kanto","sång"],
["kanuo","kanot"],
["kaosa","kaotisk"],
["kaoso","kaos"],
["kapitano","kapten"],
["kapo","huvud"],
["kapsaluto","nicka (hälsning)"],
["kapti","fånga"],
["kaptilo","fälla"],
["kaptiĝi","fångas"],
["kapturniĝo","svindel","yrsel"],
["kapturno","svindel","yrsel"],
["karafo","karaff"],
["karbo","kol"],
["karbono","kol"],
["karikaturo","karikatyr"],
["karmo","karma"],
["karnavalo","karneval"],
["karno","kött"],
["karoo","ruter"],
["karpo","karp"],
["kasejo","kassa"],
["kasisto","kassör"],
["kaso","kassa"],
["kata","katt-"],
["katastrofo","katastrof"],
["katido, katidino","kattunge"],
["katino","katthona"],
["kato","katt"],
["katodo","katod"],
["kavalirsprono, alaŭdosprono","riddarsporre (växt)"],
["kaviaro","kaviar"],
["kaĉo","gröt"],
["kaĝo","bur"],
["kaŝejo","gömställe"],
["kaŝi","gömma","dölja"],
["kaŭstika potaso","lut","kalilut","kaliumhydroxid"],
["kaŭstika sodo","kaustiksoda","natriumhydroxid"],
["kaŭzi","orsaka"],
["kaŭzo","orsak"],
["ke","att"],
["keglo","kägla"],
["keiranto","gyllenlack"],
["kelnero","kypare"],
["kemio","kemi"],
["kenopodiacoj","mållväxter"],
["kerkedulo","årta"],
["kero","hjärter"],
["kial","varför"],
["kialo","skäl","orsak"],
["kie","var (om plats)"],
["kien","vart"],
["kilo-","kilo-"],
["kiloparseko","kiloparsec"],
["kinkonino","cinkonin"],
["kirasŝranko","kassaskåp"],
["kirli","vispa"],
["kirlilo","visp"],
["kirliĝi","virvla"],
["kirlo","virvel","rotation"],
["kirlovaĵo","omelett"],
["kirurgia","kirurgisk"],
["kirurgiisto","kirurg"],
["kirurgio","kirurgi"],
["kirurgo","kirurg"],
["kitio","tretåig mås"],
["kitivako","tretåig mås"],
["kiu","vem","vilken","vilket","som"],
["kladonio","bägarlav"],
["klara","klar"],
["klare","klart"],
["klarigi","förklara"],
["klasika","klassisk"],
["klasikaĵo","klassiker"],
["klavaro","tangentbord","klaviatur"],
["klavi","trycka (på en tangent)","skriva in (på ett tangentbord)"],
["klavo","tangent (på klaviatur eller tangentbord)"],
["klinsaluto","buga sig (som en hälsning)"],
["kloro, ĥloro","klor"],
["knabino","flicka"],
["knabo","pojke"],
["knaranaso","snatterand"],
["kobalto","kobolt"],
["kokcineledoj","nyckelpigor"],
["kokso","höft"],
["koksumi","vicka på höfterna"],
["koleopteroj","skalbaggar"],
["kolhararo, haroj","man"],
["kolo","hals"],
["kolokinto","kolokvint"],
["kolono","pelare","spalt","kolumn","kolonn"],
["kolori","färga"],
["kolorigi","måla"],
["koloro","färg"],
["kolrimeno","halsband (rem)"],
["kolumno","spalt","kolumn","kolonn"],
["kolumo","krage"],
["kometo","komet"],
["komika","komisk"],
["kompreni","förstå","begripa"],
["komputa sistemo","datorsystem"],
["komputi","beräkna"],
["komputila reto","datornätverk"],
["komputilo","dator"],
["komuna","gemensam"],
["komunismo","kommunism"],
["komunisto","kommunist"],
["kondukpermesilo, stirpermesilo","körkort","förarbevis"],
["konifero","barrträd"],
["konsideri","betrakta","överväga","anse"],
["konsonanta","konsonant"],
["konspiri","konspirera"],
["konspiro","konspiration"],
["konstanta kurento","likström"],
["konsterni","bringa ur fattningen","göra bestört"],
["konsterno, konsterniĝo","bestörtning"],
["konstruarto","arkitektur"],
["kontoro","kontor"],
["kontrakto","kontrakt"],
["kontraŭjudismo","antisemitism"],
["kontraŭveneno","motgift","antidot"],
["konturo","kontur"],
["kopernicio","copernicium"],
["kopro","kopra"],
["kora","hjärtlig"],
["koro","hjärta"],
["kortego","hov (hos furste, kung, etc.)"],
["korto","gårdsplan"],
["korusano","körsångare"],
["koruso","kör (mus.)"],
["kosta","dyr"],
["kosti","kosta"],
["kosto","kostnad"],
["kotiledono","hjärtblad"],
["kovejo","rede"],
["kovi","ruva (på)"],
["koŝmaro","mardröm"],
["krano","kran"],
["kratago","hagtorn"],
["kratero","krater"],
["kreditkarto","kreditkort"],
["krei","skapa"],
["krepido","fibbla"],
["krespo","pannkaka","crêpe"],
["kreto","krita"],
["kriptono","krypton"],
["krizi","krisa"],
["krizo","kris"],
["kroketo","krocket"],
["krokodili","att tala med esperantister på modersmålet istället för på Esperanto"],
["krokodilo","krokodil"],
["krokuso","krokus"],
["kromi, ĥromi","förkroma"],
["kromo, ĥromo","krom"],
["kronika","kronisk"],
["kroniko","krönika"],
["kronprinco","kronprins"],
["kroĉi","kroka"],
["kroĉilo","krok"],
["krucifikso","krucifix"],
["krucigi, kruci","korsa"],
["kruco","kors"],
["krucumi","korsfästa"],
["krucvortenigmo, vortkrucenigmo","korsord"],
["kruro","underben","ben"],
["kruta","brant"],
["ksenono","xenon"],
["ksilofono","xylofon"],
["ksilografiisto","xylograf"],
["ksilografio","xylografi","trägravyr","trästick"],
["kuba","kubisk"],
["kubforma","kubformad"],
["kubismo","kubism"],
["kubo","kub","tärning"],
["kubuto","armbåge"],
["kudrero","stygn"],
["kudri","sy"],
["kudrilo","synål"],
["kuglo","(gevärs)kula"],
["kuirarta","kulinarisk"],
["kuirejo","kök"],
["kuiri","laga mat"],
["kuiristo","kock"],
["kuko","kaka"],
["kukumo","gurka"],
["kuleranaso","skedand"],
["kulero","sked"],
["kulmino","kulmination"],
["kulo","mygga"],
["kulpa","skyldig"],
["kulpi","vara skyldig"],
["kulpigi","beskylla"],
["kulpo","skuld"],
["kultivi","odla","bruka jorden"],
["kultivisto","jordbrukare"],
["kulvualo","myggnät"],
["kumino","spiskummin"],
["kumuluso","cumulusmoln","stackmoln"],
["kun","med"],
["kunagi","samarbeta","samverka"],
["kune","tillsammans","tillsammans med"],
["kunhelpi","medhjälpa"],
["kunigi","sammanföra","förena"],
["kuniklo","kanin"],
["kunlabori","samarbeta"],
["kunlaboro","samarbete"],
["kunmeti","sammanställa","sätta samman","lägga ihop"],
["kunsendaĵo","bilaga"],
["kupolo","kupol"],
["kupri","förkoppra"],
["kupristo","kopparslagare"],
["kupro","koppar"],
["kuratoro","förmyndare"],
["kuraĝa","modig"],
["kuraĝi","våga"],
["kuraĝo","mod"],
["kurba","krokig","svängd","kurvig"],
["kurbigi","kröka","böja"],
["kurbiĝo","kurva","krök","sväng"],
["kurbo","kurva"],
["kurento","ström"],
["kuriumo","curium"],
["kurkumo","gurkmeja"],
["kurso","kurs"],
["kursoro","markör"],
["kurteno","gardin","ridå","teaterförhänge"],
["kuseno","kudde"],
["kusentego, kusentegilo","örngott","dynvar"],
["kuzino","kvinnlig kusin"],
["kuzo","kusin"],
["kvadrata","kvadratisk"],
["kvadratigi","kvadrera"],
["kvadrato","kvadrat"],
["kvadrilo","kadrilj"],
["kvankam","fastän"],
["kvar","fyra"],
["kvara","fjärde"],
["kvasto","tofs"],
["kvazaŭ","som om","liksom"],
["kvereli","gräla"],
["kverko","ek"],
["kvin","fem"],
["kvitanco","kvitto"],
["kvorumo","kvorum","beslutsförhet"],
["la"," (bestämd artikel)"],
["labirinto","labyrint"],
["labordonanto","arbetsgivare"],
["laborestro","arbetsledare","förman"],
["labori","arbeta"],
["laboristo, laborulo","arbetare"],
["laborkapabla","arbetsför"],
["laborloko","arbetsplats"],
["laboro","arbete"],
["laca","trött"],
["lafo","lava"],
["lago","sjö"],
["lagopo","ripa","dalripa"],
["lagro","lager (i maskin)"],
["laguno","lagun"],
["lakta Vojo","Vintergatan"],
["lakto","mjölk"],
["lamenti","jämra","klaga"],
["lamiacoj","kransblommiga växter"],
["lampo","lampa"],
["lanco","lans","spjut"],
["lango","tunga"],
["langtrinki","lapa"],
["lantano","lantan"],
["lanterno","lykta"],
["lanugo","dun","fjun"],
["lapo","kardborre"],
["laringo","struphuvud"],
["larmo","tår"],
["larĝvosta rabmevo","bredstjärtad labb"],
["lavango","lavin"],
["lavendo","lavendel"],
["lavi","tvätta"],
["lavmaŝino","tvättmaskin"],
["laŭdi","berömma"],
["laŭlonge","på längden"],
["laŭrencio","lawrencium"],
["leciono","lektion"],
["legendo","legend"],
["lekcii","föreläsa"],
["lekcio","föreläsning"],
["leki","slicka"],
["lemo","lemma","hjälpsats"],
["lento","lins (växt)"],
["lentugo","fräkne"],
["leonfaŭko","lejongap"],
["leono","lejon","Lejonet"],
["leopardo","leopard"],
["leporo","hare"],
["lerta","skicklig"],
["lesivo","lut"],
["leterkesto","postlåda"],
["letero","brev"],
["leŭtenanto","löjtnant"],
["li","han"],
["lia","hans"],
["liano","lian"],
["libervola, memvola","frivillig"],
["libro","bok"],
["librobretaro","bokhylla"],
["libroŝranko","bokskåp"],
["lieno","mjälte"],
["lifto","hiss"],
["lignokarbo","träkol"],
["likado","läckande"],
["liki","läcka"],
["likimuna","tät"],
["liko","läcka"],
["liliacoj","liljeväxter"],
["lilio","lilja"],
["lineara algebro","linjär algebra"],
["lingva","språklig"],
["lingvistika","lingvistisk","språkvetenskaplig"],
["lingvistiko","lingvistik","språkvetenskap"],
["lingvisto, lingvosciencisto","lingvist"],
["lingvo","språk"],
["lingvoscienco","lingvistik","språkvetenskap"],
["liphararo, haroj","mustasch"],
["lipo","läpp"],
["literpendaĵo","överhäng"],
["litio","litium"],
["lito","säng"],
["livermorumo","livermorium"],
["logi","locka"],
["lojala","lojal"],
["loka","lokal"],
["loka reto","lokalt datornätverk"],
["loki","placera"],
["loko","plats","ställe"],
["lokomotivo","lok(omotiv)"],
["longa","lång","kort"],
["longa fingro","långfinger"],
["longe","länge"],
["longeco","längd"],
["longo","längd"],
["longvosta rabmevo","fjällabb"],
["loĝdomo","bostadshus"],
["luko","lukarn","taklucka","takfönster"],
["luksa","lyxig"],
["lukso","lyx"],
["luma","lysande","ljus-","ljus","upplyst"],
["lumbaĵo","ländstycke"],
["lumbo","länd"],
["lumbriko","daggmask"],
["lumi","lysa"],
["lumigi","belysa"],
["lumjaro","ljusår"],
["lumo","ljus"],
["lumturo","fyr(torn)"],
["luna","mån-"],
["lunarko","månskära"],
["lundo","måndag"],
["luno","måne"],
["lupino","lupin"],
["lupo","varg"],
["lupolo","humle"],
["lutecio","lutetium"],
["mafia","maffia-"],
["mafiano, mafiulo","mafioso"],
["mafio","maffia"],
["magia","magisk"],
["magio","magi"],
["magneta","magnetisk"],
["magnetigi","magnetisera"],
["magneto","magnet"],
["magnezio","magnesium"],
["maizkaĉo","majsgröt"],
["maizo","majs"],
["majo","maj"],
["majoliko","majolika"],
["majstraĵo, majstroverko","mästerverk"],
["majstro","mästare"],
["makadamo","makadam"],
["makaronio","makaroner"],
["makulo","fläck"],
["makzelo","käke"],
["malabunda","knapp","torftig"],
["malagrabla","otrevlig"],
["malamiko","ovän","fiende"],
["malbutonumi, malbutoni","knäppa upp"],
["maldeca","oanständig"],
["maldormi","vara vaken"],
["malfacilaĵo","svårighet"],
["malfono","förgrund"],
["malfrua","sen"],
["malfrui","vara sen"],
["malfruigi","försena"],
["malfruiĝi","vara sen"],
["malgranda","liten"],
["malgranda buntpego","mindre hackspett"],
["malgranda fingro","lillfinger"],
["malgranda kriaglo","mindre skrikörn"],
["malgranda otido","småtrapp"],
["malgranda pando","kattbjörn","liten panda","mindre panda","röd panda"],
["malgrandegulo","dvärg"],
["malgrava","oviktig","betydelselös"],
["malgraŭ","trots"],
["malgraŭ ke","trots att"],
["malhelpa","hindrande"],
["malhelpi","hindra","förhindra"],
["malhelpo","hinder"],
["malica","elak"],
["maljesi","neka"],
["maljusta","orättvis"],
["maljustaĵo","orättvisa"],
["malklara","oklar","otydlig"],
["malkuraĝa","ängslig","feg"],
["mallaborema","arbetsskygg","lat","slö"],
["malloka","global"],
["malloka reto","globalt datornätverk"],
["malluma","mörk"],
["mallumo","mörker"],
["malmiopa","översynt","långsynt"],
["malmolnuka, rigidnuka","styvnackad"],
["malnova","gammal"],
["malofta","ovanlig"],
["maloftaĵo","ovanlighet","raritet"],
["malofte","sällan"],
["malpendaĵo","underhäng"],
["malpermesi","förbjuda"],
["malplej","minst"],
["malplena","tom"],
["malprofunda","grund"],
["malpura","smutsig"],
["malpurigi","smutsa ner"],
["malsata","hungrig"],
["malsati","hungra"],
["malseka","blöt"],
["malseketa","fuktig"],
["malsekretigi","avslöja (en hemlighet)"],
["malto","malt"],
["malvarma","kall"],
["malvarmo","kyla"],
["malvo","malva"],
["malŝpari","slösa"],
["mameto","bröstvårta"],
["mamo","bröst"],
["mampinto","bröstvårta"],
["mamuto","mammut"],
["mamzono","bysthållare","bh"],
["manartiko","handled"],
["mandarenanaso","mandarinand"],
["mandarino","mandarin"],
["mandolino","mandolin"],
["manfingro","finger"],
["mangano","mangan"],
["mango","mango"],
["maniero","manér","sätt"],
["maniko","ärm"],
["manio","mani"],
["mano","hand"],
["manplato","handflata"],
["manpleno","handfull"],
["manradiko","handled"],
["mansardo","(hus-)vind"],
["mantiso","mantissa"],
["manĝaĵo","mat"],
["manĝi","äta"],
["manĝilaro","servis och bestick"],
["manĝo","måltid"],
["manĝokarto","meny"],
["mapo","karta"],
["marakvo","havsvatten"],
["maranaso","svärta"],
["mardo","tisdag"],
["margarino","margarin"],
["marini","marinera"],
["markolo","sund (geog.)"],
["marmelado","marmelad"],
["marmoro","marmor"],
["maro","hav"],
["marsalo","havssalt"],
["marteli","hamra"],
["martelo","hammare"],
["martiro","martyr"],
["marto","mars"],
["marĉa cirkuo","brun kärrhök"],
["marĉanaso","årta"],
["marŝi","marschera","tåga","stega"],
["marŝo","marsch"],
["maski","maskera"],
["masko","mask"],
["mastruma sistemo","operativsystem"],
["matematiko","matematik"],
["matenmanĝo","frukost"],
["mateno","morgon"],
["matenruĝo","morgonrodnad"],
["matraco","madrass"],
["matura","mogen"],
["maturiĝi","mogna"],
["mazurko","mazurka","masurka"],
["maĉi","tugga"],
["maĉo","match"],
["maŝinlingvo","maskinspråk"],
["maŝinpafilo","maskingevär"],
["mebli","möblera"],
["meblo","möbel"],
["medikamento","medicin","läkemedel"],
["mega-","mega-"],
["mejlo","mil"],
["mejtnerio","meitnerium"],
["mekaniko","mekanik"],
["melki","mjölka"],
["melono","melon","vattenmelon"],
["mem","själv"],
["mem-","själv-"],
["memeco","personlighet","identitet"],
["memo","jag (subst.)","identitet"],
["memoraĵo","souvenir","memoar","självbiografi"],
["memore","utantill"],
["memore de","till minne av"],
["memori","minnas","komma ihåg"],
["memorigi","påminna"],
["memorinda","minnesvärd"],
["memorlikado","minnesläcka"],
["memoro","minne"],
["mendelevio","mendelevium"],
["mentono","haka"],
["menueto","menuett"],
["menuredoj","lyrfåglar"],
["merganaso","vigg"],
["merkredo","onsdag"],
["meropo","biätare"],
["metalurgio","metallurgi"],
["meti","placera","ställa","lägga","sätta"],
["mezaĝa","medelålders"],
["mezaĝulo","medelålders person"],
["mezfingro","långfinger"],
["mezgranda buntpego","mellanspett"],
["meĥanika","mekanisk"],
["meĥanikisto","mekaniker"],
["meĥaniko","mekanik","mekanism"],
["meĥanismo","mekanism"],
["mi","jag"],
["mielluno","smekmånad"],
["mielmonato","smekmånad"],
["mikro-","mikro-"],
["mikroskopa","mikroskopisk"],
["mikroskopo","mikroskop"],
["mil","tusen"],
["mili-","milli-"],
["miliardo","miljard"],
["militi","kriga"],
["militisto","militär"],
["milito","krig"],
["minaci","hota"],
["minaco","hot"],
["ministro","minister"],
["minus","minus"],
["miopa","myopisk","närsynt"],
["mirinfano","underbarn"],
["misiisto","missionär"],
["misio","mission"],
["moderna","modern"],
["modifi","modifiera"],
["modkanto, furorkanto","schlager","hit"],
["molanaso","ejder"],
["molibdeno","molybden"],
["monalo","monal"],
["monata","månatlig"],
["monataĵo","menstruation"],
["monato","månad"],
["mondo","värld"],
["mondoparto","världsdel"],
["monero","mynt"],
["mono","pengar"],
["monogamio","monogami"],
["monografio","monografi"],
["monopolo","monopol"],
["monpuno","böter"],
["monstro","monster"],
["monta lagopo","fjällripa"],
["montaro","bergskedja"],
["monto","berg"],
["montra fingro","pekfinger"],
["morfino","morfin"],
["morgaŭ","i morgon"],
["mormonismo","mormonism"],
["mormono","mormon"],
["morta","död"],
["mortbati","slå ihjäl"],
["morti","dö"],
["mortigi","döda"],
["morto","död"],
["moruo","torsk"],
["motacilo","ärla"],
["motoro","motor"],
["mueli","mala"],
["muftio","mufti"],
["muka","slemmig"],
["muko","slem"],
["mulao","mulla","molla"],
["multipliki","multiplicera"],
["multipliko","multiplikation"],
["mumio","mumie"],
["municipo","kommun"],
["murego","mur"],
["muro","vägg"],
["muso","mus"],
["mustardo","senap"],
["muta","stum"],
["muzika","musikalisk"],
["muziko","musik"],
["nabo","nav"],
["naiva","naiv","barnslig"],
["najado","najad"],
["najbaro","granne"],
["najlo","spik"],
["najtingalo","näktergal"],
["nano","dvärg"],
["nano-","nano-"],
["napo","kålrot"],
["narciso","narciss"],
["naso","ryssja"],
["natrio","natrium"],
["natro","kaustiksoda","natriumhydroxid","natriumkarbonat"],
["natura","naturlig"],
["natura entjero","naturligt tal"],
["naturalismo","naturalism"],
["naturisto","naturist"],
["naturo","natur"],
["navaĥa","navajo-"],
["navaĥo, navaho,","navajo"],
["navedi","skyttla"],
["navedo","skyttel"],
["naveti","skyttla"],
["naveto","skyttel"],
["navo","skepp (i kyrka)"],
["nazego","nos"],
["nazia","nazistisk"],
["naziismo","nazism"],
["nazio","nazist"],
["nazmuko","snor"],
["nazo","näsa","nos"],
["naĝilo","fena"],
["naŭ","nio"],
["naŭno","nona"],
["naŭto","nona"],
["naŭzi","äckla"],
["naŭzo","äckel"],
["neaerobia, malaerobia","anaerob"],
["neandertala","neandertalar-"],
["neandertalulo, neandertala homo","neandertalmänniska","neandertalare"],
["neatendite","oväntat"],
["nebula","dimmig","oklar"],
["nebulastro","nebulosa"],
["nebulo","dimma"],
["nebulozo","nebulosa"],
["neceseja papero, necespapero","toalettpapper"],
["negativa","negativ (adj.)"],
["negativo","negativ (foto.)"],
["neglekti","försumma"],
["negro","neger"],
["nekrologo","dödsruna"],
["nenia","inget slags"],
["neniam","aldrig"],
["nenie","ingenstans"],
["nenies","ingens"],
["nenio","ingenting"],
["neniu","ingen"],
["neodimo","neodym"],
["neono","neon"],
["nepino","barnbarn (flicka)","sondotter","dotterdotter"],
["nepo","barnbarn (pojke)","sonson","dotterson"],
["neptunio","neptunium"],
["neracionalo","irrationellt tal"],
["nerva","nervös"],
["nervo","nerv"],
["netipa pneŭmonio","sars"],
["nevino","syskonbarn (flicka)","brorsdotter","systerdotter"],
["nevo","syskonbarn (pojke)","brorson","systerson"],
["neĝbulo","snöboll"],
["neĝero","snöflinga"],
["neĝi","snöa"],
["neĝo","snö"],
["neŭrastenio","neurasteni"],
["ni","vi"],
["nia","vår"],
["nigra","svart"],
["nigra maranaso","sjöorre"],
["nigra pego","spillkråka"],
["nigra truo","svart hål"],
["nigraflugila mevo","sotvingad mås"],
["nigrakapa mevo","svarthuvad mås"],
["nigramantela mevo","havstrut"],
["nigrulo","neger"],
["nikabo","Nikab","Niqab"],
["nikeli","förnickla"],
["nikelo","nickel"],
["nikotino","nikotin"],
["nikso","sjöjungfru"],
["nimfo","nymf"],
["niobo","niob"],
["nizo","sparvhök"],
["niĉo","nisch"],
["nobelio","nobelium"],
["nokte","på natten"],
["nokto","natt"],
["nomado","nomad"],
["nome","till namnet","nämligen"],
["nomi","döpa (till namn)","kalla"],
["nomiĝi","heta","kallas"],
["nomo","namn"],
["nomumi","utnämna"],
["nordlumo","norrsken"],
["nova","ny"],
["novaĵo","nyhet"],
["novelo","novell"],
["novembro","november"],
["novluno","nymåne"],
["nu","nå","nåväl"],
["nuanci","nyansera"],
["nuanco","nyans"],
["nuda","naken","bar"],
["nukleacido, nuklea acido","nukleinsyra"],
["nuko","nacke"],
["nukso","nöt"],
["nun","nu"],
["nuna","nuvarande"],
["nuntempo","nutid"],
["nur se","endast om"],
["oazo","oas"],
["obei","lyda"],
["objektiva","objektiv"],
["objektiveco","objektivitet"],
["oblato","oblat"],
["obligacio","obligation"],
["obsidiano","obsidian"],
["obstaklo","hinder"],
["obstina","envis"],
["obstineco","envishet"],
["obstini","envisas"],
["obstino","envishet"],
["oceano","ocean"],
["odo","ode","kväde"],
["oferado","offrande","uppoffring"],
["oferaĵo","offer"],
["oferbuĉi","offerslakta"],
["oferema","uppoffrande","generös"],
["oferi","offra"],
["ofero","uppoffring","offer"],
["oficejo","kontor"],
["oficiala","officiell"],
["oficialigi","göra officiell"],
["oficiro","officer"],
["oficisto","tjänsteman"],
["ofico","tjänst","anställning","plats"],
["ofta","vanlig","frekvent"],
["ofte","ofta"],
["ofteco","vanlighet","frekvens"],
["ok","åtta"],
["okcidento","väst"],
["oksigeni","syresätta"],
["oksigeno","syre"],
["oktobro","oktober"],
["okulisto","ögonläkare","oftalmolog"],
["okulmezure","med ögonmått"],
["okulo","öga"],
["okulvitra maranaso","vitnackad svärta"],
["okulvitroj","glasögon"],
["ol","än"],
["olei","smörja","olja in"],
["oleo","olja"],
["olivarbo, olivujo","olivträd"],
["olivo","oliv"],
["omaro","hummer"],
["ombra, ombroplena","skuggig"],
["ombrelo","paraply","parasoll"],
["ombri","skugga"],
["ombriĝi","skuggas","förmörkas"],
["ombro","skugga"],
["omeno","omen","järtecken"],
["omleto","omelett"],
["omnibuso","buss"],
["onda","vågig"],
["ondo","våg"],
["oni","man"],
["onklino","faster","moster"],
["onklo","farbror","morbror"],
["opa","kollektiv (adj.)"],
["opalo","opal"],
["operacio","operation"],
["operaciumo","operativsystem"],
["opero","opera"],
["opinii","tycka"],
["opinio","åsikt"],
["opio","opium"],
["opo","grupp"],
["optika","optisk"],
["optiko","optik"],
["optimismo","optimism"],
["optimisto","optimist"],
["ora","gyllene"],
["ora aglo","kungsörn"],
["orangutango","orangutang"],
["oranĝarbo, oranĝujo","apelsinträd"],
["oranĝo","apelsin"],
["oraĵisto","guldsmed"],
["ordeno","orden"],
["ordinato","ordinata","y-koordinat"],
["ordoni","beordra"],
["ordono","order"],
["orelo","öra"],
["orelringo","örhänge"],
["orfejo","barnhem"],
["orfo","föräldralös"],
["organismo","organism"],
["orgasmo","orgasm"],
["orgeno","orgel"],
["orgio","orgie"],
["ori","förgyll"],
["oriento","öst"],
["orli","fålla"],
["orlo","fåll"],
["ornami","pryda","smycka"],
["oro","guld"],
["oscedi","gäspa"],
["osmio","osmium"],
["osto","ben (i skelettet)"],
["ostro","ostron"],
["otido","trapp"],
["ovario","äggstock"],
["ovingo","äggkopp"],
["ovo","ägg"],
["ovoflavo, ovoflavaĵo","äggula"],
["ozono","ozon"],
["pa","äsch!","äh!","bah!"],
["paca","fredlig","fridfull"],
["paciencludo, paciencoludo","patiens"],
["pacienco","tålamod"],
["pacifismo","pacifism"],
["pacifisto","pacifist"],
["pacismo","pacifism"],
["paco","fred","frid"],
["padeli","paddla"],
["padelo","paddel","skovel"],
["padelrado","skovelhjul","vattenhjul"],
["paduso","hägg"],
["paeljo","paella"],
["pafado, pafaro","skutande"],
["pafarko","pilbåge"],
["pafaĵo","skott","projektil"],
["pafejo","skjutfält","skjutbana"],
["pafi","skjuta"],
["pafilo","skjutvapen"],
["pafo","skott"],
["pafĉesigo","eldupphör","vapenstillestånd","vapenvila"],
["pagajo","paddel"],
["paganismo","hedendom"],
["pagano","hedning"],
["pajlero","halmstrå"],
["pajlo","halm"],
["pala","blek"],
["palaco","palats"],
["paladio","palladium"],
["palatalo","palatal","palatal konsonant"],
["paliativo","palliativ"],
["paligi","bleka"],
["palindromo","palindrom"],
["paliĝi","blekna"],
["palmo","palm"],
["palpebro","ögonlock"],
["palpebrumi","blinka (med ögonen)"],
["pampelmusarbo, pampelmusujo","pompelmusträd"],
["pampelmuso","pompelmus","pomelo"],
["pandiono","fiskgjuse"],
["panero","brödsmula"],
["paniko","panik"],
["pano","bröd"],
["pantaloneto","kortbyxor","shorts"],
["pantalono","byxa","byxor"],
["pantero","panter"],
["papera","pappers-","av papper"],
["papero","papper"],
["paradizo","paradis"],
["paralela","parallell"],
["parazita rabmevo","labb"],
["parazito","parasit"],
["paraŝuto","fallskärm"],
["parigi","para ihop"],
["paro","par"],
["parseko","parsec"],
["participo","particip"],
["paseredoj","sparvar"],
["pasero","sparv"],
["paseroformaj","tättingar"],
["pasio","passion"],
["pasiva","passiv"],
["pasporto","pass"],
["patenti","patentera"],
["patento","patent"],
["patkuko","pannkaka"],
["patrino","moder"],
["patro","fader"],
["pavo","påfågel"],
["paĉjo","pappa"],
["paĝo","sida"],
["pedalo","pedal"],
["pedanta","pedantisk"],
["peki","synda"],
["peko","(en) synd"],
["pelerino","pelerin"],
["pendolo","pendel"],
["peniki","pensla"],
["peniko","pensel"],
["pensio","pension"],
["pensiulo","pensionär"],
["penti","ångra"],
["pentofari","göra bot"],
["pentraĵo","målning"],
["pentri","måla"],
["perko","abborre"],
["perkoformaj","abborrartade fiskar"],
["permesi","tillåta"],
["permesilo","tillstånd","licens"],
["persa","persisk"],
["persa Golfo","Persiska viken"],
["persiko","persika"],
["persikujo, persikarbo","persikoträd"],
["persio","Persien"],
["perso","en persisk person"],
["persona nomo","förnamn"],
["persujo","Persien"],
["perĉo","gärs"],
["peta-","peta-"],
["petromizo","nejonöga"],
["pia","from"],
["piano","piano"],
["picejo","pizzeria"],
["pico","pizza"],
["piedbati","sparka"],
["piede","till fots"],
["piede de","vid fötterna"],
["piedfingro","tå"],
["piedingo","stigbygel"],
["piedo","fot","ben"],
["pigmea mevo","dvärgmås"],
["piki","sticka"],
["piko","stick","spader"],
["piko-","piko-"],
["pilko","boll"],
["pimpinelo","bockrot"],
["pinacoj","tallväxter"],
["pingveno","pingvin"],
["pingvino","pingvin"],
["pintarko","spetsbåge"],
["pintvostanaso","stjärtand"],
["pipo","pipa"],
["pirato","pirat","sjörövare"],
["piĵamo","pyjamas"],
["plafono","(inner)tak"],
["plando","fotsula","sula"],
["plandumo","sula","skosula"],
["planedo","planet"],
["planko","golv"],
["plasto","plast"],
["platbeka anaso","gräaand"],
["plateno","platina"],
["plaĝo","strand"],
["plaŭd","plask"],
["plaŭdi","plaska"],
["plej","mest","-ast"],
["plejaĝulo","äldste"],
["plejofte","oftast"],
["plena","full","fullständig"],
["plenigi","fylla"],
["plenluno","fullmåne"],
["pli","mer","mindre"],
["plori","gråta"],
["ploro","gråt"],
["plumbo","bly"],
["pluraj","flera"],
["pluralo","plural"],
["pluso","plus"],
["plutonio","plutonium"],
["pluvarko","regnbåge"],
["pluvi","regna"],
["pluvo","regn"],
["pneŭmonio","lunginflammation"],
["poacoj","gräs"],
["podio","podium"],
["poento","poäng"],
["poleno","pollen"],
["polico","polis"],
["poliestero","polyester"],
["polinoma multipliko","polynommultiplikation"],
["politiko","politik"],
["polko","polka"],
["polonio","polonium"],
["poluri","polera","putsa"],
["polva","damm-","dammig"],
["polvo","damm"],
["polvosuĉi","dammsuga"],
["polvoŝovelilo","sopskyffel"],
["pomo","äpple"],
["pomujo, pomarbo","äppelträd"],
["ponardo","dolk"],
["ponto","bro"],
["pontolingvo","brospråk"],
["pontono","ponton"],
["poplo","poppel"],
["populara","populär"],
["porcelano","porslin"],
["porcio","portion"],
["pordego","port"],
["pordo","dörr"],
["porko","svin"],
["poro","por"],
["portalo","portal"],
["porti","bära","hämta","föra med sig"],
["portiko","portik","pelarhall","täckt pelargång","kolonnprydd förhall"],
["portisto","bärare"],
["portoseĝo","bärstol"],
["portreto","porträtt"],
["postmeti","ställa bakom"],
["postmorgaŭ","i övermorgon"],
["postskribo","efterskrift","post scriptum"],
["postulema","krävande"],
["postuli","kräva"],
["postulo","krav","efterfrågan"],
["postvango","skinka (kroppsdel)"],
["postveturilo","släp"],
["potaso","pottaska","kaliumkarbonat"],
["pozicio","position"],
["poŝo","ficka"],
["poŝtelefono, ĉeltelefono","mobiltelefon"],
["poŝtkarto","vykort"],
["poŝtkesto","brevlåda"],
["poŝtkodo, poŝtokodo","postkod"],
["poŝtranĉilo","fickkniv","fällkniv"],
["praido","avkomma"],
["pramo","färja"],
["pramŝipo","färja"],
["pranepino, postnepino","barnbarnsbarn (flicka)","barnbarnsdotter"],
["pranepo, postnepo","barnbarnsbarn (pojke)","barnbarnsson"],
["prazeodimo","praseodym"],
["predikato","predikat"],
["preferi","föredra"],
["prelego","föreläsning","föredrag"],
["preludo","preludium","förspel"],
["prepara","förberedande"],
["prepari","förbereda"],
["preriomevo","präriemås"],
["preskaŭ","nästan"],
["preteksto","förevändning"],
["prezidanto","ordförande","president"],
["prezidi","vara ordförande","härska"],
["preĝejo","kyrka"],
["preĝi","bedja"],
["prijuĝi","bedöma"],
["prikanti","besjunga"],
["prilumi","belysa","lysa upp (något)"],
["primitiva","primitiv"],
["primolacoj","viveväxter"],
["primolo","gullviva"],
["princino","prinsessa"],
["princo","prins"],
["printempo","vår"],
["prioritatigi","prioritera"],
["prioritato","prioritet"],
["priplori","begråta"],
["prirabi","råna"],
["priserĉi","visitera"],
["priskribi","beskriva"],
["prismo","prisma"],
["pro","på grund av","för"],
["problema","problematisk"],
["problemo","problem"],
["procezo","process"],
["profani","vanhelga"],
["profesio","yrke"],
["profesoro","professor"],
["profetaĵo","profetia"],
["profeto","profet"],
["profilo","profil"],
["profunda","djup"],
["profundeco","djup"],
["profundegaĵo","avgrund"],
["profundego","avgrund"],
["profundo","djup"],
["prognozo","prognos"],
["programado","programmering","matematisk programmering"],
["programaro","programvara","mjukvara"],
["programero","programpunkt"],
["programi","programmera"],
["programisto","programmerare"],
["programlingvo","programmeringsspråk"],
["programo","program"],
["prohibi","förbjuda"],
["prologo","prolog"],
["promeni","promenera"],
["promesi","lova"],
["promeso","löfte"],
["prometio","prometium"],
["promontoro","udde"],
["pronomo","pronomen"],
["prononci","uttala"],
["propagando","propaganda"],
["proponi","föreslå","erbjuda"],
["prostituejo","bordell"],
["prostitui","prostituera"],
["protaktinio","protaktinium"],
["proteino","protein"],
["protono","proton"],
["prototipo","prototyp"],
["proverbo","ordspråk"],
["provizora","provisorisk"],
["prunti","låna"],
["prunuso","plommonsläktet"],
["pruvi","bevisa"],
["pruvo","bevis"],
["psalmo","psalm"],
["pseŭdonimo","pseudonym"],
["pugno","knytnäve"],
["pulio","block (hissanordning)","remskiva"],
["pulovero","pullover","tröja"],
["puni","straffa"],
["puno","straff"],
["pupilo","pupill"],
["pupo","puppa","docka"],
["pupteatro","dockteater"],
["pura","ren"],
["purema","renlig"],
["purigi","rena","rengöra"],
["puto","brunn"],
["rabaglo","stäppörn"],
["rabarbo","rabarber"],
["rabato","rabatt (prisnedsättning)"],
["rabaĵo","byte"],
["rabejo","rövarhåla"],
["rabi","röva","plundra","råna"],
["rabia","rabiessmittad","rasande","ursinnig","rabiat"],
["rabio","rabies","raseri","ursinne"],
["rabisto","rövare","rånare"],
["rabmevo","labb"],
["rabotaĵo","hyvelspån"],
["raboti","hyvla"],
["rabotilo","hyvel"],
["racia","förnuftig","rationell","förnuftsenlig"],
["racieco","förnuftighet"],
["raciismo","rationalism"],
["racio","förnuft"],
["racionala","rationell"],
["racionalismo","rationalism"],
["racionalo","rationellt tal"],
["radikala","radikal"],
["raditeleskopo, radioteleskopo","radioteleskop"],
["radiumo","radium"],
["rado","hjul"],
["radono","radon"],
["radŝuo","rullskridsko"],
["rajdi","rida"],
["rajtigilo","tillstånd","licens"],
["ranca","härsken"],
["rano","groda"],
["ranunkolacoj","ranunkelväxter"],
["rapida","snabb","rask"],
["rapsodo","rapsod"],
["raso","ras"],
["rato","råtta"],
["ravino","ravin"],
["razeno","gräsmatta"],
["razi","raka"],
["razilo","rakhyvel"],
["razisto","barberare"],
["raŭka","hes"],
["reago","reaktion"],
["refoje","igen","en gång till"],
["rekantaĵo","refräng"],
["reklamo","reklam"],
["rekordo","rekord"],
["rekordulo","rekordhållare"],
["rekruto","rekryt"],
["rektangulo","rektangel"],
["rektoro","rektor"],
["remorko","släp"],
["remparo","mur"],
["renio","rhenium"],
["reno","njure"],
["rentgenio","röntgenium"],
["rento","ränta"],
["respekti","respektera"],
["respekto","respekt"],
["retano","internetanvändare"],
["retbabilejo","chatt"],
["retletero","e-brev","e-mail"],
["reto","nät"],
["retpoŝto","e-post","e-mail"],
["retroaktiva","retroaktiv"],
["returne","tillbaka"],
["retuŝi","retuschera"],
["reveturi","åka tillbaka"],
["rezistanco","resistans"],
["rezisti","motstå"],
["rezolucio","resolution"],
["reĝa aglo","kungsörn"],
["reĝa molanaso","praktejder"],
["ribo","vinbär"],
["ribonuklea acido","ribonukleinsyra","RNA"],
["ridegi","gapskratta"],
["rideti","le"],
["ridi","skratta"],
["ridmevo","skrattmås"],
["rikolti","skörda"],
["rimedo","medel"],
["rimeno","rem"],
["rimiĝi, interrimi","rimma"],
["rimo","rim"],
["ringa fingro","ringfinger"],
["ringo","ring"],
["ringobeka mevo","ringnäbbad mås"],
["rinocero","noshörning"],
["ripari","reparera"],
["ripeti","upprepa","repetera"],
["ripozi","vila"],
["risorto","fjäder"],
["ritmo","rytm"],
["rivalo","rival"],
["rizejo","risfält"],
["rizkampo","risfält"],
["rizo","ris"],
["riĉa","rik","fattig"],
["rodio","rodium"],
["romano","roman"],
["ronki","snarka"],
["roso","dagg"],
["rostbefo","rostbiff"],
["roza","rosa"],
["rozacoj","rosväxter"],
["rozakvo","rosenvatten"],
["rozmevo","rosenmås"],
["rozo","ros"],
["rubidio","rubidium"],
["ruino","ruin"],
["rukti","rapa"],
["rulbloko","block (hissanordning)"],
["ruleto","roulette"],
["rulseĝo, radseĝo","rullstol"],
["rulŝtuparo","rulltrappa"],
["rulŝuo","rullskridsko"],
["rusti","rosta"],
["rustiĝi","rosta"],
["rusto","rost"],
["rutenio","rutenium"],
["ruterfordio","rutherfordium"],
["ruĝa","röd"],
["sabato","lördag"],
["sabli","sanda"],
["sablo","sand"],
["sablopapero","sandpapper"],
["sabro","sabel"],
["safiro","safir"],
["sago","pil"],
["sagujo","koger"],
["sakri","svära"],
["sala","salt (adj.)"],
["sali","salta"],
["salivi","utsöndra saliv"],
["salivo","saliv"],
["salivumi","dregla"],
["salo","salt"],
["salti","hoppa"],
["salto","hopp"],
["saluti","hälsa (verb)","logga in"],
["salutnomo","inloggningsnamn","användarnamn"],
["saluto","hälsning"],
["samario","samarium"],
["sana","frisk","vid god hälsa"],
["sangadi","blöda"],
["sangadulto","incest"],
["sango","blod"],
["sano","hälsa"],
["sapo","tvål"],
["sapumi","tvåla in"],
["sario","sari"],
["sata","mätt"],
["satigi","mätta"],
["satureo","sommarkyndel"],
["saŭno","bastu"],
["sciuro","ekorre"],
["se","om","ifall"],
["se kaj nur, se... kaj nur tiam","om och endast om","omm"],
["seaborgio","seaborgium"],
["sed","men"],
["sedimento","sediment"],
["segi","såga"],
["segilo","såg"],
["seka","torr"],
["sekalo","råg"],
["sekci","dissekera"],
["sekcio","sektion"],
["sekigi","torka"],
["sekiĝi","torkas","torka ut"],
["sekreta","hemlig"],
["sekrete","i hemlighet"],
["sekretema","hemlighetsfull"],
["sekreti","hålla en hemlighet","anförtro en hemlighet"],
["sekretigi","hemlighålla"],
["sekreto","hemlighet"],
["sekshontemo, sekshonto","pryd"],
["sekto","sekt"],
["sekura","säker"],
["sekurrimeno","säkerhetsbälte","bilbälte"],
["sekurzono","säkerhetsbälte","bilbälte"],
["seleno","selen"],
["semaforo","trafiksignal"],
["semajno","vecka"],
["semantiko","semantik"],
["semi","så"],
["senagado","inaktivitet"],
["senbarba","skägglös","slätrakad"],
["sendanka","otacksam"],
["sendi","sända"],
["sendieco, sendiismo","ateism"],
["sendito","sändebud"],
["sendiulo","ateist"],
["senhaŭtigi","flå"],
["senhejmulo","hemlös"],
["senhelpa","hjälplös"],
["senhonta","skamlös"],
["senkirla","virvelfri"],
["senkora","hjärtlös"],
["senkulpa","oskyldig"],
["senmakula","obefläckad"],
["senpaperulo","papperslös"],
["senprepara","oförberedd"],
["senvostuloj","stjärtlösa groddjur"],
["senĉesa","oupphörlig"],
["senŝeligi","skala"],
["senŝeligilo","potatisskalare","skalare"],
["sep","sju"],
["septembro","september"],
["serioza","seriös"],
["serpentaglo","ormörn"],
["serpento","orm"],
["serumo","serum"],
["serĉi","söka","leta"],
["ses","sex"],
["sezamo","sesam"],
["seĝo","stol"],
["siberia molanaso","alförrädare"],
["sidvango","skinka (kroppsdel)"],
["silabo","stavelse"],
["siliciato","silikat"],
["silicio","kisel"],
["silkopapero, silkpapero","silkespapper"],
["silviedoj","sångare"],
["silvio","sångfågel"],
["singularo","singular"],
["sinofero","självuppoffring"],
["sistemo","system"],
["skalaro","skalär"],
["skaldo","skald"],
["skandio","skandium"],
["skeleto","skelett"],
["skiisto","skidåkare"],
["skio","skida"],
["skrapgumo","radergummi","suddgummi"],
["skrapi","skrapa"],
["skrapilo","skrapa (subst.)"],
["skriba","skriftlig"],
["skribado","skrift (aktivitet)"],
["skribaĵo","skrift"],
["skriberaro","stavfel","skrivfel"],
["skribi","skriva"],
["skribisto","skrivare (yrke)"],
["skribkaraktero","handstil"],
["skribmaniero","handstil"],
["skribmaŝino","skrivmaskin"],
["skribo","skrift"],
["skribtablo","skrivbord"],
["skrofulariacoj","lejongapsväxter"],
["skvamo","fjäll (på fiskar t.ex.)"],
["slogano","slogan"],
["slojdo","slöjd"],
["smirgopapero, smirga papero","sandpapper"],
["socia","social","samhällelig"],
["socio","samhälle"],
["sofo","soffa"],
["sojlo","tröskel"],
["soldato","soldat"],
["solena","högtidlig"],
["somaterio","ejder"],
["somerdomo","sommarstuga"],
["somere","på sommaren"],
["somero","sommar"],
["sonĝi","drömma"],
["sonĝo","dröm"],
["sopiri","längta"],
["sopiro","längtan"],
["sorparbo, sorpujo","oxel"],
["sortimento","sortiment"],
["sorĉarto","trollkonst"],
["spasmo","spasm"],
["speguli","(åter)spegla"],
["spegulo","spegel"],
["spermo","sperma"],
["sporada","sporadisk"],
["sproni","sporra"],
["sprono","sporre"],
["stacidomo","station","stationshus"],
["stameno","ståndare"],
["stampi","stämpla"],
["stani","förtenna"],
["stano","tenn"],
["stari","stå"],
["starigi","ställa"],
["starti","starta"],
["statiko","statik"],
["statistiko","statistik"],
["stato","tillstånd","skick"],
["statuo","staty"],
["stearino","stearin"],
["stelo","stjärna"],
["stenografado, stenografarto","stenografi"],
["stenografi","stenografera"],
["stenografio","stenografi"],
["stepaglo","stäppörn"],
["stepo","stäpp","hed"],
["steradiano","steradian"],
["sterki","gödsla"],
["sterko","gödsel"],
["sterkorario","labb"],
["stipo","fjädergräs"],
["strando","strand"],
["stroncio","strontium"],
["struto","struts"],
["studento","student"],
["studi","studera"],
["studĝardeno, eksperimentĝardeno","botanisk trädgård"],
["stupao","stupa"],
["sturgo","stör"],
["sub","under"],
["suba","undre"],
["subarbo","delträd"],
["subbrako","armhåla"],
["subjupo","underkjol"],
["submeti","underställa","underkasta"],
["submetiĝi","underkasta sig"],
["suboficiro","underofficer"],
["subskribi","underteckna","skriva under"],
["subskribo","underskrift"],
["suka","saftig"],
["sukeri","sockra"],
["sukero","socker"],
["suko","saft","essens"],
["sukoplena, sukoriĉa","saftig"],
["sulfo","svavel"],
["sulfuro","svavel"],
["sunbruno","solbränna"],
["sunfloro","solros"],
["suno","sol"],
["superjaro","skottår"],
["supernatura","övernaturlig"],
["supersateco, trosatiĝo","övermätt","däst"],
["supo","soppa"],
["sur","på"],
["surda","döv"],
["surfaco","yta"],
["surmeti","ta på sig","klä sig med"],
["surpaperigi","skriva ner"],
["surrena glando","binjure"],
["survango, vangobato","örfil"],
["svarmi","svärma"],
["svarmo","svärm"],
["sveda","svensk"],
["svedo","svensk"],
["svedujo","Sverige"],
["svelta","slank"],
["sveni","svimma"],
["svislando","Svejts"],
["svisujo","Svejts"],
["tabako","tobak"],
["tabanedoj","bromsar( familj)"],
["tabano","broms"],
["tabelo","tabell","fält"],
["tabernaklo","tabernakel"],
["tablo","bord"],
["tabulo","bräda","skiva","tavla"],
["tabuo","tabu"],
["tabureto","pall (att sitta på)"],
["tafto","taft"],
["tage","på dagen"],
["tagnokto","dygn"],
["tago","dag"],
["tajdo","tidvatten"],
["tajloro","skräddare"],
["tajpi","skriva på maskin"],
["tajpilo","skrivmaskin"],
["taksi","taxera","uppskatta","värdera"],
["taksio","taxi"],
["taksusacoj","idegransväxter"],
["taksuso","idegran"],
["taktiko","taktik"],
["takto","takt"],
["talento","begåvning","talang"],
["talio","midja","liv","tallium"],
["talismano","talisman"],
["taliumo","tallium"],
["talko","talk"],
["talmudo","talmud"],
["talpo","mullvad"],
["tamarikacoj","tamariskväxter"],
["tamariko","klådris"],
["tamburi","trumma"],
["tamburino","tamburin"],
["tamburo","trumma"],
["tamen","dock","likväl","ändå"],
["tampono","tampong"],
["tamtamo","gonggong"],
["tangi","dansa tango"],
["tango","tango"],
["tani","garva"],
["tantalo","tantal"],
["tantrismo","tantrism"],
["tantro","tantra"],
["tapeti","tapetsera"],
["tapeto","tapet"],
["tapiŝo","matta","bonad"],
["taro","taro"],
["tasko","process","uppgift"],
["taso","kopp"],
["tatuaĵo","tatuering"],
["tatui","tatuera"],
["teatro","teater"],
["teflono","teflon"],
["tegmento","(ytter-)tak","(hus-)vind"],
["teknecio","teknetium"],
["teknika","teknisk"],
["teknikisto","tekniker"],
["tekniko","teknik"],
["teknologia","teknologisk"],
["teknologio","teknologi"],
["teksto","text"],
["telefoni","telefonera","prata i telefon"],
["telefonnumero","telefonnummer"],
["telefono","telefon"],
["telero","tallrik"],
["teleskopo","teleskop"],
["televidi","se på television"],
["televidilo","TV-mottagare","TV","teve"],
["televido","television","TV","teve"],
["teluro","tellur"],
["temi","handla (om)"],
["temo","tema"],
["temperaturo","temperatur"],
["tempio","tinning"],
["tendaro","läger"],
["tendeno","sena"],
["tendo","tält"],
["tenisejo","tennisbana","tennisplan"],
["teniso","tennis","bordtennis","pingis","pingpong"],
["teo","te"],
["tera-","tera-"],
["terbio","terbium"],
["terceto","terzett"],
["terkapo","udde"],
["termika","termisk"],
["termometro","termometer"],
["terni","nysa"],
["terpeĉo","asfalt"],
["testamenti","testamentera"],
["testamento","testamente"],
["tetraono","tetrao"],
["teĥnika","teknisk"],
["teĥnikisto","tekniker"],
["teĥniko","teknik"],
["teĥnologia","teknologisk"],
["teĥnologio","teknologi"],
["tial","därför"],
["tial ke, tial ĉar","därför att"],
["tiam","då"],
["tiama","dåvarande"],
["tigro","tiger"],
["tipio","tipi"],
["tirboji","yla"],
["titano","titan"],
["toasto","rostat bröd"],
["tokipono","Toki pona"],
["tolueno","toluen"],
["tomato","tomat"],
["torio","torium"],
["trabo","bjälke"],
["trafiko","trafik"],
["trajno","tåg"],
["tralikiĝi","läcka (igenom)"],
["tramo","spårvagn","spårvagnsräls"],
["tramvojo","spårvagnsspår"],
["transloki","flytta (något)","transportera"],
["transruĝa","infraröd"],
["transurania","transuransk"],
["transuranio","transuran"],
["transviola","ultraviolett"],
["tranĉi","skära"],
["tranĉilo","kniv"],
["trapo","sjönöt","sjönötsfrukt"],
["trapofrukto, trapfrukto","sjönötsfrukt"],
["traserĉi","genomsöka"],
["travadejo","vadställe"],
["traveturi","åka igenom"],
["travintri, vintri","övervintra"],
["trefo","klöver"],
["tri","tre"],
["triangula","triangulär"],
["triangulo","triangel"],
["trifingra buntpego","tretåig hackspett"],
["trifingra mevo","tretåig mås"],
["triki","sticka"],
["trikilo","sticka (redskap)"],
["trikoloreto","styvmorsviol"],
["trinkakvo","dricksvatten"],
["tripiedo","trefot"],
["tritiko","vete"],
["triunuo","treenigheten"],
["trotuaro","trottoar"],
["trovi","finna","hitta"],
["troviĝi","befinna sig"],
["truto","öring"],
["tufanaso","vigg"],
["tulio","tulium"],
["tulipo","tulpan"],
["tunelo","tunnel"],
["turbano","turban"],
["turbino","turbin"],
["turismo","turism"],
["turisto","turist"],
["turka","turkisk"],
["turko","turk"],
["turkujo","Turkiet"],
["turni","vrida","vända","förvandla"],
["turniro","turnering"],
["turniĝi, sin turni","rotera","vridas","vändas","vända sig","förvandlas"],
["turo","torn"],
["turto","turturduva"],
["tusi","hosta"],
["tusilago","hästhov (ört)"],
["tuso","hosta (subst.)"],
["tuta","hela"],
["tute","helt (och hållet)"],
["tuteco","helhet"],
["tuĉi","rita eller skriva med tusch"],
["tuĉo","tusch"],
["tuŝi","röra (vid)","beröra"],
["tvisto","twist"],
["udono","udon"],
["ukraina","ukrainsk"],
["ukrainio","Ukraina"],
["ukraino","ukrainier","Ukraina"],
["ukrainujo","Ukraina"],
["ukrajnujo","Ukraina"],
["ulmacoj","almväxter"],
["ulmo","alm"],
["ulno","aln","armbågsben","ulna"],
["umbilika ŝnuro","navelsträng"],
["umbiliko","navel"],
["umearbo","ume-träd"],
["umeo","ume-frukt"],
["ungego","klo"],
["ungo","nagel","klo"],
["uniformo","uniform"],
["unika","unik"],
["unikorno","enhörning"],
["unio","union","union (i programmeringsspråket C)"],
["universala","universell"],
["universitato","universitet"],
["universo","universum"],
["unu","en","ett"],
["unua","första"],
["unucikli","cykla på enhjuling"],
["unuciklisto","enhjulingcyklist"],
["unuciklo","enhjuling"],
["unue","först (och främst)","för det första"],
["unueco","enhetlighet"],
["unuforma","enhetlig","enformig"],
["unuigi","förena"],
["unuiĝi","förenas"],
["unukotiledonaj","enhjärtbladiga"],
["unuo","enhet"],
["unuokula","enögd"],
["unuopa","individuell"],
["unuvoĉa, ĉiesvoĉa","enstämmigt"],
["uragano","orkan"],
["uranio","uran"],
["urbo","stad"],
["urbodomo","stadshus"],
["urinado","urinerande (handling)","kissande (handling)"],
["urini","urinera","kasta vatten","kissa"],
["urino","urin","kiss"],
["urinveziko","urinblåsa"],
["urno","urna"],
["urodeloj","stjärtgroddjur"],
["urogalo","tjäder"],
["ursedoj","björnar (familj)"],
["urso","björn"],
["utila","nyttig"],
["utiligi","nyttja","använda"],
["utilo","nytta"],
["utopio","utopi"],
["uzado","användning"],
["uzi","använda"],
["vadejo","vadställe"],
["vadi","vada"],
["vaflo","våffla"],
["vagi","ströva","irra omkring"],
["vagino","vagina"],
["vakcinio","lingon"],
["valida","giltlig"],
["validi","gälla"],
["valo","dal"],
["valsi","valsa"],
["valso","vals"],
["vampiro","vampyr","blodsugare"],
["vanadio","vanadin"],
["vanado","vanadin"],
["vango","kind"],
["varfo","kaj","brygga","pir"],
["varma","varm"],
["varmega","het"],
["varmego","hetta"],
["varmeta","ljum"],
["varmo","värme"],
["varmumi","bli förkyld"],
["vegana","vegansk"],
["veganismo","veganism"],
["vegano","vegan"],
["vegetara","vegetarisk"],
["vejno","ven"],
["vektoro","vektor"],
["veldi","svetsa"],
["veldisto","svetsare"],
["velo","segel"],
["vendredo","fredag"],
["ventro","mage","buk"],
["verbasko","kungsljus"],
["verda","grön"],
["verda pego","gröngöling"],
["verki","författa","skriva","komponera"],
["verkilo","ordbehandlare"],
["verkisto","författare","kompositör"],
["verko","verk"],
["vermo","mask"],
["vermoj","maskar"],
["vertikala","vertikal","lodrät"],
["veruko","vårta"],
["verŝajna","sannolik"],
["vespero","kväll"],
["vespo","geting"],
["vestoŝranko","garderob","klädskåp"],
["veterprognozo","väderprognos"],
["veturi","åka","fara","färdas"],
["veturigi","skjutsa","köra"],
["veturigisto","förare","chaufför"],
["veturilo","fordon"],
["viando","kött"],
["vinagro","vinäger"],
["vindaĵo","blöja"],
["vindotablo","skötbord"],
["vindotuko","blöja"],
["vino","vin"],
["vintro","vinter"],
["viola","violett"],
["violego","styvmorsviol"],
["violkolora","violett"],
["violkoloro","violett (subst.)"],
["violo","viol"],
["vipi","piska"],
["vipo","piska"],
["virkato","hankatt"],
["viruso","virus"],
["viskio","whisky"],
["viskozo","viskos"],
["vitrino","vitrinskåp"],
["vitro","glas"],
["viva arĝento","kvicksilver"],
["vivpano, vivopano","levebröd"],
["viziti","besöka"],
["vizito","besök"],
["vodko","vodka"],
["vokalo","vokal"],
["vole ne","vare sig man vill eller inte"],
["volframo","volfram"],
["voli","vilja (verb)"],
["volo","vilja (subst.)"],
["vomnuksarbo","rävkaketräd"],
["vomnukso","kräknöt"],
["vosto","svans","stjärt","släp","kö"],
["vulgara","vanlig","allmän","vulgär"],
["vulkano","vulkan"],
["vulpo","räv"],
["vulturo","gam"],
["zebro","zebra"],
["zefiro","västanfläkt"],
["zenito","zenit"],
["zepto-","zepto-"],
["zeta-","zetta-"],
["zigzago","sicksacklinje"],
["zingibro","ingefära"],
["zinki","förzinka"],
["zinko","zink"],
["zirkonio","zirkonium"],
["zizelo","sisel"],
["zodiako","zodiak","djurkrets"],
["zombio","zombie"],
["zono","bälte","gördel","midja","liv"],
["zoologiisto","zoolog"],
["zoologio","zoologi","djurlära"],
["zoologo","zoolog"],
["ĉampano","champagne"],
["ĉapelo","hatt"],
["ĉapitro","kapitel"],
["ĉapo","mössa"],
["ĉasdomo","jaktstuga"],
["ĉashundo","jakthund"],
["ĉasi","jaga"],
["ĉasisto","jägare"],
["ĉasta","kysk"],
["ĉefurbo","huvudstad"],
["ĉesi","upphöra"],
["ĉesigi","avbryta","avsluta"],
["ĉia","all slags"],
["ĉial","av alla skäl"],
["ĉiam","alltid"],
["ĉie","överallt"],
["ĉiel","på alla sätt "],
["ĉielarko","regnbåge"],
["ĉielo","himmel"],
["ĉielskrapanto, nubskrapanto","skyskrapa"],
["ĉies","var och ens","allas"],
["ĉifri","chiffrera"],
["ĉifro","chiffer"],
["ĉimpanzo","schimpans"],
["ĉiom","alltsammans"],
["ĉirkaŭbraki","krama","omfamna"],
["ĉirkaŭkolo","halsband"],
["ĉirkaŭmeti","omgärda med"],
["ĉiuhore","varje timma"],
["ĉiujara","årlig"],
["ĉiutaga","daglig","vardaglig"],
["ĉiĉerono","guide"],
["ĉokolado","choklad"],
["ĝangalo","djungel"],
["ĝardenbrasiko","kål"],
["ĝardenisto","trädgårdsmästare"],
["ĝardeno","trädgård"],
["ĝelabo","djellabah"],
["ĝemelo","tvilling"],
["ĝemeloj","Tvillingarna"],
["ĝenerala","generell","allmän"],
["ĝermanaj lingvoj","germanska språk"],
["ĝermano","german"],
["ĝi","den","det"],
["ĝia","dess"],
["ĝibo","puckel"],
["ĝirafo","giraff"],
["ĝisdatigi","uppdatera"],
["ĝoja","glad","glädjefull"],
["ĝoji","glädjas"],
["ĝojigi","glädja"],
["ĝojo","glädje"],
["ĝuado, ĝuo","njutning"],
["ĝui","njuta"],
["ĥameleono","kameleont"],
["ĥamemoro, kamemoro","hjortron"],
["ĥaosa","kaotisk"],
["ĥaose","kaotiskt"],
["ĥaosigi","oordna","orsaka kaos"],
["ĥaoso","kaos"],
["ĥemia","kemisk"],
["ĥemiaĵo","kemikalie"],
["ĥemio","kemi"],
["ĥina","kinesisk"],
["ĥino","kines"],
["ĥinujo","Kina"],
["ĥirurgia","kirurgisk"],
["ĥirurgiisto","kirurg"],
["ĥirurgio","kirurgi"],
["ĥirurgo","kirurg"],
["ĥitino","kitin"],
["ĥolero","kolera"],
["ĥorano","körsångare"],
["ĥoro","kör (mus.)"],
["ĵaluza","svartsjuk"],
["ĵaluzi","vara svartsjuk"],
["ĵaluzo","svartsjuka"],
["ĵargono","jargong"],
["ĵaŭdo","torsdag"],
["ĵigo","jig"],
["ĵongli","jonglera"],
["ĵonglisto","jonglör"],
["ŝafo","får"],
["ŝajni","tyckas","synas","förefalla"],
["ŝajnigi","låtsa(s)","föregiva"],
["ŝakalo","schakal"],
["ŝakludo","schack"],
["ŝako","schack"],
["ŝakpeco","schackpjäs"],
["ŝaktabulo","schackbräde"],
["ŝakto","(gruv)schakt"],
["ŝalo","schal"],
["ŝamanismo","schamanism"],
["ŝamano","schaman"],
["ŝamo","sämskskinn"],
["ŝampuo","schampo"],
["ŝarko","haj"],
["ŝelko","hängslen"],
["ŝelkozono","sele"],
["ŝelo","skal (program)","terminalprogram"],
["ŝenoprazo","gräslök"],
["ŝerci","skämta"],
["ŝi","hon"],
["ŝimi","mögla"],
["ŝimo","mögel"],
["ŝinko","skinka"],
["ŝipŝelo","skrov"],
["ŝiri","riva itu","dra sönder","slita"],
["ŝpari","spara"],
["ŝparigi, ŝpari","bespara"],
["ŝranko","skåp"],
["ŝraŭbi","skruva"],
["ŝraŭbilo","skruvmejsel"],
["ŝraŭbingo","mutter"],
["ŝraŭbo","skruv"],
["ŝtalo","stål"],
["ŝtata","statlig"],
["ŝtato","stat"],
["ŝtelaĵo","stöldgods"],
["ŝtele","i smyg"],
["ŝteli","stjäla"],
["ŝteliri","smyga"],
["ŝtelisto","tjuv"],
["ŝtelo","stöld"],
["ŝtelumi","smyga"],
["ŝternmevo","tärnmås"],
["ŝtofo","tyg"],
["ŝtonejo, ŝtonrompejo","stenbrott"],
["ŝtoniĝi","förstenas"],
["ŝtonmortigi","stena till döds"],
["ŝtono","sten"],
["ŝtontranĉisto","stenhuggare"],
["ŝtonumi","stena (till döds)"],
["ŝtopi","stoppa (till)","proppa","korka"],
["ŝtormo","storm"],
["ŝtrumpeto","socka","strumpa"],
["ŝtrumpo","strumpa"],
["ŝtrumpoligilo, ŝtrumpoŝelko","strumpeband"],
["ŝtuparlifto","rulltrappa"],
["ŝtuparo","trappa"],
["ŝtupetaro","stege"],
["ŝtupo","trappsteg"],
["ŝultro","skuldra","axel"],
["ŝuo","sko"],
["ŝuŝi","brusa","fräsa (ljud)"],
["ŝuŝo","brus","fräsande (ljud)"],
["ŝvebi","sväva"],
["ŝviti","svettas"],
["ŝvito","svett"],
];
var revo_sv_lower = revo_sv.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
// @license-end
