// La Reta Vortaro, GPLv2
'use strict';
var revo_ku = [
["akvo","av"],
["ami","hez kirin"],
["amiko","hewal"],
["arbo","dar"],
["blanko","spî"],
["bluo","şîn"],
["brako","bask, mil, nig"],
["cent","sed"],
["dek","deh"],
["doni","dayîn, dan"],
["dormi","xew de çûn, xewtin, xewîn, nivîn"],
["du","du"],
["edzino","bimêr"],
["edzo","bijin"],
["fermi","girtin, dadan"],
["flavo","zer"],
["floro","kulîlk, çîçek"],
["fraŭlino","ezeb(jin)"],
["fraŭlo","ezeb(mer)"],
["freneza","dîn, şêt"],
["granda","gewre, mezin"],
["homa","mirov"],
["infano","zarok, mindal"],
["insulti","çêr kirin"],
["iri","çûyîn, çûn"],
["kampo","zevî"],
["kapo","ser"],
["kara","delal"],
["kial","çima"],
["kie","ku"],
["kombilo","şeh"],
["kvar","çar"],
["kvin","pênc"],
["lando","welat"],
["legi","xwendin"],
["libera","azad"],
["libero","azadî"],
["listo","lîste"],
["lito","nivîn"],
["malfermi","vekirin"],
["mallibera","darazxwar"],
["maro","derya"],
["marŝi","rê ve çûn, meşîn"],
["masko","rûpûş"],
["mateno","sibe"],
["mi","ez"],
["mil","hezar"],
["miliono","milyon"],
["milito","şer, ceng"],
["mono","pere, draf"],
["naŭ","neh"],
["nigro","reş"],
["nokto","şev"],
["nomo","nav"],
["ok","heşt"],
["okulo","çav"],
["pano","nan"],
["patrino","da, dê"],
["piedo","nig"],
["ruĝo","Sor"],
["sep","heft"],
["ses","şeş"],
["skribi","nivîsandin"],
["streĉi","vekêşandin, şidandin"],
["tago","roj"],
["teni"," pê girtin, tepiş, derdest kirin"],
["tero","ax"],
["tri","sê"],
["trinki","vexwarin"],
["urbo","bajar"],
["verdo","kesk"],
["vespero","êvar"],
["vidi","dîtin"],
["vivi","jîn, jiyîn"],
["viŝi","paqijkirin"],
["ĉevalo","hesp"],
["ĉielo","asîman"],
["ĵeti","avêtin"],
["ŝipo","keştî"],
];
var revo_ku_lower = revo_ku.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
