// La Reta Vortaro, GPLv2
'use strict';
var revo_la = [
["Aviceno","Avicenna"],
["Cezaro","C. Iulius Caesar"],
["Florenco","Florentia"],
["Francio","Francia"],
["Germanio","Germania"],
["Hieronimo","Hieronymus"],
["Kartezio","Renatus Cartesius"],
["Kolĥido","Colchis"],
["Latiano","Latinus"],
["Latio","Latium"],
["Malgrandpolujo","Polonia Minor"],
["Metodio","Methodius"],
["Neŭtono","Newtonus"],
["Oriono","Orion"],
["Polio","Polonia"],
["Pontio","Pontius"],
["Regensburgo","Ratisbona"],
["Septuaginto","Septuaginta"],
["Sergio","Sergius"],
["Sigismundo","Sigismundus"],
["Siriuso","Sirius"],
["Vatikano","Vaticanus"],
["Venero","Venus"],
["Venusa","Venereus"],
["Venuso","Venus"],
["Vulgato","(edicio) Vulgata"],
["abelmanĝulo","Merops apiaster"],
["agnateco","agnatio"],
["agnato","agnatus"],
["aktinio","Actium"],
["aktiniumo","Actinium"],
["akvo","aqua"],
["akvoralo","Rallus aquaticus"],
["aluminio","Aluminium"],
["americio","Americum"],
["antimono","Stibium"],
["apud","apud"],
["argono","Argon"],
["arseno","Arsenium"],
["arĝento","Argentum"],
["asaro","as, assis"],
["astateno","Astatinum"],
["astato","Astatinum"],
["azoto","Nitrogenium"],
["aŭriklo","Auricula cordis"],
["aŭtismo","autismus"],
["bario","Barium"],
["berilio","Beryllium"],
["berkelio","Berkelium"],
["birdoherbo","Stellaria media"],
["bismuto","Bismutum"],
["bisturio","scalprum"],
["blua cirkuo","Circus cyaneus"],
["bluvanga abelmanĝulo","Merops superciliosus"],
["borio","Bohrium"],
["boro","Borum"],
["botaglo","Hieraaetus pennatus, Aquila pennata"],
["brankokovrilo, brankoklapo","operculum"],
["bromo","Bromum"],
["cerviko","Cervix"],
["cezio","Caesium"],
["cirozo","cirrhosis"],
["darmŝtatio","darmstadtium"],
["deltoido","Musculus deltoideus"],
["dika intesto","intestinum crassum"],
["dinoterio","deinotherium"],
["dipatrino","Mater Dei, Deipara"],
["disprozio","Dysprosium"],
["doktoro de la Eklezio","doctor ecclesiae"],
["dolo","dolus"],
["dubnio","Dubnium"],
["dukotiledonaj","Dicotelydoneae"],
["duramatro","Dura mater"],
["edilo","aedilis"],
["ejnstejnio","Einsteinium"],
["ejnŝtejnio","Einsteinium"],
["ekaŭdatoj","Batrachia"],
["elaterio","Ecballium elaterium"],
["endormiĝo","Dormitio S. Mariae"],
["entozooj","Entozoa"],
["erbio","Erbium"],
["ergotfungo","clavis purpurea"],
["eta kriaglo","Aquila pomarina"],
["etmoido","Os ethmoidale"],
["ezofago","oesophagus"],
["eŭropio","Europium"],
["fermio","Fermium"],
["filikoplantoj","Polypodiophyta, Pteridophyta"],
["fiolo","phiala"],
["fistulo","fistula"],
["fiŝaglo","Pandion haliaetus"],
["flerovio","flerovium"],
["fluoro","Fluorum"],
["fosforo","Phosphorus"],
["francio","Francium"],
["franciumo","Francium"],
["francujo","Francia"],
["fregato","fregata"],
["gadolinio","Gadolinium"],
["gajo","Caius, Gaius"],
["galiumo","Gallium"],
["galo","bilis"],
["germaniumo","Germanium"],
["germanujo","Germania"],
["gineceo","Gynoeceum"],
["griza cirkuo","Circus pygargus"],
["gvaranujo","Paullinia cupana, Paullinia guarana"],
["hafnio","Hafnium"],
["hasio","Hassium"],
["heliumo","Helium"],
["hemoptizo","haemoptoë, haemoptysis"],
["hidrogeno","Hydrogenium"],
["holmio","Holmium"],
["hostimontrilo","Ostensorium"],
["indio","Indium"],
["insektomanĝuloj","Insectivora"],
["iridio","Iridium"],
["iterbio","Ytterbium"],
["itrio","Yttrium"],
["jodo","Jodum"],
["juto","Corchorus"],
["kadmio","Cadmium"],
["kalcio","Calcium"],
["kalifornio","Californium"],
["kaliforniumo","Californium"],
["kalio","Kalium"],
["kalkaneo","calcaneum"],
["kalo","callus, clavus"],
["kantio","Kantius"],
["karbono","Carboneum"],
["kartuzio","Ordo Carthusiensis"],
["kio estis pruvota","quod erat demonstrandum, Q.E.D."],
["kitio","Rissa tridactyla"],
["kitivako","Rissa tridactyla"],
["kloro, ĥloro","Chlorum"],
["kobalto","Cobaltum"],
["kompanio","comitatus"],
["kopernicio","copernicium"],
["kotiledono","cotyledon"],
["kriptono","Krypton"],
["kromio","Chromium"],
["kromo, ĥromo","Chromium"],
["ksenono","Xenon"],
["ksifio","Xiphias gladius"],
["kuriumo","Curium"],
["kvar","quattuor"],
["kvara","quartus"],
["kvorumo","quorum"],
["labiacoj","Labiatae"],
["lagopo","Lagopus lagopus, Lagopus lagopus"],
["lakrimalo","Os lacrimale"],
["lakta Vojo","Lacteus orbis"],
["lamelibrankoj","Lamellibranchiata"],
["lamelikornoj","Lamellicornia"],
["lantano","Lanthanum"],
["liktoro","lictor"],
["limfo","lympha"],
["limfonodo","nodus lymphaticus"],
["litio","Lithium"],
["livermorumo","livermorium"],
["livio","Columba livia"],
["lutecio","Lutetium"],
["magnezio","Magnesium"],
["magnolioj","Magnoliophyta, Angiospermae (tradicie)"],
["maldika intesto","intestinum tenue"],
["mangano","Manganum"],
["marĉa cirkuo","Circus aeruginosus"],
["mediĉaj satelitoj","Sidera Medicea"],
["mejtnerio","Meitnerium"],
["mendelevio","Mendelevium"],
["merganaso","Aythya fuligula"],
["meropo","Merops apiaster"],
["meza stelario","Stellaria media"],
["mia","meus"],
["molibdeno","Molibdeanum"],
["monta lagopo","Lagopus mutus"],
["muskoj","Musci"],
["natrio","Natrium"],
["neodimo","Neodymium"],
["neono","Neon"],
["neparhufuloj","Mesaxonia"],
["neptunio","Neptunium"],
["nikelo","Niccolum"],
["niobo","Niobium"],
["nitrogeno","Nitrogenium"],
["nizaglo","Hieraaetus fasciatus"],
["nobelio","Nobelium"],
["oksigeno","Oxygenium"],
["olivarbo, olivujo","Olea europaea"],
["ora aglo","Aquila chrysaëtos, Aquila chrysaetos"],
["oro","Aurum"],
["osmio","Osmium"],
["ostofiŝoj","Osteichtyes"],
["pagro","pagrus"],
["paladio","Palladium"],
["pandiono","Pandion haliaetus"],
["paĉulo","Pogostemon patchouli"],
["perikarpo","pericarpium"],
["perineo","perineum"],
["peritoneo","peritoneum"],
["persimonujo orienta","Diospyros kaki"],
["persimonujo virginia","Diospyros virginiana"],
["plateno","Platinum"],
["plumbo","Plumbum"],
["plutonio","Plutonium"],
["poliĥetoj","polychaeta"],
["pollando","Polonia"],
["polonio","Polonium"],
["polujo","Polonia"],
["potentilo","Potentilla"],
["prazeodimo","Praseodymium"],
["pretoro","prætor"],
["prociono","Procyon lotor"],
["promecio","Promethium"],
["prometio","Promethium"],
["protaktinio","Protactinium"],
["pugno","pugnus, i"],
["pustulo","pustula"],
["rabmevo","Stercorarius"],
["radiumo","Radium"],
["radono","Radon"],
["rekta intesto","intestinum rectum"],
["renio","Rhenium"],
["rentgenio","roentgenium"],
["reprezalio","repressalia"],
["rodio","Rhodium"],
["rubeolo","Rubella"],
["rubidio","Rubidium"],
["rutenio","Ruthenium"],
["ruterfordio","Rutherfordium"],
["samario","Samarium"],
["sanmarino","Marinusia"],
["seaborgio","Seaborgium"],
["seborgio","Seaborgium"],
["seleno","Selenium"],
["serpentaglo","Circaetus gallicus"],
["silicio","Silicium"],
["skalpelo","scalprum"],
["skandio","Scandium"],
["somaterio","Somateria mollissima"],
["spiroĥeto","spirochaeta"],
["stano","Stannum"],
["sterkorario","Stercorarius"],
["stroncio","Strontium"],
["studĝardeno, eksperimentĝardeno","hortus botanicus"],
["sulfuro","Sulphur"],
["superforto","vis major"],
["svedujo","Suecia"],
["talio","Thallium"],
["taliumo","Thallium"],
["tamiaso","Tamias"],
["tantalo","Tantalum"],
["teknecio","Technetium"],
["teluro","Tellurium"],
["terbio","Terbium"],
["tibio","tibia"],
["titano","Titanium"],
["torako","thorax"],
["torio","Thorium"],
["traĥeo","trachea, trachea"],
["tufanaso","Aythya fuligula"],
["tulio","Thulium"],
["umbelo","umbella"],
["unio","unio"],
["unukotiledonaj","Monocotelydoneae, Liliopsida"],
["uranio","Uranium"],
["urinveziko","vesica urinaria"],
["vanadio","Vanadium"],
["vanado","Vanadium"],
["vegetala regno","Vegetabilia, Plantae"],
["velaro","Vela"],
["vepro","dumetum, frutectum, vepres"],
["verbo","verbum"],
["verda","viridis"],
["verdalgoj, verdaj algoj","Chlorophycota"],
["verdi","vireo"],
["verdo","viride"],
["verukherbo","Chelidonium majus"],
["vespero","vespera, vesper"],
["veziko","vesica"],
["volframo","Wolfram"],
["voĉo","Genus verbi"],
["zinko","Zincum"],
["zirkonio","Zirconium"],
["Ĝenovo","Genua"],
["Ĥeroneo","Chaeronea"],
["ĥelonio","Chelonia mydas"],
["ĥinino","chininum"],
["ĥolero","cholera"],
["ĥordo","chorda dorsalis"],
["ĥoreo","chorea"],
["ŝternmevo","Larus sabini, Xema sabini"],
];
var revo_la_lower = revo_la.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
