// La Reta Vortaro, GPLv2
'use strict';
var revo_id = [
["-forma","[bentuk] berbentuk..."],
["Afriko","Afrika"],
["Ahmadismo","Ahmadiyah"],
["Alaho","Allah"],
["Alĝerio","Aljazair"],
["Ameriko","Amerika"],
["Ampero","Ampere","ampere"],
["Andoro","Andorra"],
["Angolo","Angola"],
["Antarkto","Antarktika"],
["Araba maro","Laut Arab"],
["Argentino","Argentina"],
["Armenio","Armenia"],
["Azerbajĝano","Azerbaijan"],
["Azova maro","Laut Azov"],
["Aŭstralio","Australia"],
["Aŭstrio","Austria"],
["Babelo","Babel"],
["Babelturo","Menara Babel"],
["Bahamoj","Bahama"],
["Balta maro","Laut Baltik"],
["Barato","India"],
["Barbado","Barbados"],
["Belgio","Belgia"],
["Beringa maro","Laut Bering"],
["Beringo","Bering"],
["Biblio","Alkitab"],
["Birmo","Myanmar"],
["Bocvano","Botswana"],
["Bolivio","Bolivia"],
["Bonaero","Buenos Aires"],
["Bosnio","Bosnia"],
["Bosnio kaj Hercegovino","Bosnia Herzegovina"],
["Brazilo","Brazil"],
["Britio","Britania Raya"],
["Brunejo","Brunei Darussalam"],
["Bulgario","Bulgaria"],
["Burundo","Burundi"],
["Butano","Bhutan"],
["Centr-Afriko","Afrika Tengah"],
["Danielo, Daniel","Daniel"],
["Danio","Denmark"],
["Davido, David","Daud"],
["Efeso","Efesus"],
["Egiptio","Mesir"],
["Ekvadoro","Ekuador"],
["Ekvatora Gvineo","Guinea Khatulistiwa"],
["Elbo","Elba"],
["Epifanio","Epifani"],
["Eritreo","Eritrea"],
["Esperantisto","esperantis"],
["Esperanto","Esperanto"],
["Estonio","Estonia"],
["Etiopio","Etiopia"],
["Eŭrazio","Eurasia"],
["Farado","Faraday","farad"],
["Filipinoj","Filipina"],
["Flava maro","Laut Kuning"],
["Flava rivero","Sungai Kuning"],
["Franca Gujano","Guyana Prancis"],
["Francio","Prancis"],
["Gabono","Gabon"],
["Ganao","Ghana"],
["Germanio","Jerman"],
["Granda fasto","Ramadan"],
["Grekio","Yunani"],
["Grenado","Grenada"],
["Gronlando","Greenland","Tanah Hijau"],
["Gujano","Guyana"],
["Gvineo","Guinea"],
["Gvineo-Bisaŭo","Guinea-Bissau"],
["Haloveno","Halloween"],
["Hercegovino","Herzegovina"],
["Heĝiro","Hijriah"],
["Hispanio","Spanyol"],
["Hungario","Hongaria"],
["Ido","Ido"],
["Internacia mona Fonduso","Dana Moneter Internasional","IMF"],
["Interreto","Internet"],
["Irako","Irak","Babilonia","Mesopotamia"],
["Irlando","Irlandia"],
["Islando","Islandia"],
["Israelo","Israel"],
["Italio","Italia"],
["Jakobo, Jakob","Yakub"],
["Jamajko","Jamaika"],
["Japanio","Jepang"],
["Jemeno","Yaman"],
["Jerusalemo","Yerusalem"],
["Jomkipuro","Yom Kippur"],
["Jordanio","Yordania"],
["Jozefo, Jozef","Yusuf"],
["Jugoslavio","Yugoslavia"],
["Jugoslavujo","Yugoslavia"],
["Jupitero","Jupiter","Yupiter"],
["Kaboverdo","Tanjung Verde"],
["Kamboĝo","Kamboja"],
["Kameruno","Kamerun"],
["Kaprikorno","Jadi","Kaprikornus","Makara"],
["Karaa maro","Laut Kara"],
["Kazaĥio","Kazakhstan"],
["Kelvino","Kelvin","kelvin"],
["Kenjo","Kenya"],
["Kipro","Siprus"],
["Kirgizio","Kirgizstan"],
["Kolombio","Kolombia"],
["Kongo Brazavila, Okcidenta Kongo","Republik Kongo"],
["Kongo Kinŝasa, Orienta Kongo","Republik Demokratik Kongo"],
["Korano","Quran","Alquran"],
["Kristanismo","Kristen"],
["Kristnasko","Natal"],
["Kristo","Kristus"],
["Kroatio","Kroasia"],
["Kulombo","Coulomb","coulomb"],
["Kuvajto","Kuwait"],
["Laoso","Laos"],
["Lapteva maro","Laut Laptev"],
["LatinAmeriko"," Latin"],
["Latinidaj lingvoj","bahasa Romanik"],
["Latino","Latin"],
["Latvio","Latvia"],
["Lesbanino","lesbian"],
["Lesbo","Lesbos","lesbian"],
["Lesoto","Lesotho"],
["Libano","Lebanon"],
["Liberio","Liberia"],
["Libio","Libya"],
["Litovio","Lituania"],
["Liĥtenŝtejno","Liechtenstein"],
["Luksemburgo","Luksemburg"],
["Madejro","Madeira"],
["Makedonio","Makedonia"],
["Malajzio","Malaysia"],
["Malavio","Malawi"],
["Malnova testamento","Perjanjian Lama"],
["Malto","Malta"],
["Maroko","Maroko"],
["Marso","Mars"],
["Meksiklando","Meksiko"],
["Meksikurbo","Kota Meksiko"],
["Merkuro","Merkurius"],
["Mezmaro","Laut Mediterania","Laut Tengah"],
["Monako","Monako"],
["Monda Organizaĵo pri meteologio","Organisasi Meteorologi Dunia","WMO"],
["Monda Organizaĵo pri sano","Organisasi Kesehatan Dunia"],
["Montenegro","Montenegro"],
["Mozambiko","Mozambik"],
["Muhamado","Muhammad"],
["Namibio","Namibia"],
["Nederlando","Belanda"],
["Nepalo","Nepal"],
["Neptuno","Neptunus"],
["Neŭtono","Newton","newton"],
["Nigra maro","Laut Hitam"],
["Nord koreujo","Korea Utara"],
["Nord-Irlando, NordIrlando","Irlandia Utara"],
["NordAmeriko","Amerika Utara"],
["Norda maro","Laut Utara"],
["Norvegio","Norwegia"],
["Nov-Zelando","Selandia Baru"],
["Nova testamento","Perjanjian Baru"],
["Novlando","Newfoundland"],
["Novlando kaj Labradoro","Newfoundland dan Labrador"],
["Okcidenta samoo","Samoa Barat"],
["Olimpiko","Olimpiade"],
["Omano","Oman"],
["Omo","Ohm","ohm"],
["Omometro, Ommetro","ohm-meter"],
["Orienta Timoro","Timor Leste","Timor Timur"],
["Orienta Ĉina maro, Orientĉina maro","Laut Cina Timur"],
["Orientsiberia maro","Laut Siberia Timur"],
["Oĥocka maro","Laut Okhotsk"],
["Pakistano","Pakistan"],
["Palaŭo","Palau"],
["Papuo-Nov-Gvineo","Papua Nugini"],
["Paragvajo","Paraguay"],
["Paska semajno","Minggu Paskah"],
["Paskalo","Pascal","Pascal (bahasa pemrograman)","pascal"],
["Pasko","Paskah"],
["Pentekostismo","pentakostalisme"],
["Pentekosto","Pentakosta"],
["Peruo","Peru"],
["Portugalio","Portugal"],
["Principeo","Principe"],
["Readmono","Ulangan (kitab)"],
["Ruando","Rwanda"],
["Rusio","Rusia"],
["Ruĝa maro","Laut Merah"],
["Salafismo","Salafi"],
["Salomono","Salomo","Sulaiman"],
["Sankta skribo","Kitab Suci"],
["Saturno","Saturnus"],
["Sauda arabujo, Saud-arabujo","Arab Saudi"],
["Saĥaleno","Sakhalin"],
["Senegalo","Senegal"],
["Singapuro","Singapura"],
["Sirio","Suriah"],
["Slovakio","Slovakia"],
["Slovenio","Slovenia"],
["Somalio","Somalia"],
["Somera Olimpiko","Olimpiade musim panas"],
["Sud koreujo","Korea Selatan"],
["Sud-Afriko","Afrika Selatan"],
["SudAmeriko","Amerika Selatan"],
["Suda Ĉina maro, Sudĉina maro","Laut Cina Selatan"],
["Sudano","Sudan"],
["Sunaismo","Sunni"],
["Sunao","sunah"],
["Surinamo","Suriname"],
["Svedio","Swedia"],
["Svisio","Swiss"],
["TTT","JJJ (Jejaring Jagat Jembar)","WWW"],
["TTT-ejo","situs web"],
["TTT-paĝaro","situs web"],
["TTT-paĝo","halaman web"],
["Tanzanio","Tanzania"],
["Taĝikio","Tajikistan"],
["Timoro","Timor"],
["Tobago","Tobago"],
["Togolando","Togo"],
["Trinidado","Trinidad"],
["Trinidado kaj Tobago","Trinidad dan Tobago"],
["Tunizio","Tunisia"],
["Turkmenio","Turkmenistan"],
["Ugando","Uganda"],
["Universala kongreso","Kongres Universal"],
["Unuiĝintaj Arabaj emirlandoj","Uni Emirat Arab"],
["Urano","Uranus"],
["Urugvajo","Uruguay"],
["Usono","Amerika Serikat"],
["Vahabismo","Wahabi"],
["Valenteno","Valentine"],
["Vathoro","watt-jam"],
["Vatikano","Vatikan"],
["Vato","Watt","watt"],
["Venezuelo","Venezuela"],
["Venuso","Venus"],
["Vintra Olimpiko","Olimpiade musim dingin"],
["Volapuko","Volapuk"],
["Volto","Volt","volt"],
["Volto je metro","volt per meter"],
["Zambio","Zambia"],
["Zimbabvo","Zimbabwe"],
["a-vorto","adjektiva","kata kerja"],
["abio","cemara"],
["acida","asam"],
["acida pluvo","hujan asam"],
["acido","asam (senyawa)"],
["acipensero","sturgeon"],
["adiaŭ","selamat tinggal"],
["adiaŭi","keluar log"],
["adicii","[jumlah] menjumlahkan","[tambah] menambahkan"],
["adicio","[jumlah] penjumlahan"],
["administrantaro","unit administratif"],
["administrejo","kantor administrasi"],
["administri","[kelola] mengelola","[urus] mengurus"],
["admoni","[ingat] memperingatkan","[tegur] menegur"],
["adresanto","[kirim] pengirim"],
["adresaro","buku alamat"],
["adresi","[alamat] mengalamati","[alamat] mengalamatkan","[tuju] menujukan (surat)"],
["adreso","alamat"],
["aero","udara"],
["aeronaŭtiko","aeronautika"],
["aferisto","[bisnis] pebisnis","[usaha] pengusaha"],
["afero","hal"],
["afganio","Afganistan","afgani"],
["afganujo","Afganistan"],
["agatido","damar"],
["agorafobio","agorafobia"],
["aidoso","AIDS"],
["aidosulo","ODHA"],
["aino","Ainu"],
["ajlo","bawang putih"],
["akacio","akasia"],
["akcenti","[tekan] menekankan"],
["akcento","aksen","tekanan"],
["akcidento","[celaka] kecelakaan"],
["akiri","[dapat] mendapat","[oleh] memperoleh"],
["akompanantaro","rombongan"],
["akompananto","[damping] pendamping","[iring] pengiring"],
["akompani","[damping] mendampingi","[iring] mengiringi","[serta] menyertai","[teman] menemani"],
["akordiono","akordeon"],
["akreo","ekar"],
["akrido","belalang"],
["akselo","ketiak"],
["aktinio","aktinium"],
["aktiniumo","aktinium"],
["akutangula","sudut lancip"],
["akvisto","Akuarius","Delu","Kumba"],
["akvo","air"],
["akvofalo","air terjun"],
["akvohorloĝo","jam air"],
["akvotaksio","taksi air"],
["al","ke","kepada"],
["al antaŭ, antaŭ ...-n","ke depan"],
["al malantaŭ, malantaŭ ...-n","ke belakang"],
["al sub, sub ...-n","ke bawah"],
["al sur","ke atas"],
["albanujo","Albania"],
["albatroso","albatros"],
["albuminurio","albuminuria"],
["aldonvalora imposto","pajak pertambahan nilai"],
["alergia","alergis"],
["alergio","alergi"],
["algoj","alga"],
["algoritmo","algoritme"],
["aliflanke","di sisi lain"],
["aliformi, transformi","ubah mengubah"],
["aliformiĝi, transformiĝi","[metamorfosis] bermetamorfosis","[transformasi] bertransformasi","[ubah] berubah"],
["alilando","luar negeri"],
["alilandulo","warga negara asing"],
["alinomo","alias"],
["aliseksema","heteroseksual"],
["alivorte","dengan kata lain"],
["aliĝi","[daftar] mendaftar"],
["aliĝilo","formulir (pendaftaran)"],
["alko","elk"],
["alkoholaĵo","minuman beralkohol"],
["alkoholismo","alkoholisme"],
["alkoholo","alkohol"],
["almanako","almanak"],
["almenaŭ","paling tidak","sedikitnya","[tidak] setidaknya"],
["almozdonema","dermawan"],
["almozdoni","[amal] beramal","[derma] bederma","[sedekah] bersedekah"],
["almozi, almozpeti","[kemis] mengemis","[minta] meminta"],
["almozisto","[kemis] pengemis","[minta] peminta-minta"],
["almozkesto","kotak amal"],
["almozo","amal","derma","sedekah"],
["almozulo","[kemis] pengemis","[minta] peminta-minta"],
["alnomo, kromnomo","alias"],
["alparoli","[utara] mengutarakan"],
["alta","tinggi"],
["altaĵo","bukit"],
["alteco","[tinggi] ketinggian"],
["altigi","[angkat] mengangkat","[naik] menaikkan"],
["altmaro","(laut) pasang"],
["alto","[tinggi] ketinggian"],
["alumeto","korek api"],
["aluminio","aluminium"],
["alveni","tiba"],
["alŝuti","[unggah] mengunggah"],
["amafero","hubungan cinta"],
["amanto, amantino","pacar"],
["amara","pahit"],
["ambaŭ","dua-duanya","[dua] keduanya"],
["ambaŭflanka","bilateral"],
["ambaŭseksa","biseksual","hermafrodit","monoseus"],
["americio","amerisium"],
["amfiteatro","amfiteater"],
["ami","[cinta] mencintai"],
["amikeco","[sahabat] persahabatan"],
["amiki","[teman] berteman"],
["amikiĝi","[teman] berteman"],
["amiko","kawan","teman","sahabat"],
["aminacido, amina acido","asam amino"],
["amo","cinta"],
["amuzparko","taman hiburan"],
["analitika funkcio","fungsi analisis"],
["anaso","bebek"],
["anatomio","anatomi"],
["androido","Android"],
["angilo","belut"],
["angino","angina"],
["anglujo","Inggris"],
["angulo","sudut"],
["animala","hewani"],
["animalo","binatang","hewan"],
["ankaŭ","juga"],
["ankoraŭ","masih"],
["ankrejo","[labuh] pelabuhan"],
["ankri","[labuh] berlabuh"],
["ankro","jangkar","sauh"],
["anonctabulo","papan pengumuman"],
["anoreksio","anoreksia"],
["ansero","angsa"],
["antaŭ","di depan","[belum] sebelum"],
["antaŭ ĉio","lebih dahulu","pertama-tama"],
["antaŭa","lalu waktu"],
["antaŭanto","[dahulu] pendahulu"],
["antaŭaĵo","front"],
["antaŭe","[belum] sebelumnya"],
["antaŭeco","prioritas"],
["antaŭen","ke depan"],
["antaŭenema","progresif"],
["antaŭenigi","maju"],
["antaŭhaltigi","[cegah] mencegah"],
["antaŭi","[hadap] menghadapi","[hadap] berhadapan (dengan)"],
["antaŭigi","[maju] memajukan"],
["antaŭiĝi","[tonjol] menonjol"],
["antaŭmanĝaĵo","hidangan pembuka"],
["antaŭnomo","nama depan"],
["antaŭparolo","[buka] pembukaan","[dahulu] pendahuluan","kata pengantar","mukadimah","preambul","prolog"],
["antaŭtago, antaŭa tago","hari sebelumnya"],
["antaŭtempa","prematur"],
["antaŭulo","[dahulu] pendahulu"],
["antaŭvespero","sore"],
["antigvo","Antigua"],
["antigvo kaj Barbudo","Antigua dan Barbuda"],
["antimono","antimon"],
["antropologiisto","antropolog"],
["antropologio","antropologi"],
["anĝelo","malaikat"],
["apendicito","apendisitis","radang usus buntu"],
["apopleksio","apopleksi","strok"],
["aprilo","April"],
["aprobi","[setuju] menyetujui"],
["aprobo","[setuju] persetujuan"],
["araba Duoninsulo","Jazirah Arab","Semenanjung Arab"],
["arabujo","Arab"],
["arakido","kacang"],
["araneaĵo","jaring laba-laba"],
["araneo","laba-laba"],
["arbaro","hutan"],
["arbo","pohon"],
["argiltabulo","tablet tanah liat"],
["argono","argon"],
["arkitekturisto","arsitek"],
["arkitekturo","arsitektur"],
["arko","busur"],
["armenujo","Armenia"],
["aro","are"],
["aroganta","arogan","sombong"],
["arseno","arsenik"],
["artefarita","artifisial"],
["artefaritaĵo","artefak"],
["arterio","jalan arteri","arteri","pembuluh nadi"],
["artfajraĵo","kembang api"],
["artisto","artis"],
["arto","seni"],
["artrito","artritis"],
["arvorto","kata umum"],
["arĉinstrumento","alat musik gesek"],
["arĝento","perak"],
["arĥitekturisto","arsitek"],
["arĥitekturo","arsitektur"],
["arĥivo","arsip"],
["asfalti","[aspal] mengaspal"],
["asfalto","aspal"],
["astako","lobster","udang karang"],
["astateno","astatin"],
["astmo","asma"],
["astrobiologio","astrobiologi"],
["astrofiziko","astrofisika"],
["astronaŭto","antariksawan","astronaut","kosmonaut"],
["atendoĉambro","ruang tunggu"],
["atmosfero","atmosfer"],
["atomhorloĝo, atoma horloĝo","jam atom"],
["atrepsio","atrepsia"],
["avino","nenek"],
["aviztabulo","papan pengumuman"],
["avo","kakek"],
["azeno","keledai"],
["azerujo","Azerbaijan"],
["azoto","nitrogen"],
["aĝa","tua","[umur] berumur"],
["aĝi","[umur] berumur","[usia] berusia"],
["aĝo","umur","usia"],
["aŭ","atau"],
["aŭdi","[dengar] mendengar"],
["aŭdo","[dengar] pendengaran"],
["aŭgusto","Agustus"],
["aŭta","automotif","otomotif"],
["aŭtejo","garasi"],
["aŭti","[kemudi] mengemudikan (mobil dsb.)","[kendara] mengendarai (mobil dsb.)","[setir] menyetir (mobil dsb.)"],
["aŭtismo","autisme"],
["aŭtisto","[kemudi] pengemudi","[kendara] pengendara","motoris","sopir"],
["aŭto","mobil"],
["aŭtobusa haltejo","halte bus"],
["aŭtobushaltejo","halte bus"],
["aŭtobuso","bus"],
["aŭtuno","musim gugur"],
["babiltruo","mulut"],
["bagatela","remeh","trivial"],
["bagatelo","tetek bengek","trivia"],
["bagaĝo","bagasi"],
["bakterio","bakteri"],
["bakteriofago","bakteriofag"],
["bakteriologiisto","bakteriolog"],
["bakteriologio","bakteriologi"],
["bakteriologo","bakteriolog"],
["balai","[sapu] menyapu"],
["balailo","sapu"],
["balalajko","balalaika"],
["balancoseĝo, lulseĝo","kursi goyang"],
["balboo","balboa"],
["baldaŭ","segera"],
["baleno","paus"],
["balenŝarko","hiu paus"],
["bambuo","bambu"],
["bananmuŝo, vinagromuŝo","lalat buah"],
["banano","pisang"],
["bangladeŝo","Bangladesh"],
["bankejo","kantor cabang pembantu (bank)"],
["bankisto","bankir"],
["banko","bank"],
["bantkravato","dasi kupu-kupu"],
["banĉambro","kamar mandi"],
["banĝo","banjo"],
["baptonomo","nama baptis"],
["barbo","janggut"],
["barbudo","Barbuda"],
["barejno","Bahrain"],
["bario","barium"],
["batalkampo","medan pertempuran"],
["bebo","bayi"],
["bekerelo","becquerel"],
["bekfluto","rekorder"],
["belarta","artistik"],
["belartaĵo","karya seni"],
["belgujo","Belgia"],
["belizo","Belize"],
["belorusujo","Belarus"],
["belskribado","kaligrafi"],
["belskribisto","kaligraf"],
["benino","Benin"],
["beribero","beri-beri"],
["berilio","berilium"],
["berkelio","berkelium"],
["bestaro","fauna"],
["besto","binatang","hewan"],
["bestoĝardeno, zoologia ĝardeno","kebun binatang"],
["biblioteko","[pustaka] perpustakaan"],
["bicikli","[sepeda] bersepeda"],
["biciklo","sepeda"],
["biero","bir"],
["bildo","gambar"],
["bildrakonto","komik"],
["bildvortaro","kamus bergambar"],
["biologiisto","biolog","ahli biologi"],
["biologio","biologi"],
["biologo","biolog","ahli biologi"],
["birdo","burung"],
["biskvito","biskuit"],
["bismuto","bismut"],
["blanka","putih"],
["blanka globeto","sel darah putih"],
["blanka magio","ilmu putih"],
["blanka urso","beruang kutub"],
["blanketa","[putih] keputih-putihan"],
["blankigi","[putih] memutihkan"],
["blefarito","blefaritis","radang kelopak mata"],
["blenoreo","blenorea"],
["blinda","buta","tunanetra"],
["blindeco","[buta] kebutaan"],
["blindigi","[buta] membutakan"],
["blindumi","[buta] membutakan"],
["blonda","blonde"],
["blovharmoniko","harmonika"],
["blovinstrumento","alat musik tiup"],
["blua","biru"],
["blua Rivero","Sungai Panjang","Sungai Yangtze"],
["blualgo, blua algo","alga biru"],
["bluaĵo","lebam"],
["bluzo","blus"],
["bofilino","menantu"],
["bofilo","menantu"],
["bona","baik","buruk"],
["bone","baiklah","oke"],
["bongo","bongo"],
["bonigi","[buruk] memperburuk"],
["bonkora","baik hati"],
["bono, bonaĵo","[baik] kebaikan"],
["bonvenigi","[sambut] menyambut"],
["bonvoli","[sila] mempersilakan"],
["borio","bohrium"],
["boro","boron"],
["bosnujo","Bosnia"],
["bosnujo kaj Hercegovino","Bosnia Herzegovina"],
["botanika","botanis"],
["botanikisto","botanikus"],
["botaniko","botani"],
["boteleto","ampul"],
["botelo","botol"],
["bovo","sapi","Saur","Taurus","Wrisaba"],
["bracelethorloĝo","arloji","jam tangan"],
["brakhorloĝo","arloji","jam tangan"],
["briketo","briket"],
["briko","batu bata"],
["bromo","bromin"],
["bronkito","bronkitis","radang cabang tenggorok"],
["brovo","alis"],
["broĉo","bros"],
["bruli","[bakar] terbakar"],
["bruligaĵo","bahan bakar"],
["bruligi","[bakar] membakar"],
["brulo","[bakar] pembakaran"],
["brulumo","inflamasi"],
["bruna","(warna) cokelat"],
["brunalgoj, brunaj algoj","alga cokelat"],
["brusto","dada"],
["brustvoĉo","suara dada"],
["bufo","kodok"],
["bulgarujo","Bulgaria"],
["bulvardo","bulevar"],
["burkino","Burkina Faso"],
["busa haltejo","halte bus"],
["bushaltejo","halte bus"],
["buso","bus"],
["butero","mentega"],
["butiko","toko"],
["butikumi","[belanja] berbelanja"],
["butontruo","lubang kancing"],
["buŝharmoniko","harmonika"],
["buŝo","mulut"],
["cedro","cedar"],
["cellingvo","bahasa target"],
["celtabulo","papan target"],
["celulito","selulit"],
["cendo","sen"],
["cent","[ratus] seratus"],
["centiaro","sentiare"],
["centjaro","abad"],
["centra angulo","sudut pusat"],
["cepo","bawang merah"],
["ceramikaĵo","keramik"],
["ceramikisto","tukang keramik"],
["ceramiko","keramik","tembikar"],
["cerbeto","otak kecil"],
["cerbo","otak (besar)"],
["cerbujo","tengkorak"],
["cerio","serium"],
["cervo","rusa","karibu"],
["cezio","sesium"],
["cianobakterioj","sianobakteri"],
["cigno","angsa"],
["cilio","silium"],
["ciliuloj","ciliata"],
["cimbalo","simbal"],
["cinamo","kayu manis"],
["cindro","abu"],
["cindrujo","asbak"],
["cindrulino","Upik Abu"],
["ciprino","ikan karper","ikan mas"],
["cirozo","sirosis (hati)"],
["citaro","siter"],
["colo","inci"],
["daktilo","kurma"],
["daltonismo","buta warna","daltonisme"],
["dancarto","seni tari"],
["dancejo","diskotek","ruang dansa"],
["danci","[tari] menari"],
["dancisto","[tari] penari"],
["danco","tarian"],
["danke al, dank' al","terima kasih kepada"],
["danki","[terima kasih] berterima kasih","[syukur] mensyukuri"],
["dankofesto, dankotago","Hari Thanksgiving"],
["danujo","Denmark"],
["darmŝtatio","darmstadtium"],
["dartro","kudis","skabies"],
["daŭra planto","tanaman menahun"],
["de antaŭ","dari depan"],
["de malantaŭ","dari belakang"],
["de sub","dari bawah"],
["de sur, desur","dari atas"],
["de tempo al, tempal","dari waktu ke waktu"],
["decembro","Desember"],
["defalaĵo","limbah"],
["dek","[puluh] sepuluh"],
["dekalogo","dekalog","Sepuluh Perintah Tuhan"],
["dekkelkjarulo","remaja","umur belasan"],
["deksesuma","heksadesimal"],
["dekuma","desimal"],
["delfeno","lumba-lumba"],
["delto","delta"],
["demamigi","[sapih] menyapih"],
["demenco","demensia"],
["demografiisto","demograf"],
["demografio","demografi"],
["denaro","dinar"],
["densa","lebat","padat","rapat"],
["denseco","densitas","[padat] kepadatan","[rapat] kerapatan","massa jenis"],
["densigi","[padat] memadatkan","[kompresi] mengompresi"],
["densiĝi","[padat] memadat"],
["denso","densitas","[padat] kepadatan","[rapat] kerapatan","massa jenis"],
["dentisto, dentkuracisto","dokter gigi"],
["dentkarno, dentokarno","gusi"],
["dento","gigi"],
["dentopikilo, dentpikilo","tusuk gigi"],
["dentrado","roda gigi"],
["deponbanko","bank deposito"],
["dermatozo","dermatosis"],
["dermito","dermatitis","eksem","radang kulit"],
["derviŝo","darwis"],
["desoksiribonuklea acido","asam deoksiribonukleat","ADN","DNA"],
["devi","harus"],
["deviga","wajib"],
["devigi","[wajib] mewajibkan","[harus] mengharuskan"],
["dezerto","gurun"],
["diabeto","diabetes"],
["dialekto","dialek","logat"],
["diferenciala formo","bentuk diferensial"],
["difinvortaro","kamus ekabahasa"],
["difterito","difteri"],
["digestosistemo","sistem pencernaan"],
["dika","gemuk","gendut"],
["dika intesto","usus besar"],
["dimanĉo","Minggu"],
["dinaro","dinar"],
["disleksio","disleksia"],
["dismembrigi","[kelompok] mengelompokkan"],
["dispepsio","dispepsia"],
["dispneo","dispnea"],
["disprozio","disprosium"],
["distribua funkcio","fungsi distribusi"],
["disurio","disuria"],
["disĵeti","[sebar] menyebarkan","[siar] menyiarkan","[tabur] menabur"],
["diverskolora","warna-warni"],
["dolaro","dolar"],
["dolĉa","manis"],
["dolĉaĵo","gula-gula","manisan","permen"],
["dombesto","binatang peliharaan"],
["domhundo","anjing rumah","anjing peliharaan"],
["dominika Respubliko","Republik Dominika"],
["domo","rumah"],
["domvitro","rumah kaca"],
["dongo","dong"],
["dorlotbesto","binatang peliharaan"],
["dormema","[kantuk] mengantuk"],
["dormi","tidur"],
["dormigi","[tidur] menidurkan"],
["dormomalsano","[sakit] penyakit tidur"],
["dormosako","kantung tidur"],
["dormoĉambro","kamar tidur"],
["dorso","punggung"],
["dorsosako","ransel","tas punggung"],
["drako","naga"],
["dramarto","seni drama"],
["drinkaĵo","miras","minuman keras","minuman beralkohol"],
["drinkejo","bar","pub"],
["drinkemulo","[mabuk] pemabuk"],
["drinki","mabuk","minum (minuman keras)"],
["du","dua"],
["dua","[dua] kedua"],
["duakanona","deuterokanonika"],
["dubnio","dubnium"],
["dugongo","duyung"],
["dulingva vortaro, dudirekta vortaro","kamus dwibahasa"],
["duliteraĵo","digraf"],
["duloka","biner"],
["dumtempa, portempa","sementara","temporer"],
["duobla","dobel","ganda"],
["duon-","semi-"],
["duonglobo","hemisfer"],
["duoniganto","bisektris","garis bagi"],
["duonjaro","semester"],
["duono","[tengah] setengah"],
["duonvoĉe","diam-diam (suara)"],
["duuma","biner"],
["e-vorto","adverbia","kata keterangan"],
["ebria","mabuk"],
["ebriiga","[mabuk] memabukkan"],
["ebriigaĵo","minuman beralkohol","minuman keras"],
["ebriigi","[mabuk] memabukkan"],
["ebrio, ebrieco","[mabuk] kemabukan"],
["ebriulo","[mabuk] pemabuk"],
["ebur-Bordo","Pantai Gading"],
["ebura turo","menara gading"],
["eburo","gading"],
["eduksistemo","sistem pendidikan"],
["edzigi","[nikah] menikahkan","[nikah] menikahi"],
["edziniĝi","[nikah] menikah"],
["edzino","istri"],
["edziĝi","[nikah] menikah"],
["edziĝo","[nikah] Pernikahan Kudus"],
["edzo","suami"],
["egalvenko","seri"],
["egiptujo","Mesir"],
["ejnstejnio","einsteinium"],
["ejnŝtejnio","einsteinium"],
["eklampsio","eklampsia"],
["eklipso","gerhana"],
["eksedziĝi","[cerai] bercerai"],
["ekstempa","usang"],
["eksterlanda","asing","luar negeri"],
["eksterlandano","warga negara asing"],
["eksterlando","luar negeri"],
["eksterpartia","independen"],
["eksterrete","luar jaringan","luring"],
["ekzameno","ujian"],
["ekzemo","eksem"],
["ekzemple","contohnya","misalnya"],
["ekzempligi","[contoh] mencontohkan"],
["ekzemplo","contoh"],
["el antaŭ","dari depan"],
["el malantaŭ","dari belakang"],
["el sub","dari bawah"],
["elcento, elcentaĵo","persen"],
["elefantiazo","elefantiasis","kaki gajah"],
["elefanto","gajah"],
["elektra","elektris"],
["elektra fluo","arus listrik"],
["elektra kampintenso","intensitas medan listrik"],
["elektra kampo","medan listrik"],
["elektra streĉo","tegangan listrik"],
["elektrejo","pembangkit listrik"],
["elektro","listrik"],
["elektrokvanto","muatan listrik"],
["elektromova forto","gaya gerak listrik"],
["elektroĥemio","elektrokimia"],
["elementa funkcio","fungsi elementer"],
["elira duongrado","derajat luar"],
["elirpunkto","titik pangkal"],
["elnaĝi","muncul (dari permukaan air)","timbul (dari permukaan air)"],
["eloviĝi","[tetas] menetas"],
["elparoli","[ucap] mengucapkan"],
["elstara","istimewa"],
["elŝipejo","dermaga"],
["elŝuti","[unduh] mengunduh"],
["embolio","emboli"],
["emfizemo","emfisema"],
["emirlando","emirat"],
["emiro","emir"],
["emirujo","emirat"],
["empiemo","empiema"],
["enamiĝi","jatuh cinta"],
["encefalito","ensefalitis"],
["endokardito","endokarditis"],
["enira duongrado","derajat dalam"],
["enkarniĝo","inkarnasi"],
["enklavo","enklave"],
["enkorpigi","[bentuk] membentuk"],
["enkorpiĝo","inkarnasi"],
["enmarejo","muara"],
["eno","yen"],
["enretigi","[unggah] mengunggah"],
["enspezimposto","pajak pendapatan"],
["enterito","enteritis"],
["epiforo","epifora"],
["epilepsio","ayan","epilepsi"],
["epizootio","epizotik"],
["erarkompreni, fuŝkompreni","salah paham"],
["erbio","erbium"],
["erinaco","landak susu"],
["ermeno","cerpelai"],
["eskudo","escudo"],
["espereble","mudah-mudahan","semoga"],
["esperi","[harap] berharap","[harap] mengharapkan"],
["espero","harapan"],
["esplorkampo","bidang penelitian"],
["esplorĵurnalisto","reporter investigatif"],
["estanteco","masa kini"],
["estaĵo","makhluk"],
["esti","ada","adalah"],
["estinteco","masa lalu"],
["estonteco","masa depan"],
["eterna","abadi"],
["etiopujo","Etiopia"],
["etna dialekto","dialek etnis"],
["evitvorto","eufemisme"],
["evolulando, evoluanta lando","negara berkembang"],
["ezofago","faring","kerongkongan"],
["eĥo","gema"],
["eŭklida algoritmo","algoritme Euclid"],
["eŭro","euro"],
["eŭrolando","Zona Euro"],
["eŭropio","europium"],
["fabelo","dongeng"],
["fablo","fabel"],
["facila","gampang","mudah","lembut","ringan"],
["facile","dengan mudah"],
["faciligi","[mudah] memudahkan","[mudah] mempermudah","[ringan] meringankan"],
["facilpieda","gesit","lincah","tangkas"],
["fajra","[api] berapi"],
["fajraĵo","kembang api"],
["fajrilo","korek api"],
["fajro","api"],
["fajrobirdo","funiks"],
["fakta","nyata"],
["fakte","[benar] sebenarnya","[betul] sebetulnya","[sungguh] sesungguhnya"],
["fakto","fakta"],
["fakturo","faktur","tagihan"],
["fakvorto","istilah"],
["falakvo","air terjun"],
["faleti, duonfali","[sandung] tersandung"],
["fali","jatuh"],
["faligi","[jatuh] menjatuhkan"],
["falo","[jatuh] kejatuhan"],
["falstelo","bintang jatuh"],
["familinomo","nama keluarga"],
["fari","[buat] membuat","[laku] melakukan"],
["farigi","[buat] membuatkan"],
["faringo","esofagus","kerongkongan"],
["fariĝi","[jadi] menjadi"],
["farmaciisto","farmakolog"],
["farmacio","farmasi"],
["farmakologio","farmakologi"],
["faruno","tepung"],
["fasti","[puasa] berpuasa"],
["fasto","puasa","saum"],
["fatvo","fatwa"],
["febro","demam"],
["februaro","Februari"],
["fek","brengsek!","sialan!"],
["fekado","berak","buang air besar","defekasi"],
["fekaĵo","feses","tahi","tinja"],
["feki","berak","buang air besar","defekasi"],
["feko","berak","buang air besar","defekasi","feses","tahi","tinja"],
["femuro","paha"],
["fenestro","jendela"],
["fermio","fermium"],
["fero","besi"],
["festi","[pesta] berpesta"],
["festo","pesta"],
["fiera","bangga"],
["fieraĵo, fiero","[bangga] kebanggaan"],
["fiereco, fiero","[bangga] kebanggaan"],
["fieri","[bangga] berbangga"],
["fikstempo","tenggat"],
["filino","anak perempuan"],
["filo","anak laki-laki"],
["filologiisto","filolog"],
["filologio","filologi"],
["filozofii","[falsafah] berfalsafah","[filsafat] berfilsafat"],
["filozofio","falsafah","filosofi","filsafat"],
["fin","akhirnya"],
["fina","[akhir] terakhir"],
["finaĵo","akhiran"],
["fine","akhirnya"],
["fingro","jari"],
["fini","[akhir] mengakhiri","[selesai] menyelesaikan"],
["finiĝi","[akhir] berakhir","selesai"],
["finlerni","tamat belajar"],
["fino","akhir"],
["finofara","final"],
["fizika","fisis"],
["fizika geografio, naturgeografio","geografi fisik"],
["fizika grando","besaran fisika"],
["fizikisto","fisikawan"],
["fiziko","fisika"],
["fiĝio","Fiji"],
["fiŝi, fiŝkapti","[pancing] memancing"],
["fiŝisto","nelayan"],
["fiŝo","ikan"],
["fiŝoj","Hut","Mina","Pises"],
["fiŝreto","jala","jaring"],
["flagelo","flagelum"],
["flageluloj","flagellata"],
["flanko","sisi"],
["flava","kuning"],
["flava febro","demam kuning"],
["flaveta","[kuning] kekuningan","[kuning] kekuning-kuningan"],
["flaviĝo","sakit kuning"],
["flavmalsano","sakit kuning"],
["flerovio","flerovium"],
["flori","[bunga] berbunga","mekar"],
["floro","bunga"],
["floroplanto","tanaman (ber)bunga"],
["floroplantoj, florvegetaloj","spermatofita"],
["florsuko","nektar"],
["florĝardeno","kebun bunga","taman bunga"],
["flugdrako","layangan","layang-layang"],
["flugi","terbang"],
["flugila","[sayap] bersayap"],
["flugilo","sayap"],
["flugludilo","layang-layang","layangan"],
["flugo","[terbang] penerbangan"],
["flugpilkado","(permainan) bola voli"],
["flugpilko","bola voli"],
["flugsciuro, fluganta sciuro","tupai terbang"],
["fluoro","fluorin"],
["fluti","[suling] menyuling"],
["fluto","seruling","suling"],
["fobio","fobia"],
["foj","dari waktu ke waktu"],
["foje","sering"],
["fojo","kali"],
["foko","anjing laut"],
["fontano","air mancur"],
["fontolingvo","bahasa sumber"],
["forbalai","[sapu] menyapu bersih"],
["forinto","forint"],
["forkego","garu"],
["forketo","garpu kecil"],
["forko","garpu"],
["formado","[bentuk] pembentukan"],
["formaĵa","formal"],
["formi","[bentuk] membentuk"],
["formilo, formujo","cetakan"],
["formiĝi","[bentuk] terbentuk"],
["formo","bentuk"],
["fornomi","[ingkar] mengingkari","[mungkir] memungkiri","[sangkal] menyangkal"],
["forta","kuat"],
["fortempiĝi","kedaluwarsa"],
["fortika","kukuh","teguh"],
["fortikaĵo","benteng"],
["fortikigi","[benteng] membentengi"],
["forto","[kuat] kekuatan","gaya"],
["forĵeti","[buang] membuang"],
["fosforo","fosforus"],
["fotarto","fotografi"],
["francio","fransium"],
["franciumo","fransium"],
["francujo","Perancis"],
["franko","franc"],
["frap","tok !"],
["frapharmoniko","xilofon"],
["frapi","[ketok] mengetok","[ketuk] mengetuk"],
["frapinstrumento","alat musik pukul"],
["frapo","[ketok] ketokan","[ketuk] ketukan"],
["freneza","gila"],
["freneziĝi","[gila] menggila"],
["frenezulejo","rumah sakit jiwa"],
["fromaĝo","keju"],
["froti","[gosok] menggosok"],
["froto","gesekan"],
["frukto","buah"],
["fruktoĝardeno","kebun buah","taman buah"],
["frunto","dahi"],
["ftizo","ftisis","TBC","tuberkulosis"],
["fuligulo","itik rumbai","kambangan hitam"],
["fulmkotono","nitroselulosa"],
["fulmo","kilat"],
["fumi","[asap] berasap","[rokok] merokok"],
["fumiĝi","[asap] berasap"],
["fumo","asap"],
["fumtubo","cerobong"],
["fungo","cendawan","jamur"],
["funkciado","operasi","[operasi] pengoperasian"],
["funkcii","[fungsi] berfungsi"],
["funkciismo","fungsionalisme"],
["funkcio","fungsi"],
["funkciulo","fungsionaris"],
["funto","pon"],
["gadolinio","gadolinium"],
["gajni","[oleh] memperoleh","[menang] memenangkan"],
["galaksio","galaksi"],
["galiumo","galium"],
["galo","empedu"],
["galveziko, gala veziko","kantung empedu"],
["galŝtona malsano","batu empedu"],
["gambio","Gambia"],
["garaĝo","garasi"],
["gaso","gas"],
["gasoleo, dizeloleo","diesel"],
["gastlibro","buku tamu"],
["gazeto","majalah"],
["geedziĝi, kunedziĝi","[nikah] menikah"],
["geja","gay","homo","homoseksual"],
["gejo","gay","homo","homoseksual"],
["genera sistemo, reprodukta sistemo","sistem reproduksi"],
["genetika","genetik"],
["genetiko","genetika"],
["genezo","Kejadian (kitab)"],
["genui","[lutut] berlutut"],
["genuo","lutut"],
["geodezio","geodesi"],
["geofizikisto","geofisikawan"],
["geofiziko","geofisika"],
["geografiisto","geograf"],
["geografio","geografi"],
["geologiisto","geolog","geologiwan"],
["geologio","geologi"],
["gepardo","cheetah","citah"],
["gepatroj","orang tua"],
["germaniumo","germanium"],
["gigatuno","gigaton"],
["gingivo","gusi"],
["gisto","khamir","ragi"],
["gitaro","gitar"],
["glaciaĵo","es krim"],
["glaciejo","gletser"],
["glaciigi","[beku] membekukan"],
["glaciinsulo, glacimonto","gunung es"],
["glaciiĝi","[beku] membeku"],
["glacio","es"],
["glacipluvo","hujan es"],
["glacoviŝilo","[hapus] penghapus kaca","wiper"],
["gladotabulo","papan setrika"],
["glaso","gelas"],
["globa","sferis"],
["globkrajono","pulpen"],
["globo","globe"],
["glui","[lem] mengelem"],
["gluilo","lem"],
["gluo","lem"],
["gneto","melinjo"],
["golfeto","teluk"],
["golfo","teluk"],
["golfo, golfludo","golf"],
["gongo","gong"],
["gorilo","gorila"],
["gorĝo","tenggorokan"],
["gorĝopomo, gorĝa pomo","jakun"],
["grada","gradual","progresif"],
["gradaro","skala"],
["grado","derajat"],
["graduso","derajat"],
["gramo","gram"],
["granda","agung","besar"],
["granda kalorio","kilokalori"],
["granda litero, ĉeflitero","huruf kapital"],
["granda pando","panda","panda raksasa"],
["grandaĝa","tua","[umur] berumur"],
["grandaĝulo","orang tua (bangka)"],
["grandegulo","raksasa"],
["grandiĝi","[besar] membesar","tumbuh"],
["grando","[agung] keagungan","[besar] kebesaran","besaran"],
["grekujo","Yunani"],
["grenado","granat"],
["gripo","flu","influenza"],
["griza","abu-abu"],
["gruntbovo","yak"],
["guldeno","gulden"],
["gvatemalo","Guatemala"],
["gvidlibro","buku panduan"],
["hadiso","hadis","hadits"],
["hafnio","hafnium"],
["haitio","Haiti"],
["haktabulo, tranĉtabulo","talenan"],
["halala","halal"],
["halogenlampo, halogena lampo","lampu halogen"],
["halogeno","halogen"],
["halt","berhenti!","stop!"],
["haltejo","halte"],
["halti","[henti] berhenti"],
["haltigi","[henti] menghentikan"],
["haltigilo","rem"],
["haltigŝuo","rem blok"],
["halto","[henti] perhentian"],
["hamstro","hamster"],
["hangaro","hanggar"],
["haringo","hering"],
["harmonia","harmonis"],
["harmoniko","harmonika","akordeon"],
["harmonio","harmoni"],
["harmoniumo","harmonium"],
["haro","rambut"],
["harpo","harpa"],
["harvosto","buntut kuda","ekor kuda"],
["hasio","hasium"],
["havi","[punya] mempunyai"],
["hazardludo, hazarda ludo","judi"],
["haĝo","haji"],
["hektaro","hektar"],
["helico","heliks","baling-baling","propeler"],
["heliko","bekicot","keong","siput","\"a\" keong","tanda at"],
["heliumo","helium"],
["hemikranio","migrain","sakit kepala sebelah"],
["hemiplegio","hemiplegia"],
["hemofilio","hemofilia"],
["hemoroidoj","ambeien","bawasir","hemoroid","wasir"],
["hepato","hati","lever"],
["herco","hertz"],
["hernio","hernia"],
["herpeto","herpes"],
["hevisida funkcio","fungsi Heaviside"],
["hidrargo","merkurium","raksa"],
["hidraŭlika","hidraulis"],
["hidraŭliko","hidraulika"],
["hidrocefalo","hidrosefalus"],
["hidrofobio","hidrofobia"],
["hidrogeno","hidrogen"],
["hieno","hiena"],
["hieraŭ","kemarin"],
["hiperbola funkcio","fungsi hiperbola"],
["hipnota","hipnotis"],
["hipnotigi","[hipnosis] menghipnosis"],
["hipnotismo","hipnotisme"],
["hipnoto","hipnosis"],
["hipoĥondrio","hipokondria"],
["hirundo","burung layang-layang","walet"],
["hispana gripo","flu spanyol"],
["hispanujo","Spanyol"],
["histeria","histeris"],
["histerio","histeria"],
["historia","historis","sejarawi"],
["historiisto","historikus","sejarawan"],
["historio","histori","sejarah"],
["histriko","landak"],
["hodiaŭ","hariini"],
["holmio","holmium"],
["homaranismo","humanisme"],
["homaro","umat manusia"],
["homeca","manusiawi"],
["homeco","[manusia] kemanusiaan"],
["homido","anak-anak","anak manusia"],
["homino","perempuan","wanita"],
["hommanĝulo","kanibal"],
["homo","manusia"],
["honduro","Honduras"],
["horaro, horlibro","jadwal"],
["horloĝo","jam"],
["horo","jam"],
["horzono","zona waktu"],
["hundejo","kandang anjing"],
["hundo","anjing"],
["hungarujo","Hongaria"],
["iFono","iPhone"],
["idioto","idiot","tunagrahita"],
["ikebano","ikebana"],
["ilaro","[alat] peralatan"],
["ili","mereka"],
["ilia","milik mereka"],
["ilo","alat","instrumen"],
["imposto","pajak"],
["impostsistemo","sistem perpajakan"],
["impotenta","impoten"],
["impotenteco","impotensi"],
["imunsistemo, imuna sistemo","sistem imun","sistem pertahanan tubuh"],
["indio","indium"],
["individua","individual"],
["individueco","individualitas"],
["individuismo","individualisme"],
["individuisto","individualis"],
["individuo","individu"],
["indonezio","Indonesia"],
["industrilando, industria lando","negara industri","negara maju"],
["inertoforto, inercia forto","[lembam] kelembaman"],
["infana","[kanak] kekanak-kanakan","naif"],
["infanaĝo","masa kanak-kanak","masa kecil"],
["infaneco","masa kanak-kanak"],
["infaneto","bayi","janin"],
["infanistino","pramusiwi"],
["infano","anak-anak","anak kecil"],
["infarkto","infarktus"],
["infekti","[infeksi] menginfeksi"],
["infekto, infektado","infeksi"],
["informletero","nawala"],
["infuzorio","infusoria"],
["inko","tinta"],
["inseksa","betina","feminin"],
["insektomanĝuloj","insektivora"],
["instrua","instruktif"],
["instruado","[ajar] pengajaran","[ajar] pembelajaran","instruksi"],
["instruaĵo","[ajar] pelajaran"],
["instruejo","sekolah"],
["instrui","[ajar] mengajar","[ajar] mengajarkan"],
["instruisto","guru","instruktur"],
["instruiteco","[tahu] pengetahuan"],
["instruiĝi","[ajar] belajar"],
["instrumentisto","instrumentalis"],
["instrumento","alat","instrumen"],
["instruo","[ajar] pengajaran"],
["instruplena, instruoplena","instruktif"],
["insulo","pulau"],
["interlingvo","bahasa pengantar"],
["interparoli","[diskusi] berdiskusi"],
["interreto","internet"],
["intersezono","pancaroba"],
["intertempe","sedangkan","sementara itu"],
["intertempo","selang waktu"],
["intesto","usus"],
["intima","akrab","intim"],
["inundi","banjir","[banjir] membanjiri"],
["inversa hiperbola funkcio","fungsi hiperbola invers"],
["inversa trigonometria funkcio","fungsi siklometri"],
["inviti","[undang] mengundang"],
["invito","undangan"],
["inĝenierarto","teknik mesin"],
["irano","Iran"],
["iridio","iridium"],
["irigacii","mengairi"],
["irigacio","irigasi","pengairan"],
["iriso","iris"],
["islama","islami"],
["islamano","muslim"],
["islamo","Islam"],
["italujo","Italia"],
["iterbio","iterbium"],
["itinero","itinerari"],
["itrio","itrium"],
["jaguaro","jaguar"],
["jako","jaket"],
["januaro","Januari"],
["jarcento","abad"],
["jardo","yard"],
["jarduono","semester"],
["jarlibro","buku tahunan"],
["jarmilo","milenium"],
["jaro","tahun","milenium"],
["jes","ya"],
["jeĵuri, kunĵuri","[komplot] berkomplot","[sekongkol] bersekongkol"],
["jodo","iodin"],
["juano","yuan"],
["juki","gatal"],
["juko","gatal"],
["julio","Juli"],
["juna","muda","tua"],
["junaĝo","masa muda"],
["juneco","masa muda"],
["junio","Juni"],
["junipero","jintan saru"],
["junularo","[muda] pemuda"],
["junulo","[muda] pemuda","orang tua"],
["jupo","rok"],
["juvelŝtono","berlian","permata"],
["kabla televido","TV kabel"],
["kadio","kadi"],
["kadmio","kadmium"],
["kaj","dan"],
["kajako","kayak"],
["kalcio","kalsium"],
["kalendaro","almanak","kalender"],
["kalifo","khalifah"],
["kalifornio","kalifornium","Kalifornia"],
["kaliforniumo","kalifornium"],
["kalifujo","khilafah"],
["kalio","kalium"],
["kalkano","tumit"],
["kalkanumo","hak (sepatu)"],
["kalorio","kalori"],
["kameleono","bunglon"],
["kamparo","ladang"],
["kampi","[ladang] berladang"],
["kanado","Kanada"],
["kancero","kanker"],
["kanguruo","kanguru"],
["kankro","kepiting","Kanser","Karkata","Sartan"],
["kantarto","seni musik","seni suara"],
["kanuo","kano"],
["kapjesi","[angguk] mengangguk"],
["kapkuseno","bantal kepala"],
["kapnei","[geleng] menggeleng"],
["kapo","kepala"],
["kapreolo","rusa roe"],
["kapro","kambing"],
["kapti","[tangkap] menangkap"],
["kapvoĉo","suara kepala"],
["karakteriza funkcio","fungsi karakteristik"],
["karato","karat"],
["karbkrajono","pensil arang"],
["karbo","arang"],
["karbono","karbon"],
["karbonpapero","kertas karbon"],
["karbopapero","kertas karbon"],
["karesnomo","julukan"],
["kario","karies (gigi)"],
["karno","daging"],
["karoto","wortel"],
["kartludi","[main] bermain kartu"],
["kartvelio","Georgia"],
["kartvelujo","Georgia"],
["kastanjeto","kastanyet"],
["kastoro","berang-berang"],
["katalepsio","katalepsi"],
["katarakto","katarak"],
["kataro","Qatar"],
["kato","kucing"],
["kavernhomo","manusia gua"],
["kaverno","gua"],
["kazaĥujo","Kazakhstan"],
["kaŝnomo","nama samaran","pseudonim"],
["kecalo","quetzal"],
["kelkafoje, kelkfoje","beberapa kali"],
["kia","betapa","seperti apa"],
["kial","mengapa"],
["kialo","alasan"],
["kiam","ketika","saat","kapan"],
["kie","di mana"],
["kiel","bagaimana","begitu","sebagaimana","seperti","sebagai"],
["kien","ke mana"],
["kies","milik siapa"],
["kilogramo","kilo","kilogram"],
["kilogramo en kuba metro","kilogramper meter kubik"],
["kilotuno","kiloton"],
["kinarto","sinematografi"],
["kinaĵo","film"],
["kinejo","bioskop"],
["kinisto","sineas"],
["kino","sinematografi"],
["kio","apa","yang"],
["kiom","berapa"],
["kioma","keberapa"],
["kirasaŭto","mobil lapis baja"],
["kirgizujo","Kirgizstan"],
["kiribato","Kiribati"],
["kirlovaĵo","omelet","telur dadar"],
["kisi","[cium] mencium"],
["kiso","ciuman"],
["kiu","siapa","apa","yang mana"],
["klangulo","bebek ekor panjang"],
["klariono","klarino"],
["klarneto","klarinet"],
["klasĉambro","ruang kelas"],
["klaviklo","klavikula","tulang selangka"],
["kloro, ĥloro","klorin"],
["klorozo","klorosis"],
["klostrofobio","klaustrofobia"],
["klozetpapero","kertas toilet","tisu toilet"],
["knabino","anak perempuan"],
["knabo","anak laki-laki"],
["koalo","koala"],
["kobajo","tikus belanda"],
["kobalto","kobalt"],
["kojnodento, kojna dento","gigi taring"],
["kokainismo","kokainisme"],
["kokaino","kokaina"],
["kokluŝo","batuk rejan","pertusis"],
["koko","ayam"],
["kokoso","kelapa"],
["kokso","pinggul"],
["kolbaso","sosis"],
["kolera","marah"],
["kolerema, koleriĝema","[marah] pemarah"],
["koleri","marah"],
["kolero","amarah"],
["koliko","kolik"],
["kolo","leher"],
["kolombo","dara","merpati"],
["kolombumi","[dekut] mendekut"],
["kolonia stilo","gaya kolonial"],
["kolono","colon"],
["kolora","[warna] berwarna"],
["kolori","[warna] mewarnai"],
["kolorigilo","cat"],
["kolorilo","cat"],
["koloro","warna"],
["kolumo","kerah"],
["komato","koma"],
["kombi","[sisir] menyisir"],
["kombilo","sisir"],
["komercŝipo, komerca ŝipo","kapal dagang","kapal niaga"],
["kometo","komet"],
["komoroj","Komoro"],
["kompreneble","tentu saja"],
["kompreni","[erti] mengerti","paham","[paham] memahami"],
["komprenkapablo","[cerdas] kecerdasan","inteligensi"],
["komprenpovo","[cerdas] kecerdasan","inteligensi"],
["komputa sistemo","sistem komputer"],
["komputado","informatika"],
["komputi","[hitung] menghitung"],
["komputila reto","jaringan komputer"],
["komputilego","komputer bingkai utama","komputer kerangka utama"],
["komputilo","komputer"],
["komputisto","[program] pemrogram","programer"],
["komuna saĝo","akal sehat"],
["komuniksistemo","sistem komunikasi"],
["kongresejo","balai sidang"],
["kongresi","[kongres] berkongres"],
["kongreso","kongres"],
["konjunktivito","konjungtivitis"],
["konkeri","[takluk] menaklukkan"],
["konstelacio","konstelasi","rasi (bintang)"],
["konstruarto","arsitektur"],
["konstruaĵo","bangunan"],
["konstrui","[bangun] membangun","[diri] mendirikan"],
["konstruo","bangunan","[bangun] pembangunan"],
["kontraŭparoli","[tentang] menentang"],
["kontraŭveneno","[tawar] penawar (racun)"],
["kopernicio","kopernicium"],
["koramikino","[kasih] kekasih","pacar"],
["koramiko","[kasih] kekasih","pacar"],
["korbo","keranjang"],
["korbopilkado","(permainan) bola basket"],
["korbopilko","bola basket"],
["kordinstrumento","alat musik gesek","alat musik petik"],
["kordobo","cordoba"],
["koriandro","ketumbar"],
["koro","hati","jantung"],
["korpa","fisik"],
["korpo","badan","tubuh"],
["korsaĵo","korsase"],
["korvo","gagak"],
["kosmetiko","kosmetika","kosmetik"],
["kosmonaŭto","antariksawan","astronaut","kosmonaut"],
["kosmoŝipo","kapal luar angkasa"],
["kostariko","Kosta Rika"],
["kotonarbo, kotonujo","kapas (tumbuhan)"],
["kotono","kapas"],
["koverto","amplop"],
["krabo","kepiting","ketam"],
["krajono","pensil"],
["kranio","tengkorak"],
["kravato","dasi"],
["kreppapero","kertas krep"],
["kreto","kapur"],
["kriptono","kripton"],
["kroatujo","Kroasia"],
["krokodilo","buaya"],
["kroma, ĥroma","kromat"],
["kromedzino","gundik","selir"],
["kromo, ĥromo","kromium"],
["krono","krona"],
["kronprinco","putra mahkota"],
["kropo","tembolok","gondok"],
["ksenono","xenon"],
["ksilofono","xilofon"],
["kuba metro","meter kubik"],
["kubismo","kubisme"],
["kubo","kubus","dadu","kubik","Kuba"],
["kubuto","siku"],
["kuglingo","selongsong"],
["kuglo","pelor","peluru"],
["kuirarto","tata boga"],
["kulero","sendok"],
["kulo","nyamuk"],
["kulvualo","kelambu"],
["kuniklo","kelinci"],
["kupro","tembaga","perunggu"],
["kuracarto","terapi"],
["kurierŝipo","kapal pengangkut"],
["kuriumo","kurium"],
["kurkumo","kunyit"],
["kurso","kursus"],
["kurteno","gorden"],
["kuseno","bantal"],
["kusentego, kusentegilo","sarung bantal"],
["kvadrata metro","meter persegi"],
["kvar","empat"],
["kvaronjaro","triwulan"],
["kvin","lima"],
["kvintalo","kuintal"],
["laborkampo","lapangan kerja"],
["labortablo","meja kerja"],
["lafo","lahar","lava"],
["lageto","kolam"],
["lago","danau"],
["lakso","diare","mencret"],
["lakta Vojo","Bima Sakti (galaksi)"],
["lakto","susu"],
["laktodento","gigi susu"],
["laktosukero","laktosa"],
["lampo","lampu"],
["landano","warga negara"],
["landestro","kepala negara"],
["landido","pribumi"],
["lando","negara","negeri"],
["langeto","tab"],
["lango","lidah"],
["lano","wol"],
["lantano","lantanum"],
["laringito","laringitis"],
["larmi","[tangis] menangis"],
["larmo","air mata"],
["lasta","[akhir] terakhir"],
["lastatempe","akhir-akhir ini","baru-baru ini","belakangan ini"],
["latvujo","Latvia"],
["lavĉambro","kamar mandi"],
["laĉo","tali (sepatu)"],
["laŭ","[dasar] berdasarkan","[turut] menurut"],
["laŭrencio","lawrensium"],
["laŭvorte","harfiah"],
["legi","[baca] membaca"],
["legomĝardeno","kebun sayur"],
["lempiro","lempira"],
["leono","singa","Asad","Leo","Singa"],
["leopardo","macan tutul"],
["leporo","kelinci","terwelu"],
["leptospirozo","leptospirosis"],
["lernaĵo","[ajar] pelajaran"],
["lernejo","sekolah"],
["lerni","[ajar] belajar"],
["lernigi","[ajar] mengajarkan"],
["lernilo","tutorial"],
["lerta telefono, inteligenta telefono","ponsel pintar","telepon pintar"],
["leteri","[surat] menyurati"],
["leterkolombo, mesaĝkolombo","merpati pos"],
["letero","surat"],
["levi","[angkat] mengangkat"],
["levilo","tuas","[ungkit] pengungkit"],
["leviĝi","naik","bangkit"],
["levo","lev"],
["leŭkemio","kanker darah","leukemia"],
["li","dia (laki-laki)","dia"],
["lia","miliknya","miliknya (laki-laki)"],
["libertempo","waktu luang","waktu senggang"],
["libro","buku"],
["libro, instrulibro","buku pelajaran"],
["lido","lats"],
["ligno","kayu"],
["lignofajro","api unggun"],
["lignokarbo","arang kayu"],
["lignonajlo","pasak"],
["likeno","liken","lumut kerak"],
["limfosistemo","sistem limfatik"],
["limlando","batas negara"],
["lingvisto, lingvosciencisto","ahli bahasa","linguis"],
["lingvo","bahasa"],
["lingvoscienco","linguistik"],
["liphararo, haroj","kumis"],
["lipo","bibir"],
["liro","lira"],
["litero","huruf"],
["litio","litium"],
["litovujo","Lituania"],
["litro","liter"],
["livermorumo","livermorium"],
["loka","lokal"],
["loka reto","LAN"],
["loki","[tempat] menempatkan"],
["loknomo","nama tempat","toponimi"],
["loko","lokasi","tempat"],
["lotuso","lotus","padma","seroja","teratai"],
["loĝaŭto","karavan"],
["ludi","[main] bermain","[main] memainkan","[main] mempermainkan"],
["ludilo","mainan"],
["ludo","[main] permainan"],
["lumbago","lumbago","nyeri pinggang"],
["lumjaro","tahun cahaya"],
["lumturo","mercusuar"],
["luna","lunar"],
["lunarko","sabit","bulan sabit"],
["lundo","Senin"],
["lunkalendaro, luna kalendaro","kalender bulan","kalender lunar"],
["luno","bulan"],
["lupo","serigala"],
["lupuso","lupus"],
["lutecio","lutetium"],
["lutro","berang-berang"],
["madagaskaro","Madagaskar"],
["magia","magis"],
["magiisto","dukun","[sihir] penyihir","[sulap] pesulap"],
["magio","sihir"],
["magnezio","magnesium"],
["majo","Mei"],
["makako","makaka"],
["makrocefalo","paus sperma"],
["makzelo","makzelo"],
["malalta","pendek","rendah"],
["malaltigi","[turun] menurunkan "],
["malaltmaro","(laut) surut"],
["malamiko","musuh"],
["malantaŭ","di belakang"],
["malaprobi","[tolak] menolak"],
["malario","malaria"],
["malbonavida","jahat"],
["maldekstramana","kidal"],
["maldensa","renggang"],
["maldensigi","[renggang] merenggangkan","[dekompresi] mendekompresi"],
["maldensiĝi","[renggang] merenggang"],
["maldika","kurus"],
["maldika intesto","usus halus"],
["maldivoj","Maladewa"],
["maldolĉa","pahit"],
["malebriiĝi, elebriiĝi","sadar","siuman"],
["maleolo","mata kaki"],
["malesperi","putus asa"],
["malespero","[putus] keputusasaan"],
["malfacila","sukar","sulit","susah"],
["malfacilaĵo","[sukar] kesukaran","[sulit] kesulitan","[susah] kesusahan"],
["malfaciligi","[sukar] menyukarkan","[sukar] mempersukar","[sulit] menyulitkan","[sulit] mempersulit","[susah] menyusahkan","[susah] mempersusah"],
["malforta","lemah"],
["malfortaĵo","[lemah] kelemahan"],
["malfortigi","[lemah] melemahkan"],
["malfortiĝi, senfortiĝi","[lemah] melemah"],
["malgranda","kecil"],
["malgranda fingro","kelingking"],
["malgranda kalorio","kalori"],
["malgranda litero, etlitero","huruf kecil"],
["malgranda pando","panda merah"],
["malgranda ĉimpanzo","bonobo"],
["malgrandegulo","kurcaci"],
["malharmonio","disharmoni"],
["malintima","impersonal"],
["malio","Mali"],
["maljuneco","[tua] penuaan"],
["maljuniĝi","[tua] menua"],
["malkompreno","ketidakpahaman"],
["mallakso","konstipasi","sembelit"],
["malleviĝi","turun"],
["malloka","global"],
["malloka reto","WAN"],
["malmoderna","kuno"],
["malmolnuka, rigidnuka","keras kepala"],
["malnatura","artifisial","buatan"],
["malpacienco","[sabar] ketidaksabaran"],
["malprofito","rugi"],
["malrapida","lama","lambat","pelan"],
["malriĉeco","[miskin] kemiskinan"],
["malriĉo","[miskin] kemiskinan"],
["malsanhistorio","anamnesis","riwayat kesehatan"],
["malsaniĝi","jatuh sakit"],
["malseka","basah"],
["malsekeco","[lembap] kelembapan"],
["malseketa","lembap"],
["malsekigi","[basah] membasahi"],
["malsekretigi","[buka] membuka (rahasia)","[bongkar] membongkar (rahasia)","[kuak] menguak (rahasia)","[ungkap] mengungkapkan (rahasia)"],
["malvarma","dingin"],
["malvarmeta","sejuk"],
["malvarmigi","[dingin] mendinginkan"],
["malvirgigi","[perawan] memerawani"],
["malĝentila","kasar","songong"],
["mambestoj","mamalia"],
["mameto","puting"],
["mamo","payudara"],
["mamuloj","mamalia"],
["mamuto","mamut"],
["mamzono","BH","bra","kutang"],
["manato","lembu laut","manat"],
["mangano","mangan"],
["maniko","lengan baju"],
["mano","tangan"],
["manpilkado","(permainan) bola tangan"],
["manpilko","bola tangan"],
["mansako","tas jinjing","tas tangan"],
["mantelo","mantel"],
["manĝaĵo","makanan"],
["manĝeti","[cemil] mengemil","[kudap] mengudap"],
["manĝi","makan","sarapan","makan siang","makan malam"],
["manĝoĉambro","ruang makan"],
["manĝvagono","gerbong makan","restorasi"],
["maparo","atlas"],
["mapi, mapigi","[peta] memetakan"],
["mapklarigo","legenda"],
["mapo","peta"],
["marakvo","air laut"],
["mardo","Selasa"],
["marerinaco","landak laut","bulu babi"],
["marfiŝo","ikan air tawar"],
["marko","mark"],
["marmalsano","mabuk laut"],
["marmoto","marmot"],
["maro","laut","lautan"],
["marsalo","garam laut"],
["marstelo","bintang laut"],
["marteli","[palu] memalu"],
["martelo","martil","palu"],
["marteso","martes"],
["marto","Maret"],
["marĉevaleto","kuda laut"],
["maskofesto","pesta topeng"],
["matematikisto","matematikawan"],
["matematiko","matematika"],
["mateno","pagi"],
["matenruĝo","fajar"],
["matenstelo","bintang fajar"],
["matrica adicio","[jumlah] penjumlahan matriks"],
["maŝinlingvo","bahasa mesin"],
["maŝinĉambro","ruang mesin"],
["maŭricio","Mauritius"],
["maŭritanio","Mauritania"],
["medicina","medis"],
["medicinaĵo","obat"],
["medicinisto","medik"],
["medicino","[dokter] kedokteran"],
["megabitoko","megabita"],
["megatuno","megaton"],
["mejlo","mil"],
["mejtnerio","meitnerium"],
["melhundo","dachshund"],
["melo","luak"],
["membro","anggota gerak","anggota"],
["meminstruito","autodidak"],
["memlernanto","autodidak"],
["memlerninto","autodidak"],
["memmortigi","bunuh diri"],
["memorarto","mnemonik"],
["memstara","otonom"],
["mendelevio","mendelevium"],
["meningito","meningitis","radang selaput otak"],
["mensmalsano, mensa malsano","[sakit] penyakit jiwa"],
["mensogi","[bohong] berbohong"],
["mensogo","[bohong] kebohongan"],
["mensogulo","[bohong] pembohong"],
["mentono","dagu"],
["merkredo","Rabu"],
["mesaĝo","pesan"],
["metalo","logam","metal"],
["metaloido","metaloid","semilogam"],
["meteologiisto","meteorologiwan"],
["meteologio","meteorologi"],
["meteoro","meteor"],
["metro","meter"],
["metro en kvadrata sekundo","meter per sekon kuadrat"],
["metro en sekundo","meter per sekon"],
["metroa haltejo","stasiun metro"],
["metrohaltejo","stasiun metro"],
["metropoliteno","metro"],
["mezaĝa","separuh baya","setengah baya"],
["mezaĝulo","orang separuh baya","orang setengah baya"],
["mezfingro","jari tengah"],
["mezgranda","rata-rata","[tengah] menengah"],
["mezursistemo","sistem pengukuran"],
["mi","aku","saya"],
["mia","milikku","milik saya"],
["miaopinie, laŭ mia opinio","menurut saya"],
["miaŭ","meong!"],
["miaŭi","[meong] mengeong"],
["miaŭo","meongan"],
["mielluno","bulan madu"],
["mielmonato","bulan madu"],
["mielo","madu"],
["migreno","migrain","sakit kepala sebelah"],
["mikozo","mikosis"],
["mikrobiologio","mikrobiologi"],
["mikrobiologo","mikrobiolog"],
["mikrobo","mikroba"],
["mikronezio","Mikronesia"],
["mikroorganismo","mikroorganisme"],
["mikrovivaĵo","mikroorganisme"],
["mil","[ribu] seribu"],
["miliardo","miliar"],
["miliono","juta"],
["milionulo","miliarder","miliuner"],
["militŝiparo, milita ŝiparo","angkatan laut","armada"],
["militŝipo, milita ŝipo","kapal perang"],
["minareto","minaret"],
["mineralakvo","air mineral"],
["mineralogiisto","mineralog"],
["mineralogio","mineralogi"],
["minuto","menit"],
["mirmekobo","numbat"],
["miskompreni","salah paham"],
["mispaŝo","[peleset] terpeleset","salah langkah"],
["moderna","modern"],
["modernigi","[modern] memodernkan"],
["modernismo","modernisme"],
["moknomo","julukan"],
["moldavio","Moldova"],
["moldavujo","Moldova"],
["molekula biologio","biologi molekuler"],
["molibdeno","molibdenum"],
["monataĵo","haid","menstruasi"],
["monato","bulan"],
["mondaĝo","masa","zaman"],
["mondmapo","peta dunia"],
["mondo","dunia"],
["monero","uang receh"],
["mongolujo","Mongolia"],
["mono","uang"],
["mononukleozo","demam kelenjar"],
["monpaperujo","dompet"],
["monsistemo","sistem keuangan"],
["montaro","[gunung] pegunungan"],
["monteto","bukit"],
["monto","gunung"],
["montra fingro","jari telunjuk"],
["monujo","dompet"],
["monumento","monumen"],
["monunuo","mata uang"],
["moralinstruo","pengajaran moral"],
["morbilo","campak","morbili"],
["morgaŭ","besok"],
["morta","abadi","kekal"],
["morti","mati","[tinggal] meninggal (dunia)"],
["mortigi","[bunuh] membunuh"],
["mortigo","[bunuh] pembunuhan"],
["mortintaĵo","jenazah","mayat"],
["morto","[mati] kematian"],
["mortpafi","[tembak] menembak mati"],
["moskeo","masjid"],
["motorŝipo","kapal motor"],
["mueldento, muela dento","gigi geraham"],
["muezino","muazin"],
["muftio","mufti"],
["multfoje","acap kali","sering kali"],
["multkolora","warna-warni"],
["mumpso","beguk","gondong","parotitis"],
["murhorloĝo","jam dinding"],
["muro","dinding"],
["muskato","pala"],
["musko","lumut"],
["muskola","[otot] berotot"],
["muskolo","otot","urat"],
["muso","tikus","tetikus"],
["mustelo","cerpelai"],
["mustruo","lubang tikus"],
["muta","bisu","tunawicara","[diam] terdiam","kelu","diam"],
["mutigi","[bungkam] membungkam"],
["mutiĝi","[diam] terdiam"],
["muzeo","museum"],
["muzesciencisto, muzeosciencisto","museolog"],
["muzescienco, muzeoscienco","museologi"],
["muzika","musikal"],
["muziki","[musik] bermusik"],
["muzikigi","[musik] memusikkan"],
["muzikilo","alat musik"],
["muzikinstrumento","alat musik"],
["muzikistaro","orkestra"],
["muzikisto","musikus","musisi","[musik] pemusik"],
["muziko","musik"],
["muzikosciencisto, muzikfakulo","musikolog"],
["muzikoscienco, muzikscienco","musikologi"],
["muzikvideo","video klip"],
["muŝo","lalat"],
["n-argumenta funkcio","fungsi n variabel"],
["najbaraĵo","lingkungan"],
["najbaro","tetangga"],
["najli","[paku] memaku"],
["najlo","paku"],
["nanplanedo","planet"],
["narcisismo","narsisisme"],
["narciso","narsis","Narcissus"],
["naskiĝtago","hari ulang tahun"],
["natrio","natrium"],
["natura","alami","alamiah","natural"],
["natureco","[alami] kealamian"],
["naturhistorio","sejarah alam"],
["naturisto","naturalis"],
["naturo","alam"],
["naturparko","cagar alam"],
["naturscienco, natura scienco","ilmu pengetahuan alam"],
["nauro","Nauru"],
["nazo","hidung"],
["naztruo, nazotruo","lubang hidung"],
["naĝejo","kolam renang"],
["naĝilo","sirip"],
["naŭ","sembilan"],
["ne","tidak"],
["nebula","[kabut] berkabut"],
["nebulo","kabut"],
["neceseja papero, necespapero","kertas toilet","tisu toilet"],
["nedaŭra planto","tanaman semusim"],
["nefrito","nefritis"],
["nekompreno","ketidakpahaman"],
["neodimo","neodimium"],
["neonlampo","lampu neon"],
["neono","neon"],
["neorganika ĥemio","kimia anorganik"],
["nepino","cucu"],
["neplenaĝa","di bawah umur"],
["nepo","cucu"],
["neptunio","neptunium"],
["neregistara organizaĵo","organisasi nonpemerintah"],
["nervosistemo, nervsistemo","sistem saraf"],
["nesala","hambar"],
["netipa pneŭmonio","SARS","Sindrom Pernapasan Akut Parah"],
["neĝhomo, neĝviro","manusia salju"],
["neĝofloro, neĝfloro","edelweis"],
["neĝtabulo","papan salju"],
["neŭralgio","neuralgia","nyeri urat saraf"],
["neŭrastenio","neurastenia"],
["neŭrozo","neurosis","psikoneurosis"],
["ni","kami","kita"],
["nia","milik kami","milik kita"],
["nigra","hitam","gelap","kelam"],
["nigra magio","ilmu hitam"],
["nigra truo","lubang hitam"],
["nigrigi","[hitam] menghitamkan"],
["nigrulo","negro"],
["nikaragvo","Nikaragua"],
["nikelo","nikel"],
["niobo","niobium"],
["niĝerio","Nigeria"],
["niĝero","Niger"],
["nobelio","nobelium"],
["nobla gaso","gas mulia"],
["nodo","simpul","knot"],
["nokto","malam"],
["noktopapilio, nokta papilio","ngengat"],
["nomado","[nama] penamaan"],
["nome de, en la nomo de","atas nama"],
["nomi","[nama] menamai"],
["nomiĝi","[nama] bernama"],
["nomo","nama"],
["nomumi","[nama] menamai"],
["nordo","utara"],
["norvegujo","Norwegia"],
["novaĵletero","nawala"],
["novedzino","pengantin baru"],
["novedzo","pengantin baru"],
["novembro","November"],
["novgeedzoj","pengantin baru"],
["novluno","bulan baru"],
["novriĉulo","orang kaya baru","OKB"],
["nuba","[awan] berawan","mendung"],
["nubo","awan"],
["nukleacido, nuklea acido","asam nukleat"],
["nuko","kuduk","tengkuk"],
["nul","nol"],
["nuligi","[batal] membatalkan"],
["nuliĝi","batal"],
["nulo","nol"],
["numeri","[nomor] menomori"],
["numero","angka","nomor"],
["nun","sekarang"],
["nuntempo","saat ini"],
["nur","hanya"],
["o-vorto","kata benda","nomina","substantiva"],
["obelisko","obelisk"],
["obio","obi"],
["objekta","objektif"],
["objektiva","objektif"],
["objektiveco","objektivitas"],
["objekto","benda","objek"],
["obtuzangula","sudut tumpul"],
["oftalmito","oftalmia"],
["ok","delapan"],
["okarino","okarina"],
["okcidento","barat","Barat"],
["oksido","oksida"],
["oksigeno","oksigen"],
["oktobro","Oktober"],
["okulo","mata"],
["okulvitroj","kacamata"],
["okuma","oktal"],
["olea","[minyak] berminyak"],
["olei","[lumas] melumasi","[minyak] meminyaki"],
["olelampo, oleolampo","lampu minyak","lampu tempel","lampu teplok"],
["oleo","minyak"],
["olivo","zaitun"],
["olivoleo","minyak zaitun"],
["omaro","lobster"],
["ombra, ombroplena","teduh"],
["ombrelo","payung"],
["ombri","[naung] menaungi","[payung] memayungi"],
["ombro","bayangan","bayang-bayang"],
["ommetro","ohmmeter"],
["onda","[gelombang] bergelombang"],
["ondo","gelombang","ombak"],
["onklino","bibi","tante"],
["onklo","om","paman"],
["opinii","[dapat] berpendapat"],
["opinio","[dapat] pendapat","opini"],
["orangutango","orang utan"],
["oranĝo","jeruk"],
["orbiti","[orbit] mengorbit"],
["orbito","orbit"],
["orelbruo","tinitus"],
["orelo","telinga"],
["oreltamburo","timpani"],
["orfejo","panti asuhan"],
["orfo","yatim piatu"],
["organika ĥemio","kimia organik"],
["organizado, organizo","organisasi"],
["organizaĵo","organisasi"],
["organizi","[organisasi] mengorganisasi"],
["organiziĝi","[organisasi] terorganisasi"],
["organizo","organisasi"],
["orgeno","organ pipa","orgel"],
["orienti","[bimbing] membimbing","[orientasi] mengorientasikan"],
["orientiĝi, sin orienti","[orientasi] berorientasi"],
["orientiĝo","orientasi"],
["oriento","timur"],
["origamio","origami"],
["orkestro","orkes","orkestra"],
["orkideo","anggrek"],
["ornamarto","seni dekoratif"],
["oro","emas"],
["ortangula","sudut siku-siku"],
["ortangulo","segi empat"],
["oscedi","[uap] menguap (mengantuk)"],
["osmio","osmium"],
["ostoporozo","osteoporosis"],
["ovario","indung telur","ovarium"],
["ovingo","cangkir telur"],
["ovo","telur"],
["ovoblanko, ovoblankaĵo","albumen","putih telur"],
["ovoflavo, ovoflavaĵo","kuning telur","yolk"],
["ozono","ozon"],
["paca","damai"],
["pacienca","sabar"],
["pacienco","[sabar] kesabaran"],
["pacigi","[damai] mendamaikan"],
["pacismo","pasifisme"],
["paciĝi","[damai] berdamai"],
["paco","[damai] kedamaian"],
["paf","dor!"],
["pafado, pafaro","salvo"],
["pafarko","busur panah"],
["pafaĵo","proyektil"],
["pafi","[tembak] menembak"],
["pafilego","meriam"],
["pafilo","pistol"],
["pafisto","Danub","Kaus","Sagitarius"],
["pafmortigi","[tembak] menembak mati"],
["pafo","tembakan"],
["pagumo","musang galing"],
["pakpapero","kertas kado"],
["pala","pucat"],
["palaco","istana"],
["paladio","paladium"],
["paleontologiisto","paleontolog"],
["paleontologio","paleontologi"],
["paliĝi","[pucat] memucat"],
["palmoleo","minyak kelapa (sawit)"],
["panamo","Panama"],
["panaricio","cantengan","paronikia"],
["panero","remah-remah (roti)"],
["pano","roti"],
["papero","kertas"],
["papertigro","macan kertas"],
["papilio","kupu-kupu"],
["papriko","paprika"],
["paralizi","lumpuh"],
["paralizo","[lumpuh] kelumpuhan","paralisis"],
["paramecio","paramecium"],
["paranojo","paranoia"],
["paraplegio","paraplegia"],
["paratifo","paratifus"],
["parfumo","parfum"],
["parkejo","tempat parkir"],
["parki","parkir"],
["parko","taman","taman nasional"],
["parkumejo","tempat parkir"],
["parkumi","parkir"],
["parola","lisan","oral"],
["parolado","orasi","pidato"],
["parolarto","retorika"],
["parolema","cerewet"],
["paroli","[bicara] berbicara"],
["parolisto","[bicara] pembicara","juru bicara","orator","presenter"],
["parolo","[bicara] pembicaraan"],
["parseko","parsec"],
["partiano","partisan"],
["partio","partai","[tanding] pertandingan"],
["pasaĝero","[tumpang] penumpang"],
["pasia","[gairah] bergairah"],
["pasio","berahi","gairah","hasrat"],
["paskala triangulo","segitiga Pascal"],
["pasvorto","kata kunci","kata sandi"],
["patelo","tulang tempurung lutut"],
["patologio","patologi"],
["patrino","ibu"],
["patro","ayah","Bapa"],
["patroj","mertua"],
["patrujo","tanah air"],
["pavi","[sombong] menyombongkan (diri)"],
["paviano","babun"],
["pavilono","paviliun"],
["pavo","merak"],
["pavumi","[sombong] menyombongkan (diri)"],
["paŝi","[langkah] melangkah"],
["paŝo","langkah"],
["paŝstango","egrang","jangkungan"],
["paŭspapero","kertas kalkir"],
["pederastio","[jantan] perjantanan"],
["pedofilio","pedofilia"],
["pedofiliulo","pedofil"],
["peki","[dosa] berdosa"],
["peko","dosa"],
["pekulo","[dosa] pendosa"],
["pelagro","pelagra"],
["pelvo","tulang panggul"],
["penco","penny"],
["peniso","penis","zakar"],
["pentrarto","seni lukis"],
["perforto","[keras] kekerasan"],
["perli","[tetes] menetes"],
["perlo","mutiara"],
["persa Golfo","Teluk Persia"],
["persio","Persia"],
["persona komputilo","komputer pribadi","PC"],
["persona nomo","nama depan"],
["persujo","Persia"],
["peseto","peseta"],
["pesi","[timbang] menimbang"],
["pesilo","timbangan","Libra","Mizan","Tula"],
["peso","peso"],
["pesto","pes"],
["petrolĥemio","petrokimia"],
["petroselo","peterseli"],
["piano","piano"],
["piedpilkado","sepak bola"],
["piedpilko","bola sepak"],
["pilko","bola"],
["pilolo","pil"],
["pino","pinus"],
["pipro","lada","merica"],
["piro","pir"],
["pisi","buang air kecil","kencing","pipis"],
["pispoto","pispot"],
["pizo","ercis","polong"],
["piĵamo","piyama"],
["plando","telapak kaki","sol"],
["plandumo","sol"],
["planedo","planet"],
["planlingvo","bahasa buatan"],
["plantejo","[kebun] perkebunan"],
["planti","[tanam] menanam"],
["planto","[tanam] penanaman","tanaman","tumbuhan"],
["plasto","plastik"],
["plateno","platinum"],
["platglobo","planisfer"],
["platkomputilo","komputer tablet","sabak elektronik"],
["plejaĝulo","senior","[sepuh] sesepuh","[tua]tetua"],
["plejboneco","[baik] terbaik","optimal"],
["plenluno","bulan purnama"],
["plezurĝardeno","taman bermain"],
["pleŭrito","pleuritis"],
["pliaĝiĝi","[tua] menua"],
["pliaĝulo","senior","[sepuh] sesepuh","[tua]tetua"],
["plibonigi","[baik] memperbaiki"],
["plonĝtabulo, plonĝotabulo","papan loncatan"],
["plori","[tangis] menangis"],
["ploristino","cengeng"],
["ploro","tangis","tangisan"],
["plumbo","timbal"],
["plumnomo","nama pena"],
["plurangulo","poligon","segi banyak"],
["pluredzeco","poliandri"],
["pluredzineco","poligini"],
["plurgeedzeco","poligami"],
["plurlingveco, multlingveco","multilingualisme"],
["plurlingvismo","multilingualisme"],
["plurlingvulo","poliglot"],
["plurvoĉeco","polifoni"],
["plutonio","plutonium"],
["pluvarbaro","hutan hujan"],
["pluvarko","pelangi"],
["pluveto","gerimis"],
["pluvo","hujan"],
["pluvombrelo","payung"],
["pneŭmonio","pneumonia"],
["pocento","persen"],
["podagro","pirai"],
["poezia","puitis"],
["poezio","puisi"],
["pogrande","besar-besaran","borongan"],
["pojno","pergelangan tangan"],
["polinoma adicio","[jumlah] penjumlahan polinom"],
["polinoma funkcio","fungsi polinomial"],
["poliomjelito","polio","poliomielitis"],
["politika sistemo","sistem politik"],
["pollando","Polandia"],
["polmo","telapak tangan"],
["polonio","polonium"],
["polujo","Polandia"],
["polusa angulo","sudut polar"],
["poluso","kutub"],
["polvoviŝilo","lap","majun"],
["pomalgrande","eceran"],
["pomo","apel"],
["ponto","jembatan"],
["popolleviĝo","[berontak] pemberontakan"],
["popolrakonto","cerita rakyat"],
["por","untuk"],
["por ke","agar","supaya"],
["pordo","pintu"],
["porko","babi"],
["porparolanto","[acara] pengacara","advokat"],
["posta tago","hari berikutnya"],
["postaĵotruo","anus"],
["postkolero","dendam"],
["postkropo","ampela"],
["postmanĝaĵo",""],
["postmorgaŭ","lusa"],
["postmorta","pascakematian"],
["postparolo","epilog"],
["postskribo","notabene","N.B."],
["posttempa","[lambat] terlambat","telat"],
["povi","bisa","dapat"],
["poŝerinaco","ekidna"],
["poŝhorloĝo","jam saku"],
["poŝkomputilo","komputer saku","pembantu digital pribadi","PDA"],
["poŝlampo","senter"],
["poŝo","kantong","saku"],
["poŝtelefono, ĉeltelefono","HP","ponsel","telepon seluler","telepon genggam"],
["prahistorio, antaŭhistorio","prasejarah"],
["prahomo","manusia purba"],
["pramŝipo","feri","kapal feri"],
["pranepino, postnepino","cicit"],
["pranepo, postnepo","cicit"],
["pratempo","zaman dahulu"],
["prazeodimo","praseodimium"],
["preskaŭ","hampir"],
["preĝejo","gereja"],
["preĝi","[doa] berdoa","[ibadah] beribadah"],
["pri","tentang"],
["prifesti","[raya] merayakan"],
["priinstrua","didaktis","pedagogis"],
["princino","putri"],
["princo","pangeran"],
["princujo","[pangeran] kepangeranan"],
["printempo","musim semi"],
["priparoli","[diskusi] berdiskusi"],
["priskribi","[deskripsi] mendeskripsikan"],
["pritemi","[tema] bertemakan"],
["probablodenso","[padat] kepadatan probabilitas"],
["profito","laba","profit","untung"],
["profundaĝa","tua"],
["profundaĝulo","manula"],
["programlingvo","bahasa pemrograman"],
["prometio","prometium"],
["protaktinio","protaktinium"],
["protozoo","protozoa"],
["provbalono","balon cuaca"],
["proverbo","peribahasa"],
["provizora","provisional","sementara","temporer","tentatif"],
["provjaro","tahun ajaran"],
["provtempo, provotempo","masa percobaan"],
["pruntvorto","kata serapan","kata pinjaman"],
["psikozo","psikosis"],
["publika letero, nefermita letero","surat terbuka"],
["publika opinio, ĝenerala opinio","[dapat] pendapat publik","[dapat] pendapat umum","opini publik","opini umum"],
["publika sekreto, pulĉinela sekreto","rahasia umum"],
["pugno","kepalan tangan"],
["pugtruo","anus"],
["pulmo","paru-paru"],
["pulo","kutu"],
["pulsostelo","pulsar"],
["pulvorsukero","gula bubuk"],
["pundo","pound"],
["punkto","titik","titik dua"],
["pupilo","pupil"],
["rabio","rabies"],
["rabobestoj","karnivora"],
["racionala funkcio","fungsi rasional"],
["radiano","radian"],
["radio","radiasi","jari-jari","radius","radio"],
["radiumo","radium"],
["rado","roda"],
["radono","radon"],
["radradio","jari-jari"],
["radringo","ban"],
["radrondo","pelek"],
["rajo","pari"],
["rakito","rakitis"],
["rakonti","[cerita] bercerita","[cerita] menceritakan"],
["rakonto","cerita"],
["ramadano","Ramadan"],
["rambutano","rambutan"],
["rano","katak"],
["rapida","cepat"],
["rapideco","[cepat] kecepatan"],
["rapidigi, plirapidigi","[cepat] mempercepat"],
["rapidumo","gigi (motor)"],
["realtempa","langsung (siaran)"],
["rebonigi","[baik] memperbaiki"],
["refoje","lagi"],
["reformi","[reformasi] mereformasi"],
["regiona dialekto","dialek regional"],
["regsistemo","administrasi","sistem administrasi"],
["regturo, kontrolturo","menara kontrol"],
["rejso","real (Brazil)"],
["rekomendletero","surat rekomendasi"],
["rekta intesto","rektum"],
["rektangulo","segi empat"],
["religia","agamis","religius"],
["religio","agama"],
["renio","renium"],
["reno","ginjal"],
["rentgenio","roentgenium"],
["reprodukta sezono","musim kawin"],
["resanigilo","obat"],
["resaniĝi","sembuh"],
["restoracio","restoran","rumah makan"],
["retadreso","alamat surel (e-mail)"],
["retbutiko","toko online"],
["retejo","laman"],
["retletero","e-mail","pos-el","surel"],
["retmesaĝo","e-mail","posel","surel"],
["reto","jaring","jaringan"],
["retpoŝto","e-mail","pos-el","surel"],
["retumi","[jelajah] menjelajah","[ramban] meramban"],
["retumilo","[jelajah] penjelajah","[ramban] peramban"],
["reuzpapero","kertas daur ulang"],
["revivigi","[hidup] menghidupkan kembali"],
["reviviĝi","hidup kembali"],
["reziduo","residu"],
["reĝi","[atur] mengatur","[kuasa] menguasai"],
["reĝidino","putri"],
["reĝido","pangeran"],
["reĝino","rani","ratu","permaisuri"],
["reĝlando","[raja] kerajaan"],
["reĝo","raja"],
["reĝo de","maharaja","raja segala raja"],
["reĝujo","[raja] kerajaan"],
["reŭmatismo","encok","reumatisme"],
["rialo","riyal"],
["ribonuklea acido","asam ribonukleat","ARN","RNA"],
["ricevi","[terima] menerima","[dapat] mendapat"],
["rideti","[senyum]tersenyum"],
["rideto","senyum"],
["ridi","[tawa]tertawa"],
["rido","tawa"],
["ringa fingro","jari manis"],
["ripo","iga","tulang rusuk"],
["riverdelfeno","lumba-lumba sungai"],
["riverfiŝo","ikanair tawar"],
["rivero","sungai"],
["riĉa","kaya","miskin"],
["riĉaĵo","harta","[kaya] kekayaan"],
["riĉeco","[kaya] kekayaan"],
["riĉigi","[kaya] memperkaya"],
["riĉo","[kaya] kekayaan"],
["rodio","rodium"],
["ronda tablo","[temu] pertemuan"],
["rosmaro","walrus"],
["roso","embun"],
["rostro","belalai"],
["roza","merah muda","pink"],
["rozo","mawar"],
["rubeolo","campak jerman","rubela","rubeola"],
["rubidio","rubidium"],
["rublo","rubel"],
["rulfali","[gelinding] menggelinding"],
["rulseĝo, radseĝo","kursi roda"],
["rultabulo","papan luncur"],
["rulŝtuparo","eskalator","tangga jalan"],
["rumanio","Rumania"],
["rumanujo","Rumania"],
["rupio","rupee","rupiah"],
["rutenio","rutenium"],
["ruterfordio","ruterfordium"],
["ruĝa","merah"],
["ruĝa globeto","sel darah merah"],
["ruĝa pipro","paprika"],
["ruĝalgoj, ruĝaj algoj","alga merah"],
["ruĝiĝi","[merah] memerah"],
["ruĵo","gincu","lipstik"],
["sabato","Sabtu"],
["sablohorloĝo, sabla horloĝo","jam pasir"],
["sablopapero","ampelas"],
["sako","tas"],
["saksofono","saksofon"],
["sakstrato","jalan buntu"],
["sala","asin"],
["salajri","[gaji] menggaji"],
["salajro","gaji","upah"],
["salajrulo","karyawan"],
["salamandro","salamander"],
["sali","[garam] menggarami"],
["salikoko","udang"],
["salmo","salmon"],
["salo","garam"],
["saltotabulo","papan loncatan"],
["salvadoro","El Salvador"],
["samario","samarium"],
["samaĝulo","orang sebaya"],
["samoo","Samoa"],
["samopinieco","[bulat] kebulatan suara","mufakat"],
["samopinii","sepakat"],
["samseksema, samseksama","homoseksual"],
["samseksemulino, samseksamulino","lesbian"],
["samseksemulo, samseksamulo","gay","homo","homoseksual","lesbian"],
["samtempa","kontemporer","simultan","sinkron"],
["sana","sehat","sakit"],
["sandalo","sandalo"],
["sanema","[sakit] berpenyakit","sakit-sakitan"],
["sango","darah"],
["sangoĉelo","sel darah"],
["saniga","[sehat] menyehatkan"],
["sanigi","[sembuh] menyembuhkan"],
["sanilo","obat"],
["sankta","kudus","sakral","suci"],
["sankta vespero","malam kudus"],
["sanktega","mahasuci"],
["sanktigi","[suci] menyucikan"],
["sanktulo","santa","santo"],
["sanmarino","San Marino"],
["sano","[sehat] kesehatan","[sakit] penyakit"],
["santomeo","Sao Tome"],
["santomeo kaj Principeo","Sao Tome dan Principe"],
["sanulejo","rumah sakit"],
["sardino","sarden"],
["savtabulo","[lampung] pelampung"],
["savzono","baju pelampung"],
["saĝa","bijaksana"],
["saĝeco","[bijaksana] kebijaksanaan"],
["saĝo","[bijaksana] kebijaksanaan"],
["saĝodento","gigi tetap"],
["sciencisto","ilmuwan","saintis"],
["scienco","ilmu (pengetahuan)","sains"],
["sciuro","tupai"],
["seaborgio","seaborgium"],
["seborgio","seaborgium"],
["sed","tetapi"],
["sejŝeloj","Seychelles"],
["seka","kering"],
["sekigi","[kering] mengeringkan"],
["sekiĝi","[kering] mengering"],
["sekreti","[rahasia] merahasiakan"],
["sekreto","rahasia"],
["seksa","seksual"],
["seksismo","seksisme"],
["seksmatura","matang (secara) seksual"],
["sekso","seks"],
["seksorgano","organ genital","organ seksual"],
["seksperforti","[perkosa] memerkosa"],
["seksumi","[kopulasi] berkopulasi","[setubuh] bersetubuh"],
["seksumilo, seksilo","organ genital","organ seksual"],
["sekundo","detik","sekon"],
["sekurzono","sabuk pengaman"],
["sekvojadendro","sequoia raksasa"],
["seleno","selenium"],
["semajnfino","akhir pekan"],
["semajno","minggu","pekan"],
["sendormeco","insomnia"],
["senedzeco, senedzineco","selibat"],
["senespera","putus asa"],
["senfina","abadi","kekal"],
["senhalta","kontinu"],
["senhara","botak","gundul"],
["senkapigi","[penggal] memenggal"],
["senpartia","independen"],
["sep","tujuh"],
["septembro","September"],
["serbio","Serbia"],
["serbujo","Serbia"],
["serpento","ular"],
["servalo","serval"],
["ses","enam"],
["sezono","musim"],
["seĝo","kursi"],
["siatempe","pada waktunya"],
["sidi","duduk"],
["sidigi","[duduk] mendudukkan"],
["sidloko","tempat duduk"],
["sieraleono","Sierra Leone"],
["sifiliso","sifilis"],
["siliciato","silikat"],
["silicio","silikon"],
["silikozo","silikosis"],
["silkopapero, silkpapero","kertas rokok"],
["simio","monyet","kera"],
["simioj","primata"],
["sin mortigi","bunuh diri"],
["sinjorino","nyonya"],
["sinjoro","tuan"],
["sinusito","sinusitis"],
["sistemo","sistem"],
["sitelo","ember"],
["siverto","sievert"],
["skabio","kudis","skabies"],
["skandio","skandium"],
["skapolo","tulang belikat"],
["skarlatino","skarlatina"],
["skizofrenio","skizofrenia"],
["sklaveco","[budak] perbudakan"],
["sklavo","budak","hamba sahaya"],
["sklerozo","sklerosis"],
["skombro","makerel"],
["skorbuto","skorbut"],
["skorpio","Akrab","Kala","Skorpio"],
["skorpioj","kalajengking"],
["skriba","[tulis] tertulis"],
["skribado","[tulis] penulisan"],
["skribaĵo","tulisan"],
["skribejo","skriptorium"],
["skriberaro","[salah cetak] kesalahan cetak","typo"],
["skribi","[tulis] menulis","[kopi] mengopi","[salin] menyalin"],
["skribilo","alat tulis"],
["skribisto","[tulis] penulis"],
["skribkaraktero","tulisan tangan"],
["skribmaniero","tulisan tangan","sistem penulisan"],
["skribo","tulisan"],
["skribsistemo","sistem penulisan"],
["skribtablo","meja tulis"],
["skulptarto","seni pahat","seni ukir"],
["slango","slang"],
["slovaka","Slovak"],
["slovakujo","Slovakia"],
["slovenujo","Slovenia"],
["smeraldo","zamrud"],
["smirgopapero, smirga papero","ampelas"],
["socia dialekto","dialek sosial"],
["socia retejo","jejaring sosial"],
["sociscienco, socioscienco","ilmu pengetahuan sosial"],
["solinfano","anak semata wayang","anak tunggal"],
["somalujo","Somalia"],
["somera tempo","waktu musim panas"],
["somero","musim panas"],
["sonkoloro","timbre","warna nada"],
["sonori","[dering] berdering","[dentang] berdentang"],
["sonorilejo, sonorilturo","menara lonceng"],
["sonorilo","bel","lonceng"],
["sonsistemo","sistem fonetis"],
["sorbopapero","kertas serap"],
["soriko","celurut"],
["sorĉarto","ilmu sihir"],
["spammesaĝo","spam"],
["spegulo","cermin"],
["spektoradego","kincir raksasa","komidi putar"],
["spermo","sperma"],
["spinaco","bayam"],
["spiroĥeto","spiroket"],
["spongo","spons"],
["srilanko","Sri Lanka"],
["stacidomo","stasiun"],
["stadio","stadion","stadium"],
["stano","timah"],
["stari","[diri] berdiri"],
["statistikaĵo","statistik"],
["statistiko","statistika"],
["statuo","patung"],
["statuto","AD/ART","statuta"],
["steleto","asterisk"],
["stelo","bintang"],
["stelulo","artis","bintang film","selebritas"],
["steradiano","steradian"],
["sterlinga funto, sterlingfunto","pound sterling"],
["sternumo","tulang dada"],
["stilo","gaya"],
["stofo","pint"],
["stranga","aneh","ganjil","janggal"],
["strata lanterno","lampu jalan"],
["strategiludo, strategia ludo","[main] permainan strategi"],
["stratlampo","lampu jalan"],
["strato","jalan"],
["strattelefono","telepon umum"],
["stratulino","[lacur] pelacur"],
["stroncio","stronsium"],
["studi","[ajar] belajar"],
["studjaro","tahun akademik"],
["studo","[ajar] pembelajaran"],
["studĝardeno, eksperimentĝardeno","kebun raya"],
["sub","di bawah"],
["sub-","sub-"],
["subakvigi","[tenggelam] menenggelamkan"],
["subakviĝi","tenggelam"],
["subigi","[serah] menyerahkan"],
["subkorpo","subbidang"],
["submarŝipo","kapal selam"],
["subsistemo","subsistem"],
["subskribi","[tanda tangan] menandatangani","teken"],
["subskribo","tanda tangan"],
["subulo","bawahan (orang)"],
["sudo","selatan"],
["sukeri","[gula] menggulai"],
["sukero","gula"],
["suko","jus","esensi","intisari"],
["sulfuro","belerang","sulfur"],
["sunfloro","bunga matahari"],
["sunhorloĝo","jam matahari"],
["sunkalendaro, suna kalendaro","kalender matahari","kalender solar","kalender surya"],
["sunleviĝo","matahari terbit"],
["suno","matahari"],
["sunombrelo","payung"],
["sunsistemo","tata surya"],
["superhoma","supernatural"],
["superhomo","manusia super"],
["superjaro","tahun kabisat"],
["supernatura","supernatural"],
["superstiĉo","takhayul"],
["supkulero","sendok makan"],
["supo","sup"],
["sur","ke atas","di atas"],
["surao","Surah","Surat"],
["surda","tuli","tunarungu"],
["surdeta","pekak"],
["surdigilo","[redam] peredam (bunyi)"],
["surftabulo, surfotabulo","papan selancar"],
["suro","betis"],
["surrena","kelenjar adrenal","kelenjar anak ginjal","kelenjar suprarenalis"],
["surskribo","epigraf","inskripsi","prasasti"],
["surtabla komputilo","komputer meja"],
["suĉbotelo","botol bayi"],
["suĉinfano","bayi"],
["svaziio","Swaziland"],
["svazilando","Swaziland"],
["svaziujo","Swaziland"],
["svedujo","Swedia"],
["svislando","Swiss"],
["svisujo","Swiss"],
["tablo","meja"],
["tablolampo","lampu meja"],
["tabuleto","tablet"],
["tabulo","papan","papan tulis"],
["taga","harian"],
["tage","[hari] seharian"],
["tage kaj nokte","siang malam"],
["tago","siang","hari"],
["tago de Valenteno","Hari Valentine"],
["tajlando","Thailand"],
["tajvano","Formosa","Taiwan"],
["taksiejo","pangkalan taksi"],
["taksiisto","sopir taksi"],
["taksio","taksi"],
["talasemio","talasemia"],
["talio","pinggang"],
["taliumo","talium"],
["talpo","tikus tanah"],
["tamburo","genderang","tambur"],
["tamiaso","bajing tanah","tupai tanah"],
["tantalo","tantalum"],
["taĝiko","Tajik"],
["taĝikujo","Tajikistan"],
["teatro","teater"],
["tekkomputilo","komputer jinjing","laptop"],
["teknecio","teknetium"],
["tekulero","sendok teh"],
["telefoni","[telepon] menelepon"],
["telefonlibro","buku telepon"],
["telefonnumero","nomor telepon"],
["telefono","telepon"],
["telegrafo","telegraf"],
["telekomunikado","telekomunikasi"],
["telekomuniki","[telekomunikasi] bertelekomunikasi"],
["telero","piring"],
["televidilo","televisi","TV"],
["televido","televisi","TV"],
["teluro","telurium"],
["temaro","tematik","tematis"],
["temi","[tema] bertema"],
["temo","tema"],
["temo kun variaĵoj","tema dan variasi"],
["tempaĝo","masa","zaman"],
["tempio","pelipis"],
["tempo","masa","tempo","waktu","kala"],
["teo","teh"],
["terbio","terbium"],
["terebinto","terpentin"],
["tergaso","gas bumi"],
["terhundo","terrier"],
["terkarbo, minkarbo","batu bara"],
["tero","bumi","tanah"],
["terpomo","kentang"],
["terscienco, teroscienco","ilmu bumi"],
["tertremo","gempa"],
["testa funkcio, testofunkcio","fungsi tes"],
["testiko","testis"],
["testikujo","skrotum"],
["testudo","kura-kura"],
["tetano","tetanus"],
["tia","semacam itu"],
["tial","karena itu"],
["tiam","saat itu","waktu itu"],
["tie","di sini"],
["tiel","seperti itu"],
["ties","milik (orang) itu"],
["tifa febro, tifoida febro","demam tifoid"],
["tifo","tifus"],
["tigro","harimau","macan"],
["tima, timema","malu-malu"],
["timi","khawatir","takut"],
["timigi","[takut] menakuti"],
["timo","[khawatir] kekhawatiran","[takut] ketakutan"],
["timpano","gendang telinga","membran timpani","timpanum","timpani"],
["timulo","[takut] penakut"],
["tineo","ngengat"],
["tinuso","tuna"],
["tio","itu"],
["tiom","sebanyak itu"],
["tirharmoniko","akordeon"],
["titano","titanium"],
["tiu","itu","orang itu"],
["to-ĉemizo","kaus oblong"],
["tofuo","tahu"],
["tohuo","tahu"],
["tombomonumento, tomba monumento","mausoleum"],
["tomboŝtono, tombŝtono","batu nisan"],
["tondi","[gunting] menggunting"],
["tondilo","gunting"],
["torio","torium"],
["toŭfuo","tahu"],
["trafiki","[lalu lintas] berlalu lintas"],
["trafikilo","alat transportasi"],
["trafiko","lalu lintas"],
["tranokti","[inap] menginap","[malam] bermalam"],
["transformilo","transformator"],
["transformismo","evolusionisme"],
["transformo","transformasi"],
["translingvigi","[terjemah] menerjemahkan"],
["translokiĝi","[pindah] memindahkan"],
["transruĝa","inframerah"],
["transviola","ultraungu","ultraviolet"],
["tranĉodento, tranĉa dento","gigi seri"],
["tratrui","[tembus] menembus"],
["traĥomo","trakom"],
["trenŝipo","kapal penarik","kapal penyeret"],
["tri","tiga"],
["triangulo","segitiga"],
["trigonometria funkcio","fungsi trigonometri"],
["triliteraĵo","trigraf"],
["trimonato","kuartal","trimester","triwulan"],
["trinkakvo","air minum"],
["trinkaĵo","minuman"],
["trinki","minum"],
["trinkmono","tip","persen"],
["trinkĉokolado","cokelat panas","susu cokelat"],
["tripunkto","elipsis"],
["tritiko","gandum","terigu"],
["triunuo","Trinitas"],
["trodikeco","obesitas"],
["troja ĉevalo","Kuda Troya"],
["trombono","trombon"],
["trudmesaĝo","spam"],
["trui","[lubang] melubangi"],
["trumpeto","trompet"],
["truo","liang","lubang"],
["tualetpapero","kertas toilet","tisu toilet"],
["tuberkulozo","TBC","tuberkulosis"],
["tujmesaĝilo","pesan instan"],
["tulio","tulium"],
["turkmeno","Turkmen"],
["turkmenujo","Turkmenistan"],
["turko","Turk"],
["turkujo","Turki"],
["turo","menara","benteng (bidak catur)"],
["tutkorpa","seluruh tubuh"],
["tuvalo","Tuvalu"],
["ukrainujo","Ukraina"],
["ukrajnujo","Ukraina"],
["ukulelo","ukulele"],
["ulcero","borok"],
["ulemo","ulama"],
["ulno","hasta"],
["umbilika ŝnuro","tali pusar"],
["umbiliko","pusar"],
["ungego","cakar"],
["ungo","kuku"],
["unu","satu"],
["unua","pertama"],
["unueco","[satu] kesatuan","[satu] persatuan"],
["unuflanke","di satu sisi"],
["unuforma","[ragam] seragam","monoton"],
["unuigi","[satu] menyatukan","[satu] mempersatukan"],
["unuiĝi","[satu] bersatu"],
["unulingveco","monolingualisme"],
["unulingvismo","monolingualisme"],
["unuo","unit"],
["unuseksa","dioseus"],
["unuvoĉa, ĉiesvoĉa","mufakat","sepakat"],
["uranio","uranium"],
["urbano","urban","Urbanus"],
["urbego","metropolitan"],
["urbo","kota","suburban"],
["urbodomo","balai kota"],
["urini","buang air kecil","[kemih] berkemih","kencing","pipis"],
["urino","air kencing","urine"],
["urinveziko","kandung kemih"],
["urinŝtona malsano","batu ginjal","kencing batu"],
["urso","beruang"],
["uzbeko","Uzbek"],
["uzbekujo, uzbekio","Uzbekistan"],
["vagino","vagina"],
["vagonaro","kereta (api)"],
["vagono","gerbong (kereta)"],
["vakubotelo","termos"],
["valizo","koper"],
["vampiro","kelelawar vampir","vampir"],
["vanadio","vanadium"],
["vanado","vanadium"],
["vango","pipi"],
["vanilo","vanili"],
["vanuatuo","Vanuatu"],
["vapori","[uap] beruap"],
["vaporigi","[uap] menguapkan"],
["vaporiĝi","[uap] menguap"],
["vaporo","uap"],
["varicelo","cacar air"],
["variko","varises"],
["varma","panas"],
["varmbotelo","termos"],
["varmeta","hangat"],
["varmigi","[panas] memanaskan"],
["varmo","kalor"],
["varmumo","demam","pilek"],
["vazo","vas"],
["vaŭ","guk"],
["vejno","vena","pembuluh balik"],
["vekhorloĝo","jam beker"],
["veki","[bangun] membangunkan"],
["vekiĝi","bangun"],
["veluro","beledu","beludru"],
["velŝipo","kapal layar","perahu layar"],
["vendredo","Jumat"],
["venena","[racun] beracun","toksik"],
["veneni","[racun] meracuni"],
["veneno","racun","toksin"],
["veni","datang","asal berasal"],
["venki","[menang] memenangkan"],
["venta","[angin] berangin"],
["ventego","badai"],
["vento","angin"],
["ventoltruo","lubang angin"],
["ventro","perut"],
["ventumi","[kipas] mengipasi"],
["ventumilo","kipas"],
["verda","hijau"],
["verdalgoj, verdaj algoj","alga hijau"],
["verdi","[hijau] menghijau"],
["vespero","malam","sore"],
["vesperstelo","bintang senja"],
["vesperto","kelelawar"],
["vetero","cuaca"],
["vetludo, monludo","judi"],
["viando","daging"],
["videarto, videoarto","seni video"],
["videaĵo","video"],
["videludo, videoludo","[main] permainan video"],
["video","video"],
["vidpunkto","sudut pandang"],
["vidvino","janda"],
["vidvo","duda"],
["vilaĝo","desa","dusun","kampung"],
["vinagro","cuka"],
["vintra tempo","waktu standar"],
["vintro","musim dingin"],
["vintrodormo","hibernasi"],
["viola","ungu","violet"],
["violkolora","ungu","violet"],
["violono","biola"],
["vipi","[cambuk] mencambuk"],
["vipo","cambuk","cemeti","pecut"],
["virga","perawan"],
["virgeco","[perawan] keperawanan"],
["virgulino","dara","perawan","Kanya","Sunbulat","Virgo"],
["virgulo","bujangan","perjaka"],
["virseksa","jantan","maskulin"],
["viruso","virus"],
["virusologiisto","virolog"],
["virusologio","virologi"],
["virusologo","virolog"],
["vitro","kaca"],
["viva","langsung (live)"],
["vivaĵo","makhluk (hidup)"],
["vivero","luak","musang"],
["vivhistorio","biografi","riwayat hidup"],
["vivi","hidup"],
["vivigi","[hidup] menghidupkan"],
["vivo","[hidup] kehidupan"],
["vivoformo","bentuk kehidupan"],
["vivoĉambro","ruang keluarga"],
["vivtempo","","masa hidup","seumur hidup"],
["vizaĝo","muka","wajah"],
["viziti","[kunjung] mengunjungi"],
["vizito","kunjungan"],
["viŝi","[lap] mengelap","[seka] menyeka"],
["viŝpapero","tisu"],
["vjetnamujo","Vietnam"],
["vojforko, vojoforko","bifurkasi","[cabang] percabangan dua"],
["vole ne","mau tak mau"],
["volframo","wolfram"],
["voli","ingin","mau"],
["voluptema, voluptama","[gairah] bergairah","sensual"],
["volupto","gairah","hasrat"],
["vomi","muntah","[muntah] memuntahkan"],
["vono","won"],
["vortaristo","leksikograf","[kamus] pekamus"],
["vortaro","kamus"],
["vortblindeco","disleksia"],
["vortero","morfem"],
["vortludo","[main] permainan kata"],
["vorto","kata","firman"],
["vortodivido","[penggal] pemenggalan (suku kata)"],
["vortoprovizo, vortprovizo","kosakata","[bendahara] perbendaharaan kata"],
["vosto","buntut","ekor"],
["voĉa","lisan","vokal","[suara] bersuara (fonem)"],
["voĉdoni","[pilih] memilih (dalam pemilu"],
["voĉi","[pilih] memilih (dalam pemilu)"],
["voĉkordo","pita suara"],
["voĉo","suara","ragam (gramatikal)"],
["vulpo","rubah"],
["zebro","zebra"],
["zingibro","jahe"],
["zinko","seng"],
["zirkonio","zirkonium"],
["zono","gesper","ikat pinggang","sabuk","pinggang","zona"],
["zoologiisto","zoolog"],
["zoologio","zoologi"],
["Ĉado","Chad"],
["Ĉilio","Cile"],
["Ĉukĉa maro","Laut Chukchee"],
["ĉambro","kamar","ruang","dewan","majelis"],
["ĉapelo","topi","sirkumfleks"],
["ĉapitro","bab"],
["ĉashundo","anjing pemburu"],
["ĉeesti","hadir","[hadir] menghadiri"],
["ĉefprinco","adipati"],
["ĉefpunkto geografia","mata angin"],
["ĉefstrato","jalan protokol","jalan utama"],
["ĉefurbo","ibu kota"],
["ĉemizo","kemeja"],
["ĉenero","mata rantai"],
["ĉeni, enĉenigi","[rantai] merantai"],
["ĉeno","rantai"],
["ĉevalejo","istal"],
["ĉevalo","kuda"],
["ĉevalpovo","tenaga kuda"],
["ĉeĥo","Cek"],
["ĉeĥujo","Republik Ceko"],
["ĉi tie, tie ĉi","di sini"],
["ĉi tiu, tiu ĉi","ini","orang ini"],
["ĉi-suba","di bawah ini"],
["ĉi-tage","hari ini"],
["ĉielarko","pelangi"],
["ĉielo","langit"],
["ĉimpanzo","simpanse"],
["ĉina inko","tinta Cina"],
["ĉinujo","Cina","Tiongkok"],
["ĉiokomprena","mahatahu"],
["ĉiudujara","bienial"],
["ĉiufoje, ĉiun fojon","setiap kali","selalu"],
["ĉiuhoma","universal"],
["ĉiujara","anual","tahunan"],
["ĉiuliteraĵo","pangram"],
["ĉiutaga","[tiap] setiap hari"],
["ĉokolado","cokelat (makanan)"],
["Ĝibutio","Djibouti"],
["ĝardenisto","tukang kebun"],
["ĝardeno","kebun"],
["ĝemelo","kembar"],
["ĝemeloj","Gemini","Jauza","Mintuna"],
["ĝeneraligita funkcio","distribusi","fungsi umum"],
["ĝentila","sopan"],
["ĝentileco","[sopan] kesopanan"],
["ĝi","dia (selain manusia)"],
["ĝia","miliknya (selain manusia)"],
["ĝibdorsa baleno, ĝiba baleno","paus bungkuk"],
["ĝino","jin"],
["ĝinzo","jeans","jins"],
["ĝirafo","jerapah"],
["ĝustatempe","tepat waktu"],
["Ĥanuko","Hanukah"],
["Ĥio","Khios"],
["ĥalifo","khalifah"],
["ĥalifujo","khilafah"],
["ĥameleono","bunglon"],
["ĥaosa","kaotis"],
["ĥaoso","kaos"],
["ĥemiisto","kimiawan"],
["ĥemio","kimia"],
["ĥina inko","tinta Cina"],
["ĥolecistito","kolesistitis"],
["ĥolero","kolera"],
["ĥoro","koor"],
["Ĵulo","Joule","joule"],
["ĵaluza","cemburu","dengki","iri"],
["ĵaluzo","[cemburu] kecemburuan","[dengki] kedengkian","[iri] keirian"],
["ĵamboreo","jambore"],
["ĵargono","jargon"],
["ĵazo","jaz"],
["ĵaŭdo","Kamis"],
["ĵeti","[lempar] melempar"],
["ĵetiĝi","[lempar] terlempar"],
["ĵetkubo","dadu"],
["ĵetlanco","lembing"],
["ĵeto","lemparan","fungsi (matematika)","[peta] pemetaan (matematika)"],
["ĵura","[sumpah] tersumpah"],
["ĵuri","[sumpah] bersumpah"],
["ĵuriano","anggota juri"],
["ĵurigi","[sumpah] menyumpah","[sumpah] menyumpahi"],
["ĵurio","juri"],
["ĵurnalismo","jurnalisme"],
["ĵurnalisto","jurnalis","reporter","wartawan"],
["ĵurnalo","koran","surat kabar"],
["ĵuro","ikrar","sumpah"],
["ĵurpeti","[kemis] mengemis"],
["ĵus","barusan","baru saja"],
["ĵusa","baru-baru ini"],
["Ŝario","syariah"],
["ŝafhundo","anjing gembala"],
["ŝafo","domba","biri-biri","Aries","Hamal","Mesa"],
["ŝakludo","catur"],
["ŝako","catur","skak"],
["ŝakpeco","bidak"],
["ŝaktabulo","papan catur"],
["ŝarko","hiu"],
["ŝarĝaŭtisto","sopir truk"],
["ŝarĝaŭto","truk"],
["ŝekelo","shekel"],
["ŝi","dia (perempuan)"],
["ŝia","miliknya (perempuan)"],
["ŝijaismo","Syiah"],
["ŝilingo","shilling"],
["ŝipanaro","awak kapal","kru (kapal)"],
["ŝipano","kelasi","[laut] pelaut","matros"],
["ŝiparestro","admiral"],
["ŝiparo","armada"],
["ŝipestro","kapten (kapal)"],
["ŝipeto","perahu","sampan","sekoci"],
["ŝipi","[layar] berlayar"],
["ŝipisto","kelasi","[laut] pelaut","matros"],
["ŝipkonstruejo","galangan (kapal)"],
["ŝipo","kapal","kapal api","kapal uap"],
["ŝoforejo","kokpit"],
["ŝofori","[kemudi] mengemudikan","[kendara] mengendarai"],
["ŝoforo","sopir"],
["ŝoseo","jalan raya"],
["ŝraŭba ŝtuparo, helica ŝtuparo","tangga spiral"],
["ŝtonceramiko, ŝtonceramikaĵo","periuk belanga"],
["ŝtoneto","kerikil"],
["ŝtoniĝi","batu (diam)membatu"],
["ŝtono","batu"],
["ŝtonoleo","minyak bumi","petroleum"],
["ŝtonĵetilo","katapel"],
["ŝtupara funkcio","fungsi step"],
["ŝtupari","naik tangga"],
["ŝtuparo","tangga"],
["ŝtupetaro","tangga"],
["ŝtupo","anak tangga"],
["ŝultro","bahu","pundak"],
["ŝuo","sepatu"],
["ŝviti","[keringat] berkeringat"],
["ŝvito","keringat"],
["ŭoŭ","waw","wow"],
];
var revo_id_lower = revo_id.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
