// @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&dn=gpl-2.0.txt GPL-v2
// De La Reta Vortaro
'use strict';
var revo_grc = [
["Baktrio","Βακτρία","Βακτριανή"],
["Bizanco"," Βυζάντιον"],
["Demetrio","Δημήτριος"],
["Epifanio","επιφάνεια"],
["Ezopo","Αἴσωπος"],
["Georgo","Γεώργιος"],
["Ksenofono","Ξενοφών"],
["Ksenofonto","Ξενοφών"],
["Parakleto","παράκλητος"],
["Torao","Πεντάτευχος"],
["arkimandrito","αρχιμανδρίτης"],
["asaro","ασσάριον"],
["asketo","ασκητής"],
["dajmono","δαίμων"],
["diablo","διάβολος"],
["diocezo","διοίκησις"],
["dogmo","δόγμα"],
["eklezio","εκκλησία"],
["episkopo","επίσκοπος","αρχιεπίσκοπος"],
["episkopujo","επαρχία"],
["esenco","ουσία"],
["hipostazo","υπόστασις"],
["igumeno","ηγούμενος"],
["katolika","καθολικός"],
["klerikaro","κλήρος"],
["kleriko","κληρικός"],
["lavro","λαύρα"],
["nomado","νομάς"],
["ordinacii","χειροτονέω"],
["ordinacio","χειροτονία"],
["ortodoksa","ορθοδόξος"],
["pastro","ιερεύς"],
["pastromonaĥo","ιερομοναχός"],
["persono","πρόσωπον"],
["presbitero","πρεσβύτερος"],
["relevi","εγείρω"],
["samesenca"," ομοούσιο ς"],
["similesenca"," ομοιούσι ος"],
["testamento","διαθήκη"],
["triunuo","Τριάς"],
["veni","εκπορεύομαι"],
["ĉefpastro","αρχιερεύς","ιεράρχης"],
["ĉefpresbitero","πρωτοπρεσβύτερος","πρωτοπαπάς","πρωθιερεύς"],
["Ĥarono","Χάρων"],
];
var revo_grc_lower = revo_grc.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
// @license-end
