// La Reta Vortaro, GPLv2
'use strict';
var revo_da = [
["Argentino","Argentina"],
["Belgio","Belgien"],
["Brazilo","Brasilien"],
["Bruselo","Bryssel"],
["Estonio","Estland"],
["Francio","Frankrig"],
["Frisio","Frisland"],
["Germanio","Tyskland"],
["Gronlando","Grønland"],
["Hispanio","Spanien"],
["Italio","Italien"],
["Jupitero","Jupiter"],
["Kopenhago","København"],
["Luksemburgio","Luxembourg"],
["Luksemburgo","Luxembourg"],
["Svedio","Sverige"],
["Svisio","Svejts"],
["Urugvajo","Uruguay"],
["adenino","adenin"],
["aftozo","mund- og klovsyge"],
["akromata","akromatisk"],
["albizio","albizia"],
["almanako","almanak"],
["almanaĥo","almanak"],
["ametisto","ametyst"],
["araŭkariacoj","abeskræk-familien"],
["aŭtismo","autisme"],
["belgujo","Belgien"],
["bosono","boson"],
["britujo","Storbritannien"],
["citosolo","cytosol"],
["citozino","cytosin"],
["disidento","systemkritiker"],
["ekliptiko","ekliptika"],
["estero","ester"],
["estonujo","Estland"],
["flerovio","flerovium"],
["foino","husmår"],
["francujo","Frankrig"],
["frislando","Frisland"],
["frisujo","Frisland"],
["germanujo","Tyskland"],
["griledoj","fårekyllingen"],
["haŝio","spisepinde"],
["hispanujo","Spanien"],
["hopludo","hinke-leg"],
["italujo","Italien"],
["kajmano","kaiman"],
["kanuo","kano"],
["katetero","kateter"],
["klimatologio","klimatologi"],
["klonika","klonisk"],
["kometo","komet"],
["kopro","kopra"],
["lizosomo","lysosom"],
["megalito","megalit"],
["mikroklimato","mikroklima"],
["mitozo","mitose"],
["nigra truo","sort hul"],
["nikabo","Nikab","Niqab"],
["paciencludo, paciencoludo","kabale"],
["peptido","peptid"],
["perihelio","perihelion"],
["pino","fyr"],
["poliestero","polyester"],
["prioro","prior"],
["raketo","raket"],
["rakito","engelsk syge","rakitis"],
["retkomerco","Internethandel"],
["sablohordeo","Almindelig Marehalm","marehalm"],
["steradiano","steradian"],
["stupao","stupa"],
["svedujo","Sverige"],
["svislando","Svejts"],
["svisujo","Svejts"],
["timino","thymin"],
["tipio","tipi"],
["tokipono","Tokipono"],
["trafikcirklo","rundkørsel"],
["trafikrondo","rundkørsel"],
["tuniko","tunika"],
["ulmacoj","elme-familien"],
["ulno","alen"],
["vakuolo","vakuole"],
["Ĉilio","Chile"],
["ĉinĉilo","chinchilla"],
];
var revo_da_lower = revo_da.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
