// La Reta Vortaro, GPLv2
'use strict';
var revo_kek = [
["agonii","aakanak"],
["alparoli","aatinank"],
["aŭdado","ab̕iil"],
["aŭdi","ab̕ink"],
["aŭskultanto","ab̕inel"],
["aŭskulti","ab̕ink"],
["baniĝi","achink"],
["dialogi","aatinak"],
["diskurso","aatin"],
["fabo","aaws"],
["fremda","ab̕l"],
["fulgo","ab̕aq"],
["hamako","ab̕"],
["harpi","aarpik, aarpib̕k"],
["harpo","aarp"],
["humida","ach̕toon"],
["interparolejo","aatinob̕aal"],
["komisii","ab̕enank, ab̕enak"],
["komisio","ab̕en"],
["konsulti","aatinank"],
["lasi","ach̕ab̕ank"],
["lingvo","aatin, aatinob̕aal"],
["malluma","aak̕ab̕"],
["mikrofono","aatinob̕aal"],
["ni","aaʼo, haʼo, laaʼo"],
["noktiĝi","aak̕ab̕irk"],
["obei","ab̕ink"],
["opinio","aatin"],
["parolado","aatin"],
["paroli","aatinak, aatinamank"],
["parolisto","aatinanel"],
["parolo","aatin"],
["pendponto, pendoponto","ab̕ q̕a"],
["porparolanto","aatinahom"],
["proparolanto","aatinahom"],
["sekskuniĝi","aatinank"],
["semo","aweel"],
["sodakvo","aaw, kaxlan haʼ"],
["sterko","ab̕oon"],
["stranga","ab̕l"],
["testiko","ab̕aj"],
["tonalo","aatinob̕aal"],
["unu","jun"],
["unua","xb̕een"],
["unue","xb̕eenwa"],
["vorto","aatin"],
];
var revo_kek_lower = revo_kek.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
