// @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&dn=gpl-2.0.txt GPL-v2
// De La Reta Vortaro
'use strict';
var revo_br = [
["Abela","(group) abelian","(group) komutativel","Abel","abelian"],
["Abelo","Abel"],
["Adamo, Adam","Adam"],
["Andreo","Andrev"],
["Antono","Anton"],
["Aristotelo","Aristoteles"],
["Arturo","Arzhur"],
["Arĥimeda","-Arc'himedes"],
["Arĥimedo","Arc'himedes"],
["Aĥilo","Ac'hilles"],
["Bartolomeo","Bertele","Berteleme"],
["Berlinano","Berlinad"],
["Berlino","Berlin"],
["Bernardo","Bernez"],
["Bruselo","Brusel"],
["Cezaro","Kezar"],
["Ekstremoriento","Reter-pellañ"],
["Ernesto","Ernest"],
["Eŭgeno","Ujan"],
["Eŭklida","euklidel","euklidian"],
["Eŭklido","Euklides"],
["Filipo","Fulup"],
["Franciskano","Frañsezad"],
["Francisko","Frañsez","Fañch"],
["Gabrielo","Gabriel","Biel"],
["Georgo","Jord","Jorj"],
["Granda ursino","Kastell-karr-bras","Kastell-karr-kamm","Karr-Arzhur"],
["Henriko","Herri"],
["Hieronimo","Yerom"],
["Horacio","Horas"],
["Internacia labor-Organizaĵo","Aozadur Etrebroadel al Labour"],
["Internacia mona Fonduso","Font Moneizel Etrevroadel","FME"],
["Ivo","Erwan"],
["Jakobo, Jakob","Jalm","Jakez","Jakob"],
["Jesuo","Jezuz"],
["Johanino","Chann"],
["Johano","Yann"],
["Jozefo, Jozef","Jozeb"],
["Kalvaria vojo","Hent ar Groaz","kalvar (skeud.)","kroaz (skeud.)","merzherinti"],
["Kalvario","Kalvar"],
["Karolida","karlingat"],
["Karolido","Karlingad"],
["Karolo","Charlez"],
["Karolo la Granda","Karl-Veur"],
["Kartezia","-Descartes","kartezian"],
["Kartezio","Descartes"],
["Kristoforo","Kristof","Kristol"],
["Latinidaj lingvoj","yezhoù latin","yezhoù romanek"],
["Latino","latin"],
["Londona Akciborso","yalc'h Londrez"],
["Londono","Londrez"],
["Ludoviko","Loeiz"],
["Luko","Lug","Lukaz"],
["Luksemburgio","Luksembourg"],
["Luksemburgo","Luksembourg"],
["Malgranda ursino","Kastell-karr-kamm bihan"],
["Maniko","Mor Breizh"],
["Marko","Mark"],
["Mateo","Mazhev"],
["Mediteranea","kreizdouarel"],
["Mediteraneo","Mor Kreizdouar"],
["Mezmaro","Mor Kreizdouar"],
["Miĥaelo","Mikael"],
["Nederlanda","izelvroat","izelvroeg"],
["Nederlandano","Izelvroad"],
["Nederlando","Izelvroioù","Nederland"],
["Nigra maro","Mor Du"],
["Nikolao","Nikolaz"],
["Norda maro","Mor an Hanternoz"],
["Pentekosto","Pantekost"],
["Pitagora","-Pythagoras","pitagorisian"],
["Pitagoro","Pythagoras"],
["Readmono","Adlezenn"],
["Rejno","Rhin"],
["Renaskiĝo","Azginivelezh"],
["Sankta manĝo","Koan-Fask","Koan diwezhañ"],
["Simono","Simon"],
["Sokrato","Sokrates"],
["Stefano","Stefan"],
["Talesa","-Thales"],
["Taleso","Thales"],
["Tomaso","Tomaz"],
["Unuiĝintaj nacioj","Aozadur ar Broadoù Unanet","ABU"],
["Vergilio","Virgilius"],
["Vilhelmo","Gwilherm","Lom"],
["a-vorto","anv-gwan"],
["abatejo"," abati (menec'h)"],
["abatinejo"," abati (leanezed)"],
["abatino","abadez"],
["abato","abad"],
["abdiki","dilezel e garg a roue","reiñ e zilez"],
["abdiko","dilez","emzilez"],
["abdomeno","abdomen"],
["abelejo","gwenaneg"],
["abelisto","gwenaner"],
["abelo","gwenanenn"],
["abelreĝino","mamm-wenan"],
["abelujo","ruskenn","kestenn"],
["aberacio","aberradenn"],
["abio","saprenn","gwezenn-sapr"],
["abisma","islonkus"],
["abismo","isfont","islonk"],
["abituriento","bachelour (eil derez)"],
["ablativo","tro-lemel","ablativ"],
["aboli","terriñ (ul lezenn)"],
["abolicii","terriñ (ul lezenn)"],
["abomena","heugus","doñjerus"],
["abomeni","heugiñ","doñjeriñ"],
["abomeno","heug","doñjer"],
["aboni","bezañ koumanantet (da)","koumanantiñ (da)","lakaat e anv (e)","en em enskrivañ (e)"],
["abonigi","koumanantiñ (unan bennak)"],
["abonilo","follenn goumantiñ"],
["abono","koumanant"],
["abrikoto","abrikezenn"],
["abrikotujo, abrikotarbo","abrikezenn","gwezenn-abrikez"],
["absceso","gor"],
["absintaĵo","absint"],
["absinto","huelenn-c'hwerv"],
["absoluta valoro","talvoud absolut"],
["acero","gwezenn skav-gwrac'h","skavenn-wrac'h"],
["acida","trenk","put","flemmus","c'hwerv"],
["acido","trenkenn"],
["adiaŭ","сkenavo"],
["adiaŭi","kimiadiñ"],
["adjektivo","anv-gwan"],
["administracio","melestradurezh"],
["administrantaro","melestradurezh (an dud, an ensavadur) "],
["administrejo","melestradurezh (al lec'h)"],
["administri","melestriñ","merañ"],
["admiri","bamañ ouzh","estlammiñ ouzh"],
["admoni","atizañ","broudañ","skandalat","krozal da"],
["admono","atizadur","skandal"],
["adori","azeuliñ","bezañ sod gant"],
["adresanto","kaser"],
["adresaro","karned chomlec'hioù","roll chomlec'hioù"],
["adresato","degemerer"],
["adresi","skrivañ ar chomlec'h","kas"],
["adreso","chomlec'h"],
["adulti","avoultriñ"],
["adverbo","adverb"],
["aera","-aer"],
["aerkastelo, kastelo en aero","kestell el Loar"],
["aero","aer"],
["aerumi","aerañ"],
["aerŝtono","aerolitenn"],
["afabla","hegarat"],
["afekti","ober (an) neuz (da)","stummañ (un dremm)"],
["afero","afer","tra"],
["agaci","tozonañ","hegaziñ"],
["agema","greant","oberiant","abil"],
["agi","ober (v.)","gwerediñ war"],
["agleca","-erer"],
["aglo","erer"],
["ago","ober (ak.)","gwered"],
["agordi","toniañ (sonerezh)","keidañ (sonerezh)","kendoniañ","reizhañ (benvegoù, gwikefreoù) ","kefluniañ"],
["agordilo","tonreizher"],
["agordisto","toniour"],
["agrabla","plijus"],
["ajlo","kignen-gouez","kignen"],
["akacio","kasiaenn","gwezenn-gasia"],
["akaro","preñv ar gal"],
["akceli","buanaat","kas war-raok"],
["akcelilo","buanaer"],
["akcelo","buanadur (fizik)"],
["akcenta, akcentita","pouezmouezhiet","taolmouezhiet"],
["akcenti","pouezmouezhiañ","taolmouezhiañ"],
["akcento","pouez-mouezh","taol-mouezh"],
["akceptejo","degemer (lec'h)"],
["akcepti","degemer (verb)"],
["akcepto","degemer (anv-kadarn)"],
["akcipitro","spalouer","gwazfalc'hun"],
["akiri","akuizitañ","perc'hennañ"],
["aknero","burbuenn","porbolenn"],
["akno","burbu(enn)","burbu"],
["akompanantaro","koskoriad","ambrougadeg"],
["akompananto","kompagnun (a zalc'h kompagnunezh)","kavandad","ambrouger"],
["akompanate de, en akompano de","e-ser (ub.)","e kompagnunezh (ub.)","e kavandenn (ub.)"],
["akompani","delc’her kompagnunezh da [esti]","bezañ gant [esti]","mont gant [iri]","ambroug [iri]","eilañ (sonerezh)","seniñ da heul"],
["akra","lemm","garv (avel, mouezh)","flamm (liv)","garv"],
["akraĵo","barvenn (ul lavnenn)","dremm (ul lavnenn)"],
["akrido","karv-raden","kilhog-raden"],
["akrigi","lemmañ","begañ"],
["akrigilo","higolenn","breolim","maen da lemmañ"],
["aksa","ahelel","-ahel"],
["akselo","kazel"],
["aksingo","bendell","moell"],
["akso","ahel"],
["aktinio","aktiniom"],
["aktiniumo","aktiniom"],
["aktiva","oberiant"],
["aktivo","fred (kontouriezh)","tu-gra"],
["akuzativo","akuzativ","tro-damall"],
["akuzaĵo, akuzo","tamall (ak.)"],
["akuzi","tamall (v.)"],
["akuŝi","gwilioudiñ (v.g.) "],
["akuŝigi","gwilioudiñ (v.k.)"],
["akuŝilo","kregeier (gwilioudiñ)"],
["akuŝistino, akuŝigistino","amiegez"],
["akva","dourek","-dour"],
["akvo","dour"],
["akvofalo","lamm-dour"],
["akvohorloĝo","eurier-dour"],
["akvokoko","duanenn"],
["akvokondukilo","korzenn (da gas dour)","tuellenn (da gas dour)"],
["akvumi","doura [akvoprovizi]","dourañ"],
["alaŭdo","alc'hweder","alc'hweder-sant-Pêr"],
["alciono","diredig"],
["alfabeto","lizherenneg"],
["alfabetumo","levr deskiñ lenn"],
["alilando","arallvro (ak..)"],
["alilandulo","estren (ak.)"],
["alivorte","eleze","da lavaret eo"],
["alko","eln","karv-dour"],
["allasi","degemer","aotren"],
["almenaŭ","da nebeutañ","da vihanañ"],
["almeti","lakaat ouzhpenn","ouzhpennañ"],
["almiksi","entoueziañ"],
["almozdonema","aluzenus"],
["almozdoni","reiñ an aluzen"],
["almozi, almozpeti","goulenn an aluzen"],
["almozisto","klasker-bara","klasker-boued"],
["almozkesto","kef (da zastum an aluzen)"],
["almozo","aluzen"],
["almozulo","klasker-bara","klasker-boued"],
["alno","gwernenn","gwezenn-wern"],
["alnomo, kromnomo","lesanv","moranv"],
["alparoli","komz (ouzh)"],
["altaro","aoter"],
["altmaro","uhelvor"],
["altocentro","ortokreizenn"],
["altvalora","a dalvoudegezh vras"],
["aludi","damvenegiñ"],
["alumeto","alumetezenn","chimikenn"],
["aluminio","aluminiom"],
["amboso","annev"],
["ameli, amelumi","ampezañ"],
["amelo","ampez"],
["americio","amerikiom"],
["amfibioj","amfibienned"],
["amika","karadek"],
["amikeco","karantez (mignoniezh)","keneiliezh","mignoniezh"],
["amikino","keneilez","mignonez"],
["amikiĝi","mignoniñ"],
["amiko","keneil","mignon"],
["amoniako","amoniak"],
["amuza","fentus","diduellus"],
["amuzi","diduañ","diduellañ"],
["amuzilo","c'hoariell"],
["amuzisto","diduer"],
["ananaso","aval-ananaz"],
["ananasujo","avalenn-ananaz","plantenn ananaz"],
["anaso","houad"],
["angilo","silienn"],
["angla","saoz","saoznek [rilate al la lingvo]"],
["anglo","Saoz"],
["anglujo","Bro-Saoz"],
["angulmezurilo","kornventer"],
["ankaŭ","ivez"],
["ankoraŭ","c'hoazh"],
["ankrejo","eorlec'h"],
["ankri","eoriañ","bezañ war eor"],
["ankro","eor"],
["ansero","gwaz (evn)"],
["antaŭbrako","arvrec'h"],
["antaŭhieraŭ","derc'hent-dec'h"],
["antaŭjuĝo","rakvarn"],
["antaŭlasta","eil diwezhañ"],
["antaŭludi","c'hoari (dirak arvesterien)"],
["antaŭludo","rakc'hoari"],
["antaŭmalhelpi","diarbenn"],
["antaŭmanĝaĵo","digor-pred"],
["antaŭmeti","diskouez","kinnig (diskouez)"],
["antaŭnomo","anv bihan","kentanv"],
["antaŭparoli","komz (dirak tud)"],
["antaŭparolo","raklavar","rakskrid"],
["antaŭtagmezo","beure","mintin"],
["antikva","hen-","kozh-kozh"],
["antikvaĵisto","hendraour"],
["antikvaĵo","hendra"],
["antikveco","hended","hender","Henamzer"],
["antimono","stibiom"],
["anunciacio","gouel Maria-Veurzh"],
["anĝelo","ael"],
["apenaŭ","a-boan ma","a-vec'h ma"],
["aperaĵo, apero","gweledigezh"],
["aperi","dont war wel","seblantout","hañvalout","dont er-maez (levrioù) ","en em gavout","steŭziañ","mont diwar wel","mont da get"],
["aplaŭdi","stlakal an daouarn (da)"],
["apogi","skorañ"],
["apogilo","skor"],
["apogseĝo, brakseĝo","kador-vrec'h"],
["aprilo","Ebrel"],
["apro","hoc'h-gouez"],
["araneaĵo","gwiad-kevnid"],
["araneo","kevnidenn"],
["araneuloj","araknided"],
["arbaro","koad (koadeg vihan)","koadeg"],
["arbetaro","brouskoad"],
["arbetaĵo","bod","bodenn"],
["arbeto","brousgwezenn"],
["arbitra","tidel"],
["arbitro","tid"],
["arbo","gwezenn"],
["arbohakisto","koataer"],
["ardeo","kerc'heiz"],
["ardezo","maen-glas"],
["arestado","harzadur"],
["arestejo","toull-bac'h"],
["aresti","herzel (ul laer)"],
["arestito","den harzet"],
["arestiĝo","dalc'h (stad un den harzet)"],
["aresto","harzidigezh"],
["argila","-pri","priek"],
["argilaĵo","priaj"],
["argilo","pri"],
["argono","argon"],
["argumenti","arguzenniñ"],
["argumento","argumant","arguzenn"],
["arkitekto","adeiladour","tisavour"],
["arkitekturisto","adeiladour","tisavour"],
["arkitekturo","adeiladouriezh","tisavouriezh"],
["aro","ar (muzul)"],
["arseno","arsenik (elfenn eeun"],
["artfajraĵo","tan-arvest"],
["artikigi, artiki","koublañ (mellañ)","mellañ (koublañ)"],
["artiko","koubl","mell","kenvell"],
["artikolaro","dastumad (skridoù)","teskad (skridoù)"],
["artikolo","ger-mell"],
["artikuloj, artikpieduloj","artropoded"],
["artiŝoko","artichaodenn","penn-artichaod"],
["artropodo","artropoded"],
["arĉo","gwareg (sonerezh)"],
["arĝenta","arc'hantel"],
["arĝenti","arc'hantañ (goleiñ gant arc'hant)"],
["arĝento","arc'hant"],
["arĥitekto","adeiladour","tisavour"],
["arĥitekturisto","adeiladour","tisavour"],
["arĥitekturo","adeiladouriezh","tisavouriezh"],
["askalono","chalotez"],
["asparago","asperjezenn"],
["aspido","naer-speg"],
["astateno","astat"],
["astato","astat"],
["atendejo","sal-c'hortoz"],
["atendi","gortoz"],
["atenta","war evezh"],
["atenti","teuler evezh","teuler pled"],
["atentigi","sachañ evezh (ub. war udb.)"],
["atento","evezh","pled"],
["avara","pizh (na foran ket)","skragn"],
["avari","bezañ pizh","bezañ skragn"],
["avelo","kraoñenn-gelvez"],
["avelujo","kelvezenn","bod kelvez"],
["aveno","kerc'h"],
["aventurema","avanturus"],
["aventuro","avantur"],
["aventurulo","avanturour"],
["averti","berzañ (lakaat war ziwall)"],
["avida","c'hoantek"],
["avidi","c'hoantaat","kaout c'hoant"],
["avino","mamm-gozh"],
["avizi","kemenn (v.)"],
["avizo","kemennadenn"],
["avo","tad-kozh"],
["azeno","azen"],
["azotacido","trenkenn nitrek"],
["azoto","nitrogen","dinitrogen"],
["aĉetanto","prener"],
["aĉetebla","e gwerzh"],
["aĉeti","prenañ","gouestlaoua"],
["aĉetisto","prenour (a vicher)"],
["aĝa","oadet"],
["aĝi","bezañ oadet a"],
["aĝo","oad"],
["aŭ","pe"],
["aŭda","-klev"],
["aŭdi","klevet"],
["aŭdilo","selaouell"],
["aŭdo","klev","kleved"],
["aŭgusto","Eost (miz)"],
["aŭskultilo","selaouell"],
["aŭtori","sevel (un oberenn)"],
["aŭtoritata","aotrouniek"],
["aŭtoritato","aotrouniezh"],
["aŭtoritatulo, aŭtoritato","pennadurezh"],
["aŭtoro","aozer","oberour"],
["aŭtuno","diskar-amzer"],
["babili","fistilhañ","flapañ","klakenniñ"],
["babordo","babourzh"],
["bagatela","dister"],
["bagatelema","dibarfet"],
["bagateligi","disteraat"],
["bagatelo","bitrak","disterajoù"],
["bajoneto","baionetez"],
["bakalaŭro","bachelour (skol-veur)"],
["bakisto","pober"],
["bakujo","forn"],
["balaaĵo","skubadur","skubien"],
["balai","skubañ"],
["balailo","balaenn","skubellenn"],
["balancoseĝo, lulseĝo","kador-vrañsell"],
["baldaŭ","bremaik","hep dale","dizale"],
["baleno","balum"],
["balisto","bangounell"],
["balo","bal"],
["balustrado","aspled"],
["bambuo","bambouz"],
["banejo","sal-gibellañ","kibelldi"],
["bani","soubañ"],
["baniĝi","kibellañ","kouronkañ"],
["banknoto","bilhed (bank)","bilhed-bank"],
["bankuvo","kibell"],
["bano","kibelladenn","kouronkadenn","kibellad"],
["banto","rozennig (skoulm)"],
["banujo","kibell"],
["bapti","badeziñ"],
["baptingo","maen-badez","maen-font"],
["bapto","badez","badeziant"],
["baptofilo","filhor"],
["baptokuvo","maen-badez","maen-font"],
["baptonomo","anv-badez"],
["baptopatrino","maeronez"],
["baptopatro","paeron"],
["barakti","difretañ, en em zifretañ","diskrapañ"],
["baraĵo","stankell","bardell","fardell"],
["barbhava","barvek"],
["barbiro","perukenner [hararo]","barver [barbo]"],
["barbisto","barver"],
["barblano","marblev"],
["barbo","barv"],
["barbulo","barveg"],
["bardo","barzh (da vare ar gelted kozh)"],
["barelejo","barazherezh","tonellerezh"],
["bareleto","barazhig","barilh","taboulin (un arm, un horolaj)"],
["barelisto","barazher","toneller"],
["bareliĝi","dont da vezañ tev evel ur varrikenn"],
["barelo","barrikenn","tonell"],
["bari","stankañ (un hent)","skoilhañ","mirout ouzh"],
["barilo","draf","kloued"],
["bario","bariom"],
["barita","bonnet (mat.)"],
["baro","skoilh","harz (skoilh)"],
["barometro","barometr"],
["basko","pastell (dilhad)"],
["bastiono","beg-moger"],
["batalejo","aerva","tachenn emgann"],
["batalema","argadus","stourmidik"],
["batali","stourm ouzh","en em gannañ"],
["batalilo","arm"],
["batalisto","brezelour","kadour"],
["batalkampo","aerva","tachenn emgann"],
["batalo","emgann"],
["bedaŭre","gant keuz"],
["bedaŭri","keuziañ","kaout keuz (da)"],
["bedaŭrinda","keuzius","maleürus"],
["bedaŭrinde","siwazh","maleüruzamant"],
["bedaŭro","keuz"],
["bedo","ervenn"],
["beki","begata","pigosat"],
["beko","beg","pigos"],
["bela","brav","kaer"],
["beladono","benede"],
["belaĵo","braventez (tra vrav)"],
["beleco","kened","kaerder","braventez (perzh)"],
["belega","hollgaer","kenedus"],
["beleta","koant","bravik"],
["beligaĵo","kinkladur"],
["belo","kened","brav (ak.)"],
["beni","bennigañ"],
["benko","skaon","bank (skaon)"],
["beno","bennozh"],
["beraro","blokad (hugennoù)"],
["berilio","beriliom"],
["berkelio","berkeliom"],
["bero","hugenn","rezin sec'h [pl.]","rezin [pl.]"],
["besto","loen","aneval"],
["bestoj","rannad al loened"],
["beto","beterabezenn"],
["betulo","bezvenn","gwezenn-vezv"],
["bezona","rekis","ezhommek (traoù)"],
["bezonaĵo","ezhomm"],
["bezoni","kaout ezhomm"],
["bezono","ezhomm","c'hoant"],
["bieno","douar-font","font (douaroù)","glad (douaroù)"],
["biero","bier"],
["bildkarto","kartenn-bost skeudennaouet"],
["bindaĵo","keinadur (ul levr)","koubladur (ul levr)"],
["bindi","keinañ (ul levr)","koublañ (ul levr)"],
["birdo","evn","labous"],
["birdoherbo","brignen-logod","glered"],
["bismuto","bismut"],
["blanka","gwenn"],
["blanketa","arwenn","damwenn"],
["blankigi","gwennañ"],
["blanko","gwenn"],
["blankulo","den gwenn"],
["blato","c'hwil-du","kloreg"],
["bleki","blejal (gant an dud)"],
["blinda","dall (ag.)"],
["blinde","evel un dall"],
["blindeco","dallentez"],
["blindigi","dallañ"],
["blindulo","dall (ak.)"],
["blonda","melen (blev)"],
["blondulino","meleganez"],
["blondulo","melegan"],
["blovaĵo","c'hwezhadenn"],
["bloveksciti","c'hwezhañ (an tan)"],
["blovestingi","c'hwezhañ (ar gouleier)"],
["blovharmoniko","harmonika"],
["blovi","c'hwezhañ"],
["blovilo","megin","c'hwezherez"],
["blua","glas"],
["bluo","glaz (liv)"],
["boao","boa"],
["bobeni","punañ"],
["bobeno","kanell"],
["boji","harzhal"],
["boli","birviñ (v.g.)"],
["boligi","birviñ (v.k.)"],
["bolkruĉo","pod-berver","kitell"],
["bombono","madig"],
["bona","mat","fall"],
["bone","mat"],
["bonigi","foeltrañ","distresañ","gwashaat (v.k.)"],
["bono, bonaĵo","mad","vad"],
["bonulo","den mat"],
["boonklo","eontr-da-heul"],
["bopatrino","mammeg","mamm-gaer"],
["bopatro","tadeg","tad-kaer"],
["borderaĵo","bevenn"],
["borderi","bevenniñ"],
["bordero","bevenn"],
["boro","bor"],
["botelo","boutailh"],
["boteto","botinez"],
["botisto","kere"],
["boto","heuz"],
["bovaĵo","kig bevin","kig saout"],
["bovido","leue"],
["bovino","buoc'h"],
["bovo","bevin (loen-saout)","loen-saout","Tarv (steredeg)"],
["bracelethorloĝo","eurier-brec'h","montr arzorn"],
["braceleto","tro-vrec'h"],
["brakhorloĝo","eurier-brec'h","montr arzorn"],
["brako","brec'h"],
["brakringo","tro-vrec'h"],
["brakumi","briata"],
["bramo","brem","brell"],
["brando","gwin-ardant","lambig","odivi"],
["branko","brenk"],
["brano","brenn"],
["branĉo","barr","brank","skourr"],
["brasiko","kaol(enn)"],
["bromo","brom"],
["bronza","arem"],
["bronzaĵo","aremenn"],
["bronzo","arem"],
["brosi","broustañ"],
["broso","broust"],
["brovo","abrant"],
["brua","trouzus"],
["bruanto","kensonenn divouezh"],
["brui","ober trouz"],
["bruna","rous"],
["brunulino","rouzenn","rouzardez"],
["brunulo","rouz (rouzard)","rouzard"],
["bruo","trouz"],
["brustaĵo","bruched (boued)"],
["brusto","bruched"],
["brutaro","chatal"],
["brutigi","anevalaat"],
["bruto","penn-chatal"],
["bubalo","bual"],
["budo","lochenn","logell","stal (en un diskouezhadeg)"],
["bufedo","taoliad veuzioù"],
["bufo","touseg"],
["bukedo","boked","bokedad"],
["buljono","bouilhoñs"],
["burĝonbrasiko, bruselbrasiko","kaol-Brusel"],
["buterigi","ribotat"],
["butero","amanenn"],
["buterujo","klozenn amanenn"],
["buterumi","amanennañ"],
["buŝa","-genoù","dre gomz","-genoù (soniadoniezh)"],
["buŝego","geol"],
["buŝelo","poezell"],
["buŝharmoniko","harmonika"],
["buŝo","genoù"],
["buŝumo","minwal"],
["caro","tsar"],
["cedro","sedrezenn","gwezenn-sedrez"],
["cejano","glizinenn"],
["celerio","ach(enn)"],
["celulozo","keluloz"],
["cent","kant"],
["centra","-kreiz"],
["centralizi","kreizennañ"],
["centri, centrigi","kreizennañ"],
["centro","kreizenn"],
["cepo","ognon"],
["ceramikaĵo","priaj (traezenn)"],
["ceramikisto","poder"],
["ceramiko","prierezh"],
["cerbaĵo","boued penn"],
["cerbeto","ilpenn"],
["cerbo","empenn"],
["cerbujo","klopenn"],
["cerbumi","en em soñjal","prederiañ (en em soñjal)"],
["ceremonio","lid"],
["cerio","seriom"],
["cervo","karv","karv-erc'h"],
["cezio","seziom"],
["ci","te"],
["cidoniarbo, cidoniujo","avalenn-stoub"],
["cidonio","aval-stoub"],
["cidro","sistr"],
["cifera","niverel"],
["cifereca","niverel"],
["ciferecigi","niverelaat"],
["cifero","sifr"],
["cigana","tsigan"],
["cigano","Tsigan","Jipsian"],
["cigaredo","sigaretenn"],
["cigaringo","doug-segalenn"],
["cigaro","segalenn (da vutunat)"],
["cigarujo","boest segalenn"],
["cigno","alarc'h"],
["cikado","skrilh-wez"],
["cikatriĝi","kleizhennañ"],
["cikatro","kleizhenn"],
["ciklono","kelc'hwidenn"],
["cikonio","c'hwibon"],
["cikoniobeko","geraniom"],
["cikorio","sikorea"],
["cikuto","kegid"],
["cimbalo","simbalenn"],
["cinamo","kanell (keginerezh)"],
["cinamujo","gwezenn-ganell"],
["cindrigi","luduañ"],
["cindro","ludu"],
["cindrujo","ludueg"],
["cindrulino","Luduenn(ig)"],
["cipreso","siprezenn","gwezenn-siprez"],
["ciri","koarañ (lêr)"],
["cirkelo","kelc'hier"],
["cirko","sirk"],
["cirkulero","kelc'hlizher"],
["ciro","koaraj"],
["cirozo","kaletadur (an avu)"],
["citronmeliso","begar"],
["citrono","suraval","sitron"],
["citronujo","suravalenn"],
["civilizado, civilizo","sevenadenn"],
["civilizeco, civilizo","sevenadurezh"],
["civilizi","sevenaat (v.k.)"],
["colo","meutad"],
["daktilarbo, daktilujo","datezenn (gwezenn)"],
["daktilo","datezenn (frouezhenn)"],
["damo","damez (er c'hoari damez)","damez (er c'hoari kartoù) ","rouanez (echedoù)"],
["damoj, damludo","c'hoari damez"],
["dancejo","ti-dañsal","korolldi"],
["danci","dañsal","korolliñ"],
["dancisto","dañser","koroller"],
["danco","dañs","koroll"],
["danka","anaoudek (a ziskouez e anaoudegezh-vat) "],
["danke al, dank' al","a-drugarez da"],
["dankema","anaoudek (a ziskouez e anaoudegezh-vat) "],
["dankemo, dankemeco","anaoudegezh-vat","grad-vat"],
["danki","trugarekaat"],
["danĝera","dañjerus"],
["danĝeri","bezañ dañjerus"],
["danĝero","dañjer"],
["darmŝtatio","darmstadtiom"],
["dati","deiziadañ"],
["dativo","dativ","tro-reiñ"],
["dato","deiziad"],
["datreveno","deiz-ha-bloaz"],
["daturo","aval-spern","mezverez (aval-spern)"],
["daŭra","padus"],
["daŭreco","padusted"],
["daŭri","padout"],
["daŭrigi","lakaat da badout","kendelc'her (v.k.)"],
["daŭro","pad","padelezh"],
["deadmoni","dibennadiñ","dizaliañ"],
["deca","dereat (ag.)"],
["dece","dereat (adv.)"],
["decembro","Kerzu"],
["deci","dereout"],
["dehaki","tennañ (gant ur vouc'hal)"],
["dek","dek"],
["deka","dekvet"],
["deke","da zekvet"],
["deksesuma","c'hwezegel"],
["dekuma","degel"],
["dekuri","redek eus"],
["delasi","tennañ"],
["demamigi","dizonañ"],
["demeti","tennañ"],
["denaska, kunnaskita","enganet"],
["denaskulo","henvroad"],
["dentopasto","toaz-dent"],
["dependa","e-dalc'h","depantus"],
["dependi","bezañ e-dalc'h","bezañ diouzh"],
["des","seul... (eil elfenn)"],
["dimanĉo","Sul","disul"],
["diplomatia noto","notenn diplomatel"],
["diraka mezuro","muzul Dirac"],
["disbranĉiĝi","gaoliañ (gwez)","gaoliñ"],
["discentra, elcentra","eskreizek"],
["discentreco","eskreizegezh"],
["disfadenigi","dineudenniñ"],
["dismembrigi","diemprañ"],
["disperdi","foetañ (foranañ)","foranañ"],
["disprozio","disproziom"],
["domo","ti","tiegezh (lignez)","kêr (annez)","annez"],
["druido","drouiz"],
["du","daou [vira]","div [ina]"],
["dua","eil","daouvet [vira]","divvet [ina]"],
["dua mondmilito","eil brezel-bed"],
["due","da eil"],
["dunombro","niver-daou (yezhadur)"],
["duobla","doubl","daougement"],
["duonjaro","c'hwec'hmiziad"],
["duono","hanter"],
["duonpatrino","lezvamm"],
["duonpatro","leztad"],
["dupiedulo","daoudroadeg"],
["e-vorto","adverb"],
["egalpezo","kempouez (ak.)"],
["ejnstejnio","einsteiniom"],
["ejnŝtejnio","einsteiniom"],
["ekaboni","koumanantiñ"],
["ekrano","skramm"],
["eksmoda","e-maez a c'hiz"],
["eksterdanĝera","barrek (er-maez a zañjer)","er-maez a zañjer"],
["eksterlanda","estren (ag.)","arallvro (ag.)"],
["eksterlandano","estren (ak.)"],
["eksterlando","estrenvro"],
["elaĉeti","dasprenañ"],
["elbalai","skubañ kuit"],
["elcento, elcentaĵo","dregantad"],
["elementa okazo","darvoud elfennel"],
["ellabori","danzen"],
["ellasi","lezel da vont er-maez"],
["elmeti","lakaat war wel"],
["elmigri","divroañ"],
["elmodiĝi, eksmodiĝi","mont e-maez a c'hiz"],
["elnaĝi","diveuziñ"],
["eloviĝi","diglorañ","dinodiñ"],
["elparoli","diatagañ"],
["elperfidi","diskuliañ"],
["elvaporiĝi, forvaporiĝi","aezhennañ (v.k.)","diaezhennañ"],
["enbrakigi","kemer en e zivrec'h"],
["enbuŝaĵo","gweskenn"],
["endanĝerigi","arvariñ (v.k.)","lakaat en dañjer"],
["enlasi","lezel da zont e-barzh"],
["enmanigi","lakaat udb. etre daouarn ub."],
["enmarĉiĝi","sankañ en ur c'heun (v.g.)"],
["enmigri","enbroañ"],
["enmiksi","emellout"],
["erbio","erbiom"],
["esplorvojaĝi","ergerzhet"],
["evitvorto","flourlavar"],
["eŭropio","europiom"],
["fabela","mojennel","marzhus"],
["fabelo","kontadenn","mojenn (kontadenn)","brozenn","bidennoù [pl.]","mojenn (gaou)"],
["fablo","fablenn","mojenn (fablenn)"],
["fabo","favenn"],
["fabrikado","oberiadur"],
["fabrikanto","oberier","farder"],
["fabriki","oberiañ","fardañ (oberiañ)"],
["fabriko","greanti","labouradeg"],
["facila","aes (ag.)","aezet (ag.)"],
["facile","aes (adv.)","aezet (adv.)"],
["faciligi","aesaat (v.k.)"],
["facilpieda","mibin a droad","skañv e c'har"],
["fadenaro","pellenn (neud)"],
["fadenero","neudenn"],
["fadenigi","nezañ"],
["fadeno","neudenn","orjalenn","neudenn-orjal"],
["fago","faouenn","gwezenn-faou"],
["fajenco","feilhañs"],
["fajfi","c'hwitellat","sutal"],
["fajfilego","c'hwitellerez","korn-boud (c'hwitellerez)"],
["fajfilo","c'hwitell","sutell"],
["fajra","entanet"],
["fajraĵo","tan-arvest"],
["fajre","gant entan","gant birvidigezh","gant gred"],
["fajrejo","oaled"],
["fajrero","elf","fulenn (tan)"],
["fajri","flammañ","flammenniñ","flamminañ"],
["fajrigi","tanañ","entanañ","c'hwezhañ (an tan)"],
["fajrilo","direnn"],
["fajro","tan","entan","birvidigezh","gred"],
["fajrujo","oaled"],
["falakvo","lamm-dour"],
["falko","falc'hun"],
["familinomo","anv familh","anv-tiegezh"],
["fanto","lakez (kartenn c'hoari)"],
["februaro","C'hwevrer"],
["fera","dir (db. an dud)","divrall (db. an dud)","strizh (db. an dud)","-houarn","en houarn"],
["feraĵisto","houarnajer"],
["feraĵo","houarn (traezenn)","houarnaj"],
["fereca, ferhava","houarnek"],
["ferlado","tolenn houarn"],
["fermio","fermiom"],
["fero","houarn"],
["ferrubo","kozh-houarn"],
["feŭdulo","gwaz (dindan un aotrou)"],
["fiksbano","stabilaer (luc'hskeudennerezh) "],
["fiŝaglo","erer-spluj"],
["fiŝhaveno","porzh pesketa"],
["fiŝhoki","pesketa (war-bouez un higenn)"],
["flavaj paĝoj","pajennoù melen"],
["flavbekulo","beg-melen"],
["flerovio","fleroviom"],
["florbrasiko","kaol-fleur","kaol-bleŭñv","brikoli"],
["flughaveno","aerborzh"],
["flugludilo","sarpant-nij"],
["fluoro","fluor"],
["forbalai","skubañ kuit"],
["forkuri","redek kuit"],
["forlasi","dilezel"],
["formanĝi","peurzebriñ"],
["formeti","lemel","tennañ"],
["fornomi","dizanzav"],
["forpasi","tremen (mont da get)"],
["forperdiĝi","steuziañ (kuit)"],
["fosforo","fosfor"],
["francio","frañsiom"],
["franciumo","frañsiom"],
["frapharmoniko","zilofon"],
["freŝdata","nevez"],
["frunaskito","krouadur deuet a-raok e amzer"],
["gadolinio","gadoliniom"],
["galiumo","galliom"],
["gaŭsa kurbo, kloŝforma kurbo","krommenn Gauss"],
["genitivo","genitiv","tro-c'henel"],
["gepatro","unan eus ar gerent"],
["gepatroj","kerent (tad ha mamm)","tud (tad ha mamm)"],
["germaniumo","germaniom"],
["gigantomanio","kleñved ar brasterioù"],
["glitbobeno","bulzun"],
["grandaĝa","kozh-tre","er maez a oad"],
["grandnombra","niverus"],
["grandvalora","a dalvoudegezh vras"],
["hafnio","hafniom"],
["hajlero","grizilhenn","kazarc'henn"],
["hajleto, hajlneĝo","milerc'h"],
["hajli","grizilhañ","kazarc'hiñ","ober kazarc'h","kouezhañ ken stank hag ar grizilh"],
["hajlo","grizilh","kazarc'h"],
["hakado","bouc'halerezh"],
["haki","bouc'haliañ"],
["hakilo","bouc'hal","miñserez"],
["hako","taol (bouc'hal)"],
["halebardo","halabardenn"],
["halo","koc'hu","sal veur"],
["hamstro","hamster","razh-segal"],
["hararo","blev","blevenn [bestoj] (hollad blev ar bronneged)","pennad blev","perukenn"],
["harego","reun"],
["haremo","harem"],
["haringo","harink"],
["harligo","plezhenn (blev)"],
["harmoniko","klotadouriezh","harmonika","akordeon"],
["harmoniumo","armolud"],
["haro","blevenn","malgudennoù"],
["haroj","blev kostez ar skouarn"],
["harpi","telennañ"],
["harplektaĵo","plezhenn (blev)"],
["harpo","telenn"],
["harpuni","treantiñ (gant un treant) "],
["harpuno","treant"],
["harstariga, harhirtiga","hirisus"],
["haveno","porzh (mor)","bodenn (repu)","goudor (repu)"],
["haŭtero","kenn (kroc'hen)"],
["haŭto","kroc'hen"],
["hebrea lingvo","hebraeg"],
["hebreo","Hebre","Hebread"],
["hedero","iliav(enn)"],
["hejti","tommañ (ul lojeiz, ur mekanik) "],
["hejtilo","tommerez"],
["hejtisto","paotr an tommerezh"],
["hektaro","hektar"],
["hekto-","hekto-"],
["hektogramo","hektogram(ad)"],
["hektolitro","hektolitr(ad)"],
["hektometro","hektometr(ad)"],
["heliko","maligorn","melc'hwedenn-grogennek"],
["helikoptero","biñsaskell"],
["heliumo","hiliom"],
["helpa","-skoazell"],
["helpanto, helpisto","harper","sikourer","skoazeller"],
["helpema","sikourus"],
["helpi","harpañ","sikour (v.)","skoazellañ"],
["helpi al si","en em zibab"],
["helpo","harp","sikour (ak.)","skoazell"],
["hepataĵo","avu (boued)"],
["hepato","avu"],
["herbaĉo","louzaouenn fall"],
["herbejo","foeneg","geoteg","prad"],
["herbo","geotenn"],
["herbobedo","letonenn","glazenn"],
["hereda","hêrezhel"],
["heredaĵo, heredo","hêrezh","susit"],
["heredi","kaout da hêrezh digant","susitañ"],
["heredigi","legadiñ"],
["herezi","disivoudiñ"],
["herezo","disivoud"],
["herezulo","disivouder"],
["hernio","avelenn"],
["heroaĵo","kur","taol-kaer"],
["heroeco","harozegezh","kadarnded"],
["heroo","haroz"],
["heĝo","garzh"],
["hiacinto","louzaouenn-ar-goukoug","pourenn-vran"],
["hidrargo","merkur"],
["hidrogeno","hidrogen"],
["hieno","bleiz-broc'h"],
["hieraŭ","dec'h"],
["hieraŭo","derc'hent"],
["higiena","yec'hedus"],
["higieno","yec'hedouriezh"],
["hipokrita","pilpous"],
["hipokriti","bezañ pilpous"],
["hipokritulo","pilpouz (den)"],
["hipopotamo","dourvarc'h"],
["hipoteki","arouestlañ"],
["hipoteko","arouestl"],
["hipotenuzo","hipotenuzenn"],
["hirudo","gelaouenn","gwaderez"],
["hirundo","gwennili"],
["hiskiamo","louzaouenn-ar-c'housked","mallc'heot"],
["historia","istorel"],
["historiisto","istorour"],
["historio","istor"],
["histriko","heureuchin-reunek"],
["hobojo","oboell"],
["hodiaŭ","hiziv"],
["hoka","krogek","kromm"],
["hokfadeno, hokŝnuro","linenn (evit pesketa)"],
["hoko","krog"],
["hokstango","bazh-krog","goaf (bazh-krog)"],
["holmio","holmiom"],
["homa","-den","denel"],
["homama","dengarour"],
["homaro","denelezh"],
["homeopatia","homeopatek"],
["homeopatio","homeopatiezh"],
["homevitulo","dengasaour"],
["homido","bugel"],
["homino","maouez"],
["hommanĝulo","debrer-tud"],
["homo","den","mab-den"],
["homonimo","ger heñvelstumm"],
["honesta","onest"],
["honestaĵo","gwirionez"],
["honesto, honesteco","onestiz"],
["honestulo","den onest"],
["honora","enorus","-enor","a enor"],
["honore","gant enor"],
["honori","enoriñ"],
["honoriga","enorus"],
["honorigi","enoriñ"],
["honorinda","enorus"],
["honoro","enor"],
["hontema","mezhek","lent"],
["honti","kaout mezh"],
["hontigi","mezhekaat (v.k.)"],
["hontinda","mezhus"],
["hontindaĵo","mezh"],
["honto","mezh"],
["horaro, horlibro","euriadur"],
["hordeo","heiz"],
["hore","dre eur"],
["horizonto","dremmwel"],
["horloĝisto","horolajer"],
["horloĝo","eurier","horolaj"],
["hormontrilo","biz an eurioù"],
["horo","eur"],
["hortensio","hortensia","kaouled (hortensia)"],
["hortulano","kilheri"],
["hostimontrilo","heolenn (ar sakramant)"],
["hostio","ostiv"],
["hostiujo","kustod (evit an ostivoù)"],
["hotelestro, hotelmastro","letiour"],
["hotelo","leti","otel"],
["hufo","botez (karn)","karn"],
["hufobati","pavata"],
["hufoferi","houarnañ (ur marc'h)"],
["hufofero","houarn-marc'h"],
["hufumo","houarn-marc'h"],
["humero","paler"],
["humila","uvel"],
["humileco","uvelded"],
["humiligi","uvelaat (v.k.)"],
["humiliĝi","uvelaat (v.g.)"],
["humo","humus","rotel"],
["humoro","imor"],
["hunda","-ki"],
["hundherbo","treuzgeotenn"],
["hundo","ki"],
["hungara","hungariat"],
["hungaro","Hungariad"],
["hungarujo","Hungaria"],
["husaro","houzard"],
["ili","int","i"],
["ilia","o (dezho)"],
["ilmaŝino","mekanik-benveg"],
["indio","indiom"],
["infanaĝo","bugaleaj","bugeliezh"],
["insektomanĝuloj","amprevanataerien"],
["interago","etreober (ak.)","etregwered"],
["intermanĝeto","gortozenn"],
["intermiksi","kemmeskañ"],
["internacia","etrebroadel"],
["internaciismo","etrebroadelouriezh"],
["interparoli","kendivizout"],
["interŝanĝvaloro","talvoud eskemm"],
["inversa paro","koublad resiprokel"],
["iridio","iridiom"],
["iterbio","iterbiom"],
["itrio","itriom"],
["januaro","Genver"],
["jarcento","kantved"],
["jarmilo","milved"],
["jaro","bloaz","bloavezh"],
["jasmeno","jesmi"],
["jen","setu","setu amañ"],
["jen...","gwezh... gwezh..."],
["jena","...-mañ"],
["jene","en doare-mañ"],
["jeno","hemañ","homañ","an dra-mañ"],
["jes","ya"],
["jesa","yael"],
["jesi","lavaret ya"],
["jesigi","kadarnaat"],
["jeso","ya (ak.)"],
["jodo","iod"],
["ju","seul... (elfenn 1añ)"],
["juda","yuzev"],
["judismo","yuzevegezh"],
["judo","Yuzev"],
["jugi","bazhyevañ","yevañ","sujañ","lakaat dindan gazel-yev"],
["juglando","kraoñenn (frouezhenn)"],
["juglandujo, juglandarbo","kraoñenn (gwezenn)","gwezenn-graoñ"],
["jugo","yev","suj"],
["juki","debroniñ"],
["juko","debron"],
["julio","Gouere"],
["juna","yaouank","kozh (ag.)"],
["junaĝo","yaouankiz"],
["juneco","yaouankiz"],
["jungi","sterniañ (loened-labour)"],
["jungilaro","stern (loened-labour)"],
["jungitaro","tenn (b.)"],
["junio","Mezheven","Even"],
["junipero","jenevreg"],
["junularo","yaouankiz (an dud yaouank)","yaouankizoù"],
["junulo","yaouankiz (den yaouank)","den yaouank","kozhiad","kozh (ak.)"],
["jupo","brozh"],
["jura","gwirel"],
["juristo","gwiraour"],
["juro","gwir (lezennoù)"],
["juvelejo","bravigerezh"],
["juvelisto","bravigour"],
["juvelo","bravig (brageriz)"],
["juvelujo","skrin"],
["juĝejo","lez-varn (lec'h)"],
["juĝi","barn"],
["juĝisto","barner"],
["juĝo","barnadenn","barnedigezh"],
["juĝokostoj","mizoù (barnedigezh)"],
["kabano","kabanenn","loch","lochenn","log","logenn"],
["kadmio","kadmiom"],
["kafarbo","gwezenn-gafe","kafeenn (gwezenn)"],
["kafejo","kafedi","ti-kafe"],
["kafo","greunenn gafe","kafeenn (greunenn)","kafe","kafe (died)"],
["kafskatolo","boest kafe"],
["kafujo","gwezenn-gafe","kafeenn (gwezenn)","boest kafe"],
["kahela","karrellet"],
["kahelaro","karrelladur"],
["kaheli","karrellañ"],
["kahelo","karrell"],
["kaj","ha (stl. kenur.)"],
["kajero","kaier"],
["kala","kaledet (kroc'hen)"],
["kalcio","kalsiom"],
["kaldronego","kaoter (tommerezh)"],
["kaldrono","kaoter (kegin)","toull (torosennadur)"],
["kalendulo","rozinilenn"],
["kaleŝaĵo","karroñsadur"],
["kaleŝego","karroñs"],
["kaleŝisto","toucher","karroñser"],
["kaleŝo","rederig"],
["kalfatri","kalafetiñ"],
["kalifornio","kaliforniom"],
["kaliforniumo","kaliforniom"],
["kalio","potasiom"],
["kalkano","seul (troad)"],
["kalkansidi","bezañ kluchet","bezañ puchet"],
["kalkanumo","seul (botez)"],
["kalki","razañ (adeilad.)","gwennrazañ"],
["kalko","raz (danvez)"],
["kalko estingita","raz distan"],
["kalko kaŭstika","raz bev"],
["kalkoŝtono","maen-raz"],
["kalkumi","razañ (gounez.)"],
["kalo","kaledenn (kroc'hen)"],
["kalva","moal"],
["kambio","lizher-eskemm"],
["kamelo","kañval"],
["kameno","oaled"],
["kamenskrapisto","skarzher-siminalioù"],
["kamforarbo, kamforujo","gwezenn-gañfr"],
["kamforo","kañfr"],
["kamomilo","kramamailh"],
["kamplaboristo","devezhour","mevel (labour-douar)"],
["kanabo","kanab"],
["kanapo","gourvezvank"],
["kankro","grilh-dour","Krank (steredeg ar C'h.)"],
["kano","korzenn (plant)","bazh","gwialenn"],
["kantarido","c'hwil-glas"],
["kanzono","kanaouenn"],
["kapitano","kabiten"],
["kapjesi","lavaret ya gant ar penn"],
["kapkuseno","goubenner","treuzplueg"],
["kapono","kabon","spazhard"],
["kapopieduloj","penntroadeged"],
["kaporo","kaprezenn","gwezenn-gaprez"],
["kapreolo","yourc'h"],
["kaprimulgo","adren"],
["kapro","bouc'h","gavr"],
["kapuceno","kabusin (lean)"],
["karabeno","karabinenn"],
["karbeto","glaou bev","glaou tan"],
["karbkrajono","glaouenn-dresañ"],
["karbo","glaou"],
["karbono","karbon"],
["kardelo","pabor (evn)"],
["kardo","askolenn"],
["karesa","chourus","flourus"],
["karesi","chourañ (flourañ)","flourañ"],
["kareso","allazig","chouradenn","flouradenn"],
["kariofilo","tach-jenofl"],
["kariofilujo","gwezenn-jenofl","jenoflenn"],
["karmino","ruz-tane"],
["karnavalo","Ened","Meurlarjez"],
["karoo","karo"],
["karoserio","karroñsadur"],
["karoto","karotezenn"],
["karpeno","faouenn-but","gwezenn-faou-put"],
["karpo","karpenn"],
["kartaro","c'hoari gartoù"],
["kartezia ovalo","ovalenn Descartes"],
["kartludi","c'hoari kartoù","c'hoari ar c'hartoù"],
["kartludo","c'hoari gartoù"],
["karto","kartenn"],
["kartono","karton"],
["karuselo","kazeg-vezevenn"],
["kaserolo","kastelodenn"],
["kasko","tokarn"],
["kastelo","kastell"],
["kastoro","avank"],
["kastri","spazhañ"],
["kata","-kazh"],
["katedralo","iliz-veur"],
["katido, katidino","kazhig"],
["katino","kazhez"],
["kato","kazh"],
["kavalira","-marc'heg"],
["kavalireca","-marc'heg"],
["kavalireco","marc'hegiezh"],
["kavaliro","marc'heg"],
["kaverna","kleuz"],
["kaverno","kev (mougev)","mougev","kleuzadenn (kleñved)"],
["kaviaro","kaviar"],
["kazeigaĵo","tro (evit lakaat al laezh da gaoulediñ)"],
["kazeiĝi","kaoulediñ (laezh)"],
["kazeo","kaouledenn (laezh)"],
["kazerno","kazarn"],
["kazino","kazino"],
["kazo","troad (yezhon.)","degouezh (tro)","plegenn","tro (degouezh)"],
["kaĝo","kaoued"],
["kaŝe","e koach","e kuzh","dre goach","dre guzh"],
["kaŝejo","koach","kuzhiadell","toull-kuzh"],
["kaŝema","kuzhmuzik","kuzhuter"],
["kaŝi","koach (v.)","kuzhat","skoachañ"],
["kaŝludo","koach-koukoug"],
["kaŝnomo","anv-pluenn"],
["kaŝtana, kaŝtankolora","gell-kistin"],
["kaŝtanarbo, kaŝtanujo","gwezenn-gistin","kistinenn (gwezenn)"],
["kaŝtano","kistinenn (frouezhenn)","kistinenn-Indez (frouezhenn)"],
["kaŭze de","abalamour da","en abeg da","en arbenn (a, da, eus)"],
["kaŭzeco","arbennelezh"],
["kaŭzi","bezañ abeg (da)","bezañ kaoz (da)"],
["kaŭzo","abeg","arbenn (abeg)","kaoz (abeg)","pennabeg","pennkaoz"],
["keglaro","c'hoari gilhoù"],
["keglo","kilh"],
["kejli","ibiliañ"],
["kejlo","ibil"],
["kekso","gwispidenn"],
["kelisto","paotr ar c'hav"],
["kelnero","mevel (an ostaleri)"],
["kelo","kav","kaviad"],
["kemio","kimiezh"],
["keno","koad rousinek"],
["kepleraj leĝoj","lezennoù Kepler"],
["kero","keur"],
["kerubo","kerubin","kaezhig Doue"],
["kesto","kased","arc'hig","tiretenn"],
["kilo","kein (ar vag)"],
["kloro, ĥloro","klor"],
["kluzo","skluz"],
["knabino","plac'h"],
["knabo","paotr"],
["knedi","merat"],
["knedujo","laouer-doaz","nev-doaz","toazeg"],
["koakso","glaou-kok"],
["kobalto","kobalt"],
["koboldo","boudig","kornandon","korrigan","nozegan"],
["kojnforma skribo","skritur gennheñvel"],
["kojno","genn"],
["kokcinelo","buoc'h-Doue","c'hwilig-Doue","yarig-Doue"],
["kokido, kokidino","poñsin"],
["kokino","yar"],
["kokluŝo","drev (kleñved)","paz-yud"],
["koko","kilhog","kog"],
["kokosarbo","gwezenn-gokoz","kokozenn (gwezenn)"],
["kokoso","kokozenn (kraoñenn)","kraoñenn-gokoz"],
["kokso","lez (kroazell)","kroazell (lez)"],
["kolbaso","silzigenn"],
["kolhararo, haroj","moue"],
["kolorigi","livañ"],
["koloristo","liver"],
["koloro","liv"],
["kondukpermesilo, stirpermesilo","aotre-bleniañ"],
["kontraŭbatali","stourm","enebiñ","talañ"],
["kontraŭjudismo","enepyuzevouriezh"],
["kontraŭleĝa","enep al lezenn"],
["kontraŭparoli","dislavaret"],
["kontraŭpezi","kempouezañ"],
["kontraŭpezo","eneppouez"],
["koordinata akso, koordinatakso","ahel daveennoù","ahel kenurzhiennoù"],
["kopernicio","kopernisiom"],
["kornbruto","chatal-korn"],
["koĉenilo","tane","taneenn"],
["krajono","kreion"],
["kreditkarto","kartenn-gred"],
["krespo","krampouezhenn"],
["kriptono","kripton"],
["kromio","krom"],
["kromo, ĥromo","krom"],
["krucbekulo","beg-kroaz"],
["krucmilito, krucmilitiro","brezel ar Groaz","kroaziadeg"],
["ksenono","ksenon"],
["kuba metro","metr-kub"],
["kudromaŝino","gwrierez","mekanik gwriat"],
["kuirmaŝino","fornigell"],
["kukolo","koukoug"],
["kunagi","kenober (v.)","kenlabourat"],
["kunaŭtoro","kenoberour"],
["kunbekiĝi","en em vegata"],
["kuniklo","konikl [sovaĝa]","lapin [malsovaĝa]"],
["kunlabori","kenlabourat"],
["kunlaboro","kenlabour"],
["kunmeti","bodañ","kenstrollañ"],
["kunmezurebla","kenvuzuliadus"],
["kunokazeco","kendegouezh"],
["kunparolanto","kendivizer"],
["kupo","mandoz (kloc'hig gwer)"],
["kupolo","bolzenn"],
["kupra","kouevr","kouevrek"],
["kupri","kouevrañ"],
["kupristo","kouevrour"],
["kupro","kouevr"],
["kuproepoko","oadvezh an arem"],
["kuratoreco","kulaterezh"],
["kuratoro","kulator"],
["kuraĝa","kalonek"],
["kuraĝi","kalonekaat (v.g.)"],
["kuraĝigi","kalonekaat (v.k.)"],
["kuraĝo","kalon (nerzh-kalon)","nerzh-kalon"],
["kurba","kromm"],
["kurbeco","krommder"],
["kurbecocentro","kreizenn krommder"],
["kurbigi","krommañ"],
["kurbiĝo","krommell (pezh kromm)"],
["kurbo","krommenn (linenn gromm)"],
["kuri","redek"],
["kuriero","poster (a gas lizheroù, pakadoù)","furlukin (echedoù)"],
["kurigi","lakaat da redek"],
["kuriumo","kuriom"],
["kuro","red","redadenn"],
["kurteno","gouel (stign)","rideoz","stign","tenneris"],
["kuseno","torchenn"],
["kusentego, kusentegilo","toagenn"],
["kuvo","barazh"],
["kuzino","keniterv"],
["kuzo","kenderv"],
["kvadrata metro","metr-karrez"],
["kvar","pevar [vira]","peder [ina]"],
["kvara","pevare (ag.)","pevarvet [vira]","pedervet [ina]"],
["kvarangula","pevarc'hornek"],
["kvare","da bevare"],
["kvaronjara","trimiziek"],
["kvarono","kard","pevarvedenn","pevarvenn","palefarzh"],
["kvarpiedulo","pevarzroadeg"],
["kvazaŭvokalo, duonvokalo","hantervogalenn"],
["kvin","pemp"],
["kvina","pempvet","pempet"],
["kvine","da bempvet"],
["kvinono","pempvedenn"],
["kvitanci","kuitezañ"],
["kvitanco","kuitañs"],
["la","al","an","ar"],
["labirinto","milendall"],
["laborabelo","labourerez (gwenanenn)"],
["labordonanto","goprer","implijer"],
["laborema","labourus (tud)","oberiant"],
["laborestro","mestr-micherour"],
["labori","labourat"],
["laboristo, laborulo","labourer","micherour"],
["laborkapabla","barrek da labourat"],
["laborloko","lec'h labour"],
["laboro","labour"],
["laca","skuizh"],
["lacerto","glazard"],
["lacigi","skuizhañ (v.k.)"],
["laciĝi","skuizhañ (v.g.)"],
["lafo","lava","maen-teuz"],
["lago","lenn (dour)"],
["laguno","loc'h (lenn)"],
["lakeo","lakez"],
["laki","lakennañ"],
["lako","lakenn"],
["laksi","foerañ"],
["lakso","foerell"],
["lakta Vojo","Hent Sant-Jakez"],
["lakteca, lakta","laezhek"],
["lakti","reiñ laezh"],
["lakto","laezh"],
["laktozo","laktoz"],
["laktuko","letuzenn"],
["laktumo","laezhenn"],
["lama","kamm (ag.)","jilgamm (ag.)"],
["lamao","lama (manac'h)"],
["lami","kammañ (v.g.)","jilgammañ","mont a-dreuz"],
["lampo","lamp"],
["lamulo","kamm (ak.)","jilgamm (ak.)"],
["landano","broad (annezad)","broadour"],
["lando","bro"],
["langeto","pempilh (stlenn.)"],
["lango","teod"],
["langtrinki","lapañ"],
["lano","gloan"],
["lantano","lantan"],
["lanterno","letern"],
["lanugo","marbluñv","marblev"],
["lardi","larjezañ"],
["lardo","larjez"],
["laringo","garloc'henn"],
["larmi","daeraouiñ","gouelañ"],
["larmo","daerenn"],
["larvo","larvenn"],
["larĝa","ledan"],
["larĝeco","ledander"],
["larĝo","led","ledander"],
["lasi","lezel","leuskel"],
["lasta","diwezhañ"],
["lavi","gwalc'hiñ","kannañ (vestaĵo)","skaotañ (teleroj, ktp)"],
["lavkuvo","gwalc'heris"],
["lavmaŝino","kannerez (ardivink)"],
["laĉi","lasañ"],
["laĉo","las"],
["laŭbo","pratell (el liorzhoù)"],
["laŭdi","meuliñ"],
["laŭdinda","meulus"],
["laŭkuri","redek a-hed"],
["laŭleĝa","hervez al lezenn"],
["laŭmezura","diouzh muzul"],
["laŭpeze","diouzh ar pouez"],
["laŭrencio","laorensiom"],
["laŭro","loreenn","gwezenn-lore"],
["laŭroj","lore","gwez-lore"],
["laŭrokrono","kurunenn lore"],
["laŭta","trouzus","kreñv (mouezh, trouz)","uhel (mouezh, trouz)"],
["laŭtakcento","skiltr-mouezh"],
["laŭtilo, laŭtparolilo","uhelgomzer"],
["laŭvorte","ger-ha-ger"],
["lebega mezuro","muzul Lebesgue"],
["leciono","kentel"],
["ledo","lêr"],
["legendo","mojenn"],
["legi","lenn"],
["legilo","lennerez (benveg)"],
["lego","lennadenn"],
["legomo","legumaj (pl.)"],
["leki","lipat"],
["leksikono","geriaoueg"],
["lento","fer (plant)"],
["leonfaŭko","geol-bleiz"],
["leono","leon","Leon"],
["leontodo","c'hwervizon [pl.]"],
["leopardo","loupard"],
["leporhundo","levran"],
["leporo","gad"],
["lepro","lovrnez"],
["lernejo","skol"],
["lerni","deskiñ","deskiñ da vat"],
["lernigi","kelenn"],
["lernoservo","staj (en un embregerezh)"],
["leterkesto","boest-lizheroù (prevez)"],
["leĝa","lezennel"],
["leĝaro","lezennaoueg"],
["leĝigi","reiñ lezennoù da","lezennekaat"],
["leĝisto","gwiraour","lezennour"],
["leĝo","lezenn"],
["leĝoscienco","gwir (skiant)"],
["leŭtenanto","letanant"],
["li","eñ"],
["lia","e (dezhañ)"],
["libelo","nadoz-aer"],
["libro, instrulibro","levr-skol","dornlevr"],
["liceano","lisead"],
["licencio","aotreegezh"],
["licenciulo","aotreeg"],
["liceo","lise"],
["lieno","felc'h"],
["lifto","pignerez"],
["lignokarbo","glaou-koad"],
["lignolaboristo","koadour","koataer"],
["lignonajlo","ibil"],
["lilio","lilienn"],
["lineare dependa","depantus ent-linennel"],
["lineare nedependa, lineare sendependa","dizepant ent-linennel"],
["liphararo, haroj","mourroù"],
["litio","litiom"],
["livermorumo","livermoriom"],
["lojala","leal"],
["lojaleco","lealded"],
["lokomotivo","stlejerez (tren)"],
["lolo","dreog(enn)"],
["longdaŭra, longedaŭra","hirbad"],
["lonicero","gwezvoudenn"],
["lorno","lunedenn"],
["ludi","c'hoari (v.)"],
["ludilo","c'hoariell"],
["ludkarto","kartenn-c'hoari"],
["ludo","c'hoari (ak.)"],
["lui","feurmiñ (kemer e feurm)"],
["luigi","feurmiñ (lezel e feurm)"],
["luli","luskellañ"],
["lulilo","kavell (gwele)"],
["lulkanto","luskellerez"],
["luna","-loar"],
["lunarko","loargresk"],
["lundaŭro, lunperiodo","loariad"],
["lundo","Lun","dilun"],
["luno","loar","loarenn"],
["lupo","bleiz"],
["lupolo","houpez(enn)"],
["lustro","kantolor-skourr"],
["lutecio","lutesiom"],
["luti","soudañ"],
["lutro","dourgi","ki-dour"],
["maco","bara kann","bara panenn"],
["madono","Itron Varia"],
["magazenego","gourstal"],
["magazeno","ti-dastum","stal","gourstal"],
["magia","hud (ag.)","strobinellus"],
["magiaĵo","strobinell","tro-hud"],
["magiisto","hudour","strobineller"],
["magio","hudouriezh","strobinellerezh"],
["magnezio","magneziom"],
["mahagono","akajou"],
["maizo","maiz"],
["majesta","meurdezus"],
["majesto","meurdez"],
["majfloro","louzaouenn-an-hañv"],
["majo","Mae"],
["majoro","komandant (ofiser)"],
["majstraĵo, majstroverko","pennoberenn"],
["majstro","mestr (mailh)"],
["makarono","morlukenn"],
["maksimo","krennlavar"],
["makuli","tarchañ"],
["makulo","tarch"],
["makzelo","javed","karvan"],
["malaboni","digoumantiñ"],
["malagrabla","displijus"],
["malakito","malakit"],
["malaltmaro","izelvor"],
["malamiko","enebour"],
["malario","malaria"],
["malavara","brokus"],
["malbela","divalav"],
["malbeni","milligañ","mallozhiñ"],
["malblindigi","dizallañ (v.k.)"],
["malblindiĝi","dizallañ (v.g.)"],
["malbonavida","mennet fall"],
["maldaŭra, nedaŭra","berrbad","dibad"],
["maleolo","ibil-troad","ufern"],
["malfacila","diaes"],
["malfacilaĵo","diaester","diaezamant"],
["malfaciligi","diaesaat (v.k.)"],
["malgraŭ","daoust da"],
["malgraŭ ke","bezañ ma","daoust ma","evit da"],
["malgraŭe","evelato","evelkent","neoazh"],
["malhelpi","skoilhañ"],
["malhelpo","skoilh"],
["malhonestaĵo","dizonestiz (ober)"],
["malhonesto, malhonesteco","dizonestiz (perzh)"],
["malhonora","dizenorus"],
["malhonori, senhonorigi","dizenoriñ"],
["malhumila","balc'h","lorc'hus"],
["maljuneco","kozhni"],
["maljuniĝi","koshaat"],
["malkaresi","gwallgas"],
["malkaŝa","diguzh"],
["malkaŝi","diguzhañ","diskoachañ","diskuliañ"],
["malkaŝo","diskuliadur"],
["malkuraĝa","aonik","digalon (aonik, hep nerzh)"],
["malkuraĝo","aon","digalon (ak.)"],
["mallaborema","didalvez (tud)","lezirek"],
["mallakso","kaleter (ar c'horf)"],
["mallarĝa","enk","strizh"],
["mallaŭdi","kareziñ","rebech"],
["mallaŭdinda","diveulus"],
["mallaŭta","didrouz","izel (mouezh, trouz)"],
["mallojala","disleal"],
["malmanka","fonnus (stank)","stank (fonnus)"],
["malmiksi","diluziañ","diveskañ"],
["malmiopa","hirwel"],
["malmola","kalet"],
["malmolnuka, rigidnuka","dibleg"],
["malnova","kozh (n'eo ket nevez)"],
["malnova mondo","Bed Kozh"],
["malofta","ral (ag.)"],
["maloftaĵo","ralete"],
["malofte","ral (adv.)","ral a wezh"],
["malpacienca","dibasiant"],
["malpermesi","berzañ","difenn (berzañ)","mirout (berzañ)"],
["malpeza","skañv"],
["malpezigi, senpezigi","divec'hiañ","skañvaat (v.k.)"],
["malpia","dizeol"],
["malpiaĵo","taol disakr"],
["malpieco","dizeoliezh"],
["malto","malt"],
["malvarma","yen","difrom"],
["malvarma milito","brezel yen"],
["malvarmego","yenijenn kriz"],
["malvarmeta","fresk"],
["malvarmigi","yenaat (v.k.)"],
["malvarmo","yenijenn","yended"],
["malvo","malvenn(bleunienn)"],
["mambestoj","bronneged"],
["mameto","beg ar vronn"],
["mamnutri","bronnañ"],
["mamo","bronn"],
["mampinto","beg ar vronn"],
["mamsuĉi","denañ"],
["mamuloj","bronneged"],
["mamuto","mammout"],
["mamzono","brennidenn"],
["manao","mann (boued)"],
["manartiko","arzorn"],
["mandareno","mandarin (den)"],
["mandolino","mandolinenn"],
["mandorso","kil an dorn"],
["manen, man-en-","dorn-ha-dorn gant"],
["mangano","manganez"],
["manifestacio","manifestadeg"],
["maniko","milgin"],
["manio","mania","albac'henn"],
["manipuli","embreger"],
["manke de","dre ziouer a"],
["manki","mankout","ober diouer"],
["manko","diouer","mank"],
["manlaboro","labour dorn"],
["mano","dorn"],
["manometro","manometr"],
["manpleno","dornad"],
["manradiko","arzorn"],
["mansardo","mañsardenn"],
["mansupro","kil an dorn"],
["manufakturo","labouradeg"],
["manumo","berrvañch"],
["manuskripto","dornskrid"],
["manuzi","dornata (embreger)","embreger (gant an daouarn)"],
["manĝaĵo","boued"],
["manĝegi","alfiñ","plaouiañ"],
["manĝeti","krignat (debriñ nebeut)"],
["manĝi","debriñ","dijuniñ (v.)","leinañ","merennañ (v.g.)","koaniañ"],
["manĝigi","lakaat da zebriñ","boueta","magañ"],
["manĝilaro","stalioù (evit debriñ)"],
["manĝo","pred","pred-boued","boued"],
["manĝokarto","roll-meuzioù"],
["manĝometo","meuz"],
["maparo","atlas"],
["mapo","kartenn"],
["mardo","Meurzh (deiz)","dimeurzh"],
["margarino","margarin"],
["marhaveno","porzh-mor"],
["marini","lakaat en hili"],
["marioneto","margodenn"],
["mariskarabo","buoc'h-Doue","c'hwilig-Doue","yarig-Doue"],
["marki","merkañ"],
["markizo","markiz"],
["marko","merk","mark"],
["marmoro","marmor"],
["maro","mor"],
["marokeno","gavrgen"],
["marteli","morzholat"],
["martelo","morzhol"],
["martirigi","merzheriañ"],
["martiro","merzher"],
["marto","Meurzh (miz)"],
["marĉandado","marc'hatadenn"],
["marĉandi","marc'hata"],
["marĉo","geun","lagenn (skeud.)"],
["marŝalo","marichal"],
["marŝi","bale (v.)"],
["marŝo","bale (ak.)","ton-bale"],
["masaĝi","merata"],
["masaĝo","meratadenn"],
["masiva","tolzennek"],
["masivo, masivaĵo","tolzenn"],
["maski","masklañ"],
["masko","maskl"],
["maso","mas"],
["masoni","mañsonat"],
["mastiki","mastikañ"],
["mastiko","mastik"],
["masto","gwern (ur vag)"],
["mastri","bezañ mestr (war)","mestroniañ"],
["mastro","mestr"],
["mastruma sistemo","sistem oberiañ"],
["matadoro","matador"],
["matematikisto","matematikour"],
["matematiko","matematik"],
["matenmanĝo","dijuniñ (ak.)","lein (pred)"],
["mateno","beure","mintin"],
["matenruĝo","gouloù-deiz","tarzh-deiz"],
["matraco","matarasenn"],
["matura","azv","darev"],
["matureco","azvder","darevder"],
["maturiĝi","azviñ","dareviñ"],
["mazurko","mazurka"],
["maĉi","chaokat"],
["maŝaro","rouedad"],
["maŝine","ent-mekanikel","evel ur mekanik"],
["maŝinejo","sal an ardivinkoù"],
["maŝinisto","ardivinker","mekaniker"],
["maŝino","ardivink","ijinenn","mekanik"],
["maŝkiraso","sae mailhet"],
["maŝo","mailh (neud)"],
["maŭzoleo","mozoleon"],
["medalo","medalenn"],
["medicina","medisinel","mezegel"],
["medicinaĵo","louzaouadur"],
["medicinisto","medisin","mezeg"],
["medicino","medisinerezh","mezegiezh"],
["medikamento","louzoù (apotikerezh)"],
["medio","endro"],
["mediumo","mediom"],
["medolo","mel(-askorn,...)"],
["meduzo","morgaoulenn","Meduza"],
["megalito","meurvaen"],
["mejlo","miltir"],
["melankolia","melkonius"],
["melankolio","melkoni"],
["melaso","triakl"],
["meleagro","kilhog-Indez (virsekso)","yar-Indez (insekso)"],
["melhundo","ki-douar"],
["melki","goro"],
["melo","broc'h (loen)"],
["melono","sukrinenn","aval-sukrin","sukrinenn-dour"],
["membrano","koc'henn","diafragm"],
["membro","ezel","mempr"],
["mencii","menegiñ","ober meneg eus"],
["menciinda","da vezañ meneget"],
["mencio","meneg"],
["mendelevio","mendeleviom"],
["menhiro","maen-hir","peulvan"],
["mensogema","gaouiat"],
["mensogi","gaouiadiñ","kontañ gevier"],
["mensogo","gaou"],
["mensogulo","gaouiad","gaouier"],
["mento","bent"],
["mentono","elgezh","chik (elgezh)","groñch"],
["merkredo","Merc'her","dimerc'her"],
["merlo","moualc'h"],
["mesio","Mesiaz"],
["meso","oferenn"],
["metalo","metal"],
["meti","lakaat"],
["metiejo","labouradeg"],
["metiisto","artizan","dornwezhour"],
["metio","micher dorn"],
["metro","metr"],
["metro en kvadrata sekundo","metr dre eilenn-garrez"],
["metro en sekundo","metr dre eilenn"],
["mevo","gouelan"],
["meza","-kreiz","krenn"],
["mezaĝa","etre daou oad"],
["meze de, meze en","e-kreiz"],
["mezepoko","krennamzer"],
["meznombro, mezonombro","keidenn"],
["mezo","kreiz"],
["mezurateco","habaskter"],
["mezurebla","muzuliadus"],
["mezuri","mentañ","muzuliañ"],
["mezurilo","menter (benveg)","muzulier (benveg)"],
["mezuro","ment","muzul"],
["mezurunuo","unanenn vuzuliañ"],
["meĉo","poulc'henn"],
["mi","me"],
["mielo","mel"],
["migdalarbo, migdalujo","alamandezenn (gwezenn)","gwezenn-alamandez"],
["migdalo","alamandezenn (frouezhenn)"],
["migri","divroañ [homoj]","tremen-distremen [birdoj]"],
["miksa","mesket"],
["miksaĵo","meskad"],
["miksi","meskañ"],
["miksiĝi","en em veskañ"],
["mil","mil"],
["milio","mell (plant)"],
["miliono","milion"],
["milionulo","milioner"],
["milita","-brezel","brezelel"],
["militakiri","aloubiñ"],
["militakiro","preizh","preizhadur"],
["militestro","penn-brezel"],
["militi","brezelekaat","brezeliñ","gounit"],
["militistaro","arme"],
["militisto","brezelour","kadour"],
["milito","brezel"],
["minaci","gourdrouz (v.)"],
["minaco","gourdrouz (ak.)"],
["minaĵo","kailh"],
["minejo","min"],
["mini","minañ"],
["mino","min"],
["minuto","munut","munutenn"],
["miopa","berrwel"],
["miozoto","daoulagad-ar-Werc'hez"],
["mirho","mir (gom-rousin)"],
["mirtelo","lusenn"],
["misagorda","didoniet"],
["misiisto","misioner"],
["misio","mision"],
["mitulo","mesklenn"],
["mizera","ezhommek","reuzeudik","tavantek"],
["mizeri","bezañ en dienez","mizeriñ"],
["mizeriĝi","kouezhañ an dienez war ub.","mont da reuzeudig"],
["mizero","dienez","mizer (reuzeudigezh)","reuzeudigezh"],
["mizerulo","ezhommeg","reuzeudig","tavanteg"],
["moda","diouzh ar c'hiz"],
["modistino","kabellerez"],
["modlopasto, knedpasto","toaz-merat"],
["modo","giz","doare (yezhadur)"],
["moka","goapaus"],
["mokanto","goapaer"],
["moketi","añjinañ"],
["moki","goapaat","ober goap","ober al lu gant ub."],
["mokinda","lu (ag.)"],
["moko","goapadenn"],
["mola","blot","bouk","gwak","glebiet (soniadoniezh)"],
["molanaso","eider"],
["molibdeno","molibden"],
["moligi","boukaat","gwakaat"],
["molmatura","pezhell"],
["mona","-arc'hant","moneizel"],
["mona subunuo","isunanenn voneiz"],
["monarĥismo","unpenniezh"],
["monarĥisto","unpennelour"],
["monarĥo","unpenn"],
["monata","miziek"],
["monataĵo","amzerioù (mizioù)","mizioù (amzerioù)"],
["monato","miz"],
["monaĥejestro","superior"],
["monaĥejo","manati","kouent (leaned)","leandi (leaned)"],
["monaĥinejo","kouent (leanezed)","leandi (leanezed)"],
["monaĥino","leanez"],
["monaĥismo","manac'hegezh"],
["monaĥo","manac'h","lean"],
["monda","-bed","bedel","hollvedel"],
["mondaĝo","oadvezh"],
["mondmilito","brezel-bed"],
["mondo","bed"],
["mondoparto","rannved"],
["monedo","kavan-tour"],
["monereto","moneiz bihan"],
["monero","pezh moneiz"],
["monfalsisto","falsvoneizer"],
["monkesto","kef (moneiz)"],
["mono","arc'hant","moneiz"],
["monpaperujo","doug-paperioù"],
["monpuno","tell-gastiz"],
["monujo","doug-moneiz"],
["monunuo","unanenn voneiz"],
["morgaŭ","warc'hoazh"],
["morgaŭo","tronoz","deiz war-lerc'h"],
["moŝto","Meurdez (titl a zoujañs)","Uhelded (titl a zoujañs)"],
["multenombro, plurnombro","liester"],
["multepeza","pounner"],
["multhoma, multehoma","poblek"],
["multnombra, multenombra","niverus"],
["multvalora, multevalora","talvoudus-bras"],
["nacia","broadel"],
["naciano","broad (den)","broadour"],
["naciaĵo","dibarder broadel"],
["nacieco","broadelezh"],
["naciismo","broadelouriezh"],
["naciisto","broadelour"],
["nacio","broad"],
["nadlo","nadoz (nemet evit gwiat)"],
["naftalino","naftalin"],
["najbara","amezek"],
["najbaraĵo","amezegezh","amezegiezh"],
["najbare de","en amen da","en amen ouzh","en amezegiezh"],
["najbaro","amezeg"],
["najli","tachañ"],
["najlo","tach"],
["najtingalo","eostig"],
["nano","korr"],
["napo","irvinenn"],
["narciso","rozenn-gamm"],
["naskema","gouennus","sperius"],
["naski","genel"],
["naskigi","engehentañ"],
["naskiĝi","bezañ ganet"],
["naso","kavell (pesketa)"],
["natrio","sodiom","natriom"],
["natura","naturel"],
["natura nombro","niver anterin naturel"],
["naturalismo","naturelouriezh"],
["nature","ez-naturel","dre natur","evel-just"],
["naturisto","naturour"],
["naturo","natur"],
["naturparko","park naturel"],
["navedi","mont-dont"],
["navedo","bulzun"],
["navigacii","merdeiñ"],
["navigacio","merdeadenn"],
["navo","nev (iliz)"],
["nazkataro","friad (kleñved)"],
["nazo","fri"],
["naztruo, nazotruo","divfronell","fronelloù"],
["nazumo","lunedoù-fri"],
["naĝi","neuial"],
["naĝilo","angell"],
["naĝobarelo","boue (merdeadurezh)"],
["naĝobirdo, naĝbirdo","evn palvezek"],
["naŭ","nav"],
["naŭa","navvet"],
["naŭe","da navvet"],
["neatendite","dic'hortoz (adv.)"],
["nebarita","divonn (mat.)"],
["nebula","latarek","koumoulek (luziet)"],
["nebulastro","nivlenn (steredon.)"],
["nebulo","latar","lusenn","nivlenn (latar)","mogidell","mougenn","morenn"],
["nebulozo","nivlenn (steredon.)"],
["nedependa","dizalc'h","dizepant"],
["negro","morian"],
["neniu","den ebet","hini ebet","ebet"],
["neodimo","neodim"],
["neologismo","nevezc'her"],
["neono","neon"],
["nepara","ampar"],
["nepino","merc'h-vihan"],
["neplenaĝa","dindan an oad"],
["nepo","mab-bihan"],
["neptunio","neptuniom"],
["nerva","nervel","nervus"],
["nervo","nervenn"],
["nesti","neizhiañ (sevel)"],
["nestiĝi","neizhiañ (annezañ)"],
["nesto","neizh"],
["nevino","nizez"],
["nevo","niz"],
["ni","ni"],
["nia","hol","hon","hor"],
["nigra","du (ag.)"],
["nigrigi","duañ"],
["nigro","du (ak.)"],
["nigrulo","morian"],
["nikeli","nikelañ"],
["nikelo","nikel"],
["nikotino","nikotin"],
["niobo","niobiom"],
["nitrogeno","nitrogen"],
["nizo","sparfell c'hlas"],
["niĉo","kustod"],
["nobelio","nobeliom"],
["nokte","diouzh an noz"],
["nokti","bezañ noz"],
["noktiĝi","noziñ"],
["nokto","noz","nozvezh"],
["noktohirundo","adren"],
["noktomezo","hanternoz"],
["nomado","anvadur"],
["nomaro","anvadurezh"],
["nombra","niverel"],
["nombrebla","niveradus"],
["nombri","kontañ (niveriñ)","niveriñ"],
["nombrilo","konter (muzulier)"],
["nombro","niver","unander"],
["nombronomo","ger niveriñ"],
["nombrosistemo","niveradur"],
["nome de, en la nomo de","en anv","a-berzh"],
["nomi","envel"],
["nominativo","nominativ","tro-envel"],
["nomiĝi","bezañ graet anezhañ"],
["nomo","anv"],
["nomumi","envel da"],
["norda","hanternoz (norzh)","norzh"],
["norde de","e hanternoz","e norzh","en hanternoz da","en norzh da"],
["nordo","hanternoz (norzh)","norzh"],
["nostalgia","hiraezhus"],
["nostalgie","gant hiraezh"],
["nostalgio","hiraezh","kleñved ar gêr"],
["nostalgiulo","hiraezhour"],
["notario","noter"],
["noti","notennañ"],
["noto","notenn"],
["notoj","kevrollenn","skrid-sonerezh"],
["nova","nevez"],
["nova mondo","Bed Nevez"],
["novaĵo","nevezenti"],
["nove","a-nevez","en-dro"],
["novelaro","dastumad danevelloù"],
["novelo","danevell"],
["novembro","Du (miz)"],
["novicino","danvez leanez"],
["novico","danvez lean","neveziad"],
["novismo","nevezc'her"],
["novulo","neveziad"],
["nuba","koumoulek"],
["nubo","koumoulenn"],
["nuda","noazh"],
["nudigi","noashaat"],
["nuko","kilpenn"],
["nukso","kraoñ"],
["nula","null"],
["nuligi","nullañ"],
["nulo","zero"],
["numerebla","niveradus"],
["numeri","niverenniñ"],
["numero","niverenn"],
["nun","bremañ"],
["nuna","a-vremañ"],
["nuncio","noñs"],
["nuntempo","amzer-vremañ"],
["nur","ne ... ket nemet","hepken","nemetken"],
["nura","hep mui ken","ha netra ken"],
["nutra","magus"],
["nutraĵo","boued","magadur"],
["nutrejo","magerezh (lec'h)"],
["nutri","bouetañ","magañ"],
["nutristino","magerez"],
["o-vorto","anv-kadarn"],
["obeado","sentidigezh"],
["obei","sentiñ"],
["obeigi","plegañ (lakaat da sentiñ)","lakaat da sentiñ"],
["ofta","stank (ag. en amzer)"],
["ofte","alies"],
["ofteco","aliested"],
["oftiĝi","aliesaat (v.g.)"],
["ok","eizh"],
["oka","eizhvet"],
["okaza","degouezhel"],
["okazaĵo","degouezhadenn"],
["okaze","diwar zegouezh","dre zarvoud","dre zegouezh"],
["okaze de","da geñver"],
["okazi","c'hoarvezout","degouezhout"],
["okazigi","degas (un darvoud)","aozañ (un darvoud)"],
["okazo","darvoud","degouezh"],
["okcidenta","-kornôg","-kuzh-heol"],
["okcidentano","kornogad"],
["okcidente de","e kornôg","er c'hornôg da"],
["okcidento","kornôg","kuzh-heol","ar C'hornôg","ar C'huzh-Heol"],
["oke","da eizhvet"],
["oksigeni","oksigenañ"],
["oksigeno","oksigen"],
["oktobro","Here (miz)"],
["okula","-lagad"],
["okuli, okulumi","ober lagadenn"],
["okulisto","lagadour"],
["okullenso","gwerenn al lagad"],
["okulmezure","a-wel-dremm"],
["okulo","lagad"],
["okzalo","triñchin"],
["ol","eget","evit (eget)"],
["olea","eoulek"],
["olei","eouliañ"],
["oleo","eoul"],
["olivarbo, olivujo","gwezenn-olivez","olivezenn (gwezenn)"],
["olivo","olivezenn (frouezhenn)"],
["omaro","legestr"],
["ombra, ombroplena","disheol (ag.)","disheoliet"],
["ombraĵo, subombro","disheol (ak.)","disheolienn"],
["ombrelo","disglavier","disheolier"],
["ombri","disheoliañ (v.k.)"],
["ombriĝi","teñvalaat"],
["ombro","disheol","teñvalijenn","skeud","livadenn (skeud.)"],
["ombrumi","skeudañ"],
["onklino","moereb"],
["onklo","eontr"],
["opalo","opal"],
["ora","alaouret","aour (en aour)"],
["oranĝarbo, oranĝujo","gwezenn-orañjez","orañjezenn (gwezenn)"],
["oranĝo","orañjezenn (frouezhenn)"],
["oraĵisto","aourer","orfebour"],
["oraĵo","aouraj"],
["orejo","aoureg"],
["orela","-skouarn"],
["orelo","skouarn"],
["orelringo","kloc'hig-skouarn"],
["orelstrigo","penn-kazh","toud (evn>"],
["oreltamburo","taboulin (ar skouarn)"],
["orfejo","ti-emzivaded"],
["orfigi","emzivadañ"],
["orfo","emzivad"],
["ori","alaouriñ","aouriñ"],
["orienta","-reter","-sav-heol","-ar Reter","-ar Sav-Heol"],
["oriente","er reter"],
["oriente de","e reter","er reter da"],
["orienten","war-zu ar reter"],
["orienti","durc'haat war-zu ar reter","reteriñ (matematik)","oriantiñ (matematik)"],
["orientiĝi, sin orienti","en em reteriñ"],
["orientiĝo","reteradur (matematik)","oriantadur (matematik)"],
["oriento","reter","sav-heol","ar Reter","ar Sav-Heol"],
["origisto","alaourer"],
["oro","aour"],
["oscedi","bazailhat"],
["osmio","osmiom"],
["osta","-eskern","en askorn","askornek"],
["ostaro","skeledenn"],
["osto","askorn"],
["ostocerbo","mel (askorn)","mel-askorn"],
["ostro","istrenn"],
["ovala","ovalek"],
["ovalo","ovalenn"],
["ovario","vierez"],
["ovaĵo","vioù (boued)"],
["ovingo","dalc'her-vi"],
["ovo","vi"],
["ovolo","viell"],
["ovoĉelo","viell"],
["ovujo","boest vioù"],
["ovulo","viell"],
["pacienca","pasiant"],
["pacienci","pasiantiñ"],
["pacienco","pasianted"],
["pajlo","kolo","plouz"],
["pajloŝtopi","plouzañ"],
["palaco","palez"],
["paladio","palladiom"],
["palata","-staon","staoniekaet"],
["palato","staon (korf.)"],
["palpebro","malvenn (korf.)"],
["palpebrumi","gwilc'hañ"],
["pandiono","erer-spluj"],
["pano","bara"],
["pantaloneto","bragoù berr"],
["pantalono","bragoù"],
["pantero","panterenn"],
["pantoflo","chaoson","kofignon"],
["papago","peroked"],
["papaveto","rozenn-aer"],
["papavo","rozenn-voc'h"],
["papera","-paper"],
["papero","paper","paperenn"],
["paperujo","doug-paperioù","kleurenn","doug-dielloù"],
["paperŝmiri","paperajiñ"],
["papilio","balafenn","pobelan"],
["papo","pab","pape"],
["para","par (ag.)"],
["paradi","dibunañ (soudarded)","bragal"],
["paradizludo","troadig-kamm"],
["paradizo","baradoz"],
["parado","gweladeg","bragerezh"],
["paralizi","seizañ"],
["paralizo","seizi"],
["paraziti","bevañ diwar-goust","sunata"],
["parazito","arvevad","suner"],
["pardoni","pardoniñ"],
["pardono","pardon"],
["pareco","parder"],
["parenca","kar (ag.)"],
["parenco","kar (ak.)"],
["parfumi","frondiñ"],
["parfumo","c'hwezh-vat","frond","porfum"],
["pargetero","plankenn (ar plañchod)"],
["pargeto","plañcheris","plañchod"],
["parigi","parañ (lakaat daou-ha-daou)"],
["parkere","dindan eñvor","dre eñvor"],
["parko","liorzh (park)","park (liorzh)","park naturel"],
["paro","re (manegoù, botoù...)","koublad","koubald (mat.)"],
["parola","dre gomz"],
["parolado","prezegenn"],
["paroli","komz (v.)"],
["parolisto","komzer"],
["parolo","komz (ak.)","ger (promesa)"],
["paroĥanaro","parrez (parreziad)","parreziad"],
["paroĥano","parrezianad"],
["paroĥestro","beleg-parrez","person (beleg)"],
["paroĥismo","spered parrez"],
["paroĥo","parrez"],
["partero","leur (c'hoariva)","rez-an-douar"],
["partia","untu","untuek"],
["partiano","ezel eus ur strollad"],
["participo","anv-gwan-verb"],
["partieca","untu","untuek"],
["partio","partiad"],
["paruo","pennduig"],
["pasado","tremenadenn"],
["pasamenti","pasamantañ"],
["pasamentisto","pasamanter"],
["pasamento","pasamant"],
["pasanto","tremeniad","tremener"],
["pase","diwar dremen"],
["pasejo","tremen (lec'h)","tremenvan (lec'h)"],
["pasema","o tremen","berrbad"],
["pasero","filip (evn)","golvan"],
["paseroformaj","golvaneged"],
["pasi","paseal (v.g.)","tremen (v.g.)"],
["pasigi","tremen (v.k..)"],
["pasporto","paseporzh","tremen-hent"],
["pastelo","pastilhezenn"],
["pasteĉo","formaj-kig"],
["pastinako","panezenn"],
["pasto","toaz"],
["pastri","bezañ beleg"],
["pastro","beleg"],
["pasvorto","ger tremen"],
["patenti","breouañ"],
["patento","breou"],
["pato","paelon-lostek","palarenn","pillig-lostek"],
["patreco","tadelezh"],
["patrineco","mammelezh"],
["patrino","mamm"],
["patrio","mammvro"],
["patro","tad"],
["patroj","tud-kaer"],
["patrujo","mammvro"],
["pavi","rodal","bragal"],
["pavimero","pavez"],
["pavimi","pavezañ"],
["pavimo","pavez (hollad pavezioù ur straed)"],
["pavo","paun","brager"],
["pavumi","bragal"],
["paĝio","floc'h"],
["paĝo","pajenn"],
["paŝado","bale (doare)","kerzhed"],
["paŝi","bale (v.)","kerzhet"],
["paŝo","kammed","pazenn (kammed)","pazenn (un helis)"],
["paŝtataro","chatal","tropell"],
["paŝtejo","peurvan"],
["paŝti","kas da beuriñ","peuriñ (kas da beuriñ)"],
["paŝtisto","bugul","maesaer"],
["paŝtiĝejo","peurvan"],
["paŝtiĝi","peuriñ (v.g.)"],
["paŭti","mousklenniñ","ober ur vousklenn"],
["paŭto","mousklenn"],
["paŭzi","ober un ehan","ober ur paouez"],
["paŭzo","ehan","paouez (ehan)"],
["pedika","laouek","-al laou"],
["pediko","laouenn"],
["pedikovo","nezenn"],
["pejzaĝisto","livour maezioù"],
["pejzaĝo","dremmvro","gweledva"],
["peki","pec'hiñ"],
["pekliberigi","absolviñ","gwalc'hiñ eus ar pec'hed"],
["peko","pec'hed"],
["pekulo","pec'her"],
["pelikano","pilikant"],
["peltaĵo","mantell feur"],
["pelto","feur","foulinenn"],
["pelvo","basin","divgroazell"],
["pendi","bezañ a-istribilh"],
["pendigi","istribilhañ","krougañ"],
["pendigilo","kroug"],
["pendolo","momeder"],
["pendumi","krougañ"],
["pendumilo","kroug"],
["penegi","kiañ"],
["penego","striv bras-meurbet"],
["peni","poaniañ (strivañ)","strivañ"],
["peniga","poanius (a c'houlenn kalz strivoù)"],
["peninda","a dalv ar boan"],
["penindi","talvezout ar boan"],
["peno","poan (striv)","striv"],
["penti","morc'hediñ"],
["pentofari","ober pinijenn"],
["pentraĵo","livadur"],
["pentri","pentañ","taolenniñ (gant gerioù)","empentiñ"],
["pentrinda","livus"],
["perdi","koll"],
["perdiĝi","bezañ kollet","en em goll"],
["perdriko","klujar"],
["perfekta","peurvat","(niver) parfet"],
["perfektigi","peurwellaat"],
["perfekto","amzer amdremenet kevrennek"],
["perfidi","traisañ","trubardiñ"],
["perfido","treitouriezh","trubarderezh"],
["perfidulo","treitour","trubard (ak.)"],
["pergameno","parch"],
["peritoneo","rouedenn ar bouzelloù","rouedenn-gof"],
["perko","brell (perch)","perch"],
["perla","-perlez"],
["perlabori, laborakiri","gounit (dre labourat)"],
["perlamoto","nakr"],
["perli","perlezenniñ (pizennañ)","pizennañ"],
["perlo","perlezenn"],
["permesi","permetiñ","aotren","reiñ an tu da","digouviañ"],
["permesilo","aotre (skrid-testeni)"],
["perono","menk-ti"],
["persekuti","poursuiñ","heskinañ","gervel dirak al lez-varn"],
["persekutisto","urcher"],
["persiko","pechezenn (frouezhenn)"],
["persikujo, persikarbo","gwezenn-bechez","pechezenn (gwezenn)"],
["persona nomo","anv bihan","kentanv"],
["pesi","pouezañ (v.k.)"],
["pesilo","balañs","mentel","pouezerez","Balañs (steredeg)"],
["pesto","bosenn (kleñved)"],
["petegi","aspediñ","azgoulenn"],
["peti","goulenn (v.)"],
["peti ies manon","goulenn dorn ub."],
["peto","goulenn (ak.)"],
["petrolo","eoul-maen"],
["petromizo","lamprez"],
["petroselo","perisilh"],
["petveturi","c'hoari biz-meud"],
["peza","pouezant"],
["peza laboro","labour tenn"],
["pezi","pouezañ (v.g.)"],
["pezigi","pounneraat (v.k.)"],
["pezilo","pouez (tamm metal)"],
["peziĝi","pounneraat (v.g.)"],
["pezo","pouez"],
["pezocentro","kreizenn gravitet","barikreizenn"],
["peĉo","peg"],
["pia","deol","devot"],
["piceo","pinenn-groaz"],
["pieco","deoliezh","devosion"],
["piedbenketo","skabell (da lakaat e dreid warni)"],
["piede","war droad"],
["piede de","ouzh troad"],
["piedestalo","sichenn (un delwenn)"],
["piedingo","stleug"],
["piednoto","notenn diaz ar bajenn"],
["piedo","troad"],
["pigo","pig"],
["pilolo","pilulenn"],
["pipo","korn-butun","korn (-butun)"],
["piprarbeto","pebrenn"],
["pipri","pebrañ"],
["pipro","pebr"],
["pipromento","bent-liorzh"],
["piprujo","pebrer","pebrenn"],
["pipso","pibid"],
["piro","perenn (frouezhenn)"],
["pirolo","beuf"],
["pirozo","kalondev","kalonlosk"],
["pirujo, pirarbo","gwezenn-ber","perenn (gwezenn)"],
["pirvino","sistr-per"],
["pistako","hogan-Spagn","pistachezenn (frouezhenn)"],
["pistakujo","gwezenn-bistachez","pistachezenn (gwezenn)"],
["pistolo","pistolenn"],
["piulo","devod"],
["plateno","platin"],
["plejboneco","gwellañ (a.k.)"],
["plejofte","peurliesañ"],
["plektobarilo","treilh"],
["plenaĝa","deuet (d'e oad gour)"],
["plenblovi","c'hwezañ"],
["plenbuŝo","genaouad"],
["plibeligi","bravaat","kaeraat (v.k.)"],
["plibonigi","gwellaat (v.k.)"],
["plioftiĝi","aliesaat (v.g.)"],
["plumbero","drajezenn (plomenn)","plomemm (drajezenn)"],
["plumbo","plom (metal)"],
["plumbofadeno","neudenn-blom"],
["plutonio","plutoniom"],
["pluvombrelo","disglavier"],
["polonio","poloniom"],
["pomejo","avalenneg"],
["porparolanto","alvokad (dre skeud.)","breutaer (dre skeud.)"],
["postkuri","redek war-lerc'h"],
["postlasi","lezel war e lerc'h"],
["postmanĝaĵo","dibenn-pred"],
["postmeti","lakaat war-lerc'h"],
["postmorgaŭ","goude warc'hoazh","antronoz all"],
["postparolo","goude-skrid","gourfennskrid"],
["posttagmezo","enderv"],
["postvango","feskenn","peñs"],
["poŝhorloĝo","eurier-godell"],
["poŝtkarto","kartenn-bost"],
["poŝtkesto","boest-lizheroù (post)"],
["praavino","mamm-guñv"],
["praavo","tad-kuñv"],
["prahistorio, antaŭhistorio","ragistor"],
["pranepo, postnepo","mab-kuñv"],
["prapatro","gourdad","hendad"],
["prazeodimo","prazeodim"],
["preteratenti","na ober van (eus, ouzh)"],
["preterlasi","lezel da dremen"],
["preterpasi","mont hebiou"],
["prilabori","labourat (v.k.)","merat (labourat)"],
["primeti","staliañ (an daol,...)"],
["priparoli","komz diwar-benn"],
["profundaĝa","er maez a oad"],
["promecio","prometiom"],
["prometio","prometiom"],
["propeka kapro, pekporta kapro","bouc'h ar pec'hedoù"],
["protaktinio","protaktiniom"],
["provludi","pleustriñ (c'hoariva, sonerezh)"],
["provnumero","niverenn skouer (kelaouennoù)"],
["punlaborejo","galeoù"],
["rabobestoj","kigdebrerien"],
["rabobirdoj, rabbirdoj","evned-preizh","laboused-preizh"],
["radiumo","radiom"],
["radono","radon"],
["rajtigilo","aotre (skrid-testeni)"],
["reaperanto","seblant (tasmant)"],
["rebonigi","dresañ"],
["remaĉi","daskiriat"],
["renio","reniom"],
["renovigi","adneveziñ (v.k.)","neveziñ (v.k.)"],
["renoviĝi","adneveziñ (v.g.)","neveziñ (v.g.)"],
["rentgenio","roentgeniom"],
["retadreso","chomlec'h postel"],
["reto","rouedad"],
["reuzpapero","paper adimplijet"],
["ridmevo","gouelanig maskl du"],
["rinocero","frikorneg"],
["ripo","kostenn","kostezenn (askorn)"],
["rodio","rodiom"],
["rotacia akso","ahel troiadur"],
["rotacia centro","kreizenn troiadur"],
["rubidio","rubidiom"],
["rutenio","ruteniom"],
["ruĝa beto","beterabezenn ruz"],
["ruĝa pipro","paprika"],
["sabato","Sadorn","disadorn"],
["sablohorloĝo, sabla horloĝo","eurier-traezh"],
["samario","samariom"],
["samaĝulo","den kenoad"],
["samcentra","kengreiz"],
["samlandano","kenvroad"],
["samvalora","kendalvoud","kenkoulz"],
["sangadulto","gadaliezh etre kar ha karez","insest"],
["sangkolbaso, sangokolbaso","gwadegenn"],
["sanktolei","oleviñ"],
["sekshontemo, sekshonto","elevez","mezh (elevez)"],
["sekurrimeno","gouriz-surentez"],
["sekurzono","gouriz-surentez"],
["seleno","seleniom"],
["senagado","dizoberiantiz"],
["senakcenta, ne","dibouezmouezh"],
["senatenta","dievezh"],
["senbarba","divarv","blouc'h"],
["senbezona","diezhomm"],
["sencerbulo","den diempenn","penn divouedet"],
["senceremonia","diardoù"],
["sendanka","dianaoudek"],
["sendanĝera","dizañjer"],
["sendependa","dizalc'h"],
["senhara","moal"],
["senhaŭtigi","digroc'henañ"],
["senhelpa","diharp","diskoazell","diremed","dirapar (diremed)"],
["senheredigi","dishêriañ"],
["senhoma","didud"],
["senhomigi","didudañ (v.k.)"],
["senhonta","divezh"],
["senlabora","dilabour (ag.)"],
["senlaboreco","dioberiantiz","dilabour (ak.)"],
["senlaca, nelacigebla","diskuizhus (tud)"],
["senmakula","disaotr"],
["senmanka","klok","hep mank"],
["senmaskigi","divasklañ"],
["senmezura, supermezura","divuzul","hep muzul","dreist muzul"],
["senmiksa","divesk"],
["senmona","diarc'hant"],
["sennombra, nenombrebla","diniver"],
["senpartia","diuntuek","neptu"],
["senpaŭze","dibaouez"],
["senpedikigi","dilaouañ"],
["senpeka","dibec'hed"],
["senpekigi","absolviñ","gwalc'hiñ eus ar pec'hed"],
["senpene","diboan (aes)"],
["senvalora","didalvez"],
["senvorte","dilavar (adv.)"],
["senvualigi","dioueliañ"],
["sep","seizh"],
["sepa","seizhvet"],
["sepe","da seizhvet"],
["septembro","Gwengolo"],
["ses","c'hwec'h"],
["sesa","c'hwec'hvet"],
["sesdekuma","triugentel"],
["sese","da c'hwec'hvet"],
["sidvango","feskenn","peñs"],
["silicio","silisiom"],
["simetriakso","ahel simetriezh"],
["simetricentro","kreizenn simetriezh"],
["simio","marmouz"],
["skandio","skandiom"],
["somerdomo","ti-hañv"],
["somero","hañv"],
["sonkesto","kef-dasson"],
["spina medolo","mel gwalenn-gein"],
["spirblovi","dianaliñ"],
["stacidomo","porzh-houarn","ti-gar"],
["stani","staenañ"],
["stano","staen"],
["strata lanterno","kleuzeur-straed"],
["strigo","kaouenn"],
["stroncio","strontiom"],
["sub libera ĉielo","dindan an amzer"],
["suba baro","minorer"],
["subakvigi","beuziñ (tr.)","soubañ (en dour)"],
["subakviĝi"," splujañ (dindan an dour) "],
["subarbo","isgwezenn"],
["subbrako","kazel"],
["subjupo","brozh-dindan","goueledenn","lostenn-dindan"],
["subleŭtenanto","isletanant"],
["submeti","bazhyevañ","sujañ"],
["subunuo","isunanenn"],
["sukerbeto","beterabezenn sukr"],
["sukerkano","korzenn-sukr"],
["sulfuro","soufr","sulfur"],
["sunbano","heoliadenn"],
["sunbrunigi","rouzañ (kroc'hen - v.k.)"],
["sunbruniĝi","rouzañ (kroc'hen - v.g.)"],
["sunbruno","rouster"],
["sunhorloĝo","eurier-heol","horolaj-heol"],
["sunombrelo","disheolier"],
["supera baro","majorer"],
["superakvego","liñvadenn","dour-beuz"],
["superakvi","liñvañ"],
["superhoma","dreistdenel"],
["superhomo","dreistden"],
["superjaro","bloavezh bizeost"],
["supernatura","dreistnatur"],
["superpezi","bezañ trec'h war"],
["superpezo, plipezo","soulgarg"],
["supremenciita","meneget uheloc'h"],
["surfadenigi","strobañ (ouzh un neudenn)"],
["surmeti","gwiskañ"],
["surpaperigi","lakaat war baper"],
["survango, vangobato","flac'had","jodad","skouarnad"],
["tabako","butun"],
["tabulbarilo","kael peulioù"],
["tagmanĝo","merenn"],
["tagmezo","kreisteiz"],
["tagnokto","deiz (24 eur)"],
["talio","taliom"],
["taliumo","taliom"],
["tantalo","tantal"],
["teknecio","teknetiom"],
["telefonbudo","logell bellgomz"],
["telefonkarto","kartenn-bellgomz"],
["teluro","tellur"],
["tempaĝo","oadvezh"],
["tempopasigilo","tremen-amzer"],
["terbio","terbiom"],
["terkarbo, minkarbo","glaou-douar"],
["terpeĉo","asfalt"],
["terpiro","perenn-douar"],
["tipio","tipi"],
["tirboji","yudal"],
["tirharmoniko","akordeon"],
["titano","titan"],
["tombomonumento, tomba monumento","mozoleon"],
["torio","toriom"],
["traakvigi"," dourañ (un dachenn douar) "],
["trablovo","avel-sil"],
["trakuri","redek dre"],
["tralasi","lezel da dreuziñ"],
["tralegi","lenn penn-da-benn"],
["tranokti","nozvezhiañ"],
["transmara","tramor"],
["transpasi","tremen (hebiou)"],
["trapasi","treizhañ","treuziñ"],
["tri","tri [vira]","teir [ina]"],
["tria","trede","trivet [vira]","teirvet [ina]"],
["tria mondo","Trede Bed"],
["triamonda","eus an Trede Bed"],
["trie","da drede"],
["triono","trederenn"],
["tripkolbaso","anduilhenn"],
["triunuo","Treinded"],
["trovo","faltazi (c'hoant)"],
["tubera helianto","perenn-douar"],
["tubo","siminal"],
["tufanaso","houad du","kanig du [komune]"],
["tulio","tuliom"],
["ulcero","gouli (gwiadennoù ar c'horf)"],
["ulmo","gwezenn-oulm","oulmenn"],
["ulno","ilinad","kefilin"],
["umbilika ŝnuro","funig ar begel"],
["umbiliko","begel"],
["unco","oñs"],
["ungego","kraban","skilf"],
["ungo","ivin [homoj]","karn","skilf"],
["uniformo","lifre (unwisk)","unwisk"],
["universa","hollvedel"],
["universala","hollvedel"],
["universitato","skol-veur"],
["universo","hollved"],
["unu","unan","ul","un","ur"],
["unua","kentañ"],
["unua mondmilito","brezel-bed kentañ"],
["unue","da gentañ"],
["unuigi","unaniñ"],
["unuiĝi","en em unaniñ"],
["ununura","nemetañ (-don, -dout, -ti)"],
["unuo","unanenn"],
["unuokula","born (ag.)"],
["unupeca","en ur pezh"],
["unuvorte","berr-ha-berr","eberr gomzoù","en ur ger"],
["uranio","uraniom"],
["urbo","kêr"],
["urbodomo","ti-kêr"],
["urinado","troazhadenn [homoj]","staotadenn [bestoj]"],
["urini","troazhañ [homoj]","staotañ [bestoj]"],
["urino","troazh [homoj]","staot [bestoj]"],
["urinveziko","c'hwezhigell (troazh)"],
["urno","jarl","jarlig kañv [por mortocindrojn]","jarlig ludu [por mortocindrojn]","pod ar mouezhioù"],
["urso","arzh"],
["urtiko","linad(enn)"],
["utero","mammog"],
["vadbirdoj, vadobirdoj","hirc'hareged"],
["vaflo","galfrezenn"],
["vagi","c'hwistolat","kantren","troidellañ"],
["vagonaro","tren"],
["vagono","bagon"],
["vakcinado","vaksinadur"],
["vakcini","vaksinañ"],
["vakcinio","gwezenn-lus"],
["vakcino","brec'h (vaksin)","vaksin"],
["vaksi","koarañ"],
["vakso","koar","koar siellañ"],
["valizo","malizenn"],
["valo","traoñienn"],
["valora","talvoudek","talvoudus"],
["valori","talvezout","talvout"],
["valori la penon","talvezout ar boan"],
["valoro","talvoudegezh","gwerzh (talvoud)","talvoud"],
["valsi","valsiñ"],
["valso","valsenn"],
["vana","aner (ag.)"],
["vanadio","vanadiom"],
["vanado","vanadiom"],
["vane","en aner"],
["vango","boc'h","jod"],
["vanilo","vanilha"],
["vapora","aezhennus","aezhennel"],
["vapori","divogediñ (en ur zisteurel aezhenn)"],
["vaporigi","aezhennañ (v.k.)"],
["vaporigilo","difruer"],
["vaporiĝi","aezhennañ (v.k.)","diaezhennañ"],
["vaporkaldrono","kaoter (tommerezh)"],
["vapormaŝino","ijinenn dre vurezh"],
["vaporo","aezhenn","burezh"],
["varbi","tuta"],
["variolo","brec'h (kleñved)"],
["varma","tomm"],
["varmega","brout","gor (ag.)","tomm-berv"],
["varmego","birvidigezh"],
["varmeta","klouar"],
["varmeto","freskadurezh"],
["varmigi","tommañ"],
["varmo","tommder"],
["varmumi","tapout anoued","pakañ riv"],
["varti","diwall (ur bugel, ul loen yaouank...)"],
["vartistino","diwallerez"],
["vasalo","gwaz (dindan un aotrou)"],
["vekhorloĝo","dihuner"],
["vendredo","Gwener","digwener"],
["verukherbo","louzaouenn-ar-plac'h-koant"],
["veselleŭtenanto","letanant a vor"],
["vespermanĝo","koan"],
["vetkuro","redadeg"],
["viando","kig"],
["vicleŭtenanto","isletanant"],
["vicluigi","eilfeurmiñ"],
["vicsubleŭtenanto","adjudant"],
["vinberaro","blokad rezin","bodad rezin","barr rezin"],
["virabelo","tad-gwenan"],
["virbovo","tarv"],
["virkato","targazh"],
["viruso","viruz"],
["vivdaŭro","hoali","remzi"],
["vojaĝi","beajiñ"],
["vojaĝo","beaj"],
["vojo","hent-houarn"],
["vokalo","vogalenn"],
["vokativo","vokativ","tro-c'helver"],
["vokkazo","vokativ","tro-c'helver"],
["volframo","tungsten"],
["volumeno","volum"],
["vomi","dislonkañ","rechetiñ"],
["vorta","dre gomz"],
["vortaristo","geriadurour"],
["vortaro","geriadur"],
["vortfarado","ar stummañ gerioù"],
["vortformo","furm (ger)"],
["vortigi, envortigi","geriañ"],
["vortkunmeto","kenstrollad (anvioù, gerioù)"],
["vorto","ger","Verb (kristeniezh)"],
["vortobatali","tabutal"],
["vortoprovizo, vortprovizo","geriaoueg"],
["vosto","lost"],
["voĉlegi","lenn a vouezh uhel"],
["vuali","goueliañ"],
["vualo","gouel"],
["vulkano","menez-tan"],
["vulpo","louarn"],
["zebuo","zebu"],
["zinko","zink"],
["zirkonio","zirkoniom"],
["zoni","gourizañ"],
["zono","gouriz","dargreiz","zonenn (sferek)"],
["ĉapobeko","lerbenn"],
["ĉashundo","ki-chase","ki-hemolc'h"],
["ĉebrusto, ĉebrustaĵo","bruched (dilhad)"],
["ĉemane","dindan dorn","dindan e zorn"],
["ĉenhundo","ki-porzh"],
["ĉieliro","Pignidigezh (Jezuz-Krist) ","Yaou-Bask"],
["ĉielo","oabl","neñv"],
["ĉielrando","dremmwel"],
["ĉirkaŭbari","mogeriañ","bac'hañ","kelc'hiañ"],
["ĉirkaŭbraki","briata"],
["ĉirkaŭhaki","bouc'halañ"],
["ĉirkaŭmano","tro-vrec'h"],
["ĉirkaŭparoli","lakaat troidelloù en e gomzoù"],
["ĉiuhore","bep eurvezh"],
["ĉiujara","bloaziek","bloavezhiek"],
["ĝemelo","gevell (ak.)"],
["ĝemeloj","Gevelled"],
["ĝirafo","jirafenn"],
["ĝisnuna","betek bremañ"],
["ĵazbando","strollad jazz"],
["ĵaŭdo","Yaou","diriaou"],
["ŝafhundo","ki-deñved"],
["ŝnurdancisto","fungoroller"],
["ŝtonoleo","tireoul"],
["ŝtuparlifto","diri-ruilh","escalator"],
["ŝvitbano","saona"],
];
var revo_br_lower = revo_br.map(function(a) { return a.map(function(x) { return x.toLowerCase(); }) });
// @license-end
